'use strict';
const { assertIdempotentEventSink, createDomainEvent } = require('../../core/src/events');
class PandoraBookingService {
  constructor({ repository, eventSink, notifications = null }) {
    for(const method of ['listAvailability','createReservationAtomic','cancelReservationAtomic']) if(!repository||typeof repository[method]!=='function') throw new TypeError(`booking repository.${method} is required`);
    if(repository.transactionSafe!==true) throw new Error('booking repository must guarantee transaction-safe capacity changes');
    assertIdempotentEventSink(eventSink,'booking event sink');
    if(notifications&&typeof notifications.send!=='function') throw new TypeError('booking notifications adapter is invalid');
    this.repository=repository;this.eventSink=eventSink;this.notifications=notifications;
  }
  async listAvailability({scopeId,from,to,resourceId=null,timezone}){validateTimezone(timezone);const start=canonicalInstant(from,'from');const end=canonicalInstant(to,'to');if(start>=end)throw new TypeError('availability range must increase');return this.repository.listAvailability({scopeId:required(scopeId,'scopeId'),from:start,to:end,resourceId});}
  async createReservation({project,scopeId,slotId,identity,guest={},idempotencyKey}){const userId=required(identity&&identity.userId,'identity.userId');const reservation=await this.repository.createReservationAtomic({scopeId:required(scopeId,'scopeId'),slotId:required(slotId,'slotId'),customerUserId:userId,guest:safeGuest(guest),idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:'reservation.created',schemaVersion:'1.0',project,actor:{userId},aggregate:{type:'reservation',id:String(reservation.id)},payload:{slotId:String(reservation.slotId),status:String(reservation.status)},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);if(this.notifications&&reservation.notificationRecipient){await this.notifications.send({scopeId,channel:'email',recipient:reservation.notificationRecipient,template:'booking_confirmation',variables:{reservationId:String(reservation.id)},idempotencyKey:`reservation:${reservation.id}:confirmation`,metadata:{event:'reservation.created'}});}return Object.freeze({...reservation,event});}
  async cancelReservation({project,scopeId,reservationId,identity,idempotencyKey}){const userId=required(identity&&identity.userId,'identity.userId');const reservation=await this.repository.cancelReservationAtomic({scopeId:required(scopeId,'scopeId'),reservationId:required(reservationId,'reservationId'),customerUserId:userId,idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:'reservation.cancelled',schemaVersion:'1.0',project,actor:{userId},aggregate:{type:'reservation',id:String(reservation.id)},payload:{slotId:String(reservation.slotId),status:String(reservation.status)},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);return Object.freeze({...reservation,event});}
}
function canonicalInstant(value,field){const date=value instanceof Date?value:new Date(value);if(Number.isNaN(date.getTime()))throw new TypeError(`${field} must be a valid timestamp`);return date.toISOString();}
function validateTimezone(timezone){required(timezone,'timezone');try{new Intl.DateTimeFormat('en-US',{timeZone:timezone}).format(new Date());}catch{throw new TypeError('timezone must be a valid IANA timezone');}return timezone;}
function formatInstantInTimezone(value,timezone,locale='en-US'){validateTimezone(timezone);const instant=new Date(canonicalInstant(value,'instant'));const formatter=new Intl.DateTimeFormat(locale,{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23',timeZoneName:'short'});return Object.freeze(Object.fromEntries(formatter.formatToParts(instant).filter((part)=>part.type!=='literal').map((part)=>[part.type,part.value])));}
function safeGuest(value){if(!value||typeof value!=='object'||Array.isArray(value))return Object.freeze({});const allowed=['name','email','phone','notes'];const output={};for(const [key,child] of Object.entries(value)){if(!allowed.includes(key))throw new Error(`guest field is not allowed: ${key}`);if(typeof child!=='string'||child.length>1000)throw new TypeError(`guest.${key} must be bounded text`);output[key]=child.trim();}return Object.freeze(output);}
function required(value,field){if(typeof value!=='string'||!value.trim())throw new TypeError(`${field} is required`);return value.trim();}
module.exports={PandoraBookingService,canonicalInstant,formatInstantInTimezone,safeGuest,validateTimezone};
