'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const bi = require('../src/index.js');

function objective(overrides={}) { return bi.createBusinessObjective({objectiveId:'obj-1',projectSpecId:'spec-1',objective:'Increase direct bookings',primaryMetricKey:'completed_booking',baseline:{value:12,provenance:'customer_supplied'},target:{value:25},measurementWindow:{amount:7,unit:'day'},...overrides}); }
function measurement(overrides={}) { return {metricKey:'completed_booking',value:20,sampleSize:20,windowStart:'2026-08-20T00:00:00Z',windowEnd:'2026-08-27T00:00:00Z',lastObservedAt:'2026-08-27T00:00:00Z',complete:true,source:'analytics',quality:'valid',...overrides}; }

test('objective supports honest unmeasured state',()=>{ const obj=bi.createBusinessObjective({objectiveId:'o',projectSpecId:'s',objective:'Improve brand trust'}); assert.equal(obj.primaryMetricKey,null); assert.equal(obj.baseline.value,null); assert.equal(obj.target.value,null); });
test('metric registry contains canonical booking metric',()=>{ const registry=new bi.BusinessMetricRegistry(); assert.equal(registry.require('completed_booking').event,'booking_completed'); });
test('duplicate metric keys are rejected',()=>{ const registry=new bi.BusinessMetricRegistry([]); registry.register({key:'x',event:'x_done',aggregation:'count',unit:'count'}); assert.throws(()=>registry.register({key:'x',event:'x_done',aggregation:'count',unit:'count'}),/already registered/); });
test('instrumentation contract maps metric to event',()=>{ const registry=new bi.BusinessMetricRegistry(); assert.deepEqual(bi.instrumentationRequirement(registry.require('completed_booking')).requiredEvent,'booking_completed'); });
test('customer business event requires tenant and version scope',()=>{ const event=bi.validateEventEnvelope({kind:'customer_app_business_event',event:'booking_completed',scope:{organizationId:'org-a',projectId:'proj-a',projectVersionId:'v19',environment:'production'},properties:{schema_version:'1.0.0'}}); assert.equal(event.scope.projectVersionId,'v19'); });
test('customer app cannot forge Pandora internal event',()=>{ assert.throws(()=>bi.validateEventEnvelope({kind:'customer_app_business_event',event:'build_completed',scope:{organizationId:'org',projectId:'p',projectVersionId:'v',environment:'production'}}),/not allowed/); });
test('untrusted caller cannot emit Pandora internal event',()=>{ assert.throws(()=>bi.validateEventEnvelope({kind:'pandora_internal_event',event:'publish_completed',scope:{organizationId:'org',projectId:'p',projectVersionId:'v',environment:'production'}}),/trusted server/); });
test('sensitive and arbitrary properties are rejected',()=>{ assert.throws(()=>bi.validateEventEnvelope({kind:'customer_app_business_event',event:'booking_completed',scope:{organizationId:'org',projectId:'p',projectVersionId:'v',environment:'production'},properties:{email:'a@example.com'}}),/not allowlisted|sensitive/); });
test('analytics scope prevents cross-project leakage',()=>{ assert.throws(()=>bi.assertProviderScope({organizationId:'org',projectId:'a',environment:'production',projectVersionId:'v1'},{organizationId:'org',projectId:'b',environment:'production',projectVersionId:'v1'}),/scope mismatch/); });
test('measurement readiness distinguishes configured from ready',()=>{ const obj=objective(); const metric=new bi.BusinessMetricRegistry().require('completed_booking'); assert.equal(bi.measurementReadiness({objective:obj,metricDefinition:metric,instrumentationVerified:false}).state,'configured'); assert.equal(bi.measurementReadiness({objective:obj,metricDefinition:metric,instrumentationVerified:true,querySucceeded:true,receivingData:true,attributionComplete:true,stale:false}).state,'ready'); });
test('no data is awaiting_data, not zero success',()=>{ const obj=objective(); const metric={...new bi.BusinessMetricRegistry().require('completed_booking'),freshnessSeconds:999999999}; const out=bi.assessOutcome({objective:obj,metric,measurement:measurement({value:null,sampleSize:0})}); assert.equal(out.state,'awaiting_data'); });
test('insufficient sample is inconclusive',()=>{ const obj=objective({primaryMetricKey:'checkout_conversion_rate',baseline:{value:0.14,provenance:'analytics'},target:{value:0.18}}); const metric={...new bi.BusinessMetricRegistry().require('checkout_conversion_rate'),freshnessSeconds:999999999}; const out=bi.assessOutcome({objective:obj,metric,measurement:{...measurement(),metricKey:'checkout_conversion_rate',value:0.2,sampleSize:5}}); assert.equal(out.state,'inconclusive'); });
test('target met requires sufficient data',()=>{ const obj=objective(); const metric={...new bi.BusinessMetricRegistry().require('completed_booking'),freshnessSeconds:999999999}; const out=bi.assessOutcome({objective:obj,metric,measurement:measurement({value:25})}); assert.equal(out.state,'target_met'); });
test('version comparison never claims causality',()=>{ const result=bi.compareVersions({a:{value:0.074,sampleSize:200},b:{value:0.092,sampleSize:210}}); assert.equal(result.state,'improved'); assert.equal(result.causal,false); });
test('version comparison is inconclusive for small samples',()=>{ const result=bi.compareVersions({a:{value:0.074,sampleSize:5},b:{value:0.092,sampleSize:6}}); assert.equal(result.state,'inconclusive'); });
test('funnel reports conversion and drop off',()=>{ const def=bi.defineFunnel({key:'booking',objectiveId:'obj',steps:['room_viewed','availability_checked','booking_started','booking_completed']}); const result=bi.analyzeFunnel(def,{room_viewed:100,availability_checked:80,booking_started:50,booking_completed:25}); assert.equal(result.completionRate,0.25); assert.equal(result.steps[2].dropOff,30); });
test('recommendation requires evidence',()=>{ assert.throws(()=>bi.createRecommendation({recommendationId:'r',organizationId:'o',projectId:'p',objectiveId:'obj',observedFact:'x',affectedMetric:'m',suggestedChange:'y',expectedImpactHypothesis:'z'}),/evidence/); });
test('accepted recommendation produces governed change intent, not mutation',()=>{ const r=bi.createRecommendation({recommendationId:'r1',organizationId:'o',projectId:'p',objectiveId:'obj',observedFact:'42% mobile abandonment at date selection',evidence:['mobile conversion 4.1%, desktop 8.7%'],affectedMetric:'checkout_conversion_rate',suggestedChange:'Simplify mobile date selection',expectedImpactHypothesis:'Improve booking completion',confidence:'medium',risk:'low',estimatedCost:3,status:'accepted'}); const intent=bi.optimizationChangeIntent(r); assert.equal(intent.intentKind,'change'); assert.equal(intent.provenance.recommendationId,'r1'); });
test('recommendations with unknown cost are not falsely ranked',()=>{ const r=bi.createRecommendation({recommendationId:'r2',organizationId:'o',projectId:'p',objectiveId:'obj',observedFact:'drop off',evidence:['e'],affectedMetric:'m',suggestedChange:'change',expectedImpactHypothesis:'impact'}); assert.equal(bi.prioritizeRecommendation(r).band,'needs_estimate'); });
test('owner projection excludes provider query internals',()=>{ const summary=bi.ownerSafeBusinessSummary({objective:objective(),metric:new bi.BusinessMetricRegistry().require('completed_booking'),measurement:measurement(),outcome:{state:'near_target',health:'on_track'},measurementState:'ready',posthogQuery:{secret:'no'}}); assert.equal(summary.goal,'Increase direct bookings'); assert.equal('posthogQuery' in summary,false); });
