import "jsr:@supabase/functions-js@2.4.5/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.57.2";

const URL=Deno.env.get("SUPABASE_URL")||"";
const ANON=Deno.env.get("SUPABASE_ANON_KEY")||"";
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const GEMINI=Deno.env.get("PANDORA_VISION_GEMINI_MODEL")||"gemini-3.7-flash";
const OPENAI=Deno.env.get("PANDORA_VISION_OPENAI_MODEL")||"gpt-5.6-luna";
type R=Record<string,unknown>;
const rec=(v:unknown):R=>v&&typeof v==="object"&&!Array.isArray(v)?v as R:{};
const txt=(v:unknown,d="")=>typeof v==="string"&&v.trim()?v.trim():d;
const arr=(v:unknown)=>Array.isArray(v)?v:[];
const n=(v:unknown,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
const secret=(v:unknown)=>/AIza[0-9A-Za-z_-]{20,}|github_pat_[A-Za-z0-9_]{20,}|gh[pousr]_[A-Za-z0-9_]{20,}|sk-[A-Za-z0-9_-]{20,}|Bearer\s+[A-Za-z0-9._~+/-]{12,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|postgres(?:ql)?:\/\/[^:\s@]+:[^@\s]+@/i.test(JSON.stringify(v));
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}

async function auth(req:Request){
  const authorization=req.headers.get("authorization")||"";
  if(!/^Bearer\s+\S+$/i.test(authorization))throw Error("SIGN_IN_REQUIRED");
  const user=createClient(URL,ANON,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});
  const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
  const u=await user.auth.getUser();
  if(u.error||!u.data.user)throw Error("SIGN_IN_REQUIRED");
  const requested=req.headers.get("x-organization-id")?.trim()||"";
  let q=user.from("memberships").select("organization_id,role,status").eq("user_id",u.data.user.id).eq("status","active").limit(3);
  if(requested)q=q.eq("organization_id",requested);
  const m=await q;
  if(m.error||!m.data?.length)throw Error("ORGANIZATION_ACCESS_REQUIRED");
  if(!requested&&m.data.length!==1)throw Error("ORGANIZATION_SELECTION_REQUIRED");
  const row=rec(m.data[0]),role=txt(row.role);
  if(!["owner","admin"].includes(role))throw Error("OWNER_ROLE_REQUIRED");
  return{user,admin,userId:u.data.user.id,organizationId:txt(row.organization_id),role};
}
async function rate(admin:any,org:string,user:string){const r=await admin.rpc("consume_runtime_rate_limit",{p_organization_id:org,p_key_hash:await sha(user+":pandora-vision"),p_limit:30,p_window_seconds:60});if(r.error)throw Error("RATE_LIMIT_UNAVAILABLE");if(rec(r.data).allowed!==true)throw Error("RATE_LIMITED")}
function geminiJson(v:unknown){const e=rec(v);if(n(e.status)<200||n(e.status)>=300)throw Error("PROVIDER_UNAVAILABLE");const b=rec(e.body),c=rec(arr(b.candidates)[0]),content=rec(c.content),raw=arr(content.parts).map(p=>txt(rec(p).text)).join("").trim();if(!raw)throw Error("INVALID_MODEL_OUTPUT");try{return JSON.parse(raw)}catch{throw Error("INVALID_MODEL_OUTPUT")}}
function openaiJson(v:unknown){const e=rec(v);if(n(e.status)<200||n(e.status)>=300)throw Error("PROVIDER_UNAVAILABLE");const b=rec(e.body),c=rec(arr(b.choices)[0]),m=rec(c.message),raw=txt(m.content);if(!raw)throw Error("INVALID_MODEL_OUTPUT");try{return JSON.parse(raw)}catch{throw Error("INVALID_MODEL_OUTPUT")}}
async function modelJson(admin:any,instruction:string,frames:any[]=[]){
  const parts:any[]=[{text:instruction}];
  for(const f of frames)parts.push({inlineData:{mimeType:f.mimeType,data:f.dataBase64}});
  const gbody={systemInstruction:{parts:[{text:"You are Pandora Vision Intelligence. Return JSON only. Report observable evidence only. Never identify a real person or infer protected traits, health, emotion, guilt, criminality, or intent. Temporary anonymous track keys may only express visible continuity across supplied frames. Machine observations are not verified facts."}]},contents:[{role:"user",parts}],generationConfig:{responseMimeType:"application/json",temperature:.1,maxOutputTokens:4096}};
  if(!secret(gbody)){const g=await admin.rpc("pandora_worker_b_gemini_request_20260829",{p_model:GEMINI,p_body:gbody});if(!g.error){try{return{provider:"gemini",model:GEMINI,value:geminiJson(g.data)}}catch{}}}
  const oparts:any[]=[{type:"text",text:instruction}];
  for(const f of frames)oparts.push({type:"image_url",image_url:{url:"data:"+f.mimeType+";base64,"+f.dataBase64,detail:"low"}});
  const obody={messages:[{role:"developer",content:"You are Pandora Vision Intelligence. Return JSON only. Report observable evidence only. Never identify a real person or infer protected traits, health, emotion, guilt, criminality, or intent. Temporary anonymous track keys may only express visible continuity across supplied frames. Machine observations are not verified facts."},{role:"user",content:oparts}],response_format:{type:"json_object"},reasoning_effort:"low",max_completion_tokens:4096,stream:false};
  if(secret(obody))throw Error("CREDENTIAL_MATERIAL_REJECTED");
  const o=await admin.rpc("pandora_openai_chat_request_v1",{p_model:OPENAI,p_body:obody});
  if(o.error)throw Error("PROVIDER_UNAVAILABLE");
  return{provider:"openai",model:OPENAI,value:openaiJson(o.data)};
}
function frames(v:unknown){
  const a=arr(v);if(a.length<1||a.length>4)throw Error("INVALID_FRAMES");let bytes=0;
  return a.map((raw,i)=>{const f=rec(raw),mimeType=txt(f.mimeType).toLowerCase(),dataBase64=txt(f.dataBase64),capturedAt=txt(f.capturedAt,new Date().toISOString());if(!["image/jpeg","image/png","image/webp"].includes(mimeType)||!dataBase64||!/^[A-Za-z0-9+/=]+$/.test(dataBase64)||!Number.isFinite(Date.parse(capturedAt)))throw Error("INVALID_FRAMES");bytes+=Math.ceil(dataBase64.length*.75);if(bytes>620000)throw Error("FRAMES_TOO_LARGE");return{index:i,mimeType,dataBase64,capturedAt}});
}
function analysis(v:unknown){
  const x=rec(v),countsRaw=rec(x.counts);
  const counts={people:Math.max(0,Math.round(n(countsRaw.people))),vehicles:Math.max(0,Math.round(n(countsRaw.vehicles))),bicycles:Math.max(0,Math.round(n(countsRaw.bicycles))),packages:Math.max(0,Math.round(n(countsRaw.packages)))};
  const observations=arr(x.observations).slice(0,80).map((raw,i)=>{const o=rec(raw);return{index:i,observationType:txt(o.observationType||o.observation_type,"object").slice(0,80),objectClass:txt(o.objectClass||o.object_class).slice(0,80)||null,label:txt(o.label).slice(0,160)||null,count:o.count==null?null:Math.max(0,Math.round(n(o.count))),confidence:Math.max(0,Math.min(1,n(o.confidence,.5))),trackKey:txt(o.trackKey||o.track_key).replace(/[^A-Za-z0-9_.:-]/g,"").slice(0,80)||null,description:txt(o.description).slice(0,1000)||null,zoneName:txt(o.zoneName||o.zone_name).slice(0,120)||null,attributes:rec(o.attributes)}});
  const events=arr(x.events).slice(0,40).map(raw=>{const e=rec(raw),severity=["info","warning","critical"].includes(txt(e.severity))?txt(e.severity):"info";return{eventType:txt(e.eventType||e.event_type,"activity").slice(0,100),severity,title:txt(e.title,"Observed activity").slice(0,240),description:txt(e.description).slice(0,1500),confidence:Math.max(0,Math.min(1,n(e.confidence,.5))),zoneName:txt(e.zoneName||e.zone_name).slice(0,120)||null,startFrameIndex:Math.max(0,Math.round(n(e.startFrameIndex||e.start_frame_index))),endFrameIndex:Math.max(0,Math.round(n(e.endFrameIndex||e.end_frame_index))),observationIndexes:arr(e.observationIndexes||e.observation_indexes).map(x=>Math.round(n(x,-1))).filter(x=>x>=0).slice(0,40),metadata:rec(e.metadata)}});
  return{sceneSummary:txt(x.sceneSummary||x.scene_summary).slice(0,2000),counts,observations,events};
}
async function analyze(c:any,b:R){
  const cameraId=txt(b.cameraId||b.camera_id);if(!/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(cameraId))throw Error("INVALID_CAMERA");
  const cr=await c.admin.from("enterprise_vision_cameras").select("id,display_name,location_label,analysis_enabled,public_feed,anonymous_tracking_enabled").eq("id",cameraId).eq("organization_id",c.organizationId).maybeSingle();
  if(cr.error||!cr.data)throw Error("CAMERA_NOT_FOUND");const cam=rec(cr.data);
  if(cam.public_feed===true)throw Error("PUBLIC_FEED_ANALYSIS_DISABLED");if(cam.analysis_enabled!==true)throw Error("CAMERA_ANALYSIS_DISABLED");
  const fs=frames(b.frames),zonesRead=await c.admin.from("enterprise_vision_zones").select("id,name,zone_kind,polygon").eq("organization_id",c.organizationId).eq("camera_id",cameraId).eq("enabled",true);if(zonesRead.error)throw Error("BACKEND_READ_FAILED");const zones=zonesRead.data||[];
  const run=await c.admin.from("enterprise_vision_analysis_runs").insert({organization_id:c.organizationId,camera_id:cameraId,requested_by:c.userId,frame_count:fs.length,status:"running",metadata:{purpose:txt(b.purpose,"live_observation").slice(0,120)}}).select("id").single();if(run.error)throw Error("BACKEND_WRITE_FAILED");const runId=txt(run.data.id),lastAt=fs[fs.length-1].capturedAt,firstAt=fs[0].capturedAt;
  const instruction='Analyze '+fs.length+' chronological frame(s) from authorized enterprise camera "'+txt(cam.display_name)+'" at "'+txt(cam.location_label)+'". Capture times: '+fs.map(f=>f.capturedAt).join(", ")+'. Configured zones: '+JSON.stringify(zones)+'. Return JSON with sceneSummary, counts, observations, events. counts must include people, vehicles, bicycles, packages for the latest frame. observations fields: observationType, objectClass, label, count, confidence, trackKey, description, zoneName, attributes. events fields: eventType, severity, title, description, confidence, zoneName, startFrameIndex, endFrameIndex, observationIndexes, metadata. Useful event types: person_entry, person_exit, vehicle_entry, vehicle_exit, line_crossing, crowding, queue, loitering, unattended_object, restricted_zone_entry, fall, collision, fight_or_physical_altercation, delivery, loading_activity, unusual_activity, after_hours_activity. Only emit visually supported events. Never infer identity or intent.';
  try{
    const provider=await modelJson(c.admin,instruction,fs),a=analysis(provider.value),requestDigest=await sha(JSON.stringify(fs.map(f=>({mimeType:f.mimeType,capturedAt:f.capturedAt,bytes:f.dataBase64.length})))),responseDigest=await sha(JSON.stringify(a)),zoneMap=new Map<string,string>();for(const z of zones)zoneMap.set(txt((z as any).name).toLowerCase(),txt((z as any).id));
    const rows=a.observations.map(o=>({organization_id:c.organizationId,camera_id:cameraId,run_id:runId,zone_id:o.zoneName?zoneMap.get(o.zoneName.toLowerCase())||null:null,observed_at:lastAt,observation_type:o.observationType,object_class:o.objectClass,label:o.label,count_value:o.count,confidence:o.confidence,track_key:cam.anonymous_tracking_enabled===true?o.trackKey:null,description:o.description,attributes:o.attributes,human_state:"machine",source_ref:"vision-run:"+runId}));
    const oi=rows.length?await c.admin.from("enterprise_vision_observations").insert(rows).select("id"):{data:[],error:null};if(oi.error)throw Error("BACKEND_WRITE_FAILED");const ids=(oi.data||[]).map((x:any)=>txt(x.id));
    const erows=a.events.map(e=>({organization_id:c.organizationId,camera_id:cameraId,run_id:runId,zone_id:e.zoneName?zoneMap.get(e.zoneName.toLowerCase())||null:null,event_type:e.eventType,severity:e.severity,title:e.title,description:e.description,confidence:e.confidence,started_at:fs[Math.min(e.startFrameIndex,fs.length-1)]?.capturedAt||firstAt,ended_at:fs[Math.min(e.endFrameIndex,fs.length-1)]?.capturedAt||lastAt,observation_ids:e.observationIndexes.map(i=>ids[i]).filter(Boolean),human_state:"machine",source_ref:"vision-run:"+runId,metadata:e.metadata}));
    const ei=erows.length?await c.admin.from("enterprise_vision_events").insert(erows).select("id,event_type,severity,title,started_at"):{data:[],error:null};if(ei.error)throw Error("BACKEND_WRITE_FAILED");
    const baserows=[{organization_id:c.organizationId,camera_id:cameraId,run_id:runId,observed_at:lastAt,observation_type:"scene_summary",object_class:"scene",label:"scene",description:a.sceneSummary,attributes:{counts:a.counts},human_state:"machine",source_ref:"vision-run:"+runId},{organization_id:c.organizationId,camera_id:cameraId,run_id:runId,observed_at:lastAt,observation_type:"people_count",object_class:"person",count_value:a.counts.people,description:a.counts.people+" people visible in latest analyzed frame.",attributes:{},human_state:"machine",source_ref:"vision-run:"+runId},{organization_id:c.organizationId,camera_id:cameraId,run_id:runId,observed_at:lastAt,observation_type:"vehicle_count",object_class:"vehicle",count_value:a.counts.vehicles,description:a.counts.vehicles+" vehicles visible in latest analyzed frame.",attributes:{},human_state:"machine",source_ref:"vision-run:"+runId}];
    await c.admin.from("enterprise_vision_observations").insert(baserows);
    await c.admin.from("enterprise_vision_analysis_runs").update({status:"succeeded",provider:provider.provider,model:provider.model,request_sha256:requestDigest,response_sha256:responseDigest,completed_at:new Date().toISOString()}).eq("id",runId);
    await c.admin.from("enterprise_vision_cameras").update({source_status:"live",last_frame_at:lastAt,last_analysis_at:new Date().toISOString(),source_observed_at:new Date().toISOString(),source_message:"Authorized camera analysis completed.",updated_at:new Date().toISOString()}).eq("id",cameraId);
    return{runId,provider:provider.provider,model:provider.model,machineObservation:true,verifiedFact:false,sceneSummary:a.sceneSummary,counts:a.counts,observationsCreated:rows.length+3,events:ei.data||[]};
  }catch(e){await c.admin.from("enterprise_vision_analysis_runs").update({status:"failed",completed_at:new Date().toISOString(),error_code:e instanceof Error?e.message.slice(0,120):"unexpected"}).eq("id",runId);throw e}
}
function plan(v:unknown){const x=rec(v),allowed=new Set(["latest","search","count_latest","count_events","trend","first_seen","incident_report","request_clip","create_rule"]);return{operation:allowed.has(txt(x.operation))?txt(x.operation):"search",query:txt(x.query).slice(0,240)||null,minutes:Math.max(1,Math.min(10080,Math.round(n(x.minutes,60)))),eventTypes:arr(x.eventTypes||x.event_types).map(s=>txt(s).slice(0,100)).filter(Boolean).slice(0,16),objectClasses:arr(x.objectClasses||x.object_classes).map(s=>txt(s).slice(0,80)).filter(Boolean).slice(0,16),trackKey:txt(x.trackKey||x.track_key).replace(/[^A-Za-z0-9_.:-]/g,"").slice(0,80)||null,severity:["info","warning","critical"].includes(txt(x.severity))?txt(x.severity):"warning",ruleName:txt(x.ruleName||x.rule_name).slice(0,160)||null}}
async function query(c:any,message:string,b:R){
  const rawCam=txt(b.cameraId||b.camera_id)||null,cameraId=rawCam&&/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(rawCam)?rawCam:null;
  const p=plan((await modelJson(c.admin,'Classify this owner request about stored Vision Intelligence evidence. Return JSON with operation, query, minutes, eventTypes, objectClasses, trackKey, severity, ruleName. operation is latest, search, count_latest, count_events, trend, first_seen, incident_report, request_clip, or create_rule. latest means what is happening now. count_latest means how many are visible now. count_events means passed/entered/exited totals. trend means busier/quieter. first_seen requires an explicit anonymous track key. request_clip means save/show/extract footage. create_rule means future alert/watch instructions. minutes defaults to 60. Selected camera: '+(cameraId||"none")+'. Request: '+message)).value);
  const end=new Date(),start=new Date(end.getTime()-p.minutes*60000);
  if(p.operation==="first_seen"&&!p.trackKey)return{reply:"Select a tracked subject or provide its anonymous track key first. Pandora will not guess which person you mean.",plan:p,providerReadback:{verified:true,source:"vision_store",observationState:"machine"}};
  if(p.operation==="request_clip"){if(!cameraId)return{reply:"Choose a camera first so Pandora knows which authorized recording should supply the clip.",plan:p,providerReadback:{verified:true,source:"vision_clip_queue"}};const x=await c.user.rpc("pandora_vision_request_clip_v1",{p_organization_id:c.organizationId,p_camera_id:cameraId,p_start_at:start.toISOString(),p_end_at:end.toISOString(),p_reason:message.slice(0,1000),p_event_id:null});if(x.error)throw Error("CLIP_REQUEST_FAILED");return{reply:"Clip extraction has been requested for the selected authorized camera.",plan:p,clipRequest:x.data,providerReadback:{verified:true,source:"vision_clip_queue"}}}
  if(p.operation==="create_rule"){if(!cameraId)return{reply:"Choose a camera first so Pandora can scope that alert rule.",plan:p,providerReadback:{verified:true,source:"vision_rules"}};const types=p.eventTypes.length?p.eventTypes:[p.query?p.query.replace(/\s+/g,"_").toLowerCase():"unusual_activity"],x=await c.admin.from("enterprise_vision_rules").insert({organization_id:c.organizationId,camera_id:cameraId,name:p.ruleName||("Pandora alert · "+types.join(", ")).slice(0,160),event_types:types,severity:p.severity,min_confidence:.65,notify_roles:["owner","admin"],enabled:true,created_by:c.userId}).select("id,name,event_types,severity,enabled").single();if(x.error)throw Error("RULE_CREATE_FAILED");return{reply:"Alert rule created for "+types.join(", ")+".",plan:p,rule:x.data,providerReadback:{verified:true,source:"vision_rules"}}}
  const term=p.trackKey||p.query||(p.eventTypes[0]||p.objectClasses[0]||null),s=await c.user.rpc("pandora_vision_search_v1",{p_organization_id:c.organizationId,p_query:term,p_camera_id:cameraId,p_start_at:start.toISOString(),p_end_at:end.toISOString(),p_limit:180});if(s.error)throw Error("VISION_SEARCH_FAILED");const data=rec(s.data),events=arr(data.events).map(rec),observations=arr(data.observations).map(rec);
  if(p.operation==="count_latest"){const wanted=p.objectClasses[0]||p.query||"person",kind=/vehicle|car|truck|van|bus/i.test(wanted)?"vehicle_count":"people_count",xs=observations.filter(o=>txt(o.observationType)===kind).sort((a,b)=>Date.parse(txt(b.observedAt))-Date.parse(txt(a.observedAt))),latest=xs[0],value=latest?Math.max(0,Math.round(n(latest.count))):null;return{reply:value==null?"No matching analyzed count is available yet.":value+" "+(kind==="vehicle_count"?"vehicles":"people")+" were visible in the latest analyzed frame. This is a machine observation, not a human-verified fact.",plan:p,evidence:{events:[],observations:latest?[latest]:[]},providerReadback:{verified:true,source:"vision_store",observationState:"machine"}}}
  if(p.operation==="count_events"){const xs=p.eventTypes.length?events.filter(e=>p.eventTypes.includes(txt(e.eventType))):events;return{reply:xs.length+" matching recorded Vision event"+(xs.length===1?"":"s")+" were found in the last "+p.minutes+" minutes.",plan:p,evidence:{events:xs,observations:[]},providerReadback:{verified:true,source:"vision_store"}}}
  if(p.operation==="trend"){const kind=/vehicle|car|truck/i.test(p.query||"")?"vehicle_count":"people_count",points=observations.filter(o=>txt(o.observationType)===kind&&Number.isFinite(Number(o.count))).map(o=>({at:Date.parse(txt(o.observedAt)),count:n(o.count)})).filter(x=>Number.isFinite(x.at)).sort((a,b)=>a.at-b.at);if(points.length<2)return{reply:"Pandora does not yet have enough analyzed count samples to establish a trend.",plan:p,evidence:{events:[],observations},providerReadback:{verified:true,source:"vision_store"}};const mid=start.getTime()+(end.getTime()-start.getTime())/2,avg=(xs:any[])=>xs.length?xs.reduce((sum,x)=>sum+x.count,0)/xs.length:0,a=avg(points.filter(x=>x.at<mid)),bavg=avg(points.filter(x=>x.at>=mid)),delta=bavg-a,direction=Math.abs(delta)<.75?"roughly stable":delta>0?"increasing":"decreasing";return{reply:"Activity is "+direction+". Average visible "+(kind==="vehicle_count"?"vehicles":"people")+" changed from "+a.toFixed(1)+" to "+bavg.toFixed(1)+".",plan:p,evidence:{events:[],observations},providerReadback:{verified:true,source:"vision_store",observationState:"machine"}}}
  if(p.operation==="first_seen"){const xs=observations.filter(o=>txt(o.trackKey)===p.trackKey).sort((a,b)=>Date.parse(txt(a.observedAt))-Date.parse(txt(b.observedAt))),first=xs[0];return{reply:first?"Anonymous track "+p.trackKey+" first appears at "+txt(first.observedAt)+". Pandora is not identifying the person.":"No stored observation was found for anonymous track "+p.trackKey+".",plan:p,evidence:{events:[],observations:first?[first]:[]},providerReadback:{verified:true,source:"vision_store",observationState:"machine"}}}
  const context={request:message,window:{startAt:start.toISOString(),endAt:end.toISOString()},plan:p,events:events.slice(0,60),observations:observations.slice(0,80)},ans=rec((await modelJson(c.admin,"Answer the owner only from this stored Vision evidence. Do not claim machine observations are human-verified. If evidence is insufficient, say so. Return JSON with reply and, for incident_report only, incidentTitle, incidentSummary, severity. Evidence: "+JSON.stringify(context))).value),answer=txt(ans.reply,"No matching analyzed Vision evidence is available.");let incident=null;
  if(p.operation==="incident_report"&&events.length){const title=txt(ans.incidentTitle||ans.incident_title,"Vision incident report").slice(0,240),summary=txt(ans.incidentSummary||ans.incident_summary,answer).slice(0,6000),severity=["info","warning","critical"].includes(txt(ans.severity))?txt(ans.severity):"warning",created=await c.admin.from("enterprise_vision_incidents").insert({organization_id:c.organizationId,title,summary,severity,status:"reviewing",started_at:txt(events[events.length-1]?.startedAt,start.toISOString()),ended_at:txt(events[0]?.endedAt||events[0]?.startedAt,end.toISOString()),event_ids:events.map(e=>txt(e.id)).filter(Boolean).slice(0,100),report:{machineGenerated:true,verified:false,evidenceWindow:context.window},created_by:c.userId}).select("id,title,severity,status,created_at").single();if(!created.error)incident=created.data}
  return{reply:answer,plan:p,evidence:{events,observations},incident,providerReadback:{verified:true,source:"vision_store",machineGenerated:true}};
}
async function register(c:any,b:R){const key=txt(b.cameraKey||b.camera_key).toLowerCase(),name=txt(b.displayName||b.display_name),sourceType=txt(b.sourceType||b.source_type),publicFeed=b.publicFeed===true||b.public_feed===true,analysisEnabled=b.analysisEnabled===true||b.analysis_enabled===true;if(!/^[a-z0-9][a-z0-9._-]{1,79}$/.test(key)||!name||name.length>160||!["rtsp","onvif","nvr","upload","edge_agent","provider_embed"].includes(sourceType))throw Error("INVALID_CAMERA");if(publicFeed&&analysisEnabled)throw Error("PUBLIC_FEED_ANALYSIS_DISABLED");const sourceRef=txt(b.sourceRef||b.source_ref).slice(0,500)||null;if(secret(sourceRef))throw Error("CREDENTIAL_MATERIAL_REJECTED");const x=await c.admin.from("enterprise_vision_cameras").upsert({organization_id:c.organizationId,camera_key:key,display_name:name,location_label:txt(b.locationLabel||b.location_label).slice(0,240)||null,source_type:sourceType,source_ref:sourceRef,source_status:txt(b.sourceStatus||b.source_status,"disconnected"),analysis_enabled:analysisEnabled&&!publicFeed,public_feed:publicFeed,biometric_identification_enabled:false,anonymous_tracking_enabled:b.anonymousTrackingEnabled!==false,retention_hours:Math.max(0,Math.min(8760,Math.round(n(b.retentionHours||b.retention_hours,72)))),analysis_interval_seconds:Math.max(1,Math.min(3600,Math.round(n(b.analysisIntervalSeconds||b.analysis_interval_seconds,10)))),created_by:c.userId,updated_at:new Date().toISOString()},{onConflict:"organization_id,camera_key"}).select("id,camera_key,display_name,location_label,source_type,source_status,analysis_enabled,public_feed,anonymous_tracking_enabled,retention_hours,analysis_interval_seconds").single();if(x.error)throw Error("CAMERA_REGISTER_FAILED");return x.data}
async function rule(c:any,b:R){const name=txt(b.name),types=arr(b.eventTypes||b.event_types).map(x=>txt(x).slice(0,100)).filter(Boolean).slice(0,24);if(!name||name.length>160||!types.length)throw Error("INVALID_RULE");const x=await c.admin.from("enterprise_vision_rules").insert({organization_id:c.organizationId,camera_id:txt(b.cameraId||b.camera_id)||null,name,event_types:types,min_confidence:Math.max(0,Math.min(1,n(b.minConfidence||b.min_confidence,.65))),min_count:b.minCount==null?null:Math.max(1,Math.round(n(b.minCount))),dwell_seconds:b.dwellSeconds==null?null:Math.max(0,Math.round(n(b.dwellSeconds))),severity:["info","warning","critical"].includes(txt(b.severity))?txt(b.severity):"warning",notify_roles:["owner","admin"],enabled:b.enabled!==false,created_by:c.userId}).select("id,name,event_types,severity,enabled").single();if(x.error)throw Error("RULE_CREATE_FAILED");return x.data}
function publicError(e:unknown){const code=e instanceof Error?e.message:"UNEXPECTED",m:R={SIGN_IN_REQUIRED:[401,"Please sign in again."],ORGANIZATION_ACCESS_REQUIRED:[403,"This account cannot access that organization."],ORGANIZATION_SELECTION_REQUIRED:[409,"Choose an organization first."],OWNER_ROLE_REQUIRED:[403,"Owner or admin access is required."],RATE_LIMITED:[429,"Pandora Vision is receiving many requests. Try again shortly."],BODY_TOO_LARGE:[413,"That Vision request is too large."],INVALID_JSON:[400,"Pandora could not read that Vision request."],INVALID_ACTION:[400,"That Vision action is not supported."],INVALID_MESSAGE:[400,"Enter a Vision Intelligence question."],INVALID_FRAMES:[400,"One or more camera frames are invalid."],FRAMES_TOO_LARGE:[413,"Those camera frames are too large for one analysis turn."],INVALID_CAMERA:[400,"That camera configuration is invalid."],CAMERA_NOT_FOUND:[404,"That camera is not available in this organization."],CAMERA_ANALYSIS_DISABLED:[409,"Analysis is disabled for that camera."],PUBLIC_FEED_ANALYSIS_DISABLED:[403,"Automated analysis is disabled for public third-party feeds."],INVALID_RULE:[400,"That alert rule is invalid."],CREDENTIAL_MATERIAL_REJECTED:[400,"Credentials cannot be sent through Vision Intelligence."],PROVIDER_UNAVAILABLE:[503,"Vision analysis is temporarily unavailable."]};return{code,p:(m[code]||[500,"Pandora Vision could not complete that request safely."]) as [number,string]}}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return reply({ok:false,plainMessage:"Use POST for Vision Intelligence."},405);try{const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>900000)throw Error("BODY_TOO_LARGE");let parsed;try{parsed=JSON.parse(raw)}catch{throw Error("INVALID_JSON")}const b=rec(parsed),action=txt(b.action);if(secret(b))throw Error("CREDENTIAL_MATERIAL_REJECTED");if(!["overview","analyze","query","register_camera","create_rule","request_clip","verify_observation","ack_alert"].includes(action))throw Error("INVALID_ACTION");const c=await auth(req);await rate(c.admin,c.organizationId,c.userId);if(action==="overview"){const x=await c.user.rpc("pandora_vision_overview_v1",{p_organization_id:c.organizationId});if(x.error)throw Error("BACKEND_READ_FAILED");return reply({ok:true,overview:x.data})}if(action==="analyze")return reply({ok:true,result:await analyze(c,b)});if(action==="query"){const message=txt(b.message);if(!message||message.length>4000)throw Error("INVALID_MESSAGE");return reply({ok:true,...await query(c,message,b)})}if(action==="register_camera")return reply({ok:true,camera:await register(c,b)});if(action==="create_rule")return reply({ok:true,rule:await rule(c,b)});if(action==="request_clip"){const x=await c.user.rpc("pandora_vision_request_clip_v1",{p_organization_id:c.organizationId,p_camera_id:txt(b.cameraId||b.camera_id),p_start_at:txt(b.startAt||b.start_at),p_end_at:txt(b.endAt||b.end_at),p_reason:txt(b.reason,"Vision clip request"),p_event_id:txt(b.eventId||b.event_id)||null});if(x.error)throw Error("CLIP_REQUEST_FAILED");return reply({ok:true,clipRequest:x.data})}if(action==="verify_observation"){const x=await c.user.rpc("pandora_vision_verify_observation_v1",{p_organization_id:c.organizationId,p_observation_id:txt(b.observationId||b.observation_id),p_state:txt(b.state)});if(x.error)throw Error("VERIFY_FAILED");return reply({ok:true,observation:x.data})}if(action==="ack_alert"){const x=await c.user.rpc("pandora_vision_ack_alert_v1",{p_organization_id:c.organizationId,p_alert_id:txt(b.alertId||b.alert_id),p_status:txt(b.status,"acknowledged")});if(x.error)throw Error("ALERT_UPDATE_FAILED");return reply({ok:true,alert:x.data})}throw Error("INVALID_ACTION")}catch(e){console.error("pandora-vision-intelligence",e instanceof Error?e.message:"unexpected");const x=publicError(e);return reply({ok:false,code:x.code,plainMessage:x.p[1]},x.p[0])}});
