'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
let api,http,Provider,NativeStore;const ORG='00000000-0000-4000-8000-000000000001',PROJECT='00000000-0000-4000-8000-000000000002',USER='00000000-0000-4000-8000-000000000003',REQUEST='00000000-0000-4000-8000-000000000004';
const token='opw_'+'a'.repeat(43),URL='https://jcyqixttuebxqqfkjonq.supabase.co/functions/v1/pandora-intelligence-router/';
test.before(async()=>{api=await import('../packages/pandora-operations-inference/policy.mjs');http=await import('../packages/pandora-operations-inference/http-handler.mjs');Provider=(await import('../packages/pandora-operations-inference/gemini-native.mjs')).GeminiNativeProvider;NativeStore=(await import('../packages/pandora-operations-inference/native-store.mjs')).NativeInferenceStore;});
function harness({owner={userId:USER,active:true},authError=null,serviceError=null}={}){const calls=[];const store={durability:'durable',authenticate:async digest=>{calls.push(['authenticate',digest]);if(authError)throw authError;return{organizationId:ORG,projectId:PROJECT,workerId:'fixture',principalKey:'fixture',callerDigest:digest};},events:async payload=>{calls.push(['events',payload]);return{events:[],syntheticProgress:false};}};const service={infer:async(actor,payload)=>{calls.push(['infer',actor,payload]);if(serviceError)throw serviceError;return{state:'verification_pending',taskComplete:false};},status:async(actor,id)=>{calls.push(['status',id]);return{state:'executing',taskComplete:false};},cancel:async(actor,id)=>{calls.push(['cancel',id]);return{state:'cancel_requested',providerStopped:false};},verify:async()=>{throw new api.InferenceError('INFERENCE_CANONICAL_VERIFICATION_REQUIRED');}};return{calls,handler:http.createInferenceHandler({store,serviceForActor:()=>({service,memory:null}),authenticateOwner:async jwt=>{calls.push(['owner',jwt]);return owner;},allowedOrigins:['https://owner.example.test']})};}
function request(route='infer',payload={},extra={}){return new Request(URL+route,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json',...extra.headers},body:JSON.stringify(payload),...extra,headers:{authorization:'Bearer '+token,'content-type':'application/json',...extra.headers}});}
test('worker authentication is hashed and evaluated before payload processing',async()=>{const h=harness();const response=await h.handler(request('infer',{safe:'fixture'}));assert.equal(response.status,202);assert.equal(h.calls[0][0],'authenticate');assert.equal(h.calls[0][1],api.sha256(token));assert.equal(JSON.stringify(h.calls).includes(token),false);});
for(const auth of ['', 'Basic whatever','Bearer owner-jwt-that-is-not-a-worker-token','Bearer opw_short'])test(`reject worker credential shape ${auth.slice(0,20)}`,async()=>{const h=harness();const response=await h.handler(request('infer',{}, {headers:{authorization:auth}}));assert.equal(response.status,401);assert.equal(h.calls.length,0);});
test('credential revocation is enforced before service call',async()=>{const h=harness({authError:new api.InferenceError('INFERENCE_CALLER_DENIED')});const response=await h.handler(request());assert.equal(response.status,401);assert.equal(h.calls.length,1);});
test('unapproved browser origin never reaches authentication',async()=>{const h=harness();assert.equal((await h.handler(request('infer',{}, {headers:{origin:'https://unapproved.test'}}))).status,403);assert.equal(h.calls.length,0);});
test('approved preflight describes transport only and executes no work',async()=>{const h=harness();const response=await h.handler(new Request(URL+'infer',{method:'OPTIONS',headers:{origin:'https://owner.example.test'}}));assert.equal(response.status,204);assert.equal(response.headers.get('access-control-allow-origin'),'https://owner.example.test');assert.equal(h.calls.length,0);});
test('wrong route and method are denied',async()=>{const h=harness();assert.equal((await h.handler(new Request(URL+'infer'))).status,405);assert.equal((await h.handler(request('unknown'))).status,404);assert.equal((await h.handler(request('status?x=1'))).status,404);});
for(const body of ['{','\u0000','true'])test(`malformed or nonscoped body ${JSON.stringify(body)}`,async()=>{const h=harness();const response=await h.handler(new Request(URL+'status',{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body}));assert.equal(response.status,400);});
test('oversized advertised body is rejected without parsing',async()=>{const h=harness();assert.equal((await h.handler(request('status',{}, {headers:{'content-length':'10000000'}}))).status,413);});
test('body content type is mandatory',async()=>{const h=harness();assert.equal((await h.handler(request('status',{}, {headers:{'content-type':'text/plain'}}))).status,400);});
test('arbitrary internal provider messages are not returned',async()=>{const h=harness({serviceError:new Error('private server diagnostic SECRET')});const response=await h.handler(request());const body=await response.text();assert.equal(response.status,503);assert.equal(body.includes('SECRET'),false);});
test('existing canonical verification cannot be replaced by worker JSON',async()=>{const h=harness();const response=await h.handler(request('verify',{requestId:REQUEST,verificationRunId:USER,verified:true}));assert.equal(response.status,400);});
test('owner events derive the user from authentication rather than an actor payload',async()=>{const h=harness();const response=await h.handler(request('events',{organizationId:ORG,projectId:PROJECT,after:'9007199254740993',limit:100}));assert.equal(response.status,200);const eventCall=h.calls.find(x=>x[0]==='events');assert.equal(eventCall[1].userId,USER);assert.equal(eventCall[1].after,'9007199254740993');assert.equal(h.calls.some(x=>x[0]==='authenticate'),false);});
test('forged owner identity in event body is rejected',async()=>{const h=harness();assert.equal((await h.handler(request('events',{organizationId:ORG,projectId:PROJECT,after:'0',limit:100,userId:USER}))).status,400);});
for(const patch of [{after:1},{after:'01'},{after:'9223372036854775808'},{limit:201},{organizationId:'other'}])test(`reject event shape ${JSON.stringify(patch)}`,async()=>{const h=harness();const response=await h.handler(request('events',{organizationId:ORG,projectId:PROJECT,after:'0',limit:100,...patch}));assert.equal(response.status,400);});
test('streaming JSON read enforces actual bytes rather than trusting Content-Length',async()=>{const req=new Request(URL+'infer',{method:'POST',headers:{'content-type':'application/json'},body:'{"text":"'+'x'.repeat(300)+'"}'});await assert.rejects(()=>http.readJson(req,{maxBytes:100}),/BODY_LIMIT/);});
test('hung body is bounded and reader is cancelled',async()=>{let cancelled=false;const body=new ReadableStream({pull(){return new Promise(()=>{});},cancel(){cancelled=true;}});const req=new Request(URL+'infer',{method:'POST',headers:{'content-type':'application/json'},body,duplex:'half'});await assert.rejects(()=>http.readJson(req,{timeoutMs:20}),/TIMEOUT/);await Promise.resolve();assert.equal(cancelled,true);});
const input=()=>({taskClass:'complex_coding',parts:[{type:'text',text:'fixture'}],maxOutputTokens:128,deadlineMs:1000,memoryContext:''});
const model=()=>({provider:'gemini',transport:'gemini_rpc',executionBoundary:'cloud',model:'fixture-only',modelRevision:null});
const providerBody=()=>({candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'internal reasoning fixture'},{text:'Answer'}]}}],modelVersion:'fixture-v1',usageMetadata:{promptTokenCount:5,candidatesTokenCount:2,totalTokenCount:7}});
function providerHarness(status=200,body=providerBody()){let count=0,args;const p=new Provider({supabaseUrl:'https://jcyqixttuebxqqfkjonq.supabase.co',rpc:async(name,payload)=>{count++;args={name,payload};return{data:{status,body},error:null};}});return{p,count:()=>count,args:()=>args};}
test('Gemini uses the existing fixed Vault-backed RPC with actual response digest, not credentials',async()=>{const h=providerHarness();const r=await h.p.execute(input(),model());assert.equal(h.args().name,'pandora_worker_b_gemini_request_20260829');assert.equal(r.output,'Answer');assert.equal(r.receipt.outputDigest,api.sha256('Answer'));assert.equal(r.receipt.billedCostMicros,null);assert.equal(r.receipt.usage.totalTokens,7);assert.equal(r.receipt.providerReceipt,'gemini-http-200-sha256:'+api.sha256(providerBody()));});
for(const [status,code]of[[429,'rate_limit'],[401,'permission_denied'],[403,'permission_denied'],[503,'unavailable']])test(`provider HTTP ${status} preserves failure classification`,async()=>{const h=providerHarness(status,{error:{message:'do not leak this message'}});const r=await h.p.execute(input(),model());assert.equal(r.output,null);assert.equal(r.receipt.code,code);assert.equal(JSON.stringify(r).includes('do not leak'),false);});
for(const reason of ['SAFETY','PROHIBITED_CONTENT','BLOCKLIST','RECITATION'])test(`provider ${reason} is not a successful or automatically reroutable result`,async()=>{const b=providerBody();b.candidates[0].finishReason=reason;const h=providerHarness(200,b);assert.equal((await h.p.execute(input(),model())).receipt.code,'safety_refusal');});
test('truncated output does not count as a valid response',async()=>{const b=providerBody();b.candidates[0].finishReason='MAX_TOKENS';assert.equal((await providerHarness(200,b).p.execute(input(),model())).receipt.code,'invalid_output');});
test('configured model revision mismatch is explicit',async()=>{const r=await providerHarness().p.execute(input(),{...model(),modelRevision:'different'});assert.equal(r.receipt.code,'model_revision_mismatch');assert.equal(r.output,null);});
test('structured extraction requires actual valid JSON',async()=>{const r=await providerHarness().p.execute({...input(),taskClass:'structured_extraction'},model());assert.equal(r.receipt.code,'invalid_output');});
test('unreported token metrics stay null',async()=>{const b=providerBody();delete b.usageMetadata;const r=await providerHarness(200,b).p.execute(input(),model());assert.deepEqual(r.receipt.usage,{inputTokens:null,outputTokens:null,totalTokens:null});});
test('provider refuses phone-private before any transport',async()=>{const h=providerHarness();await assert.rejects(()=>h.p.execute({...input(),taskClass:'local_private'},model()),/SCOPE_DENIED/);assert.equal(h.count(),0);});
test('provider rejects credential-shaped output without echoing it',async()=>{const b=providerBody();b.candidates[0].content.parts=[{text:'ghp_'+'X'.repeat(24)}];const r=await providerHarness(200,b).p.execute(input(),model());assert.equal(r.receipt.code,'invalid_output');assert.equal(r.output,null);});
test('native store rejects noncanonical targets',()=>{for(const url of ['https://example.test','http://jcyqixttuebxqqfkjonq.supabase.co','https://jcyqixttuebxqqfkjonq.supabase.co/?x=1'])assert.throws(()=>new NativeStore({supabaseUrl:url,rpc(){}}),/TARGET_DENIED/);});
test('unknown provider transport error remains unknown, not a billed-zero failure',async()=>{const p=new Provider({supabaseUrl:'https://jcyqixttuebxqqfkjonq.supabase.co',rpc:async()=>({error:{message:'private'},data:null})});await assert.rejects(()=>p.execute(input(),model()),e=>e.code==='INFERENCE_PROVIDER_OUTCOME_UNKNOWN'&&e.outcomeUnknown===true);});
