
const test=require('node:test');const assert=require('node:assert/strict');
const modules=Promise.all([import('../packages/pandora-operations-memory/workload-rpc.mjs'),import('../packages/pandora-operations-memory/owner-read.mjs'),import('../packages/pandora-operations-inference/vercel-runtime.mjs')]);
const token=()=>['fixture'.repeat(12),'body'.repeat(15),'signature'.repeat(9)].join('.');
const args=m=>({p_memory_user_id:m.memoryUserId,p_namespace:m.namespace,p_project_id:m.memoryProjectId,p_principal_key:m.principalKey,p_environment:m.environment,p_operation:'context',p_payload:{}});
const success=b=>Response.json({ok:true,requestId:b.requestId,operation:b.operation,projectId:b.projectId,namespace:b.namespace,memoryProjectRef:'ivmvufhcsezyhczzondn',data:{fixture:true}});
async function transport(fetchFn,extra={}){const [a,b]=await modules;return new a.WorkloadOperationsMemoryRpc({mapping:b.OPERATIONS_MEMORY_MAPPING,resolveWorkloadToken:async()=>token(),fetchFn,...extra});}
for(const operation of ['context','propose_outcome','readback'])test(`workload ${operation} forwards one fixed request without caller identity or service keys`,async()=>{
 const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;let count=0;
 const c=await transport(async(url,init)=>{count++;assert.equal(url,'https://ivmvufhcsezyhczzondn.supabase.co/functions/v1/pandora-memory-bridge');assert.equal(init.redirect,'error');
  assert.equal(init.headers['x-pandora-vercel-oidc'],token());assert.equal(init.headers.apikey,undefined);assert.equal(init.headers.authorization,undefined);
  const b=JSON.parse(init.body);assert.deepEqual(Object.keys(b).sort(),['action','namespace','operation','payload','projectId','requestId'].sort());assert.equal(b.operation,operation);return success(b);});
 const pending=c.rpc('memory_operations_bridge_v1',{...args(m),p_operation:operation});const [one,two]=await Promise.all([pending,pending]);assert.deepEqual(one.data,{fixture:true});assert.deepEqual(one,two);assert.equal(count,1);
});
test('performance fixed RPC maps to read-only performance operation',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;
 const c=await transport(async(_url,init)=>{const b=JSON.parse(init.body);assert.equal(b.operation,'performance');assert.equal(b.payload.taskClass,'complex_coding');return success(b);});
 const {p_operation,p_payload,...rest}=args(m);const r=await c.rpc('memory_operations_performance_v1',{...rest,p_request:{taskClass:'complex_coding'}});assert.equal(r.error,null);
});
for(const key of ['p_memory_user_id','p_project_id','p_principal_key','p_namespace','p_environment'])test(`caller cannot override ${key}`,async()=>{
 const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(()=>assert.fail('unauthorized provider call'));
 assert.throws(()=>c.rpc('memory_operations_bridge_v1',{...args(m),[key]:'wrong'}),/MAPPING_MISMATCH/);
});
for(const name of ['arbitrary_sql','memory_approve','memory_operations_bridge_v2'])test(`RPC catalogue denies ${name}`,async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(()=>assert.fail());assert.throws(()=>c.rpc(name,args(m)),/RPC_DENIED/);});
for(const key of ['sql','destination','serviceRoleKey'])test(`extra ${key} rejected`,async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(()=>assert.fail());assert.throws(()=>c.rpc('memory_operations_bridge_v1',{...args(m),[key]:'untrusted'}),/FIELDS_INVALID/);});
for(const key of ['requestId','operation','projectId','namespace','memoryProjectRef'])test(`wrong receipt ${key} is rejected and retains uncertain write`,async()=>{
 const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(async(_url,init)=>{const r=await success(JSON.parse(init.body)).json();r[key]='wrong';return Response.json(r);});
 await assert.rejects(c.rpc('memory_operations_bridge_v1',{...args(m),p_operation:'propose_outcome'}),e=>e.code==='OPS_MEMORY_WORKLOAD_RECEIPT_MISMATCH'&&e.outcomeUnknown===true);
});
test('definite native denial is definite and never retried',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;let calls=0;const c=await transport(async()=>{calls++;return Response.json({ok:false,error:'OPS_MEMORY_GRANT_DENIED',outcomeUnknown:false},{status:403});});
 await assert.rejects(c.rpc('memory_operations_bridge_v1',{...args(m),p_operation:'propose_outcome'}),e=>e.code==='OPS_MEMORY_GRANT_DENIED'&&!e.outcomeUnknown);assert.equal(calls,1);
});
test('uncertain provider failure remains unknown and hides provider diagnostics',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;let calls=0;const c=await transport(async()=>{calls++;return Response.json({ok:false,error:'private provider details'},{status:502});});
 await assert.rejects(c.rpc('memory_operations_bridge_v1',{...args(m),p_operation:'propose_outcome'}),e=>e.code==='OPS_MEMORY_PROVIDER_REJECTED'&&e.outcomeUnknown);assert.equal(calls,1);
});
test('unprovisioned workload identity fails before network',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(()=>assert.fail(),{resolveWorkloadToken:async()=>undefined});await assert.rejects(c.rpc('memory_operations_bridge_v1',args(m)),/WORKLOAD_IDENTITY_UNAVAILABLE/);});
test('deadline prevents a provider that never resolves from retaining the request',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(()=>new Promise(()=>{}),{timeoutMs:10});await assert.rejects(c.rpc('memory_operations_bridge_v1',{...args(m),p_operation:'propose_outcome'}),e=>e.code==='OPS_MEMORY_TIMEOUT'&&e.outcomeUnknown);});
test('abort before send does not invoke workload resolver or provider',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(()=>assert.fail(),{resolveWorkloadToken:()=>assert.fail()});await assert.rejects(c.rpc('memory_operations_bridge_v1',args(m)).abortSignal(AbortSignal.abort()),e=>e.code==='OPS_MEMORY_CANCELLED'&&!e.outcomeUnknown);});
test('abort after provider send preserves mutation uncertainty',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const controller=new AbortController();const c=await transport(async()=>{controller.abort();return new Promise(()=>{});});await assert.rejects(c.rpc('memory_operations_bridge_v1',{...args(m),p_operation:'propose_outcome'}).abortSignal(controller.signal),e=>e.code==='OPS_MEMORY_CANCELLED'&&e.outcomeUnknown);});
test('stream body has a byte cap even with no Content-Length',async()=>{const [,{OPERATIONS_MEMORY_MAPPING:m}]=await modules;const c=await transport(async()=>new Response('x'.repeat(49000)));await assert.rejects(c.rpc('memory_operations_bridge_v1',{...args(m),p_operation:'propose_outcome'}),e=>e.code==='OPS_MEMORY_RESPONSE_INVALID'&&e.outcomeUnknown);});
test('actual Native client factory binds all four methods',async()=>{const [a,b]=await modules;const m=a.createWorkloadOperationsMemory({mapping:b.OPERATIONS_MEMORY_MAPPING,resolveWorkloadToken:async()=>token(),fetchFn:()=>assert.fail()});for(const name of ['getTaskContext','getPerformance','proposeOutcome','reconcileOutcome'])assert.equal(typeof m[name],'function');});
async function ownerFixture({role='owner',userId='33e5b2de-048b-4814-b601-7d7daac7a649',revoke=false}={}){
 const [,b]=await modules;const calls=[];let resolutions=0;
 const run=b.createOwnerMemoryRead({authenticator:{authenticate:async()=>({userId,accessToken:token(),scopeClaimsPresent:false})},membershipResolver:{resolve:async(organizationId,id)=>{resolutions++;return {organizationId,userId:id,role:revoke&&resolutions>1?'viewer':role};}},memory:{getTaskContext:async(scope,q)=>{calls.push({scope,q});return {state:'available',authorizationGranted:false};},getPerformance:async(scope,q)=>{calls.push({scope,q});return {state:'insufficient_history',authorizationGranted:false};}}});return {run,calls};
}
for(const operation of ['context','performance'])test(`owner can read ${operation} but receives no authorization`,async()=>{const f=await ownerFixture();const r=await f.run('Bearer '+token(),{operation,request:operation==='context'?{intent:'coding_building',actionMode:'read_only'}:{taskClass:'complex_coding'}});assert.equal(r.ok,true);assert.equal(r.authorizationGranted,false);assert.equal(f.calls.length,1);});
for(const role of ['operator','member','viewer'])test(`${role} cannot use owner Memory route`,async()=>{const f=await ownerFixture({role});await assert.rejects(f.run('Bearer '+token(),{operation:'performance',request:{taskClass:'complex_coding'}}),/OWNER_SCOPE_DENIED/);assert.equal(f.calls.length,0);});
test('owner revocation during a read prevents data release',async()=>{const f=await ownerFixture({revoke:true});await assert.rejects(f.run('Bearer '+token(),{operation:'performance',request:{taskClass:'complex_coding'}}),/OWNER_SCOPE_DENIED/);});
for(const operation of ['propose_outcome','readback','approve'])test(`public owner route cannot ${operation}`,async()=>{const f=await ownerFixture();await assert.rejects(f.run('Bearer '+token(),{operation,request:{}}),/OWNER_OPERATION_DENIED/);assert.equal(f.calls.length,0);});
test('owner route rejects source/mapping injection',async()=>{const f=await ownerFixture();await assert.rejects(f.run('Bearer '+token(),{operation:'context',request:{},projectId:'elsewhere'}),/FIELDS_INVALID/);});
const box='https://jcyqixttuebxqqfkjonq.supabase.co';
test('server RPC refuses noncanonical target and arbitrary function',async()=>{const [,,a]=await modules;assert.throws(()=>new a.VercelInferenceRpc({supabaseUrl:'https://example.invalid',serviceRoleKey:'fixture'.repeat(10)}),/CONFIGURATION_DENIED/);const c=new a.VercelInferenceRpc({supabaseUrl:box,serviceRoleKey:'fixture'.repeat(10),fetchFn:()=>assert.fail()});assert.throws(()=>c.rpc('run_sql',{sql:'select 1'}),/RPC_DENIED/);});
test('server RPC returns a native denial to the existing durable store without claiming success',async()=>{const [,,a]=await modules;let count=0;const c=new a.VercelInferenceRpc({supabaseUrl:box,serviceRoleKey:'fixture'.repeat(10),fetchFn:async(url,init)=>{count++;assert.equal(init.redirect,'error');assert.equal(url,box+'/rest/v1/rpc/pandora_ops_inference_authenticate_v1');return Response.json({code:'42501',message:'INFERENCE_WORKER_AUTH_DENIED'},{status:403});}});const p=c.rpc('pandora_ops_inference_authenticate_v1',{p_digest:'a'.repeat(64)});const [one,two]=await Promise.all([p,p]);assert.equal(one.error.code,'42501');assert.deepEqual(one,two);assert.equal(count,1);});
test('real HTTP handler authenticates owner before exact native event query',async()=>{
 const [,,a]=await modules;const calls=[];const userId='33e5b2de-048b-4814-b601-7d7daac7a649';const input={organizationId:'2270b266-59da-4c39-bfd9-9f8d08352af0',projectId:'ee282126-3f61-4058-8c92-2fedbfcecf1f',after:'0',limit:100};
 const handler=a.createVercelInferenceRuntime({supabaseUrl:box,serviceRoleKey:'fixture'.repeat(10),publishableKey:'fixture'.repeat(6),resolveWorkloadToken:()=>assert.fail('owner event reads do not need Memory identity'),fetchFn:async(url,init)=>{calls.push(url);if(url===box+'/auth/v1/user')return Response.json({id:userId,is_anonymous:false});assert.equal(url,box+'/rest/v1/rpc/pandora_ops_event_feed_v1');const b=JSON.parse(init.body);assert.equal(b.p_actor_id,userId);assert.equal(b.p_project_id,input.projectId);return Response.json({events:[],fixture:true});}});
 const r=await handler(new Request('https://mcpmaster.vercel.app/pandora-intelligence-router/events',{method:'POST',headers:{authorization:'Bearer '+token(),'content-type':'application/json'},body:JSON.stringify(input)}));assert.equal(r.status,200);assert.equal(calls.length,2);
});
test('anonymous authentication response cannot access any event RPC',async()=>{const [,,a]=await modules;let calls=0;const h=a.createVercelInferenceRuntime({supabaseUrl:box,serviceRoleKey:'fixture'.repeat(10),publishableKey:'fixture'.repeat(6),resolveWorkloadToken:()=>assert.fail(),fetchFn:async()=>{calls++;return Response.json({id:'33e5b2de-048b-4814-b601-7d7daac7a649',is_anonymous:true});}});const r=await h(new Request('https://mcpmaster.vercel.app/pandora-intelligence-router/events',{method:'POST',headers:{authorization:'Bearer '+token(),'content-type':'application/json'},body:'{}'}));assert.equal(r.status,401);assert.equal(calls,1);});
