'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const NOW = Date.parse('2026-09-26T01:00:00Z');
const request = () => ({requestId:'00000000-0000-4000-8000-000000000001',taskId:'TASK',leaseId:'00000000-0000-4000-8000-000000000002',generation:1,sourceSha:'a'.repeat(40),taskClass:'complex_coding',parts:[{type:'text',text:'Review this source.'}],maxOutputTokens:128,maxCostMicros:100,deadlineMs:1000});
const model = (overrides={}) => ({provider:'fixture',model:'strong',modelRevision:'v1',configurationDigest:'c'.repeat(64),classes:['complex_coding'],modalities:['text'],executionBoundary:'cloud',riskTier:3,contextTokens:4096,maxInputBytes:4096,maxOutputTokens:1024,imageTokenUpperBound:0,transport:'fixture',approved:true,approvalRef:'fixture:approval',approvalExpiresAt:new Date(NOW+60000).toISOString(),available:true,healthObservedAt:new Date(NOW).toISOString(),estimatedLatencyMs:100,maxCostMicros:50,maxConcurrency:2,...overrides});
const policy = (overrides={}) => ({version:'fixture-v1',models:[model()],maxAttempts:2,maxHealthAgeMs:60000,minHistorySamples:5,maxHistoryAgeMs:86400000,minimumRiskTier:{read:0,source:2,preview:1,production:3,destructive:3},allowedBoundaries:['cloud','phone'],allowedProviders:['fixture'],allowedFallbackCodes:['rate_limit','unavailable'],override:null,requireMemoryContext:true,...overrides});
const scope={principalKey:'fixture-builder',taskId:'TASK',risk:'source'};
const opts={now:NOW,transports:['fixture']};
let api; test.before(async()=>{api=await import('../packages/pandora-operations-inference/policy.mjs');});
test('uses the same ten frozen Memory capability classes',()=>{assert.equal(api.CAPABILITY_CLASSES.length,10);});
for(const cls of ['deep_reasoning','complex_coding','fast_coding','vision','long_context','research','structured_extraction','cheap_bulk','independent_verification']) test(`admitted class ${cls}`,()=>{
 const r=api.normalizeRequest({...request(),taskClass:cls}); assert.equal(api.selectCandidates(r,policy({models:[model({classes:[cls]})]}),scope,null,opts).candidates.length,1);
});
test('local private is rejected on cloud even with a phone catalog entry',()=>{const r=api.normalizeRequest({...request(),taskClass:'local_private'}); assert.throws(()=>api.selectCandidates(r,policy({models:[model({classes:['local_private'],executionBoundary:'phone'})]}),scope,null,opts),/PHONE_LOCAL/);});
test('local private can only select phone inside a phone execution boundary',()=>{const r=api.normalizeRequest({...request(),taskClass:'local_private'}); const result=api.selectCandidates(r,policy({models:[model({classes:['local_private'],executionBoundary:'phone'})]}),scope,null,{...opts,executionBoundary:'phone'});assert.equal(result.candidates[0].executionBoundary,'phone');});
for(const [field,value,code] of [['generation',0,'CLASS'],['taskClass','other','CLASS'],['requestId','x','IDENTITY'],['leaseId','x','IDENTITY'],['sourceSha','main','IDENTITY'],['maxCostMicros',-1,'BUDGET'],['maxOutputTokens',0,'BUDGET'],['deadlineMs',60001,'BUDGET'],['parts',[],'INPUT']])test(`reject request ${field}`,()=>{assert.throws(()=>api.normalizeRequest({...request(),[field]:value}),new RegExp(code));});
test('raw model/provider/override fields cannot supply authority',()=>{assert.throws(()=>api.normalizeRequest({...request(),provider:'other'}),/FIELDS/);});
test('credentials in text are rejected before routing',()=>{assert.throws(()=>api.normalizeRequest({...request(),parts:[{type:'text',text:'ghp_'+'X'.repeat(24)}]}),/CREDENTIAL/);});
test('request digest is stable across object key order and changes with content',()=>{const a=request(), b=Object.fromEntries(Object.entries(a).reverse());assert.equal(api.normalizeRequest(a).requestDigest,api.normalizeRequest(b).requestDigest);b.parts=[{type:'text',text:'different'}];assert.notEqual(api.normalizeRequest(a).requestDigest,api.normalizeRequest(b).requestDigest);});
for(const [label,change,reason] of [['risk',{riskTier:0},'risk'],['context',{contextTokens:10},'context'],['output',{maxOutputTokens:10},'context'],['stale health',{healthObservedAt:new Date(NOW-60001).toISOString()},'unavailable_or_stale'],['future health',{healthObservedAt:new Date(NOW+6001).toISOString()},'unavailable_or_stale'],['revoked approval',{approvalExpiresAt:new Date(NOW-1).toISOString()},'unavailable_or_stale'],['unavailable',{available:false},'unavailable_or_stale'],['unknown price ceiling',{maxCostMicros:null},'budget_or_unknown_ceiling'],['budget',{maxCostMicros:101},'budget_or_unknown_ceiling'],['transport',{transport:'missing'},'transport_or_attempted'],['class',{classes:['research']},'capability']])test(`excludes ${label}`,()=>{const x=api.selectCandidates(api.normalizeRequest(request()),policy({models:[model(change)]}),scope,null,opts);assert.equal(x.candidates.length,0);assert.ok(x.rejected[0].reasons.includes(reason));});
test('security filters happen before forced choice',()=>{const p=policy({allowedProviders:['other'],override:{provider:'fixture',model:'strong',principalKey:scope.principalKey,taskId:'TASK',expiresAt:new Date(NOW+60000).toISOString(),evidenceRef:'fixture:override',allowFallback:false}});assert.throws(()=>api.selectCandidates(api.normalizeRequest(request()),p,scope,null,opts),/FORCED_MODEL/);});
for(const change of [{principalKey:'other'},{taskId:'OTHER'},{expiresAt:new Date(NOW-1).toISOString()}])test(`override bound ${JSON.stringify(change)}`,()=>{const override={provider:'fixture',model:'strong',principalKey:scope.principalKey,taskId:'TASK',expiresAt:new Date(NOW+60000).toISOString(),evidenceRef:'fixture:override',allowFallback:false,...change};assert.throws(()=>api.selectCandidates(api.normalizeRequest(request()),policy({override}),scope,null,opts),/OVERRIDE_SCOPE/);});
test('forced choice does not silently fall back',()=>{const p=policy({models:[model({model:'fast'})],override:{provider:'fixture',model:'strong',principalKey:scope.principalKey,taskId:'TASK',expiresAt:new Date(NOW+60000).toISOString(),evidenceRef:'fixture:override',allowFallback:false}});assert.throws(()=>api.selectCandidates(api.normalizeRequest(request()),p,scope,null,opts),/FORCED_MODEL/);});
test('explicit override fallback may choose another eligible candidate',()=>{const p=policy({models:[model({model:'fast'})],override:{provider:'fixture',model:'strong',principalKey:scope.principalKey,taskId:'TASK',expiresAt:new Date(NOW+60000).toISOString(),evidenceRef:'fixture:override',allowFallback:true}});assert.equal(api.selectCandidates(api.normalizeRequest(request()),p,scope,null,opts).candidates[0].model,'fast');});
test('high risk ranks strength before latency and price',()=>{const p=policy({models:[model({model:'fast',riskTier:2,maxCostMicros:0,estimatedLatencyMs:1}),model()]});assert.equal(api.selectCandidates(api.normalizeRequest(request()),p,scope,null,opts).candidates[0].model,'strong');});
test('two duplicate catalog keys rejected',()=>{assert.throws(()=>api.selectCandidates(api.normalizeRequest(request()),policy({models:[model(),model()]}),scope,null,opts),/DUPLICATE/);});
for(const code of ['permission_denied','safety_refusal','cancelled','timeout','unknown'])test(`cannot authorize unsafe fallback ${code}`,()=>{assert.throws(()=>api.validatePolicy(policy({allowedFallbackCodes:[code]})),/FALLBACK_POLICY/);});
test('image requires a validated modality and a conservative token budget',()=>{const r=api.normalizeRequest({...request(),taskClass:'vision',parts:[{type:'image',mimeType:'image/png',data:'YQ=='}]});let p=policy({models:[model({classes:['vision'],modalities:['text','image'],imageTokenUpperBound:300})]});assert.equal(api.selectCandidates(r,p,scope,null,opts).candidates.length,1);p.models[0].contextTokens=200;assert.equal(api.selectCandidates(r,p,scope,null,opts).candidates.length,0);});
for(const part of [{type:'image',mimeType:'image/svg+xml',data:'YQ=='},{type:'image',mimeType:'image/png',data:'http://private'},{type:'url',url:'http://localhost'},{type:'text',text:''}])test(`reject unsafe input ${JSON.stringify(part)}`,()=>assert.throws(()=>api.normalizeRequest({...request(),parts:[part]})));
const perf=(m, overrides={})=>({provider:m.provider,model:m.model,modelRevision:m.modelRevision,configurationDigest:m.configurationDigest,taskClass:'complex_coding',canonStatus:'hard_canon',recordType:'provider_performance',recordDigest:'b'.repeat(64),memoryItemId:'00000000-0000-4000-8000-000000000003',sampleCount:10,verificationPassCount:9,negativeOutcomeCount:1,approvedAt:new Date(NOW-1000).toISOString(),reviewDueAt:new Date(NOW+10000).toISOString(),evidenceWindowEnd:new Date(NOW-2000).toISOString(),...overrides});
const history=records=>({state:'available',authorizationGranted:false,providerApprovalGranted:false,summingSamplesAllowed:false,records});
test('verified compatible evidence ranks before latency and cost',()=>{const slow=model({model:'slow',estimatedLatencyMs:1000}),fast=model({model:'fast',estimatedLatencyMs:1,maxCostMicros:1});const e=history([perf(slow,{verificationPassCount:10}),perf(fast,{verificationPassCount:5})]);assert.equal(api.selectCandidates(api.normalizeRequest(request()),policy({models:[fast,slow]}),scope,e,opts).candidates[0].model,'slow');});
for(const mismatch of [{canonStatus:'candidate'},{modelRevision:'other'},{configurationDigest:'d'.repeat(64)},{sampleCount:1,verificationPassCount:1},{reviewDueAt:new Date(NOW-1).toISOString()},{approvedAt:new Date(NOW+1).toISOString()}])test(`does not learn from mismatched history ${JSON.stringify(mismatch)}`,()=>{const e=history([perf(model(),mismatch)]);assert.equal(api.selectCandidates(api.normalizeRequest(request()),policy(),scope,e,opts).candidates[0].history,null);});
test('overlapping performance snapshots are not summed',()=>assert.throws(()=>api.selectCandidates(api.normalizeRequest(request()),policy(),scope,history([perf(model()),perf(model())]),opts),/OVERLAPPING/));
test('selection creates neither authority nor fabricated performance',()=>{const x=api.selectCandidates(api.normalizeRequest(request()),policy(),scope,{state:'insufficient_history'},opts);assert.equal(x.authorizationGranted,false);assert.equal(x.candidates[0].history,null);});

test('nested request bytes are immutable after digesting',()=>{const r=api.normalizeRequest(request());assert.throws(()=>{r.parts[0].text='changed';},TypeError);});
for(const key of ['taskId','requestId','leaseId','sourceSha'])test(`identity is a string, not coerced: ${key}`,()=>assert.throws(()=>api.normalizeRequest({...request(),[key]:123})));
test('image bytes consume the model payload budget',()=>{const r=api.normalizeRequest({...request(),taskClass:'vision',parts:[{type:'image',mimeType:'image/png',data:'YQ=='.repeat(1)}]});assert.equal(r.inputBytes,4);const p=policy({models:[model({classes:['vision'],modalities:['image'],imageTokenUpperBound:10,maxInputBytes:1})]});assert.equal(api.selectCandidates(r,p,scope,null,opts).candidates.length,0);});
test('mixed known and unknown history ordering is permutation independent',()=>{const models=[model({model:'a',estimatedLatencyMs:100}),model({model:'b',estimatedLatencyMs:1}),model({model:'c',estimatedLatencyMs:50})];const e=history([perf(models[0],{verificationPassCount:10}),perf(models[2],{verificationPassCount:5})]);const permutations=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];for(const order of permutations){const p=policy({models:order.map(i=>models[i]),maxAttempts:3});assert.deepEqual(api.selectCandidates(api.normalizeRequest(request()),p,scope,e,opts).candidates.map(m=>m.model),['a','c','b']);}});

test('valid binary image with credential-looking base64 is not plaintext credential material',()=>{
 const fixture=require('./fixtures/inference-image-fixture.cjs')();
 assert.ok(fixture.data.includes(fixture.tokenLookingText));
 const r=api.normalizeRequest({...request(),taskClass:'vision',parts:[{type:'image',mimeType:'image/png',data:fixture.data}]});
 assert.equal(r.inputBytes,fixture.data.length);assert.equal(r.imageCount,1);
 assert.throws(()=>api.normalizeRequest({...request(),parts:[{type:'text',text:fixture.tokenLookingText}]}),/CREDENTIAL_REJECTED/);
 assert.throws(()=>api.normalizeRequest({...request(),parts:[{type:'image',mimeType:'image/png',data:fixture.data},{type:'text',text:fixture.tokenLookingText}]}),/CREDENTIAL_REJECTED/);
});
test('nullable latency has a total, permutation-independent order before price',()=>{
 const models=[model({model:'A',estimatedLatencyMs:1,maxCostMicros:3}),model({model:'B',estimatedLatencyMs:null,maxCostMicros:1}),model({model:'C',estimatedLatencyMs:2,maxCostMicros:2})];
 for(const order of [[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]]){
  const r=api.selectCandidates(api.normalizeRequest(request()),policy({models:order.map(i=>models[i]),maxAttempts:3}),scope,null,opts);
  assert.deepEqual(r.candidates.map(x=>x.model),['A','C','B']);
 }
});
test('all unknown latencies compare by price and stable model identity without assigning a latency',()=>{
 const p=policy({models:[model({model:'Z',estimatedLatencyMs:null,maxCostMicros:2}),model({model:'B',estimatedLatencyMs:null,maxCostMicros:1}),model({model:'A',estimatedLatencyMs:null,maxCostMicros:1})],maxAttempts:3});
 const r=api.selectCandidates(api.normalizeRequest(request()),p,scope,null,opts);assert.deepEqual(r.candidates.map(m=>m.model),['A','B','Z']);assert.ok(r.candidates.every(m=>m.estimatedLatencyMs===null));
});
