'use strict';const test=require('node:test'),assert=require('node:assert/strict');let api;const NOW=Date.now(),ORG='00000000-0000-4000-8000-000000000001',PROJECT='00000000-0000-4000-8000-000000000002';
const scope=()=>({organizationId:ORG,projectId:PROJECT,sessionKey:'fixture-owner-session'});
const event=(id='1',type='inference_received')=>({id,key:'fixture:'+id,taskId:'TASK',type,receiptRef:'fixture:provider-response',occurredAt:new Date(NOW).toISOString()});
const page=(events=[event()],extra={})=>({schemaVersion:'pandora-operations-events-v1',organizationId:ORG,projectId:PROJECT,observedAt:new Date(NOW).toISOString(),events,nextCursor:events.at(-1)?.id??'0',highWatermark:events.at(-1)?.id??'0',hasMore:false,authority:'immutable_operations_events',syntheticProgress:false,...extra});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
test.before(async()=>{api=await import('../packages/pandora-operations-inference/theatre.mjs');});
test('provider response and verified inference do not announce task completion or invented progress',()=>{for(const type of ['inference_received','inference_verified','inference_send_started','inference_cancel_requested']){const e=api.eventView(event('1',type));assert.equal(e.taskComplete,false);assert.equal(e.progress,null);}assert.equal(api.eventView(event('1','verification_accepted')).taskComplete,true);});
test('empty current stream remains empty, not synthetic activity',async()=>{const t=new api.OperationsTheatre({readEvents:async()=>page([]),clock:()=>NOW});t.reset(scope());const s=await t.refresh();assert.equal(s.events.length,0);assert.equal(s.generatedProgress,false);});
test('bigint cursors never round through JavaScript Number',async()=>{const t=new api.OperationsTheatre({readEvents:async()=>page([event('9007199254740993'),event('9007199254740994')]),clock:()=>NOW});t.reset(scope());const s=await t.refresh();assert.equal(s.cursor,'9007199254740994');assert.equal(s.events[0].id,'9007199254740993');});
test('one refresh is shared instead of issuing parallel duplicate reads',async()=>{const d=deferred();let calls=0;const t=new api.OperationsTheatre({readEvents:()=>{calls++;return d.promise;},clock:()=>NOW});t.reset(scope());const a=t.refresh(),b=t.refresh();assert.equal(a,b);d.resolve(page());await a;assert.equal(calls,1);});
for(const change of [{organizationId:'00000000-0000-4000-8000-000000000003'},{projectId:'00000000-0000-4000-8000-000000000003'},{syntheticProgress:true},{authority:'model_prediction'},{nextCursor:'2'},{nextCursor:1},{highWatermark:'0'},{observedAt:new Date(NOW-60001).toISOString()},{observedAt:new Date(NOW+30001).toISOString()}])test(`reject invalid current-event envelope ${JSON.stringify(change)}`,async()=>{const t=new api.OperationsTheatre({readEvents:async()=>page([event()],change),clock:()=>NOW});t.reset(scope());await assert.rejects(()=>t.refresh());assert.equal(t.snapshot().events.length,0);assert.equal(t.snapshot().cursor,'0');});
test('out-of-order and duplicate ids invalidate the whole page atomically',async()=>{for(const events of [[event('2'),event('1')],[event('1'),event('1')]]){const t=new api.OperationsTheatre({readEvents:async()=>page(events,{highWatermark:'2'}),clock:()=>NOW});t.reset(scope());await assert.rejects(()=>t.refresh(),/CURSOR|DUPLICATE/);assert.equal(t.snapshot().events.length,0);}});
test('global event id gaps are legitimate and are not filled with fake events',async()=>{const t=new api.OperationsTheatre({readEvents:async()=>page([event('1'),event('40')]),clock:()=>NOW});t.reset(scope());assert.equal((await t.refresh()).events.length,2);});
test('old-session responses cannot repopulate a reset tenant view',async()=>{const d=deferred();const t=new api.OperationsTheatre({readEvents:()=>d.promise,clock:()=>NOW});t.reset(scope());const old=t.refresh();await Promise.resolve();t.reset({...scope(),projectId:'00000000-0000-4000-8000-000000000003',sessionKey:'new-session'});d.resolve(page());await old;assert.equal(t.snapshot().events.length,0);assert.equal(t.snapshot().scope.projectId,'00000000-0000-4000-8000-000000000003');});
test('read failure releases the lock for a subsequent explicit refresh',async()=>{let n=0;const t=new api.OperationsTheatre({readEvents:async()=>{if(n++===0)throw new Error('fixture network failed');return page();},clock:()=>NOW});t.reset(scope());await assert.rejects(()=>t.refresh());assert.equal((await t.refresh()).events.length,1);assert.equal(n,2);});
test('bounded event retention keeps the newest exact events',async()=>{const t=new api.OperationsTheatre({readEvents:async()=>page([event('1'),event('2'),event('3')]),clock:()=>NOW,maxEvents:2});t.reset(scope());assert.deepEqual((await t.refresh()).events.map(e=>e.id),['2','3']);});
test('reset to signed-out clears all event and tenant state',async()=>{const t=new api.OperationsTheatre({readEvents:async()=>page(),clock:()=>NOW});t.reset(scope());await t.refresh();t.reset();assert.equal(t.snapshot().scope,null);assert.equal(t.snapshot().events.length,0);await assert.rejects(()=>t.refresh(),/SCOPE_REQUIRED/);});
test('renderer uses text nodes for untrusted event material',()=>{const created=[];const document={createElement(tag){const element={tag,children:[],textContent:'',setAttribute(){},appendChild(child){this.children.push(child);}};created.push(element);return element;}};let root;const container={replaceChildren(value){root=value;}};const unsafe=api.eventView({...event(),receiptRef:'<img src=x onerror=alert(1)>'});api.renderTheatre(container,{events:[unsafe]},{document});assert.equal(root.tag,'ol');assert.equal(created.some(e=>'innerHTML'in e),false);assert.ok(created.some(e=>e.textContent.includes('<img')));});

test('real events without external receipts remain valid and do not acquire invented evidence',async()=>{
 const t=new api.OperationsTheatre({readEvents:async()=>page([{...event('1','tasks_ingested'),receiptRef:null}]),clock:()=>NOW});
 t.reset(scope());const view=await t.refresh();assert.equal(view.events[0].receiptRef,null);assert.equal(view.events[0].progress,null);
});
