'use strict';
const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), path=require('node:path');
const {randomUUID}=require('node:crypto'); const {PGlite}=require('@electric-sql/pglite');
const {normalizeTask,REPOSITORIES}=require('../packages/pandora-operations-room/contracts');
let db,api; const SHA='a'.repeat(40), OUT='e'.repeat(64);
async function rpc(name,args){const values=Object.entries(args).map(([k,x])=>k==='p_tasks' || (x!==null&&typeof x==='object'&&!Array.isArray(x))?JSON.stringify(x):x);return(await db.query('select public.'+name+'('+Object.keys(args).map((k,i)=>k+'=>$'+(i+1)).join(',')+') value',values)).rows[0].value;}
const call=(s,operation,payload)=>rpc('pandora_ops_inference_transition_v1',{p_operation:operation,p_actor:s.actor,p_payload:payload});
function model(){const now=Date.now();return{provider:'fixture',model:'strong',modelRevision:'v1',configurationDigest:'c'.repeat(64),classes:['complex_coding'],modalities:['text'],executionBoundary:'cloud',riskTier:3,contextTokens:4096,maxInputBytes:4096,maxOutputTokens:1024,imageTokenUpperBound:0,transport:'fixture',approved:true,approvalRef:'fixture:not-production-approval',approvalExpiresAt:new Date(now+3600000).toISOString(),available:true,healthObservedAt:new Date(now).toISOString(),estimatedLatencyMs:1,maxCostMicros:50,maxConcurrency:2};}
function policy(){return{version:'fixture-v1',models:[model()],maxAttempts:3,maxHealthAgeMs:60000,minHistorySamples:5,maxHistoryAgeMs:86400000,minimumRiskTier:{read:0,source:2,preview:1,production:3,destructive:3},allowedBoundaries:['cloud'],allowedProviders:['fixture'],allowedFallbackCodes:['rate_limit','unavailable'],override:null,requireMemoryContext:false};}
async function setup({budget=200,modelPatch={}}={}){
 const org=randomUUID(),project=randomUUID(),owner=randomUUID(),digest=api.sha256(randomUUID());
 await db.query('insert into public.organizations values($1)',[org]);
 const args={p_organization_id:org,p_project_id:project};
 await rpc('pandora_ops_project_binding_v1',{...args,p_state:'active',p_evidence_ref:'fixture:not-a-real-project'});
 await rpc('pandora_ops_initialize_v1',{...args,p_budget_micros:10000,p_max_concurrency:4});
 await rpc('pandora_ops_register_worker_v1',{...args,p_worker_key:'BUILDER',p_principal_key:'fixture-builder',p_lanes:['backend'],p_capabilities:['source.write'],p_capacity:4,p_receipt_ref:'fixture:not-a-real-worker'});
 const spec=normalizeTask({id:'TASK',title:'Fixture task',lane:'backend',priority:0,dependsOn:[],resources:[{key:'source/fixture',mode:'write'}],requiredCapabilities:['source.write'],maxCostMicros:budget,maxDurationSeconds:600,maxAttempts:2,risk:'source',acceptance:['fixture-only output verification'],source:{repository:REPOSITORIES[0],baseSha:SHA}});
 await rpc('pandora_ops_ingest_v1',{...args,p_tasks:[spec]}); await rpc('pandora_ops_control_v1',{...args,p_expected_revision:0,p_action:'resume'});
 await rpc('pandora_ops_claim_v1',{...args,p_task_key:'TASK',p_worker_key:'BUILDER',p_task_revision:0,p_control_revision:1});
 const lease=(await db.query('select * from private.pandora_ops_leases where organization_id=$1 and project_id=$2',[org,project])).rows[0];
 // Synthetic fixture establishment only. These rows are never used as live-worker evidence.
 await db.query("update private.pandora_ops_leases set state='running' where id=$1",[lease.id]);
 await db.query("update private.pandora_ops_tasks set status='implementing' where organization_id=$1 and project_id=$2",[org,project]);
 const p=policy();Object.assign(p.models[0],modelPatch);
 await db.query('insert into private.pandora_ops_inference_policies values($1,$2,1,$3,true,$4)',[org,project,JSON.stringify(p),'fixture:not-production-approval']);
 await db.query("insert into private.pandora_ops_inference_callers values($1,$2,$3,'BUILDER','fixture-builder',true,clock_timestamp()+interval '1 hour',$4,'fixture:not-real-enrollment')",[digest,org,project,['complex_coding']]);
 await db.query("insert into public.memberships values($1,$2,'owner','active')",[org,owner]);
 const actor=await rpc('pandora_ops_inference_authenticate_v1',{p_digest:digest});
 const raw={requestId:randomUUID(),taskId:'TASK',leaseId:lease.id,generation:Number(lease.generation),sourceSha:SHA,taskClass:'complex_coding',parts:[{type:'text',text:'Fixture only.'}],maxOutputTokens:128,maxCostMicros:100,deadlineMs:1000};
 const normalized=api.normalizeRequest(raw); const {parts,...metadata}=normalized;metadata.inputDigest=normalized.requestDigest;
 return {org,project,owner,digest,actor,raw,metadata,lease,policy:p};
}
async function prepare(s){await call(s,'admit',s.metadata);const context=await call(s,'context',s.metadata);const attempt=await call(s,'prepare',{requestId:s.metadata.requestId,modelKey:'fixture:strong',policyDigest:context.policyDigest});return{...attempt,policyDigest:context.policyDigest};}
async function send(s,a){return call(s,'send',{requestId:s.metadata.requestId,attemptId:a.attemptId,policyDigest:a.policyDigest});}
const receipt=(state='received',patch={})=>({state,outputDigest:state==='received'?OUT:null,providerReceipt:'fixture:provider-response',billedCostMicros:null,usage:{inputTokens:null,outputTokens:null,totalTokens:null},code:state==='received'?null:'unavailable',latencyMs:10,modelRevision:null,...patch});
const record=(s,a,value)=>call(s,'record',{requestId:s.metadata.requestId,attemptId:a.attemptId,receipt:value});
const status=s=>call(s,'status',{requestId:s.metadata.requestId});
test.before(async()=>{api=await import('../packages/pandora-operations-inference/policy.mjs');db=await PGlite.create();await db.exec(`create role anon;create role authenticated;create role service_role;create schema private;create schema extensions;
create table public.organizations(id uuid primary key);create table public.memberships(organization_id uuid,user_id uuid,role text,status text);
create table public.pandora_verification_runs(id uuid primary key,organization_id uuid not null,project_id uuid not null,status text not null,source_commit text,required_check_profile text,completed_at timestamptz,artifact_digest text,builder_identity text,verifier_identity text,runtime_target_digest text);
create function extensions.digest(data bytea,algorithm text) returns bytea language plpgsql immutable as $$begin if algorithm<>'sha256' then raise exception 'unsupported digest';end if;return pg_catalog.sha256(data);end$$;`);
await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260925101319_pandora_operations_room_runtime_v1.sql'),'utf8'));
await db.exec(fs.readFileSync(path.join(__dirname,'../packages/pandora-operations-inference/schema.sql'),'utf8'));});
test.after(async()=>db?.close());
test('native schema seeds no caller, worker or policy',async()=>{for(const t of ['pandora_ops_inference_callers','pandora_ops_inference_policies','pandora_ops_workers'])assert.equal((await db.query('select count(*)::int n from private.'+t)).rows[0].n,0);});
test('native tables deny direct browser and service-role access and use RLS',async()=>{const rows=(await db.query("select c.relname,c.relrowsecurity,has_table_privilege('anon',c.oid,'select') a,has_table_privilege('authenticated',c.oid,'insert') u,has_table_privilege('service_role',c.oid,'update') s from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relkind='r' and c.relname like 'pandora_ops_inference_%'")).rows;assert.equal(rows.length,5);for(const r of rows){assert.equal(r.relrowsecurity,true);assert.equal(r.a,false);assert.equal(r.u,false);assert.equal(r.s,false);}});
test('only service-role can execute the public native boundary',async()=>{for(const role of ['anon','authenticated'])assert.equal((await db.query("select has_function_privilege($1,'public.pandora_ops_inference_transition_v1(text,jsonb,jsonb)','execute') ok",[role])).rows[0].ok,false);});
test('missing authentication fails closed',async()=>{await assert.rejects(()=>rpc('pandora_ops_inference_authenticate_v1',{p_digest:'a'.repeat(64)}),/CALLER_DENIED/);});
test('native policy scope is bound to the real parent lease',async()=>{const s=await setup();const c=await call(s,'context',s.metadata);assert.equal(c.scope.principalKey,'fixture-builder');assert.equal(c.scope.taskId,'TASK');assert.match(c.policyDigest,/^[a-f0-9]{64}$/);});
for(const field of ['organizationId','projectId','workerId','principalKey','callerDigest'])test(`native rejects forged ${field}`,async()=>{const s=await setup();s.actor={...s.actor,[field]:field.endsWith('Id')&&field!=='workerId'?randomUUID():'wrong'};await assert.rejects(()=>call(s,'admit',s.metadata),/CALLER_DENIED/);});
test('native admission is exact-payload idempotent without execution',async()=>{const s=await setup();assert.equal((await call(s,'admit',s.metadata)).created,true);const second=await call(s,'admit',s.metadata);assert.equal(second.created,false);assert.equal(second.canSend,false);await assert.rejects(()=>call(s,'admit',{...s.metadata,requestDigest:'b'.repeat(64)}),/REPLAY_CONFLICT/);});
test('raw prompt cannot be smuggled into durable metadata',async()=>{const s=await setup();await assert.rejects(()=>call(s,'admit',{...s.metadata,parts:s.raw.parts}),/METADATA_ONLY/);});
test('parent budget cannot be multiply reserved',async()=>{const s=await setup({budget:100});await call(s,'admit',s.metadata);await assert.rejects(()=>call(s,'admit',{...s.metadata,requestId:randomUUID()}),/PARENT_BUDGET/);});
test('cancelled zero-attempt request releases its unused parent budget reservation',async()=>{
 const s=await setup({budget:100});await call(s,'admit',s.metadata);await call(s,'cancel',{requestId:s.metadata.requestId});
 const second={...s.metadata,requestId:randomUUID()};const admitted=await call(s,'admit',second);assert.equal(admitted.created,true);
});
test('failed zero-billed attempt releases unused parent budget while unknown billing stays reserved',async()=>{
 const s=await setup({budget:100}),a=await prepare(s);await send(s,a);await record(s,a,receipt('failed',{billedCostMicros:0}));
 const second={...s.metadata,requestId:randomUUID()};assert.equal((await call(s,'admit',second)).created,true);
});
for(const sql of ["update private.pandora_ops_workspaces set paused=true where organization_id=$1", "update private.pandora_ops_workers set connected=false where organization_id=$1", "update private.pandora_ops_tasks set cancel_requested=true where organization_id=$1", "update private.pandora_ops_leases set expires_at=clock_timestamp()-interval '1 second' where organization_id=$1", "update private.pandora_ops_inference_callers set enabled=false where organization_id=$1"] )test(`native admission rechecks ${sql.split(' ')[2]}`,async()=>{const s=await setup();await db.query(sql,[s.org]);await assert.rejects(()=>call(s,'admit',s.metadata));});
test('one durable sender and no implicit provider completion',async()=>{const s=await setup(),a=await prepare(s);assert.equal(a.created,true);assert.equal((await send(s,a)).canSend,true);assert.equal((await send(s,a)).canSend,false);const x=await status(s);assert.equal(x.request.state,'executing');assert.equal(x.taskComplete,false);});
test('policy change between preparation and sending blocks the send',async()=>{const s=await setup(),a=await prepare(s);await db.query("update private.pandora_ops_inference_policies set policy=jsonb_set(policy,'{version}','\"fixture-v2\"') where organization_id=$1",[s.org]);await assert.rejects(()=>send(s,a),/POLICY_CHANGED/);});
test('request cancellation after preparation blocks sending without pretending provider stopped',async()=>{const s=await setup(),a=await prepare(s);const c=await call(s,'cancel',{requestId:s.metadata.requestId});assert.equal(c.providerStopped,false);assert.equal(c.cancelled,false);await assert.rejects(()=>send(s,a),/REQUEST_FENCED/);await record(s,a,receipt('not_sent',{billedCostMicros:0}));assert.equal((await status(s)).request.state,'cancelled');});
test('known provider response remains verification pending and unknown bill stays null',async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt());const x=await status(s);assert.equal(x.request.state,'verification_pending');assert.equal(x.attempts[0].billed_micros,null);assert.equal(x.taskComplete,false);});
test('exact receipt replay succeeds but conflicting receipt is rejected',async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt());assert.equal((await record(s,a,receipt())).replayed,true);await assert.rejects(()=>record(s,a,receipt('received',{outputDigest:'f'.repeat(64)})),/RECEIPT_CONFLICT/);});
test('unknown provider outcome holds the parent lease and forbids retry',async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt('reconciliation_required'));assert.equal((await status(s)).request.state,'reconciliation_required');assert.equal((await db.query('select state from private.pandora_ops_leases where id=$1',[s.lease.id])).rows[0].state,'reconcile');await assert.rejects(()=>send(s,a),/LEASE_FENCED|REQUEST_FENCED/);});
test('unresolved billing prevents parent settlement',async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt());await assert.rejects(()=>db.query('select private.pandora_ops_settle_v1($1,$2,$3,$4,0,$5)',[s.org,s.project,s.lease.id,s.lease.generation,'fixture:settle']),/UNRESOLVED/);});
test('actual billing readback is immutable and cannot under-report settlement',async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt());await call(s,'billing',{requestId:s.metadata.requestId,attemptId:a.attemptId,billedCostMicros:20,receiptRef:'fixture:billing-receipt'});await assert.rejects(()=>call(s,'billing',{requestId:s.metadata.requestId,attemptId:a.attemptId,billedCostMicros:0,receiptRef:'fixture:different'}),/BILLING_CONFLICT/);await assert.rejects(()=>db.query('select private.pandora_ops_settle_v1($1,$2,$3,$4,0,$5)',[s.org,s.project,s.lease.id,s.lease.generation,'fixture:settle']),/UNDERREPORTED/);});
test('model capacity is checked across two requests',async()=>{const s=await setup({modelPatch:{maxConcurrency:1}}),a=await prepare(s);const original=s.metadata;s.metadata={...s.metadata,requestId:randomUUID()};await assert.rejects(()=>prepare(s),/CAPACITY_HELD/);s.metadata=original;assert.equal((await status(s)).attempts[0].id,a.attemptId);});
test('half-open probe has one owner and does not expire into a free slot',async()=>{const s=await setup();await db.query("insert into private.pandora_ops_inference_circuits(organization_id,model_key,state,retry_after) values($1,'fixture:strong','open',clock_timestamp()-interval '1 second')",[s.org]);const a=await prepare(s);const original=s.metadata;s.metadata={...s.metadata,requestId:randomUUID()};await assert.rejects(()=>prepare(s),/CIRCUIT_HELD/);s.metadata=original;await send(s,a);await record(s,a,receipt('reconciliation_required'));assert.equal((await db.query('select probe_attempt from private.pandora_ops_inference_circuits where organization_id=$1',[s.org])).rows[0].probe_attempt,a.attemptId);});
async function verification(s,patch={}){const id=randomUUID();const v={organization_id:s.org,project_id:s.project,status:'PASS',source_commit:SHA,required_check_profile:'backend_service',completed_at:new Date().toISOString(),artifact_digest:OUT,builder_identity:'fixture-builder',verifier_identity:'fixture-verifier',runtime_target_digest:s.metadata.requestDigest,...patch};await db.query('insert into public.pandora_verification_runs(id,'+Object.keys(v).join(',')+') values('+[id,...Object.values(v)].map((_,i)=>'$'+(i+1)).join(',')+')',[id,...Object.values(v)]);return id;}
async function enrollVerifier(s){await rpc('pandora_ops_register_worker_v1',{p_organization_id:s.org,p_project_id:s.project,p_worker_key:'VERIFIER',p_principal_key:'fixture-verifier',p_lanes:['release'],p_capabilities:['source.write'],p_capacity:1,p_receipt_ref:'fixture:not-a-real-independent-worker'});}
for(const patch of [{artifact_digest:'f'.repeat(64)},{source_commit:'b'.repeat(40)},{runtime_target_digest:'f'.repeat(64)},{builder_identity:'wrong'},{verifier_identity:'fixture-builder'},{status:'FAIL'},{project_id:randomUUID()}])test(`canonical verification rejects ${JSON.stringify(patch)}`,async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt());await enrollVerifier(s);const id=await verification(s,patch);await assert.rejects(()=>call(s,'verify',{requestId:s.metadata.requestId,verificationRunId:id}),/CANONICAL_VERIFICATION/);});
test('unregistered independent identity cannot satisfy verification',async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt());const id=await verification(s);await assert.rejects(()=>call(s,'verify',{requestId:s.metadata.requestId,verificationRunId:id}),/INDEPENDENT_VERIFIER/);});
test('independent output-and-request-bound canonical PASS verifies inference, not the task',async()=>{const s=await setup(),a=await prepare(s);await send(s,a);await record(s,a,receipt());await enrollVerifier(s);const id=await verification(s);const v=await call(s,'verify',{requestId:s.metadata.requestId,verificationRunId:id});assert.equal(v.state,'verified');assert.equal(v.taskComplete,false);assert.equal((await db.query('select status from private.pandora_ops_tasks where organization_id=$1',[s.org])).rows[0].status,'implementing');});
test('owner event feed reads actual scoped events with stable string cursors',async()=>{const s=await setup();const args={p_organization_id:s.org,p_project_id:s.project,p_actor_id:s.owner,p_after:0,p_limit:2};const first=await rpc('pandora_ops_event_feed_v1',args);assert.equal(first.schemaVersion,'pandora-operations-events-v1');assert.equal(first.events.length,2);assert.equal(first.hasMore,true);assert.equal(typeof first.nextCursor,'string');const second=await rpc('pandora_ops_event_feed_v1',{...args,p_after:first.nextCursor,p_limit:200});assert.ok(second.events.every(e=>BigInt(e.id)>BigInt(first.nextCursor)));assert.equal(second.syntheticProgress,false);});
test('cross-owner and cross-project event feed access is denied',async()=>{const s=await setup();const args={p_organization_id:s.org,p_project_id:s.project,p_actor_id:s.owner,p_after:0,p_limit:10};await assert.rejects(()=>rpc('pandora_ops_event_feed_v1',{...args,p_actor_id:randomUUID()}),/OWNER_DENIED/);await assert.rejects(()=>rpc('pandora_ops_event_feed_v1',{...args,p_project_id:randomUUID()}),/PROJECT_DENIED/);});
for(const patch of [{p_after:-1},{p_limit:0},{p_limit:201},{p_after:'9223372036854775807'}])test(`reject invalid event cursor ${JSON.stringify(patch)}`,async()=>{const s=await setup();await assert.rejects(()=>rpc('pandora_ops_event_feed_v1',{p_organization_id:s.org,p_project_id:s.project,p_actor_id:s.owner,p_after:0,p_limit:10,...patch}),/CURSOR/);});

// Execute the actual JavaScript service against the actual native SQL, not an in-memory authority.
async function serviceFixture(s,{execute,preflight,memory=null,performance=null}={}){
 const {NativeInferenceStore}=await import('../packages/pandora-operations-inference/native-store.mjs');
 const {OperationsInferenceService}=await import('../packages/pandora-operations-inference/service.mjs');
 const client={supabaseUrl:'https://jcyqixttuebxqqfkjonq.supabase.co',rpc:async(name,args)=>{try{return{data:await rpc(name,args),error:null};}catch(error){return{data:null,error:{message:error.message,code:error.code}};}}};
 const store=new NativeInferenceStore(client);let executions=0;
 const service=new OperationsInferenceService({store,providers:{fixture:{preflight,execute:async(...args)=>{executions++;if(execute)return execute(...args);const output='Fixture output';return{output,receipt:receipt('received',{outputDigest:api.sha256(output)})};}}},memory,performance});
 return{store,service,executions:()=>executions};
}
test('real service executes once through native authorization and records receipt without task completion',async()=>{const s=await setup(),f=await serviceFixture(s);const result=await f.service.infer(s.actor,s.raw);assert.equal(result.state,'verification_pending');assert.equal(result.taskComplete,false);assert.equal(result.output,'Fixture output');assert.equal(f.executions(),1);const native=await status(s);assert.equal(native.attempts.length,1);assert.equal(native.attempts[0].receipt.outputDigest,api.sha256(result.output));assert.equal(native.attempts[0].billed_micros,null);});
test('service exact raw-request replay reads the original result without resending or inventing recovered output',async()=>{const s=await setup(),f=await serviceFixture(s);await f.service.infer(s.actor,s.raw);const second=await f.service.infer(s.actor,structuredClone(s.raw));assert.equal(f.executions(),1);assert.equal(second.outputRecovered,false);assert.equal(second.output,undefined);assert.equal(second.state,'verification_pending');});
test('service rejects changed prompt under the same request id without another provider call',async()=>{const s=await setup(),f=await serviceFixture(s);await f.service.infer(s.actor,s.raw);await assert.rejects(()=>f.service.infer(s.actor,{...s.raw,parts:[{type:'text',text:'changed'}]}),/REPLAY_CONFLICT/);assert.equal(f.executions(),1);});
test('configured required Memory cannot be bypassed by a missing client',async()=>{const s=await setup();await db.query("update private.pandora_ops_inference_policies set policy=jsonb_set(policy,'{requireMemoryContext}','true') where organization_id=$1",[s.org]);const f=await serviceFixture(s);await assert.rejects(()=>f.service.infer(s.actor,s.raw),/MEMORY_CALLER_NOT_CONFIGURED/);assert.equal(f.executions(),0);assert.equal((await db.query('select count(*)::int n from private.pandora_ops_inference_requests where organization_id=$1',[s.org])).rows[0].n,0);});
test('Memory context participates in the native immutable request digest and provider context',async()=>{const s=await setup();let supplied;const memory={getTaskContext:async()=>({state:'available',authorizationGranted:false,context:{fixture:'reference'},receiptRef:'fixture:memory-context'})};const f=await serviceFixture(s,{memory,execute:async request=>{supplied=request;const output='Context checked';return{output,receipt:receipt('received',{outputDigest:api.sha256(output)})};}});await f.service.infer(s.actor,s.raw);const native=await status(s);assert.ok(supplied.memoryContext.includes('reference'));assert.equal(native.request.metadata.inputDigest,api.normalizeRequest(s.raw).requestDigest);assert.notEqual(native.request.request_digest,native.request.metadata.inputDigest);assert.equal(native.request.metadata.parts,undefined);assert.ok(native.request.metadata.textBytes>s.metadata.textBytes);});
test('degraded required Memory stops prior to admitting a request',async()=>{const s=await setup();await db.query("update private.pandora_ops_inference_policies set policy=jsonb_set(policy,'{requireMemoryContext}','true') where organization_id=$1",[s.org]);const f=await serviceFixture(s,{memory:{getTaskContext:async()=>({state:'degraded',authorizationGranted:false,context:{}})}});await assert.rejects(()=>f.service.infer(s.actor,s.raw),/MEMORY_DEGRADED/);assert.equal(f.executions(),0);});
test('credential-shaped Memory context is rejected before durable admission or provider execution',async()=>{const s=await setup();const memory={getTaskContext:async()=>({state:'available',authorizationGranted:false,context:{note:'Bearer AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},receiptRef:'fixture:memory-context'})};const f=await serviceFixture(s,{memory});await assert.rejects(()=>f.service.infer(s.actor,s.raw),/CREDENTIAL_REJECTED/);assert.equal(f.executions(),0);assert.equal((await db.query('select count(*)::int n from private.pandora_ops_inference_requests where organization_id=$1',[s.org])).rows[0].n,0);});
test('service provider uncertainty retains the native parent lease and never retries',async()=>{const s=await setup(),f=await serviceFixture(s,{execute:async()=>{throw new Error('fixture transport lost');}});const result=await f.service.infer(s.actor,s.raw);assert.equal(result.state,'reconciliation_required');assert.equal(f.executions(),1);assert.equal((await db.query('select state from private.pandora_ops_leases where id=$1',[s.lease.id])).rows[0].state,'reconcile');const again=await f.service.infer(s.actor,s.raw);assert.equal(again.state,'reconciliation_required');assert.equal(f.executions(),1);});
for(const code of ['permission_denied','safety_refusal'])test(`service will not reroute ${code}`,async()=>{const s=await setup();const second={...s.policy.models[0],model:'second'};s.policy.models.push(second);await db.query('update private.pandora_ops_inference_policies set policy=$2 where organization_id=$1',[s.org,JSON.stringify(s.policy)]);const f=await serviceFixture(s,{execute:async()=>({output:null,receipt:receipt('failed',{code,billedCostMicros:0})})});const result=await f.service.infer(s.actor,s.raw);assert.equal(result.state,'failed');assert.equal(f.executions(),1);});
test('all capacity-held candidates cancel the admitted request instead of stranding budget',async()=>{
 const s=await setup(),f=await serviceFixture(s);
 f.store.prepare=async()=>{throw new api.InferenceError('INFERENCE_CAPACITY_HELD');};
 const r=await f.service.infer(s.actor,s.raw);assert.equal(r.state,'cancelled');assert.equal(r.reason,'no_capacity_available');assert.equal(f.executions(),0);
 const native=await status(s);assert.equal(native.request.state,'cancelled');assert.equal(native.attempts.length,0);
});
test('service known authorized rate-limit fallback uses a distinct durable attempt and preserves both receipts',async()=>const s=await setup();s.policy.models.push({...s.policy.models[0],model:'second'});await db.query('update private.pandora_ops_inference_policies set policy=$2 where organization_id=$1',[s.org,JSON.stringify(s.policy)]);let n=0;const f=await serviceFixture(s,{execute:async()=>{n++;if(n===1)return{output:null,receipt:receipt('failed',{code:'rate_limit',billedCostMicros:0})};return{output:'Fallback result',receipt:receipt('received',{providerReceipt:'fixture:second-response',outputDigest:api.sha256('Fallback result')})};}});const result=await f.service.infer(s.actor,s.raw);assert.equal(result.state,'verification_pending');assert.equal(f.executions(),2);const native=await status(s);assert.equal(native.attempts.length,2);assert.equal(native.attempts[0].state,'failed');assert.equal(native.attempts[1].state,'received');});
test('service native verification consumes an existing output-and-request-bound independent PASS',async()=>{const s=await setup(),f=await serviceFixture(s);const result=await f.service.infer(s.actor,s.raw);await enrollVerifier(s);const native=await status(s);const id=await verification(s,{artifact_digest:result.outputDigest,runtime_target_digest:native.request.request_digest});const verified=await f.service.verify(s.actor,s.raw.requestId,id);assert.equal(verified.status.state,'verified');assert.equal(verified.status.taskComplete,false);const {modelOutcome}=await import('../packages/pandora-operations-inference/memory-adoption.mjs');const outcome=modelOutcome(verified.native);assert.equal(outcome.sourceRunId,s.raw.requestId);assert.equal(outcome.verificationStatus,'pass');assert.equal(outcome.billedCostMicros,null);assert.equal(outcome.estimatedCostMicros,null);assert.equal(outcome.downstreamOutcomeStatus,'unknown');assert.ok(outcome.evidenceRefs.includes('verification-run:'+id));});
test('Memory adoption refuses an unverified provider response',async()=>{const s=await setup(),f=await serviceFixture(s);await f.service.infer(s.actor,s.raw);const {modelOutcome}=await import('../packages/pandora-operations-inference/memory-adoption.mjs');assert.throws(()=>modelOutcome(awaitablePlaceholder()),/VERIFIED_NATIVE/);function awaitablePlaceholder(){return{request:{state:'verification_pending'},attempts:[]};}});
test('new native service never stores raw task context or provider output in request or receipt rows',async()=>{const s=await setup(),f=await serviceFixture(s);const output=await f.service.infer(s.actor,s.raw);const rows=await status(s);const text=JSON.stringify(rows);assert.equal(text.includes(s.raw.parts[0].text),false);assert.equal(text.includes(output.output),false);assert.equal(text.includes(output.outputDigest),true);});

for(const [reason,sql]of[
 ['pause',"update private.pandora_ops_workspaces set paused=true where organization_id=$1"],
 ['caller revocation',"update private.pandora_ops_inference_callers set enabled=false where organization_id=$1"],
 ['policy change',"update private.pandora_ops_inference_policies set policy=jsonb_set(policy,'{version}','\"changed\"') where organization_id=$1"],
 ['task generation',"update private.pandora_ops_tasks set generation=generation+1 where organization_id=$1"]])test(`known rejected send after ${reason} is natively not_sent, not a provider-unknown hold`,async()=>{
 const s=await setup(),f=await serviceFixture(s),send=f.store.send.bind(f.store);
 f.store.send=async(...args)=>{await db.query(sql,[s.org]);return send(...args);};
 const r=await f.service.infer(s.actor,s.raw);assert.equal(f.executions(),0);assert.equal(r.state,'cancelled');
 const native=await status(s);assert.equal(native.attempts[0].state,'not_sent');assert.equal(native.attempts[0].billed_micros,0);
 assert.equal((await db.query('select state from private.pandora_ops_leases where id=$1',[s.lease.id])).rows[0].state,'running');
 await db.query('select private.pandora_ops_settle_v1($1,$2,$3,$4,0,$5)',[s.org,s.project,s.lease.id,s.lease.generation,'fixture:not-sent-settlement']);
});
test('definite native send rejection never escalates to reconciliation if recovery readback also fails',async()=>{
 const s=await setup(),f=await serviceFixture(s),send=f.store.send.bind(f.store);
 f.store.send=async(...args)=>{await db.query("update private.pandora_ops_workspaces set paused=true where organization_id=$1",[s.org]);return send(...args);};
 f.store.recover=async()=>{throw new api.InferenceError('INFERENCE_STORE_REJECTED');};
 await assert.rejects(()=>f.service.infer(s.actor,s.raw),/WORKSPACE_PAUSED|REQUEST_FENCED|ACCESS_DENIED/);assert.equal(f.executions(),0);
 const native=await status(s);assert.equal(native.attempts[0].state,'prepared');
 assert.equal((await db.query('select state from private.pandora_ops_leases where id=$1',[s.lease.id])).rows[0].state,'running');
});
test('unknown preparation response is recovered by native fencing without sending or replaying',async()=>{
 const s=await setup(),f=await serviceFixture(s),prepare=f.store.prepare.bind(f.store);
 f.store.prepare=async(...args)=>{await prepare(...args);throw new api.InferenceError('INFERENCE_TIMEOUT',{outcomeUnknown:true});};
 const r=await f.service.infer(s.actor,s.raw);assert.equal(r.state,'cancelled');assert.equal(f.executions(),0);
 const native=await status(s);assert.equal(native.attempts.length,1);assert.equal(native.attempts[0].state,'not_sent');assert.equal(native.attempts[0].billed_micros,0);
 assert.equal((await f.service.infer(s.actor,s.raw)).state,'cancelled');assert.equal(f.executions(),0);
});
test('recovery before a delayed prepare permanently fences that request',async()=>{
 const s=await setup();await call(s,'admit',s.metadata);const c=await call(s,'context',s.metadata);
 const r=await call(s,'recover_prepare',{requestId:s.metadata.requestId});assert.equal(r.resolved,true);assert.equal(r.sendFenced,true);assert.equal(r.providerStopped,false);
 await assert.rejects(()=>call(s,'prepare',{requestId:s.metadata.requestId,modelKey:'fixture:strong',policyDigest:c.policyDigest}),/REQUEST_FENCED/);
 assert.equal((await status(s)).attempts.length,0);
});
test('a lost committed send response remains unknown, not falsely not_sent',async()=>{
 const s=await setup(),f=await serviceFixture(s),send=f.store.send.bind(f.store);
 f.store.send=async(...args)=>{await send(...args);throw new api.InferenceError('INFERENCE_TIMEOUT',{outcomeUnknown:true});};
 const r=await f.service.infer(s.actor,s.raw);assert.equal(r.state,'reconciliation_required');assert.equal(f.executions(),0);
 const native=await status(s);assert.equal(native.attempts[0].state,'reconciliation_required');assert.equal(native.attempts[0].billed_micros,null);
 assert.equal((await db.query('select state from private.pandora_ops_leases where id=$1',[s.lease.id])).rows[0].state,'reconcile');
});
test('read-only provider preflight rejects before request admission or attempt reservation',async()=>{
 const s=await setup(),f=await serviceFixture(s,{preflight:()=>{throw new api.InferenceError('INFERENCE_PAYLOAD_LIMIT');}});
 await assert.rejects(()=>f.service.infer(s.actor,s.raw),/PAYLOAD_LIMIT/);assert.equal(f.executions(),0);
 assert.equal((await db.query('select count(*)::int n from private.pandora_ops_inference_requests where organization_id=$1',[s.org])).rows[0].n,0);
});
test('recovery never releases a provider attempt with granted sending authority',async()=>{
 const s=await setup(),a=await prepare(s);await send(s,a);
 const r=await call(s,'recover_prepare',{requestId:s.metadata.requestId});assert.equal(r.resolved,false);assert.equal(r.providerStopped,false);
 assert.equal((await status(s)).attempts[0].state,'sent');
});
test('actual native owner feed can consume receipt-less ingestion/control events without inventing evidence',async()=>{
 const s=await setup(),{OperationsTheatre}=await import('../packages/pandora-operations-inference/theatre.mjs');
 const theatre=new OperationsTheatre({readEvents:args=>rpc('pandora_ops_event_feed_v1',{p_organization_id:args.organizationId,p_project_id:args.projectId,p_actor_id:s.owner,p_after:args.after,p_limit:args.limit})});
 theatre.reset({organizationId:s.org,projectId:s.project,sessionKey:'fixture-owner'});const view=await theatre.refresh();
 assert.ok(view.events.some(e=>e.type==='tasks_ingested'&&e.receiptRef===null));assert.ok(view.events.some(e=>e.type==='owner_resume'&&e.receiptRef===null));
 assert.ok(view.events.every(e=>e.progress===null));
});
test('binary image request traverses the real native service without false credential rejection',async()=>{
 const image=require('./fixtures/inference-image-fixture.cjs')(),s=await setup({modelPatch:{classes:['vision'],modalities:['text','image'],imageTokenUpperBound:512}});
 await db.query("update private.pandora_ops_inference_callers set classes=array['vision'] where organization_id=$1",[s.org]);
 s.raw={...s.raw,taskClass:'vision',parts:[{type:'image',mimeType:'image/png',data:image.data}]};
 const f=await serviceFixture(s);const r=await f.service.infer(s.actor,s.raw);assert.equal(r.state,'verification_pending');assert.equal(f.executions(),1);
});
