'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {PandoraBookingService,formatInstantInTimezone}=require('../packages/primitives/booking/src');
class AtomicRepo{constructor(capacity=1){this.transactionSafe=true;this.capacity=capacity;this.reserved=0;this.rows=new Map();this.queue=Promise.resolve();}async listAvailability(){return[{id:'slot-1',capacity:this.capacity,remaining:this.capacity-this.reserved}];}async createReservationAtomic(input){let release;const prior=this.queue;this.queue=new Promise(r=>release=r);await prior;try{if(this.rows.has(input.idempotencyKey))return this.rows.get(input.idempotencyKey);if(this.reserved>=this.capacity){const e=new Error('slot unavailable');e.code='CAPACITY_EXHAUSTED';throw e;}await new Promise(r=>setTimeout(r,5));this.reserved++;const row={id:`r${this.reserved}`,slotId:input.slotId,status:'confirmed'};this.rows.set(input.idempotencyKey,row);return row;}finally{release();}}async cancelReservationAtomic({reservationId}){const row=[...this.rows.values()].find(r=>r.id===reservationId);if(!row)throw new Error('missing');if(row.status!=='cancelled'){row.status='cancelled';this.reserved--;}return row;}}
function service(repo,events=[]){return new PandoraBookingService({repository:repo,eventSink:{idempotent:true,async publish(e){events.push(e);}}});}
test('booking proof: available slot -> reservation -> event -> availability decreases',async()=>{const repo=new AtomicRepo(1);const events=[];const booking=service(repo,events);assert.equal((await booking.listAvailability({scopeId:'s',from:'2027-01-01T00:00:00Z',to:'2027-01-02T00:00:00Z',timezone:'Asia/Manila'}))[0].remaining,1);const row=await booking.createReservation({project:{id:'p',versionId:'v1',environment:'test'},scopeId:'s',slotId:'slot-1',identity:{userId:'u1'},idempotencyKey:'reserve-1'});assert.equal(row.status,'confirmed');assert.equal(events[0].name,'reservation.created');assert.equal((await repo.listAvailability())[0].remaining,0);});
test('concurrent reservation collision is transactionally rejected',async()=>{const repo=new AtomicRepo(1);const booking=service(repo);const [a,b]=await Promise.allSettled([booking.createReservation({project:{id:'p',versionId:'v',environment:'test'},scopeId:'s',slotId:'slot-1',identity:{userId:'u1'},idempotencyKey:'a'}),booking.createReservation({project:{id:'p',versionId:'v',environment:'test'},scopeId:'s',slotId:'slot-1',identity:{userId:'u2'},idempotencyKey:'b'})]);assert.equal([a,b].filter(x=>x.status==='fulfilled').length,1);assert.equal([a,b].filter(x=>x.status==='rejected').length,1);assert.equal(repo.reserved,1);});
test('idempotent reservation retry does not consume capacity twice',async()=>{const repo=new AtomicRepo(1);const booking=service(repo);const req={project:{id:'p',versionId:'v',environment:'test'},scopeId:'s',slotId:'slot-1',identity:{userId:'u1'},idempotencyKey:'same'};const first=await booking.createReservation(req);const second=await booking.createReservation(req);assert.equal(first.id,second.id);assert.equal(repo.reserved,1);});
test('timezone rendering is intentional and DST aware',()=>{const jan=formatInstantInTimezone('2027-01-15T12:00:00Z','America/New_York');const jul=formatInstantInTimezone('2027-07-15T12:00:00Z','America/New_York');assert.equal(jan.hour,'07');assert.equal(jul.hour,'08');assert.throws(()=>formatInstantInTimezone('2027-01-01T00:00:00Z','Not/AZone'),/IANA/);});
test('booking migration uses atomic capacity mutation, idempotency, customer ownership and RLS',()=>{const sql=fs.readFileSync(path.join(__dirname,'..','packages/primitives/booking/migrations/001_booking.sql'),'utf8');assert.match(sql,/reserved_count=reserved_count\+1/);assert.match(sql,/reserved_count<capacity/);assert.match(sql,/UNIQUE\(scope_id,idempotency_key\)/);assert.match(sql,/customer_user_id=\(SELECT auth.uid\(\)\)/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/SECURITY DEFINER/);assert.match(sql,/target: customer-app-runtime-only/);});
test('booking slot visibility is scope-bound for authenticated users',()=>{const sql=fs.readFileSync(require.resolve('../packages/primitives/booking/migrations/001_booking.sql'),'utf8');assert.match(sql,/primitive_booking_scope_access/);assert.match(sql,/booking scope access denied/);assert.doesNotMatch(sql,/USING\(true\)/);});
test('booking requires idempotent event publication and forwards scope to notification confirmation',async()=>{const repository={transactionSafe:true,async listAvailability(){return[]},async createReservationAtomic(){return{id:'r1',slotId:'s1',status:'confirmed',notificationRecipient:'u@example.com'}},async cancelReservationAtomic(){return{id:'r1',slotId:'s1',status:'cancelled'}}};assert.throws(()=>new PandoraBookingService({repository,eventSink:{async publish(){} }}),/idempotent/);let notificationScope=null;const service=new PandoraBookingService({repository,eventSink:{idempotent:true,async publish(){}},notifications:{async send(input){notificationScope=input.scopeId;return{receipt:{deliveryId:'d1'}};}}});await service.createReservation({project:{id:'p1',versionId:'v1',environment:'test'},scopeId:'scope-1',slotId:'s1',identity:{userId:'u1'},idempotencyKey:'r:1'});assert.equal(notificationScope,'scope-1');});
