'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {PandoraCrmService,minimizeContact}=require('../packages/primitives/crm/src');
const {PandoraFormsService,validateSchema}=require('../packages/primitives/forms/src');
const {PandoraFilesService,validateImageTransform}=require('../packages/primitives/files/src');
const project={id:'project-1',versionId:'version-1',environment:'test'};
function sink(){return {idempotent:true,events:[],async publish(event){this.events.push(event);}};}
test('CRM minimizes contact data and emits canonical idempotent events',async()=>{assert.throws(()=>minimizeContact({medicalCondition:'x'},new Set(['medicalCondition'])),/sensitive/i);const events=sink();const service=new PandoraCrmService({repository:{async upsertContact(x){return{id:'c1',...x.contact};},async createLead(){return{id:'l1'};},async addInteraction(x){return x;},async listContacts(){return[];}},eventSink:events});const out=await service.upsertContact({project,scopeId:'scope-1',identity:{userId:'u1'},contact:{name:'A',email:'a@example.com'},idempotencyKey:'crm-1'});assert.equal(out.event.name,'customer.created');assert.equal(out.event.idempotencyKey,'event:crm-1');});
test('Forms validates schema server-side and rejects unknown/oversized input',async()=>{assert.throws(()=>validateSchema({fields:[{name:'email',type:'email',required:true}]},{email:'bad'}),/email/);assert.throws(()=>validateSchema({fields:[{name:'name',type:'text'}]},{other:'x'}),/unknown/);const events=sink();const service=new PandoraFormsService({repository:{async getForm(){return{id:'f1',active:true,schema:{fields:[{name:'name',type:'text',required:true,maxLength:20}]},attachmentPolicy:{maxFiles:0}};},async createSubmission(x){return{id:'s1',status:'submitted',...x};}},spamGuard:{async assess(){return{allowed:true};}},eventSink:events,maxPayloadBytes:128});const out=await service.submit({project,scopeId:'scope-1',formKey:'contact',values:{name:'Jane'},idempotencyKey:'form-1'});assert.equal(out.event.name,'form.submitted');assert.equal(events.events.length,1);});
test('Files requires detected content agreement and private owner-bound access',async()=>{const rows=new Map();const storage={async putVerified(x){return{detectedContentType:x.declaredContentType,sha256:'a'.repeat(64),byteSize:x.sizeBytes};},async signPrivateUrl(x){return{url:'https://signed.invalid/private',...x};},async remove(){}};const repository={async createMetadata(x){const row={id:'file-1',scopeId:x.scopeId,ownerUserId:x.ownerUserId,objectKey:x.objectKey,originalName:x.originalName,deletedAt:null};rows.set(row.id,row);return row;},async getMetadata({fileId}){return rows.get(fileId)||null;},async markDeleted({fileId}){rows.get(fileId).deletedAt=new Date().toISOString();}};const service=new PandoraFilesService({storage,repository,allowedContentTypes:['image/png'],maxBytes:1024});const file=await service.upload({scopeId:'scope-1',identity:{userId:'u1'},fileName:'avatar.png',declaredContentType:'image/png',sizeBytes:12,bytes:Buffer.from('fake')});assert.match(file.objectKey,/^scope-1\/u1\/[a-f0-9]{36}-avatar\.png$/);const signed=await service.signAccess({scopeId:'scope-1',identity:{userId:'u1'},fileId:'file-1',ttlSeconds:120});assert.equal(signed.ttlSeconds,120);});
test('Files rejects MIME mismatch, unsafe transforms, and cross-owner access',async()=>{const storage={async putVerified(x){return{detectedContentType:'application/pdf',sha256:'b'.repeat(64),byteSize:x.sizeBytes};},async signPrivateUrl(){return{};},async remove(){}};const repository={async createMetadata(){throw new Error('must not persist');},async getMetadata(){return{id:'f',scopeId:'scope-1',ownerUserId:'u2',objectKey:'k',originalName:'x',deletedAt:null};},async markDeleted(){}};const service=new PandoraFilesService({storage,repository,allowedContentTypes:['image/png','application/pdf']});await assert.rejects(()=>service.upload({scopeId:'scope-1',identity:{userId:'u1'},fileName:'x.png',declaredContentType:'image/png',sizeBytes:3,bytes:Buffer.from('x')}),/detected content type/);assert.throws(()=>validateImageTransform({width:9000}),/1-4096/);await assert.rejects(()=>service.signAccess({scopeId:'scope-1',identity:{userId:'u1'},fileId:'f',ttlSeconds:60}),/denied/);});
test('customer-runtime migrations fail closed and keep client writes disabled',()=>{for(const rel of ['crm/migrations/001_crm.sql','forms/migrations/001_forms.sql','files/migrations/001_files.sql']){const sql=fs.readFileSync(path.join(__dirname,'../packages/primitives',rel),'utf8');assert.match(sql,/customer-app-runtime-only/);assert.match(sql,/projectos_execution_plans/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/REVOKE ALL/);}const crm=fs.readFileSync(path.join(__dirname,'../packages/primitives/crm/migrations/001_crm.sql'),'utf8');assert.match(crm,/primitive_has_permission\(scope_id,'crm\.read'\)/);const files=fs.readFileSync(path.join(__dirname,'../packages/primitives/files/migrations/001_files.sql'),'utf8');assert.match(files,/object bucket\/container provisioning is Worker F responsibility/);});
