'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs');
const { PandoraRbacService, PermissionDeniedError }=require('../packages/primitives/rbac/src');
const { PandoraAuditService, sanitizeMetadata }=require('../packages/primitives/audit/src');
const { PandoraAdminService, normalizeListQuery }=require('../packages/primitives/admin/src');
function rbacFor(role){return new PandoraRbacService({membershipResolver:{async resolve({tenantId}){return[{tenantId,role}]}}});}
function adapters(){ const records=[]; return { records, resource:{async list(q){return {items:[],query:q}},async create(x){return{id:'r1',...x}},async update(x){return{id:x.resourceId,...x.patch}},async changeStatus(x){return{id:x.resourceId,status:x.status}},async remove(x){return{id:x.resourceId,removed:true}}}, sink:{async append(r){records.push(r);return{receiptId:`a${records.length}`}}} }; }
test('admin list is bounded and requires admin.read',async()=>{const a=adapters();const svc=new PandoraAdminService({rbac:rbacFor('staff'),resourceAdapter:a.resource,audit:new PandoraAuditService({sink:a.sink})});const result=await svc.list({userId:'u1',tenantId:'t1',query:{pageSize:50,search:' hello ',direction:'desc'}});assert.equal(result.query.pageSize,50);assert.equal(result.query.search,'hello');assert.throws(()=>normalizeListQuery({pageSize:101}),/1-100/);});
test('admin mutation requires backend permission and emits audit receipt',async()=>{const a=adapters();const owner=new PandoraAdminService({rbac:rbacFor('owner'),resourceAdapter:a.resource,audit:new PandoraAuditService({sink:a.sink,clock:()=>new Date('2026-01-01T00:00:00Z')})});const created=await owner.create({userId:'u1',tenantId:'t1',resourceType:'booking',data:{status:'new'},mutationId:'m1'});assert.equal(created.id,'r1');assert.equal(a.records[0].eventName,'booking.created');assert.match(a.records[0].changeDigest,/^sha256:/);const denied=new PandoraAdminService({rbac:rbacFor('member'),resourceAdapter:a.resource,audit:new PandoraAuditService({sink:a.sink})});await assert.rejects(()=>denied.create({userId:'u2',tenantId:'t1',resourceType:'booking',data:{status:'new'},mutationId:'m2'}),PermissionDeniedError);});
test('destructive admin action requires explicit resource confirmation',async()=>{const a=adapters();const svc=new PandoraAdminService({rbac:rbacFor('owner'),resourceAdapter:a.resource,audit:new PandoraAuditService({sink:a.sink})});await assert.rejects(()=>svc.remove({userId:'u1',tenantId:'t1',resourceType:'order',resourceId:'o1',mutationId:'m1',confirmation:'yes'}),/confirmation/);const result=await svc.remove({userId:'u1',tenantId:'t1',resourceType:'order',resourceId:'o1',mutationId:'m2',confirmation:'DELETE o1'});assert.equal(result.removed,true);assert.equal(a.records.at(-1).eventName,'order.deleted');});
test('audit metadata strips secret-shaped fields and migration is read-only to clients',()=>{assert.deepEqual(sanitizeMetadata({status:'ok',apiKey:'secret',nested:{token:'bad',safe:true}}),{status:'ok',nested:{safe:true}});const sql=fs.readFileSync(require.resolve('../packages/primitives/audit/migrations/001_audit.sql'),'utf8');assert.match(sql,/customer-app-runtime-only/);assert.match(sql,/refused on Pandora Control Plane-like schema/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/primitive_has_permission\(tenant_id, 'audit.read'\)/);assert.doesNotMatch(sql,/GRANT (?:INSERT|UPDATE|DELETE).*authenticated/i);});
