'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {planPrimitiveUpgrades}=require('../packages/primitives/src/lifecycle');
const {planPrimitiveMaterialization,planExecutionBoundaries,validateEventCompatibility,buildWorkerDMaterializationRequest}=require('../packages/primitives/src/materialization');
const H='sha256:'+'a'.repeat(64),B='sha256:'+'b'.repeat(64),C='sha256:'+'c'.repeat(64),D='sha256:'+'d'.repeat(64);
function registry(defs){const map=new Map(defs.map(d=>[`${d.name}@${d.version}`,d]));return{getExact:(n,v)=>map.get(`${n}@${v}`)||null};}
const manifest={projectId:'p1',projectVersionId:'pv1',manifestDigest:H,primitives:[{name:'alpha',version:'1.0.0',sourceDigest:B},{name:'beta',version:'1.0.0',sourceDigest:C}]};
test('minor trusted upgrade is deterministic AUTO with exact migration',()=>{const r=registry([{name:'alpha',version:'1.1.0',trustState:'TRUSTED',sourceDigest:C,definitionDigest:D}]);const out=planPrimitiveUpgrades(r,{currentManifest:manifest,targets:[{name:'alpha',version:'1.1.0'}],migrations:[{name:'alpha',id:'m1',fromVersion:'1.0.0',toVersion:'1.1.0',digest:D,reversible:true,rollback:'m1_down'}],now:'2026-08-29T00:00:00Z'});assert.equal(out.ok,true);assert.equal(out.plan.decision,'AUTO');assert.match(out.plan.planDigest,/^sha256:/);});
test('major, experimental and irreversible upgrade requires review',()=>{const r=registry([{name:'alpha',version:'2.0.0',trustState:'EXPERIMENTAL',sourceDigest:C,definitionDigest:D}]);const out=planPrimitiveUpgrades(r,{currentManifest:manifest,targets:[{name:'alpha',version:'2.0.0'}],migrations:[{name:'alpha',id:'m2',fromVersion:'1.0.0',toVersion:'2.0.0',digest:D,reversible:false}]});assert.equal(out.plan.decision,'MANUAL_REVIEW');assert.deepEqual(out.plan.steps[0].reasons,['irreversible-migration','major-version-change','target-experimental']);});
test('blocked target and migration gaps fail closed',()=>{const r=registry([{name:'alpha',version:'1.2.0',trustState:'BLOCKED',sourceDigest:C,definitionDigest:D}]);const out=planPrimitiveUpgrades(r,{currentManifest:manifest,targets:[{name:'alpha',version:'1.2.0'}],migrations:[]});assert.equal(out.ok,false);assert.match(out.errors[0],/migration chain has a gap/);});
test('customer-owned files are preserved and primitive-core edits collide',()=>{const plan=planPrimitiveMaterialization({manifest,sourceFiles:[{path:'src/core.js',primitive:'alpha',contentDigest:C,basePrimitiveDigest:B,ownership:'primitive-core'},{path:'src/custom.js',primitive:'alpha',contentDigest:C,ownership:'customer-owned'}],currentFiles:[{path:'src/core.js',primitive:'alpha',contentDigest:D,basePrimitiveDigest:B,ownership:'primitive-core'},{path:'src/custom.js',primitive:'alpha',contentDigest:B,ownership:'customer-owned'}]});assert.equal(plan.decision,'MANUAL_REVIEW');assert.equal(plan.collisions[0].reason,'primitive-core-modified-by-customer');assert.equal(plan.actions.find(a=>a.path==='src/custom.js').type,'PRESERVE');});
test('extension point preserves customization only when base primitive digest is unchanged',()=>{const ready=planPrimitiveMaterialization({manifest,sourceFiles:[{path:'ext.js',primitive:'alpha',contentDigest:C,basePrimitiveDigest:B,ownership:'extension-point'}],currentFiles:[{path:'ext.js',primitive:'alpha',contentDigest:D,basePrimitiveDigest:B,ownership:'extension-point'}]});assert.equal(ready.decision,'READY');assert.equal(ready.actions[0].type,'PRESERVE');const bad=planPrimitiveMaterialization({manifest,sourceFiles:[{path:'ext.js',primitive:'alpha',contentDigest:C,basePrimitiveDigest:C,ownership:'extension-point'}],currentFiles:[{path:'ext.js',primitive:'alpha',contentDigest:D,basePrimitiveDigest:B,ownership:'extension-point'}]});assert.equal(bad.collisions[0].reason,'extension-base-changed');});
test('event major-version conflicts are rejected',()=>{const result=validateEventCompatibility([{name:'a',events:[{name:'order.created',version:'1.0'}]},{name:'b',events:[{name:'order.created',version:'2.1'}]}]);assert.equal(result.ok,false);assert.match(result.errors[0],/incompatible majors/);});
test('cross-provider nontransactional steps require compensation',()=>{const bad=planExecutionBoundaries([{id:'db',provider:'postgres',transactional:true},{id:'charge',provider:'payments',transactional:false}]);assert.equal(bad.ok,false);const good=planExecutionBoundaries([{id:'db',provider:'postgres',transactional:true},{id:'charge',provider:'payments',transactional:false,compensation:'refund'}]);assert.equal(good.ok,true);assert.equal(good.requiresSaga,true);});
test('Worker D request is exact-digest only and rejects raw secrets',()=>{const mat=planPrimitiveMaterialization({manifest,sourceFiles:[{path:'a.js',primitive:'alpha',contentDigest:C,ownership:'primitive-core'}]});const req=buildWorkerDMaterializationRequest({manifest,materializationPlan:mat,runtimeBindings:{database:{bindingId:'db-1'}}});assert.equal(req.projectVersionId,'pv1');assert.match(req.requestDigest,/^sha256:/);assert.throws(()=>buildWorkerDMaterializationRequest({manifest,materializationPlan:mat,runtimeBindings:{paymentSecret:'x'}}),/raw secret/);});
