'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {NotificationTemplateRegistry,PandoraNotificationService}=require('../packages/primitives/notifications/src');const {PandoraAnalytics}=require('../packages/primitives/analytics/src');
function idempotencyStore(){const state=new Map();const keyOf=({scopeId,idempotencyKey})=>`${scopeId}:${idempotencyKey}`;return{async claim(input){const key=keyOf(input);if(state.has(key))return{claimed:false,receipt:state.get(key).receipt||null};state.set(key,{status:'claimed'});return{claimed:true};},async complete(input,receipt){state.set(keyOf(input),{status:'complete',receipt});},async fail(input,error){state.delete(keyOf(input));return error;}};}
test('notification template escapes HTML and rejects undeclared variables',()=>{const templates=new NotificationTemplateRegistry({booking_confirmation:{subject:'Booking {{code}}',body:'Hello {{name}}',allowedVariables:['code','name'],format:'html'}});const rendered=templates.render('booking_confirmation',{code:'B1',name:'<script>x</script>'});assert.equal(rendered.body,'Hello &lt;script&gt;x&lt;/script&gt;');assert.throws(()=>templates.render('booking_confirmation',{code:'B1',name:'A',token:'x'}),/not allowed/);});
test('notification retries are idempotent and do not send duplicate confirmation',async()=>{let sends=0;const templates=new NotificationTemplateRegistry({order_confirmation:{subject:'Order {{id}}',body:'Confirmed',allowedVariables:['id']}});const service=new PandoraNotificationService({provider:{async send(){sends++;return{deliveryId:'d1',status:'delivered'};}},templates,idempotencyStore:idempotencyStore()});const request={scopeId:'scope-1',channel:'email',recipient:'user@example.com',template:'order_confirmation',variables:{id:'O1'},idempotencyKey:'order:O1:confirmation'};assert.equal((await service.send(request)).duplicate,false);assert.equal((await service.send(request)).duplicate,true);assert.equal(sends,1);});
test('notification provider failure releases idempotency claim for bounded retry',async()=>{let attempts=0;const store=idempotencyStore();const service=new PandoraNotificationService({provider:{async send(){attempts++;if(attempts===1){const e=new Error('down');e.code='TEMPORARY';throw e;}return{deliveryId:'d2'};}},templates:new NotificationTemplateRegistry({status:{subject:'Status',body:'Updated',allowedVariables:[]}}),idempotencyStore:store});const req={scopeId:'scope-1',channel:'email',recipient:'u@example.com',template:'status',variables:{},idempotencyKey:'status:1'};await assert.rejects(()=>service.send(req),/down/);const second=await service.send(req);assert.equal(second.duplicate,false);assert.equal(attempts,2);});
test('analytics emits canonical project/version/environment event and pseudonymizes user identity',async()=>{const events=[];const analytics=new PandoraAnalytics({sink:{idempotent:true,async capture(event){events.push(event);return{eventId:'e1'};}}});const result=await analytics.captureBusinessEvent({name:'booking_completed',project:{id:'p1',versionId:'v18',environment:'preview'},actor:{userId:'user-real'},aggregate:{type:'reservation',id:'r1'},properties:{amount_minor:2500,currency:'PHP',token:'secret'},idempotencyKey:'booking:r1:completed'});assert.equal(result.event.name,'business.booking_completed');assert.equal(result.event.project.versionId,'v18');assert.equal(result.event.project.environment,'preview');assert.notEqual(result.event.actor.userId,'user-real');assert.equal(result.event.payload.token,undefined);assert.equal(events.length,1);});
test('analytics refuses ad hoc event meanings',async()=>{const analytics=new PandoraAnalytics({sink:{idempotent:true,async capture(){return{eventId:'e1'};}}});await assert.rejects(()=>analytics.captureBusinessEvent({name:'whatever_happened',project:{id:'p',versionId:'v',environment:'test'},idempotencyKey:'whatever:1'}),/unsupported canonical/);});

const fs=require('node:fs');
test('notification and analytics migrations enforce customer-runtime isolation and server-only writes',()=>{for(const rel of ['../packages/primitives/notifications/migrations/001_notifications.sql','../packages/primitives/analytics/migrations/001_analytics_outbox.sql']){const sql=fs.readFileSync(require.resolve(rel),'utf8');assert.match(sql,/customer-app-runtime-only/);assert.match(sql,/refused on Pandora Control Plane-like schema/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.doesNotMatch(sql,/GRANT (?:INSERT|UPDATE|DELETE).*authenticated/i);}});

test('notification idempotency is scope-bound and analytics rejects non-idempotent sinks',async()=>{let sends=0;const store=idempotencyStore();const service=new PandoraNotificationService({provider:{async send(){sends++;return{deliveryId:`d${sends}`};}},templates:new NotificationTemplateRegistry({status:{subject:'Status',body:'Updated',allowedVariables:[]}}),idempotencyStore:store});const base={channel:'email',recipient:'u@example.com',template:'status',variables:{},idempotencyKey:'same-key'};await service.send({...base,scopeId:'scope-a'});await service.send({...base,scopeId:'scope-b'});assert.equal(sends,2);assert.throws(()=>new PandoraAnalytics({sink:{async capture(){return{eventId:'x'};}}}),/idempotent/);});
