'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {PandoraSearchService}=require('../packages/primitives/search/src');
const {PandoraContentService}=require('../packages/primitives/content/src');
const {PandoraSchedulingService,appliesOnLocalDate,normalizeSchedule}=require('../packages/primitives/scheduling/src');
const {PandoraCustomerProfileService,normalizePatch}=require('../packages/primitives/customer-profile/src');
const {PandoraSettingsService,normalizeSettings}=require('../packages/primitives/settings/src');
const {PandoraFeatureFlagsService,flagKey}=require('../packages/primitives/feature-flags/src');
const project={id:'project-1',versionId:'version-1',environment:'test'};
function auth(){return{calls:[],async assertAllowed(x){this.calls.push(x);return{allowed:true};}};}function sink(){return{idempotent:true,events:[],async publish(e){this.events.push(e);}};}
test('Search is scope-aware, bounded, authorized, and rejects cross-scope provider output',async()=>{const authorization=auth();const provider={scopeAware:true,async search(x){return{scopeId:x.scopeId,items:[{id:'1'}],nextCursor:null};}};const svc=new PandoraSearchService({provider,authorization});const out=await svc.search({scopeId:'tenant-1',identity:{userId:'u1'},query:' cafe ',filters:{active:true},sort:{field:'name',direction:'asc'},limit:10});assert.equal(out.scopeId,'tenant-1');assert.equal(authorization.calls[0].permission,'data.read');const bad=new PandoraSearchService({provider:{scopeAware:true,async search(){return{scopeId:'tenant-2',items:[]};}},authorization});await assert.rejects(()=>bad.search({scopeId:'tenant-1',identity:{userId:'u1'}}),/cross-scope/);await assert.rejects(()=>svc.search({scopeId:'tenant-1',identity:{userId:'u1'},filters:{x:{nested:true}}}),/bounded scalar/);});
test('Content exposes only published records publicly and backend-authorizes mutations',async()=>{const authorization=auth(),events=sink();let row={id:'c1',kind:'page',slug:'about-us',title:'About',body:'Body',status:'published',version:1};const repo={async getBySlug(){return row;},async listPublished(){return[row];},async createDraft(x){return{id:'c2',kind:x.kind,slug:x.slug,title:x.title,body:x.body,status:'draft',version:1};},async updateDraft(x){return{id:x.contentId,kind:'page',slug:'about-us',title:x.title,body:x.body,status:'draft',version:2};},async setStatus(x){return{id:x.contentId,kind:'page',slug:'about-us',title:'About',body:'Body',status:x.status,version:2};}};const svc=new PandoraContentService({repository:repo,authorization,eventSink:events});assert.equal((await svc.getPublished({scopeId:'tenant-1',kind:'page',slug:'about-us'})).status,'published');row={...row,status:'draft'};assert.equal(await svc.getPublished({scopeId:'tenant-1',kind:'page',slug:'about-us'}),null);const created=await svc.createDraft({project,scopeId:'tenant-1',identity:{userId:'u1'},kind:'faq',slug:'shipping',title:'Shipping',body:'Info',idempotencyKey:'content-1'});assert.equal(authorization.calls.at(-1).permission,'data.write');assert.equal(created.event.name,'content.changed');assert.equal(created.event.idempotencyKey,'event:content-1');});
test('Scheduling validates IANA timezone, weekly recurrence, and local-date exceptions',async()=>{const schedule=normalizeSchedule({timezone:'Asia/Manila',weekly:[{weekday:'mon',start:'09:00',end:'17:00'}],exceptions:[{date:'2026-08-31',closed:true},{date:'2026-09-01',windows:[{start:'10:00',end:'12:00'}]}]});assert.deepEqual(appliesOnLocalDate(schedule,'2026-08-31'),[]);assert.deepEqual(appliesOnLocalDate(schedule,'2026-09-01'),[{start:'10:00',end:'12:00'}]);assert.throws(()=>normalizeSchedule({timezone:'Not/AZone',weekly:[{weekday:'mon',start:'09:00',end:'17:00'}]}),/IANA/);const authorization=auth(),events=sink(),repo={async getSchedule(){return schedule;},async saveSchedule(x){return{id:'sch-1',...x};}};const svc=new PandoraSchedulingService({repository:repo,authorization,eventSink:events});const out=await svc.save({project,scopeId:'tenant-1',identity:{userId:'u1'},resourceId:'room-1',schedule,idempotencyKey:'sched-1'});assert.equal(out.event.name,'schedule.changed');assert.equal(authorization.calls[0].permission,'data.write');});
test('Customer profile binds self identity and blocks sensitive or arbitrary fields',async()=>{assert.throws(()=>normalizePatch({religion:'x'}),/sensitive/i);assert.throws(()=>normalizePatch({arbitrary:'x'}),/not allowed/i);const authorization=auth();let last=null;const repo={async getProfile({userId}){return{userId,displayName:'Jane',preferences:{theme:'light'}};},async upsertProfile(x){last=x;return x;}};const svc=new PandoraCustomerProfileService({repository:repo,authorization});await svc.updateSelf({scopeId:'tenant-1',identity:{userId:'actual-user'},patch:{displayName:'Jane',preferences:{theme:'dark'}},idempotencyKey:'profile-1'});assert.equal(last.userId,'actual-user');const admin=await svc.getForAdmin({scopeId:'tenant-1',identity:{userId:'admin'},userId:'other-user'});assert.equal(admin.userId,'other-user');assert.equal(authorization.calls[0].permission,'users.read');});
test('Settings require read/manage permissions and validate locale/timezone/currency/bounded objects',async()=>{assert.equal(normalizeSettings({businessName:'Acme',timezone:'Asia/Manila',currency:'php',locale:'en-PH'}).currency,'PHP');assert.throws(()=>normalizeSettings({timezone:'Mars/Olympus'}),/IANA/);const authorization=auth(),repo={async getSettings(){return{businessName:'Acme',timezone:'Asia/Manila',currency:'PHP',locale:'en-PH'};},async saveSettings(x){return x.settings;}};const svc=new PandoraSettingsService({repository:repo,authorization});await svc.get({scopeId:'tenant-1',identity:{userId:'u1'}});await svc.save({scopeId:'tenant-1',identity:{userId:'u1'},settings:{businessName:'Acme'},idempotencyKey:'settings-1'});assert.deepEqual(authorization.calls.map(x=>x.permission),['settings.read','settings.manage']);});
test('Feature flags deny dangerous keys, use safe defaults, require authorization, and audit writes',async()=>{for(const key of ['service_role','raw_sql','disable-auth','allow_all'])assert.throws(()=>flagKey(key),/unsafe/);const authorization=auth(),audit={records:[],async record(x){this.records.push(x);}},rows=new Map();const store={scopeAware:true,async get({scopeId,key}){const row=rows.get(`${scopeId}:${key}`);return row?{scopeId,...row}:null;},async set({scopeId,key,value}){rows.set(`${scopeId}:${key}`,{key,value});return{key,value};},async remove({scopeId,key}){rows.delete(`${scopeId}:${key}`);return{removed:true};}};const svc=new PandoraFeatureFlagsService({store,authorization,audit});assert.equal(await svc.evaluate({scopeId:'tenant-1',identity:{userId:'u1'},key:'new_checkout',defaultValue:false}),false);await svc.set({scopeId:'tenant-1',identity:{userId:'u1'},key:'new_checkout',value:true,idempotencyKey:'flag-1'});assert.equal(await svc.evaluate({scopeId:'tenant-1',identity:{userId:'u1'},key:'new_checkout'}),true);assert.equal(audit.records[0].event,'feature_flag.set');assert.ok(authorization.calls.every(x=>['settings.read','settings.manage'].includes(x.permission)));});
test('customer-runtime migrations fail closed, force RLS, and bind merged RBAC permissions',()=>{for(const rel of ['content/migrations/001_content.sql','scheduling/migrations/001_scheduling.sql','customer-profile/migrations/001_customer_profile.sql','settings/migrations/001_settings.sql']){const sql=fs.readFileSync(path.join(__dirname,'../packages/primitives',rel),'utf8');assert.match(sql,/customer-app-runtime-only/);assert.match(sql,/projectos_execution_plans/);assert.match(sql,/FORCE ROW LEVEL SECURITY/);assert.match(sql,/REVOKE ALL/);}const content=fs.readFileSync(path.join(__dirname,'../packages/primitives/content/migrations/001_content.sql'),'utf8');assert.match(content,/status='published'/);assert.match(content,/primitive_has_permission\(scope_id,'data\.read'\)/);const profile=fs.readFileSync(path.join(__dirname,'../packages/primitives/customer-profile/migrations/001_customer_profile.sql'),'utf8');assert.match(profile,/user_id=\(SELECT auth\.uid\(\)\)/);assert.doesNotMatch(profile,/jsonb.*custom/i);});
test('service contracts reject unscoped providers and non-idempotent event sinks',()=>{assert.throws(()=>new PandoraSearchService({provider:{async search(){}},authorization:auth()}),/scope-aware/);const repository={async getBySlug(){},async listPublished(){return[];},async createDraft(){},async updateDraft(){},async setStatus(){}};assert.throws(()=>new PandoraContentService({repository,authorization:auth(),eventSink:{async publish(){}}}),/idempotent/);});
test('all six platform sources are credential-literal free and syntactically loadable',()=>{for(const rel of ['search/src/index.js','content/src/index.js','scheduling/src/index.js','customer-profile/src/index.js','settings/src/index.js','feature-flags/src/index.js']){const source=fs.readFileSync(path.join(__dirname,'../packages/primitives',rel),'utf8');assert.doesNotMatch(source,/(?:AIza[0-9A-Za-z_-]{20,}|gh[pousr]_[0-9A-Za-z]{20,}|Bearer\s+[A-Za-z0-9._-]{20,})/);}});
