'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {buildPrimitiveFailureDecision,buildPrimitiveVerificationDecision,scanPrimitiveAdversarialFixtures}=require('../packages/pandora-verification/src/primitive-trust');
const {FIXTURES}=require('./fixtures/trusted-primitives/adversarial');
const D='sha256:'+'a'.repeat(64);
function definition(){return{name:'pandora-test',version:'1.0.0',sourceDigest:D};}
function passRun(overrides={}){return{verification_run_id:'vr-1',status:'PASS',identity_digest:'sha256:'+'b'.repeat(64),completed_at:'2026-08-29T00:00:00Z',request:{source_digest:D},required_checks:['security.auth','database.policy'],results:[{check_id:'security.auth',status:'PASS',authoritative_issuer:'pandora-verification-engine',evidence_refs:['ev-auth']},{check_id:'database.policy',status:'PASS',authoritative_issuer:'pandora-verification-engine',evidence_refs:['ev-db']}],...overrides};}
test('authoritative exact-source Worker E PASS creates registry-compatible evidence',()=>{const decision=buildPrimitiveVerificationDecision({definition:definition(),run:passRun()});assert.equal(decision.authority,'worker-e');assert.equal(decision.status,'PASS');assert.equal(decision.sourceDigest,D);});
test('builder lookalike PASS without authoritative issuer is rejected',()=>{const run=passRun();run.results=run.results.map(x=>({...x,authoritative_issuer:'worker-i'}));assert.throws(()=>buildPrimitiveVerificationDecision({definition:definition(),run}),/not authoritative/);});
test('mismatched source digest cannot create PASS',()=>{const run=passRun();run.request={source_digest:'sha256:'+'c'.repeat(64)};assert.throws(()=>buildPrimitiveVerificationDecision({definition:definition(),run}),/does not match/);});
test('PASS requires every required check and evidence reference',()=>{const run=passRun();run.results=run.results.slice(0,1);assert.throws(()=>buildPrimitiveVerificationDecision({definition:definition(),run}),/missing required/);const noRef=passRun();noRef.results[0]={...noRef.results[0],evidence_refs:[]};assert.throws(()=>buildPrimitiveVerificationDecision({definition:definition(),run:noRef}),/evidence references/);});
test('all deliberate vulnerable primitive fixtures are independently detected',()=>{for(const [name,fixture] of Object.entries(FIXTURES)){const result=scanPrimitiveAdversarialFixtures([fixture]);assert.equal(result.ok,false,`${name} should fail`);assert.ok(result.findings.length>=1,`${name} needs finding`);assert.match(result.evidenceDigest,/^sha256:/);}});
test('unsafe AUTO upgrade is rejected by adversarial verification',()=>{const result=scanPrimitiveAdversarialFixtures([{path:'src/safe.js',content:'module.exports={};'}],{upgrade:{decision:'AUTO',irreversible:true,majorChange:true,targetTrustState:'BLOCKED',migrationDigest:'branch-main'}});assert.equal(result.ok,false);assert.ok(result.findings.some(x=>x.code==='UNSAFE_AUTO_UPGRADE'));assert.ok(result.findings.some(x=>x.code==='MUTABLE_MIGRATION_IDENTITY'));});
test('vulnerable fixture produces FAIL evidence, never PASS',()=>{const scan=scanPrimitiveAdversarialFixtures([FIXTURES.badRls]);const decision=buildPrimitiveFailureDecision({definition:definition(),evidenceId:'worker-e-fixture-1',findings:scan.findings});assert.equal(decision.authority,'worker-e');assert.equal(decision.status,'FAIL');assert.ok(decision.findingCodes.includes('RLS_DISABLED'));});
