'use strict';
const SCREEN_STATES=Object.freeze(['loading','empty','error','permission-denied','offline','success']);
const FEATURE_MODULES=Object.freeze(['auth','admin','booking','commerce','content','forms','profile','settings']);
const DEFAULT_TOKENS=Object.freeze({spacing:Object.freeze({xs:4,sm:8,md:12,lg:16,xl:24,xxl:32}),radius:Object.freeze({sm:8,md:12,lg:20,pill:999}),motion:Object.freeze({fast:120,normal:200,slow:320}),breakpoints:Object.freeze({mobile:0,tablet:600,desktop:1024}),tapTarget:44});
function createDesignTokens(overrides={}){if(!overrides||typeof overrides!=='object'||Array.isArray(overrides))throw new TypeError('token overrides must be an object');for(const key of Object.keys(overrides))if(!['spacing','radius','motion','breakpoints','tapTarget'].includes(key))throw new TypeError(`unknown token group: ${key}`);const out={};for(const group of ['spacing','radius','motion','breakpoints'])out[group]=Object.freeze({...DEFAULT_TOKENS[group],...boundedNumericMap(overrides[group]||{},group)});out.tapTarget=boundedNumber(overrides.tapTarget??DEFAULT_TOKENS.tapTarget,44,96,'tapTarget');if(out.breakpoints.mobile!==0||!(out.breakpoints.tablet>=480&&out.breakpoints.desktop>out.breakpoints.tablet))throw new TypeError('breakpoints must be mobile=0, tablet>=480, desktop>tablet');return Object.freeze(out);}
function createScreenState({kind,title,message='',action=null}={}){if(!SCREEN_STATES.includes(kind))throw new TypeError('unsupported screen state');const state={kind,title:text(title,160,'title'),message:optionalText(message,1000,'message'),action:null};if(action){if(!action||typeof action!=='object')throw new TypeError('action must be an object');state.action=Object.freeze({label:text(action.label,80,'action.label'),actionId:identifier(action.actionId,'action.actionId')});}return Object.freeze(state);}
function createResponsiveContract({regions,breakpoints=DEFAULT_TOKENS.breakpoints}={}){if(!regions||typeof regions!=='object'||Array.isArray(regions))throw new TypeError('regions must be an object');const bp=createDesignTokens({breakpoints}).breakpoints;const out={};for(const name of ['mobile','tablet','desktop']){const region=regions[name];if(!region||typeof region!=='object')throw new TypeError(`regions.${name} is required`);out[name]=Object.freeze({columns:boundedNumber(region.columns,1,24,`${name}.columns`),gutter:boundedNumber(region.gutter,0,64,`${name}.gutter`),maxWidth:boundedNumber(region.maxWidth,240,2400,`${name}.maxWidth`)});}return Object.freeze({breakpoints:bp,regions:Object.freeze(out)});}
function validateAccessibleComponent(component){const errors=[];if(!component||typeof component!=='object')return Object.freeze({ok:false,errors:Object.freeze(['component must be an object'])});const interactive=component.interactive===true;if(interactive){if(typeof component.accessibleLabel!=='string'||!component.accessibleLabel.trim())errors.push('interactive component requires accessibleLabel');if(!Number.isInteger(component.focusOrder)||component.focusOrder<0)errors.push('interactive component requires non-negative integer focusOrder');if(!Number.isFinite(component.minTargetSize)||component.minTargetSize<44)errors.push('interactive component minimum target size is 44');if(component.iconOnly===true&&!component.accessibleLabel)errors.push('icon-only control requires accessibleLabel');}if(component.textScaleLocked===true)errors.push('text scaling may not be locked');if(component.contrastToken&&typeof component.contrastToken==='string'&&!/^(text|surface|border|accent)\.[a-z0-9_.-]+$/i.test(component.contrastToken))errors.push('contrastToken must be semantic');return Object.freeze({ok:errors.length===0,errors:Object.freeze(errors)});}
function formatLocalized({type,value,locale='en',timeZone='UTC',currency='USD'}={}){if(typeof locale!=='string'||locale.length>32)throw new TypeError('locale is invalid');validateTimeZone(timeZone);if(type==='date'||type==='datetime'){const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))throw new TypeError('date value is invalid');return new Intl.DateTimeFormat(locale,{timeZone,dateStyle:'medium',...(type==='datetime'?{timeStyle:'short'}:{})}).format(d);}if(type==='currency'){if(typeof value!=='number'||!Number.isFinite(value))throw new TypeError('currency value must be finite number');if(!/^[A-Z]{3}$/.test(currency))throw new TypeError('currency must be ISO 4217 code');return new Intl.NumberFormat(locale,{style:'currency',currency}).format(value);}if(type==='number'){if(typeof value!=='number'||!Number.isFinite(value))throw new TypeError('number value must be finite');return new Intl.NumberFormat(locale).format(value);}throw new TypeError('unsupported localization type');}
function buildFeatureUiPlan({features,projectType='web_application'}={}){if(!Array.isArray(features)||features.length===0)throw new TypeError('features are required');const selected=[...new Set(features)];for(const f of selected)if(!FEATURE_MODULES.includes(f))throw new TypeError(`unsupported UI feature: ${f}`);if(!['website','web_application','mobile_application','system'].includes(projectType))throw new TypeError('projectType does not support reusable UI modules');const modules=selected.sort().map(name=>Object.freeze({name,requiredStates:SCREEN_STATES,requiresKeyboardNavigation:projectType!=='mobile_application',requiresScreenReader:true,requiresLocalization:true}));return Object.freeze({schemaVersion:'1.0',projectType,modules:Object.freeze(modules),foundation:Object.freeze({designTokens:true,responsiveLayout:true,standardStates:SCREEN_STATES,accessibility:'WCAG-2.2-AA-target',localization:true})});}
function boundedNumericMap(v,field){if(!v||typeof v!=='object'||Array.isArray(v))throw new TypeError(`${field} must be an object`);const out={};for(const [k,n] of Object.entries(v)){if(!/^[a-z][a-z0-9_-]{0,31}$/i.test(k))throw new TypeError(`${field}.${k} key invalid`);out[k]=boundedNumber(n,0,4096,`${field}.${k}`);}return out;}
function boundedNumber(v,min,max,field){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw new TypeError(`${field} must be ${min}-${max}`);return v;}function text(v,max,f){if(typeof v!=='string'||!v.trim()||v.length>max)throw new TypeError(`${f} is invalid`);return v.trim();}function optionalText(v,max,f){if(v==null||v==='')return '';return text(v,max,f);}function identifier(v,f){const x=text(v,96,f);if(!/^[a-z][a-z0-9_.-]+$/.test(x))throw new TypeError(`${f} is invalid`);return x;}function validateTimeZone(v){try{new Intl.DateTimeFormat('en',{timeZone:v}).format(new Date());}catch{throw new TypeError('timeZone must be valid IANA timezone');}}
module.exports={DEFAULT_TOKENS,FEATURE_MODULES,SCREEN_STATES,buildFeatureUiPlan,createDesignTokens,createResponsiveContract,createScreenState,formatLocalized,validateAccessibleComponent};
