import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createRemoteJWKSet, decodeJwt, jwtVerify } from "npm:jose@5.10.0";
import { assertProductionVercelClaims } from "./identity-policy.mjs";
const ORG_ID="2270b266-59da-4c39-bfd9-9f8d08352af0",MAX_BYTES=512000;
type Input=Record<string,unknown>;type Route={rpc:string;params:Input;key:string};
const isRecord=(v:unknown):v is Input=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v);
const json=(s:number,b:Input)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const reqText=(i:Input,k:string)=>typeof i[k]==="string"&&(i[k] as string).trim()?(i[k] as string).trim():undefined;
const optText=(i:Input,k:string)=>reqText(i,k)??null;
const optNumber=(i:Input,k:string)=>typeof i[k]==="number"&&Number.isFinite(i[k])?i[k] as number:null;
const optBoolean=(i:Input,k:string)=>typeof i[k]==="boolean"?i[k] as boolean:undefined;
const objectValue=(i:Input,k:string)=>isRecord(i[k])?i[k] as Input:{};
const arrayValue=(i:Input,k:string)=>Array.isArray(i[k])?i[k] as unknown[]:[];
const bearer=(r:Request)=>r.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1]?.trim();
const auds=(v:unknown):string[]=>typeof v==="string"?[v]:Array.isArray(v)&&v.every(x=>typeof x==="string")?v as string[]:[];
function issuerFor(token:string){const d=decodeJwt(token);if(typeof d.iss!=="string")throw new Error();const u=new URL(d.iss);const s=u.pathname.split("/").filter(Boolean);if(u.protocol!=="https:"||u.hostname!=="oidc.vercel.com"||s.length>1)throw new Error();u.search="";u.hash="";u.pathname=s.length?`/${s[0]}`:"";return u.toString().replace(/\/$/,"");}
async function verify(token:string){const d=decodeJwt(token),issuer=issuerFor(token),a=auds(d.aud);if(!a.length||!a.every(v=>v.startsWith("https://vercel.com/")))throw new Error();const {payload}=await jwtVerify(token,createRemoteJWKSet(new URL(`${issuer}/.well-known/jwks`)),{issuer,audience:a});assertProductionVercelClaims(payload,a);}
function serviceKey(){const modern=Deno.env.get("SUPABASE_SECRET_KEYS");if(modern){try{const p=JSON.parse(modern) as Input;if(typeof p.default==="string"&&p.default)return p.default;}catch{/*fallback*/}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??undefined;}
async function rpc(name:string,params:Input){const url=Deno.env.get("SUPABASE_URL"),key=serviceKey();if(!url||!key)throw new Error();const r=await fetch(`${url}/rest/v1/rpc/${name}`,{method:"POST",redirect:"error",headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({p_organization_id:ORG_ID,...params})});if(!r.ok)throw new Error();return r.json();}
function route(i:Input):Route|undefined{const a=reqText(i,"action");
 if(a==="health")return{rpc:"projectos_get_dashboard",params:{p_project_key:"mcpmaster"},key:"dashboard"};
 if(a==="dashboard_get")return{rpc:"projectos_get_dashboard",params:{p_project_key:optText(i,"projectKey")},key:"dashboard"};
 if(a==="registry_get")return{rpc:"projectos_get_registry",params:{},key:"registry"};
 if(a==="context_get"){const projectKey=reqText(i,"projectKey");if(!projectKey)return;return{rpc:"projectos_get_context",params:{p_project_key:projectKey,p_task_key:optText(i,"taskKey")},key:"context"};}
 if(a==="agents_recommend"){const projectKey=reqText(i,"projectKey");if(!projectKey)return;return{rpc:"projectos_recommend_agents",params:{p_project_key:projectKey,p_role:optText(i,"role")??"builder",p_limit:optNumber(i,"limit")??5},key:"agents"};}
 if(a==="bootstrap_apply"){const manifest=objectValue(i,"manifest");if(!Array.isArray(manifest.projects))return;return{rpc:"projectos_apply_manifest",params:{p_manifest:manifest,p_created_by:optText(i,"createdBy")},key:"result"};}
 if(a==="intake_plan"){const intakeId=reqText(i,"intakeId"),plan=objectValue(i,"plan");if(!intakeId||!Array.isArray(plan.tasks))return;return{rpc:"projectos_plan_intake",params:{p_intake_id:intakeId,p_plan:plan},key:"result"};}
 if(a==="health_set"){const projectKey=reqText(i,"projectKey"),provider=reqText(i,"provider"),status=reqText(i,"status");if(!projectKey||!provider||!status)return;return{rpc:"projectos_set_integration_health",params:{p_project_key:projectKey,p_provider:provider,p_status:status,p_details:objectValue(i,"details"),p_last_event_at:optText(i,"lastEventAt"),p_last_success_at:optText(i,"lastSuccessAt"),p_stale_after:optText(i,"staleAfter")},key:"health"};}
 if(a==="project_register"){const projectKey=reqText(i,"projectKey"),name=reqText(i,"name");if(!projectKey||!name)return;return{rpc:"projectos_register_project",params:{p_project_key:projectKey,p_name:name,p_repository:optText(i,"repository"),p_objective:optText(i,"objective")??"",p_created_by:optText(i,"createdBy")},key:"project"};}
 if(a==="intake_accept"){const requestText=reqText(i,"requestText");if(!requestText)return;return{rpc:"projectos_accept_intake",params:{p_requester_id:optText(i,"requesterId"),p_request_text:requestText,p_project_key:optText(i,"projectKey"),p_project_name:optText(i,"projectName"),p_repository:optText(i,"repository"),p_request_type:optText(i,"requestType")??"work",p_source:optText(i,"source")??"system",p_idempotency_key:optText(i,"idempotencyKey")},key:"result"};}
 if(a==="event_record"){const provider=reqText(i,"provider"),deliveryId=reqText(i,"deliveryId"),eventType=reqText(i,"eventType"),payloadHash=reqText(i,"payloadHash");if(!provider||!deliveryId||!eventType||!payloadHash)return;return{rpc:"projectos_record_external_event",params:{p_provider:provider,p_delivery_id:deliveryId,p_event_type:eventType,p_payload_hash:payloadHash,p_payload_redacted:objectValue(i,"payloadRedacted"),p_project_key:optText(i,"projectKey"),p_repository:optText(i,"repository"),p_external_created_at:optText(i,"externalCreatedAt")},key:"event"};}
 if(a==="evidence_record"){const projectKey=reqText(i,"projectKey"),taskKey=reqText(i,"taskKey"),evidenceType=reqText(i,"evidenceType"),provider=reqText(i,"provider"),externalId=reqText(i,"externalId"),status=reqText(i,"status");if(!projectKey||!taskKey||!evidenceType||!provider||!externalId||!status)return;return{rpc:"projectos_record_evidence",params:{p_project_key:projectKey,p_task_key:taskKey,p_evidence_type:evidenceType,p_provider:provider,p_external_id:externalId,p_status:status,p_source_url:optText(i,"sourceUrl"),p_repository:optText(i,"repository"),p_head_sha:optText(i,"headSha"),p_verdict:optText(i,"verdict"),p_payload_redacted:objectValue(i,"payloadRedacted")},key:"result"};}
 if(a==="project_recompute"){const projectKey=reqText(i,"projectKey");if(!projectKey)return;return{rpc:"projectos_recompute_project",params:{p_project_key:projectKey},key:"projection"};}
 if(a==="outcome_record"){const projectKey=reqText(i,"projectKey"),taskKey=reqText(i,"taskKey"),success=optBoolean(i,"success");if(!projectKey||!taskKey||success===undefined)return;return{rpc:"projectos_record_outcome",params:{p_project_key:projectKey,p_task_key:taskKey,p_success:success,p_planned:objectValue(i,"planned"),p_actual:objectValue(i,"actual"),p_quality_score:optNumber(i,"qualityScore"),p_duration_seconds:optNumber(i,"durationSeconds"),p_repair_attempts:optNumber(i,"repairAttempts")??0,p_deployment_result:optText(i,"deploymentResult"),p_impact_metrics:objectValue(i,"impactMetrics"),p_agent_observations:arrayValue(i,"agentObservations"),p_lessons:arrayValue(i,"lessons")},key:"result"};}
 return undefined;}
Deno.serve(async(r:Request)=>{if(r.method!=="POST")return json(405,{ok:false,error:"method_not_allowed"});const t=bearer(r);if(!t)return json(401,{ok:false,error:"unauthorized"});try{await verify(t);}catch{return json(401,{ok:false,error:"unauthorized"});}const raw=await r.text();if(new TextEncoder().encode(raw).byteLength>MAX_BYTES)return json(413,{ok:false,error:"request_too_large"});let i:Input;try{const p=JSON.parse(raw);if(!isRecord(p))throw new Error();i=p;}catch{return json(400,{ok:false,error:"invalid_json"});}const selected=route(i);if(!selected)return json(400,{ok:false,error:"unsupported_or_invalid_action"});try{return json(200,{ok:true,[selected.key]:await rpc(selected.rpc,selected.params)});}catch{return json(502,{ok:false,error:"projectos_operation_unavailable"});}});
