'use strict';
const {assertIdempotentEventSink,createDomainEvent}=require('../../core/src/events');
const WEEKDAYS=Object.freeze(['sun','mon','tue','wed','thu','fri','sat']);
class PandoraSchedulingService {
  constructor({repository,authorization,eventSink}){for(const m of ['getSchedule','saveSchedule'])if(!repository||typeof repository[m]!=='function')throw new TypeError(`scheduling repository.${m} is required`);if(!authorization||typeof authorization.assertAllowed!=='function')throw new TypeError('scheduling authorization.assertAllowed is required');assertIdempotentEventSink(eventSink,'scheduling event sink');this.repository=repository;this.authorization=authorization;this.eventSink=eventSink;}
  async get({scopeId,identity,resourceId}){await this.authorization.assertAllowed({userId:required(identity&&identity.userId,'identity.userId'),tenantId:required(scopeId,'scopeId'),permission:'data.read'});const row=await this.repository.getSchedule({scopeId,resourceId:required(resourceId,'resourceId')});return row?normalizeSchedule(row):null;}
  async save({project,scopeId,identity,resourceId,schedule,idempotencyKey}){await this.authorization.assertAllowed({userId:required(identity&&identity.userId,'identity.userId'),tenantId:required(scopeId,'scopeId'),permission:'data.write'});const normalized=normalizeSchedule(schedule);const row=await this.repository.saveSchedule({scopeId:required(scopeId,'scopeId'),resourceId:required(resourceId,'resourceId'),schedule:normalized,actorUserId:identity.userId,idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:'schedule.changed',schemaVersion:'1.0',project,actor:{userId:identity.userId},aggregate:{type:'schedule',id:String(row.id||resourceId)},payload:{resourceId:String(resourceId),timezone:normalized.timezone},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);return Object.freeze({...row,schedule:normalized,event});}
}
function normalizeSchedule(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('schedule must be an object');const timezone=ianaTimezone(value.timezone);if(!Array.isArray(value.weekly)||value.weekly.length<1||value.weekly.length>21)throw new TypeError('schedule.weekly must contain 1-21 windows');const weekly=value.weekly.map(normalizeWindow);const seen=new Set();for(const w of weekly){const key=`${w.weekday}:${w.start}-${w.end}`;if(seen.has(key))throw new Error('duplicate schedule window');seen.add(key);}const exceptions=normalizeExceptions(value.exceptions||[]);return Object.freeze({timezone,weekly:Object.freeze(weekly),exceptions:Object.freeze(exceptions)});}
function normalizeWindow(v){if(!v||typeof v!=='object')throw new TypeError('weekly window must be an object');if(!WEEKDAYS.includes(v.weekday))throw new TypeError('weekday is invalid');const start=clock(v.start,'start'),end=clock(v.end,'end');if(minutes(start)>=minutes(end))throw new Error('schedule window end must follow start');return Object.freeze({weekday:v.weekday,start,end});}
function normalizeExceptions(items){if(!Array.isArray(items)||items.length>366)throw new TypeError('exceptions must be a bounded array');const seen=new Set();return items.map(v=>{if(!v||typeof v!=='object'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(v.date))throw new TypeError('exception date must be YYYY-MM-DD');if(seen.has(v.date))throw new Error('duplicate exception date');seen.add(v.date);if(v.closed===true)return Object.freeze({date:v.date,closed:true,windows:Object.freeze([])});if(!Array.isArray(v.windows)||v.windows.length>8)throw new TypeError('exception windows must be bounded');return Object.freeze({date:v.date,closed:false,windows:Object.freeze(v.windows.map(w=>{const start=clock(w.start,'start'),end=clock(w.end,'end');if(minutes(start)>=minutes(end))throw new Error('exception window end must follow start');return Object.freeze({start,end});}))});});}
function appliesOnLocalDate(schedule,date){const normalized=normalizeSchedule(schedule);if(typeof date!=='string'||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date))throw new TypeError('date must be YYYY-MM-DD');const exception=normalized.exceptions.find(x=>x.date===date);if(exception)return exception.closed?Object.freeze([]):exception.windows;const weekday=weekdayForDate(date);return Object.freeze(normalized.weekly.filter(x=>x.weekday===weekday).map(x=>Object.freeze({start:x.start,end:x.end})));}
function weekdayForDate(date){const d=new Date(`${date}T12:00:00Z`);if(Number.isNaN(d.getTime()))throw new TypeError('invalid date');return WEEKDAYS[d.getUTCDay()];}
function ianaTimezone(v){const value=required(v,'timezone');try{new Intl.DateTimeFormat('en-US',{timeZone:value}).format(new Date());}catch{throw new TypeError('timezone must be a valid IANA timezone');}return value;}
function clock(v,f){if(typeof v!=='string'||!/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test(v))throw new TypeError(`${f} must be HH:MM`);return v;}function minutes(v){const [h,m]=v.split(':').map(Number);return h*60+m;}function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={PandoraSchedulingService,WEEKDAYS,appliesOnLocalDate,ianaTimezone,normalizeSchedule};
