import "jsr:@supabase/functions-js@2.4.5/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2.57.2";

const URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const REPO="pandora-rvw-314296438-20260820/pandoras-box";
const PROOF_SHA="ff9a9d91d631def224e5e813f0b00bb437419a59508e40e8ddc01003cdf38dd5";
const SHA=/^[0-9a-f]{40}$/;
const BR=/^(?:chatgpt|recovery|repair|fix)\/[A-Za-z0-9._\/-]{1,220}$|^enterprise-ui(?:[-\/][A-Za-z0-9._\/-]{1,200})?$/;
const PATH=/^(?!\/)(?!.*(?:^|\/)\.\.?(?:\/|$))[A-Za-z0-9_@+.,()\[\]{} -]+(?:\/[A-Za-z0-9_@+.,()\[\]{} -]+)*$/;
const SECRET=/(?:github_pat_[A-Za-z0-9_]{20,}|gh[pousr]_[A-Za-z0-9_]{20,}|(?:^|[^A-Za-z0-9])s[k]-[A-Za-z0-9_-]{20,}|AIza[A-Za-z0-9_-]{20,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE K[E]Y-----)/;
type R=Record<string,unknown>;
const obj=(v:unknown):R=>v&&typeof v==="object"&&!Array.isArray(v)?v as R:{};
const str=(v:unknown)=>typeof v==="string"?v:"";
const out=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function unb64(v:string){const x=atob(v.replace(/\s+/g,"")),b=new Uint8Array(x.length);for(let i=0;i<x.length;i++)b[i]=x.charCodeAt(i);return b;}
async function hashBytes(b:Uint8Array){const d=await crypto.subtle.digest("SHA-256",b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("");}
function db(){if(!URL||!SERVICE)throw Error("CONTROL_CONFIG_UNAVAILABLE");return createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});}
async function auth(req:Request){const proof=req.headers.get("x-pandora-machine-proof")||"";let proofBytes:Uint8Array;try{proofBytes=unb64(proof);}catch{throw Error("MACHINE_AUTH_REJECTED");}if(!proof||await hashBytes(proofBytes)!==PROOF_SHA)throw Error("MACHINE_AUTH_REJECTED");const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>14*1024*1024)throw Error("REQUEST_TOO_LARGE");let p:R;try{p=obj(JSON.parse(raw));}catch{throw Error("INVALID_JSON");}if(p.version!==1)throw Error("PAYLOAD_VERSION_INVALID");const at=Date.parse(str(p.timestamp));if(!Number.isFinite(at)||Math.abs(Date.now()-at)>300000)throw Error("PAYLOAD_EXPIRED");const nonce=str(p.nonce);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(nonce))throw Error("NONCE_INVALID");const a=db();await a.from("pandora_rdp_sync_nonces").delete().lt("observed_at",new Date(Date.now()-86400000).toISOString());const q=await a.from("pandora_rdp_sync_nonces").insert({nonce,key_id:"rdp-dpapi-v1",observed_at:new Date().toISOString()});if(q.error)throw Error("REPLAY_REJECTED");return{p,a};}
async function gh(a:ReturnType<typeof db>,m:string,path:string,body:R|null=null){const{data,error}=await a.rpc("pandora_rdp_github_request_v1",{p_method:m,p_path:`/repos/${REPO}${path}`,p_body:body});if(error)throw Error("GITHUB_TRANSPORT_FAILED");const e=obj(data);return{status:Number(e.status||0),body:obj(e.body)};}
async function probe(a:ReturnType<typeof db>,branch:string){if(branch!=="main"&&!BR.test(branch))throw Error("BRANCH_INVALID");const r=await gh(a,"GET",`/git/ref/heads/${branch}`),sha=str(obj(r.body.object).sha).toLowerCase();return{status:r.status,sha:sha||null};}
async function start(a:ReturnType<typeof db>,branch:string,base:string){if(!BR.test(branch)||!SHA.test(base))throw Error("BRANCH_REQUEST_INVALID");const main=await probe(a,"main");if(main.status!==200||main.sha!==base)throw Error("BASE_MAIN_MOVED");const old=await probe(a,branch);if(old.status===200){if(old.sha!==base)throw Error("BRANCH_ALREADY_MOVED");return{branch,sha:old.sha,replayed:true};}if(old.status!==404)throw Error("BRANCH_READ_FAILED");const w=await gh(a,"POST","/git/refs",{ref:`refs/heads/${branch}`,sha:base});if(w.status!==201)throw Error(`BRANCH_CREATE_${w.status}`);const rb=await probe(a,branch);if(rb.status!==200||rb.sha!==base)throw Error("BRANCH_CREATE_READBACK_FAILED");return{branch,sha:base,replayed:false};}
function actor(v:unknown){const x=obj(v),name=str(x.name).trim(),email=str(x.email).trim(),date=str(x.date).trim();if(!name||name.length>160||!/^\S+@\S+$/.test(email)||email.length>254||!Number.isFinite(Date.parse(date)))throw Error("COMMIT_ACTOR_INVALID");return{name,email,date};}
async function publish(a:ReturnType<typeof db>,p:R){const branch=str(p.branch),parent=str(p.expectedParentSha).toLowerCase(),wantTree=str(p.expectedTreeSha).toLowerCase(),local=str(p.localCommitSha).toLowerCase(),message=str(p.message);if(!BR.test(branch)||!SHA.test(parent)||!SHA.test(wantTree)||!SHA.test(local)||!message||message.length>100000)throw Error("COMMIT_REQUEST_INVALID");const au=actor(p.author),co=actor(p.committer),cur=await probe(a,branch);if(cur.status!==200||cur.sha!==parent)throw Error("REMOTE_HEAD_MOVED");const pc=await gh(a,"GET",`/git/commits/${parent}`);if(pc.status!==200)throw Error("PARENT_COMMIT_UNAVAILABLE");const baseTree=str(obj(pc.body.tree).sha).toLowerCase();if(!SHA.test(baseTree))throw Error("PARENT_TREE_INVALID");const ch=Array.isArray(p.changes)?p.changes.map(obj):[];if(ch.length<1||ch.length>250)throw Error("CHANGESET_INVALID");let total=0;const tree:R[]=[],seen=new Set<string>();for(const c of ch){const path=str(c.path),mode=str(c.mode),action=str(c.action);if(!PATH.test(path)||path.length>600||seen.has(path)||!["100644","100755","120000"].includes(mode)||!["upsert","delete"].includes(action))throw Error("CHANGESET_INVALID");seen.add(path);if(action==="delete"){tree.push({path,mode,type:"blob",sha:null});continue;}const encoded=str(c.contentBase64).replace(/\s+/g,"");let bytes:Uint8Array;try{bytes=unb64(encoded);}catch{throw Error("SOURCE_ENCODING_INVALID");}if(bytes.length<1||bytes.length>4*1024*1024)throw Error("SOURCE_FILE_SIZE_INVALID");total+=bytes.length;if(total>10*1024*1024)throw Error("CHANGESET_TOO_LARGE");let source:string;try{source=new TextDecoder("utf-8",{fatal:true}).decode(bytes);}catch{throw Error("SOURCE_UTF8_REQUIRED");}if(/(?:^|\/)\.env(?:\.|$)/i.test(path)||SECRET.test(source))throw Error("SOURCE_SECRET_REJECTED");const bl=await gh(a,"POST","/git/blobs",{content:encoded,encoding:"base64"}),bs=str(bl.body.sha).toLowerCase();if(bl.status!==201||!SHA.test(bs))throw Error("BLOB_WRITE_FAILED");tree.push({path,mode,type:"blob",sha:bs});}
const mt=await gh(a,"POST","/git/trees",{base_tree:baseTree,tree}),ts=str(mt.body.sha).toLowerCase();if(mt.status!==201||ts!==wantTree)throw Error("TREE_SHA_MISMATCH");const mc=await gh(a,"POST","/git/commits",{message,tree:ts,parents:[parent],author:au,committer:co}),rs=str(mc.body.sha).toLowerCase();if(mc.status!==201||!SHA.test(rs))throw Error("COMMIT_WRITE_FAILED");const mv=await gh(a,"PATCH",`/git/refs/heads/${branch}`,{sha:rs,force:false});if(mv.status!==200)throw Error(`REF_UPDATE_${mv.status}`);const rb=await probe(a,branch);if(rb.status!==200||rb.sha!==rs)throw Error("REF_READBACK_FAILED");return{branch,remoteSha:rs,localCommitSha:local,treeSha:ts,exactTree:true,exactCommit:rs===local};}
function status(c:string){if(["MACHINE_AUTH_REJECTED","REPLAY_REJECTED","PAYLOAD_EXPIRED"].includes(c))return 401;if(c.includes("INVALID")||c.includes("REJECTED")||c.includes("MISMATCH"))return 400;if(c.includes("MOVED")||c.includes("ALREADY"))return 409;return 503;}
Deno.serve(async req=>{if(req.method!=="POST"||req.headers.get("origin"))return out({ok:false,code:"METHOD_ORIGIN_REJECTED"},403);try{const{p,a}=await auth(req),op=str(p.operation);if(op==="probe"){const branch=str(p.branch)||"main";return out({ok:true,operation:op,branch,...await probe(a,branch)});}if(op==="start_branch")return out({ok:true,operation:op,...await start(a,str(p.branch),str(p.baseSha).toLowerCase())});if(op==="publish_commit")return out({ok:true,operation:op,...await publish(a,p)});throw Error("OPERATION_INVALID");}catch(e){const code=e instanceof Error?e.message:"FAILED";console.error("pandora-rdp-github-sync",code);return out({ok:false,code},status(code));}});
