'use strict';
const assert=require('node:assert/strict');const test=require('node:test');const path=require('node:path');
const I=require(path.resolve(__dirname,'..','dist','index.js'));
function reg(){const r=new I.ModelCapabilityRegistry();for(const m of [
{provider:'gemini',modelId:'gemini-test',latencyClass:'interactive',costClass:'low',reliabilityClass:'high',metadata:{modelVersion:'g1'}},
{provider:'kimi',modelId:'kimi-test',latencyClass:'standard',costClass:'high',reliabilityClass:'standard',metadata:{modelVersion:'k1'}}])r.register({...m,capabilities:{coding:true,structuredOutput:true,reasoning:true},maxContextTokens:1e6,outputModes:['structured','json','text']});return r}
const req=(o={})=>I.createModelRequest({requestId:'r',task:'generate_code',outputMode:'structured',requiredCapabilities:['coding','structuredOutput'],context:{},input:{},budget:{maxAttempts:2,remainingAttempts:2,maxCostUsd:1},...o});
const ok=p=>({execute:async(_r,d)=>({provider:p,model:d.modelId,output:{ok:true},usage:I.createModelUsage({})})});
const fail=(code,retryable=true)=>({execute:async()=>{throw Object.assign(new Error(code),{code,retryable})}});
const router=a=>new I.ModelRouter({registry:reg(),adapters:a});

test('Gemini-compatible default and soft Kimi preference obey hard disable',async()=>{const R=router({gemini:ok('gemini'),kimi:ok('kimi')});assert.equal((await R.execute(req())).routedProvider,'gemini');let p=I.createRoutingPolicy({taskPreferences:{generate_code:{preferredProvider:'kimi'}}});assert.equal((await R.execute(req(),{policy:p})).routedProvider,'kimi');p=I.createRoutingPolicy({taskPreferences:{generate_code:{preferredProvider:'kimi'}},providerControls:{kimi:{enabled:false}}});const out=await R.execute(req(),{policy:p});assert.equal(out.routedProvider,'gemini');assert.ok(out.routingDecision.excludedCandidates.some(x=>x.provider==='kimi'&&x.reasons.includes('provider_disabled'))) });

test('kill/quarantine/task/model controls and capability filter are hard constraints',()=>{const R=router({gemini:ok('gemini'),kimi:ok('kimi')});for(const p of [I.createRoutingPolicy({providerControls:{kimi:{killSwitch:true}}}),I.createRoutingPolicy({providerControls:{kimi:{quarantined:true}}}),I.createRoutingPolicy({providerControls:{kimi:{deniedTasks:['generate_code']}}}),I.createRoutingPolicy({modelControls:{'kimi:kimi-test':{enabled:false}}})])assert.deepEqual(R.candidates(req(),{policy:p}).map(x=>x.provider),['gemini'])});

test('sticky session cannot silently cross provider; explicit recovery increments epoch',async()=>{const s=I.createSessionRoutingState({provider:'gemini',model:'gemini-test',modelVersion:'g1',stickinessMode:'sticky',recoveryEpoch:2,lastCompatibleTurnId:'t7'});let R=router({gemini:ok('gemini'),kimi:ok('kimi')});let p=I.createRoutingPolicy({taskPreferences:{generate_code:{preferredProvider:'kimi'}}});assert.equal((await R.execute(req(),{policy:p,session:s})).routedProvider,'gemini');R=router({gemini:fail('provider_unavailable'),kimi:ok('kimi')});await assert.rejects(()=>R.execute(req(),{session:s}),e=>e.code==='provider_unavailable');const out=await R.execute(req(),{session:s,allowRecoveryBoundary:true});assert.equal(out.routedProvider,'kimi');assert.equal(out.nextSessionState.recoveryEpoch,3);assert.equal(out.nextSessionState.stickinessMode,'recovering');assert.equal(out.nextSessionState.lastCompatibleTurnId,'t7')});

test('fallback matrix blocks security/auth but permits bounded retryable availability and prevents loops',async()=>{assert.equal(I.fallbackEligible({code:'authentication_failed',retryable:true}),false);assert.equal(I.fallbackEligible({code:'timeout',retryable:true}),true);let calls=0;let R=router({gemini:fail('authentication_failed'),kimi:{execute:async()=>{calls++;return{}}}});await assert.rejects(()=>R.execute(req()),e=>e.code==='authentication_failed');assert.equal(calls,0);R=router({gemini:fail('timeout'),kimi:ok('kimi')});const out=await R.execute(req());assert.deepEqual(out.routingDecision.attempts.map(x=>x.provider),['gemini','kimi']);const list=R.candidatesDetailed(req(),{attemptHistory:[{provider:'gemini',model:'gemini-test'}]});assert.deepEqual(list.candidates.map(x=>x.model.provider),['kimi']);await assert.rejects(()=>R.execute(req(),{maxProviderAttempts:1}),e=>e.code==='timeout')});

test('circuit, cost, latency, reliability and quality floors run before score',()=>{const observed='2026-09-02T00:00:00Z';const policy=I.createRoutingPolicy({maxEstimatedCostUsd:.5,maxLatencyMs:1000,minObservedSuccessRate:.9,minObservedQuality:.8,hardFloorMinSamples:20,circuits:{kimi:{state:'open'}},performance:{'kimi:kimi-test':{quality:.5,successRate:.5,latencyScore:.2,costScore:.2,sampleCount:100,p95LatencyMs:5000,estimatedCostUsd:.9,observedAt:observed}},adaptive:{enabled:true,windowMs:1e12}});const R=router({gemini:ok('gemini'),kimi:ok('kimi')});const d=R.candidatesDetailed(req(),{policy,nowMs:Date.parse(observed),costEstimator:m=>m.provider==='kimi'?.9:.1});assert.deepEqual(d.candidates.map(x=>x.model.provider),['gemini']);const ex=d.excluded.find(x=>x.provider==='kimi');assert.ok(ex.reasons.includes('circuit_open'));assert.ok(ex.reasons.includes('observed_reliability_floor'));assert.ok(ex.reasons.includes('observed_quality_floor'));assert.ok(ex.reasons.includes('latency_ceiling'));assert.ok(ex.reasons.includes('estimated_cost_ceiling'))});

test('automatic circuit breaker opens on sanitized health and supports cooldown probe',()=>{const cfg=I.normalizeCircuitBreakerConfig({enabled:true,minSamples:10,successRateFloor:.8,timeoutRateCeiling:.2,serverErrorRateCeiling:.2,consecutiveFailureLimit:3,cooldownMs:1000});assert.equal(I.evaluateCircuitBreaker({state:'closed',sampleCount:50,successRate:.7,timeoutRate:.1,serverErrorRate:.1,consecutiveRetryableFailures:0},cfg,2000).state,'open');assert.equal(I.evaluateCircuitBreaker({state:'open',openedAtMs:0},cfg,2000).state,'half_open')});

test('deterministic cohorts, traffic weights and bounded exploration are stable and disabled by default',()=>{assert.equal(I.deterministicCohortBucket('org:p:t'),I.deterministicCohortBucket('org:p:t'));let p=I.createRoutingPolicy({trafficWeights:{generate_code:{'kimi:kimi-test':.1}}});assert.equal(I.trafficPreference(p,'generate_code','stable-key'),I.trafficPreference(p,'generate_code','stable-key'));assert.equal(I.explorationEnabledForRequest(p.adaptive,'generate_code','stable-key'),false);p=I.createRoutingPolicy({adaptive:{enabled:true,explorationCap:.05,explorationEligibleTasks:['generate_code']}});assert.equal(typeof I.explorationEnabledForRequest(p.adaptive,'generate_code','stable-key'),'boolean')});

test('recency/confidence/version weighting and task-specific soft weights are bounded',()=>{const now=Date.parse('2026-09-02T00:00:00Z'),recent={quality:.9,successRate:.9,latencyScore:.8,costScore:.7,sampleCount:100,observedAt:'2026-09-01T23:59:00Z',modelVersion:'v2'},old={...recent,observedAt:'2025-01-01T00:00:00Z'};const a={enabled:true,windowMs:1e12,halfLifeMs:3600000,minSamples:20,versionMismatchWeight:.1};const nr={...recent,observedAtMs:Date.parse(recent.observedAt)},no={...old,observedAtMs:Date.parse(old.observedAt)};assert.ok(I.evidenceWeight(nr,a,now,'v2')>I.evidenceWeight(no,a,now,'v2'));assert.ok(I.evidenceWeight(nr,a,now,'v1')<I.evidenceWeight(nr,a,now,'v2'));const p=I.createRoutingPolicy({taskWeights:{generate_code:{qualityWeight:5,successWeight:1,latencyWeight:0,costWeight:0}},performance:{'kimi:kimi-test':recent},adaptive:a});assert.ok(I.routingPolicyScoreDetailed(reg().get('kimi','kimi-test'),p,{task:'generate_code',nowMs:now}).performance>0)});

test('routing audit is structured and contains no credential/cohort material',async()=>{const R=router({gemini:fail('timeout'),kimi:ok('kimi')});const out=await R.execute(req(),{cohortKey:'secret-cohort'});assert.equal(out.routingDecision.selectedProvider,'kimi');assert.ok(Array.isArray(out.routingDecision.eligibleCandidates));assert.ok(Array.isArray(out.routingDecision.attempts));assert.doesNotMatch(JSON.stringify(out.routingDecision),/secret-cohort|authorization|api[_-]?key/i)});
