
'use strict';
module.exports = {
  ...require('./contracts/model.js'),
  ...require('./contracts/project-spec.js'),
  ...require('./capabilities/registry.js'),
  ...require('./validation/structured-output.js'),
  ...require('./security/secret-boundary.js'),
  ...require('./prompts/templates.js'),
  ...require('./prompts/trusted-material-registry.js'),
  ...require('./prompts/trusted-context-bundle.js'),
  ...require('./providers/gemini.js'),
  ...require('./providers/kimi.js'),
  ...require('./routing/adaptive.js'),
  ...require('./routing/session.js'),
  ...require('./routing/policy.js'),
  ...require('./routing/model-router.js'),
  ...require('./skills/registry.js'),
  ...require('./skills/agent-catalog-adapter.js'),
  ...require('./knowledge/registry.js'),
  ...require('./import/external-source-policy.js'),
  ...require('./import/candidate-importer.js'),
  ...require('./lineage/ai-execution-receipt.js'),
  ...require('./planning/intelligence-composer.js'),
};
