'use strict';
const ALL_PROJECT_TYPES=['website','web_application','mobile_application','system','api','automation','other']; const WEB_SYSTEM_TYPES=['website','web_application','mobile_application','system']; const emptyConfig=()=>({type:'object',additionalProperties:false,properties:{}});
function primitive(overrides){return{version:'1.0.0',trustState:'EXPERIMENTAL',supportedProjectTypes:ALL_PROJECT_TYPES,configurationSchema:emptyConfig(),dependencies:[],runtimeRequirements:[],secretRequirements:[],extensionPoints:['theme','copy','business-rules','events'],permissions:[],events:[],sourceDigest:null,deprecation:null,complexity:'medium',verificationProfile:{requiredChecks:['contract','security','composition']},...overrides};}
const INITIAL_PRIMITIVES=Object.freeze([
primitive({name:'pandora-auth',category:'identity',capabilities:['auth.email_password','auth.password_reset','auth.session','auth.email_verification','auth.magic_link'],runtimeRequirements:[{capability:'identity-provider',required:true}],secretRequirements:['auth.provider_configuration'],permissions:['auth.session.read','auth.session.revoke'],source:{kind:'combination',path:'packages/primitives/auth'},sourceDigest:'sha256:f06d34a7aabd1fd1ab94fdc0374efa88d093bc8211f70ccd769d78c9e1e6849c',verificationProfile:{requiredChecks:['signup-login','protected-route','sign-out','session-invalidation','secret-boundary']}}),
primitive({name:'pandora-rbac',category:'authorization',capabilities:['rbac.roles','rbac.permissions','rbac.backend_enforcement'],dependencies:[{name:'pandora-auth',range:'>=1.0.0 <2.0.0'}],source:{kind:'combination',path:'packages/primitives/rbac'},sourceDigest:'sha256:7ce794620e444755ac9701677ca58821178b9ea0e0e0ebf4e33048e0f68388c4',verificationProfile:{requiredChecks:['role-mapping','server-authorization','cross-user-denial','rls-policy']}}),
primitive({name:'pandora-admin',category:'operations',capabilities:['admin.data_table','admin.filtering','admin.search','admin.pagination','admin.crud','admin.status'],supportedProjectTypes:WEB_SYSTEM_TYPES,dependencies:[{name:'pandora-rbac',range:'^1.0.0'},{name:'pandora-audit',range:'^1.0.0'}],source:{kind:'combination',path:'packages/primitives/admin'},sourceDigest:'sha256:5f48184a6579dd0550a6d05d8e5413e192de6b326b36562b45e8c54d87c7b441',verificationProfile:{requiredChecks:['role-aware-actions','destructive-confirmation','server-authorization','responsive-accessibility']}}),
primitive({name:'pandora-audit',category:'observability',capabilities:['audit.business_mutation','audit.admin_mutation','audit.actor_attribution'],dependencies:[{name:'pandora-rbac',range:'^1.0.0'}],runtimeRequirements:[{capability:'database',required:true}],events:[{name:'audit.recorded',version:'1.0'}],source:{kind:'migration-package',path:'packages/primitives/audit'},sourceDigest:'sha256:23e04d2256d2bb9231fe43cf4469fa2ddd479ff64fe135fed7954908ea49cb1e'}),
primitive({name:'pandora-notifications',category:'communications',capabilities:['notifications.email','notifications.in_app','notifications.template','notifications.delivery_receipt','notifications.idempotency'],runtimeRequirements:[{capability:'notification-provider',required:true},{capability:'database',required:true}],secretRequirements:['notifications.provider_secret'],events:[{name:'notification.requested',version:'1.0'},{name:'notification.delivered',version:'1.0'},{name:'notification.failed',version:'1.0'}],source:{kind:'combination',path:'packages/primitives/notifications'},sourceDigest:'sha256:446bcbb4d197d6709f73c7045880eaac052cb206259d67805284f20823ff06f6',verificationProfile:{requiredChecks:['template-safety','idempotent-delivery','fake-provider-receipt','retry-policy']}}),
primitive({name:'pandora-analytics',category:'analytics',capabilities:['analytics.business_events','analytics.project_attribution','analytics.environment_attribution','analytics.privacy_controls'],runtimeRequirements:[{capability:'analytics-sink',required:true},{capability:'database',required:true}],secretRequirements:['analytics.write_credential'],events:[{name:'analytics.business_event',version:'1.0'}],source:{kind:'package',path:'packages/primitives/analytics'},sourceDigest:'sha256:4a2f838a5a7c0a0e9e562cd38a553cafcd27dc20003ae92bc13d00c1a3adc774',verificationProfile:{requiredChecks:['event-schema','project-version-attribution','privacy-redaction','fake-sink']}}),
primitive({name:'pandora-booking',category:'booking',capabilities:['booking.resources','booking.availability','booking.reservation','booking.cancellation','booking.capacity','booking.timezone'],supportedProjectTypes:WEB_SYSTEM_TYPES,dependencies:[{name:'pandora-auth',range:'^1.0.0',optional:true},{name:'pandora-notifications',range:'^1.0.0',optional:true},{name:'pandora-analytics',range:'^1.0.0',optional:true}],runtimeRequirements:[{capability:'database',required:true},{capability:'transactions',required:true}],configurationSchema:{type:'object',additionalProperties:false,required:['timezone'],properties:{timezone:{type:'string',maxLength:64},requiresPayment:{type:'boolean'},capacityMode:{type:'string',enum:['inventory','resource','unlimited']},cancellationPolicy:{type:'string',maxLength:2000}}},events:[{name:'reservation.created',version:'1.0'},{name:'reservation.cancelled',version:'1.0'}],source:{kind:'combination',path:'packages/primitives/booking'},sourceDigest:'sha256:51465976ab10d5fe7882f1b59e5b90edb2debb64a4518e01f7e034089e1c12ad',verificationProfile:{requiredChecks:['availability','reservation','concurrency-collision','authorization','timezone-dst','event-emission']}}),
primitive({name:'pandora-commerce',category:'commerce',capabilities:['commerce.catalog','commerce.variants','commerce.inventory','commerce.cart','commerce.checkout','commerce.order','commerce.promotions'],supportedProjectTypes:WEB_SYSTEM_TYPES,runtimeRequirements:[{capability:'database',required:true},{capability:'transactions',required:true}],events:[{name:'order.created',version:'1.0'},{name:'order.completed',version:'1.0'}],source:{kind:'combination',path:'packages/primitives/commerce'},sourceDigest:'sha256:036157e688c199bf61f4a851e13d525653ca27af76568e8d3bc684632636371e',verificationProfile:{requiredChecks:['minor-unit-money','inventory-concurrency','order-state','business-event']}}),
primitive({name:'pandora-billing',category:'payments',capabilities:['payments.intent','payments.status','payments.refund','payments.webhook','payments.receipt'],dependencies:[{name:'pandora-commerce',range:'^1.0.0',optional:true}],runtimeRequirements:[{capability:'payment-provider',required:true},{capability:'database',required:true}],secretRequirements:['payments.provider_secret','payments.webhook_signing_secret'],events:[{name:'payment.completed',version:'1.0'},{name:'payment.refunded',version:'1.0'}],source:{kind:'combination',path:'packages/primitives/billing'},sourceDigest:'sha256:a33262d419b16b2ca5cd3013a5252f0a94fbdae7b0475940909b747b9e70e43b',verificationProfile:{requiredChecks:['signature-verification','webhook-idempotency','replay-protection','client-success-rejection','no-card-storage']}}),
primitive({name:'pandora-crm',category:'crm',capabilities:['crm.contact','crm.customer','crm.lead','crm.interaction','crm.notes','crm.tags','crm.pipeline','crm.assignee'],runtimeRequirements:[{capability:'database',required:true}],events:[{name:'customer.created',version:'1.0'},{name:'lead.created',version:'1.0'}],source:{kind:'combination',path:'packages/primitives/crm'},verificationProfile:{requiredChecks:['data-minimization','authorization','activity-lineage']}}),
primitive({name:'pandora-forms',category:'forms',capabilities:['forms.schema','forms.validation','forms.submission','forms.attachments','forms.spam_hooks'],runtimeRequirements:[{capability:'database',required:true}],events:[{name:'form.submitted',version:'1.0'}],source:{kind:'generated-module',path:'packages/primitives/forms'},verificationProfile:{requiredChecks:['server-validation','payload-limit','injection','abuse-hook']}}),
primitive({name:'pandora-files',category:'files',capabilities:['files.upload','files.signed_access','files.ownership','files.retention','files.metadata','files.image_pipeline'],runtimeRequirements:[{capability:'object-storage',required:true}],configurationSchema:{type:'object',additionalProperties:false,properties:{maxBytes:{type:'integer',minimum:1},allowedContentTypes:{type:'array'},privateByDefault:{type:'boolean'}}},source:{kind:'combination',path:'packages/primitives/files'},verificationProfile:{requiredChecks:['content-type','size-limit','signed-access','ownership','bucket-policy']}}),
primitive({name:'pandora-search',category:'search',capabilities:['search.text','search.filtering','search.sorting','search.pagination'],runtimeRequirements:[{capability:'search-provider',required:true}],source:{kind:'package',path:'packages/primitives/search'}}),
primitive({name:'pandora-content',category:'content',capabilities:['content.pages','content.articles','content.faqs','content.business_editing'],runtimeRequirements:[{capability:'database',required:true}],source:{kind:'combination',path:'packages/primitives/content'}}),
primitive({name:'pandora-scheduling',category:'scheduling',capabilities:['scheduling.slots','scheduling.resource_schedule','scheduling.availability','scheduling.timezone','scheduling.exceptions','scheduling.recurrence'],runtimeRequirements:[{capability:'database',required:true}],events:[{name:'schedule.changed',version:'1.0'}],source:{kind:'package',path:'packages/primitives/scheduling'}}),
primitive({name:'pandora-customer-profile',category:'profile',capabilities:['profile.identity_reference','profile.preferences','profile.contact','profile.history_links','profile.consent'],dependencies:[{name:'pandora-auth',range:'^1.0.0',optional:true}],runtimeRequirements:[{capability:'database',required:true}],source:{kind:'combination',path:'packages/primitives/customer-profile'}}),
primitive({name:'pandora-settings',category:'settings',capabilities:['settings.business_name','settings.timezone','settings.currency','settings.locale','settings.branding','settings.operational_defaults'],runtimeRequirements:[{capability:'database',required:true}],source:{kind:'package',path:'packages/primitives/settings'}}),
primitive({name:'pandora-feature-flags',category:'configuration',capabilities:['config.feature_flags','config.runtime_values','config.bounded_override'],runtimeRequirements:[{capability:'configuration-store',required:true}],source:{kind:'package',path:'packages/primitives/feature-flags'},verificationProfile:{requiredChecks:['authorization','safe-default','dangerous-setting-denial','audit-hook']}})
]);
module.exports={INITIAL_PRIMITIVES};
