'use strict';
const { validateConfiguration } = require('./configuration');
const { digest } = require('./registry');
const { satisfies } = require('./semver');
function composePrimitives(registry, request) {
  const errors=[]; if (!request || typeof request !== 'object') return { ok:false, errors:['composition request must be an object'], manifest:null };
  for (const field of ['projectId','projectVersionId','projectType']) if (typeof request[field] !== 'string' || !request[field].trim()) errors.push(`${field} is required`);
  if (!Array.isArray(request.primitives) || request.primitives.length===0) errors.push('primitives must contain at least one exact version'); if (errors.length) return { ok:false, errors, manifest:null };
  const runtimeCapabilities=new Set(request.runtimeCapabilities || []); const selected=new Map();
  for (const selection of request.primitives) { if (!selection || typeof selection !== 'object') { errors.push('primitive selection must be an object'); continue; } if (selection.version==='latest') { errors.push(`${selection.name || 'primitive'} may not use latest`); continue; } const definition=registry.getExact(selection.name,selection.version); if (!definition) { errors.push(`unknown primitive ${selection.name}@${selection.version}`); continue; } if (selected.has(definition.name)) { errors.push(`multiple versions selected for ${definition.name}`); continue; } if (definition.trustState==='BLOCKED') errors.push(`${definition.name}@${definition.version} is BLOCKED`); if (request.requireTrusted && definition.trustState!=='TRUSTED') errors.push(`${definition.name}@${definition.version} is not TRUSTED`); if (!definition.supportedProjectTypes.includes(request.projectType)) errors.push(`${definition.name}@${definition.version} does not support ${request.projectType}`); for (const requirement of definition.runtimeRequirements || []) if (requirement.required!==false && !runtimeCapabilities.has(requirement.capability)) errors.push(`${definition.name}@${definition.version} requires runtime capability ${requirement.capability}`); const configValidation=validateConfiguration(definition.configurationSchema,selection.configuration || {}); configValidation.errors.forEach((error)=>errors.push(`${definition.name}: ${error}`)); selected.set(definition.name,{ definition, selection }); }
  for (const {definition} of selected.values()) for (const dependency of definition.dependencies || []) { const actual=selected.get(dependency.name); if (!actual) { if (!dependency.optional) errors.push(`${definition.name}@${definition.version} requires ${dependency.name} ${dependency.range}`); continue; } if (!satisfies(actual.definition.version,dependency.range)) errors.push(`${definition.name}@${definition.version} requires ${dependency.name} ${dependency.range}, got ${actual.definition.version}`); }
  if (errors.length) return { ok:false, errors, manifest:null };
  const primitives=[...selected.values()].map(({definition,selection})=>({ name:definition.name, version:definition.version, trustState:definition.trustState, definitionDigest:definition.definitionDigest, sourceDigest:definition.sourceDigest || null, source:definition.source, capabilities:definition.capabilities, runtimeRequirements:definition.runtimeRequirements, configuration:selection.configuration || {}, configurationDigest:digest(selection.configuration || {}), customization:selection.customization || {}, customizationDigest:digest(selection.customization || {}) })).sort((a,b)=>a.name.localeCompare(b.name));
  const manifestBase={ schemaVersion:'1.0', projectId:request.projectId, projectVersionId:request.projectVersionId, projectType:request.projectType, runtimeCapabilities:[...runtimeCapabilities].sort(), primitives };
  return { ok:true, errors:[], manifest:Object.freeze({ ...manifestBase, manifestDigest:digest(manifestBase) }) };
}
function deriveGeneratedSourceLineage(manifest,generatedFiles){ if (!manifest || !Array.isArray(manifest.primitives)) throw new TypeError('composition manifest required'); if (!Array.isArray(generatedFiles)) throw new TypeError('generatedFiles must be an array'); const exact=new Map(manifest.primitives.map((primitive)=>[primitive.name,primitive])); return generatedFiles.map((file)=>{ if (!file || typeof file.path !== 'string' || !file.path.trim()) throw new TypeError('generated file path required'); const primitive=exact.get(file.primitive); if (!primitive) throw new Error(`file ${file.path} references primitive outside composition`); return Object.freeze({ path:file.path, origin:`${primitive.name}@${primitive.version}`, primitiveDefinitionDigest:primitive.definitionDigest, primitiveSourceDigest:primitive.sourceDigest, customizationDigest:file.customizationDigest || primitive.customizationDigest, ownership:file.ownership || 'primitive-core' }); }); }
module.exports = { composePrimitives, deriveGeneratedSourceLineage };
