'use strict';
const DANGEROUS=/(?:service.?role|master.?token|raw.?sql|disable.?auth|allow.?all|password|secret|private.?key|authorization|cookie)/i;
class PandoraFeatureFlagsService {
  constructor({store,authorization,audit}){if(!store||typeof store.get!=='function'||typeof store.set!=='function'||typeof store.remove!=='function')throw new TypeError('feature flag store contract is required');if(store.scopeAware!==true)throw new Error('feature flag store must be scope-aware');if(!authorization||typeof authorization.assertAllowed!=='function')throw new TypeError('feature flag authorization.assertAllowed is required');if(!audit||typeof audit.record!=='function')throw new TypeError('feature flag audit.record is required');this.store=store;this.authorization=authorization;this.audit=audit;}
  async evaluate({scopeId,identity,key,defaultValue=false}){const scope=required(scopeId,'scopeId');await this.authorization.assertAllowed({userId:required(identity&&identity.userId,'identity.userId'),tenantId:scope,permission:'settings.read'});const name=flagKey(key);const fallback=flagValue(defaultValue);const row=await this.store.get({scopeId:scope,key:name});if(!row)return fallback;if(row.scopeId!==scope)throw new Error('cross-scope feature flag result rejected');return flagValue(row.value);}
  async set({scopeId,identity,key,value,idempotencyKey}){const scope=required(scopeId,'scopeId'),userId=required(identity&&identity.userId,'identity.userId');await this.authorization.assertAllowed({userId,tenantId:scope,permission:'settings.manage'});const name=flagKey(key),clean=flagValue(value),idem=required(idempotencyKey,'idempotencyKey');const result=await this.store.set({scopeId:scope,key:name,value:clean,actorUserId:userId,idempotencyKey:idem});await this.audit.record({scopeId:scope,actorUserId:userId,event:'feature_flag.set',resourceType:'feature_flag',resourceId:name,mutationId:idem,metadata:{valueType:typeof clean}});return result;}
  async remove({scopeId,identity,key,idempotencyKey}){const scope=required(scopeId,'scopeId'),userId=required(identity&&identity.userId,'identity.userId');await this.authorization.assertAllowed({userId,tenantId:scope,permission:'settings.manage'});const name=flagKey(key),idem=required(idempotencyKey,'idempotencyKey');const result=await this.store.remove({scopeId:scope,key:name,actorUserId:userId,idempotencyKey:idem});await this.audit.record({scopeId:scope,actorUserId:userId,event:'feature_flag.removed',resourceType:'feature_flag',resourceId:name,mutationId:idem,metadata:{}});return result;}
}
function flagKey(v){const value=required(v,'key');if(value.length>96||!/^[a-z][a-z0-9_.-]+$/.test(value)||DANGEROUS.test(value))throw new Error('feature flag key is unsafe');return value;}
function flagValue(v){if(!['boolean','string','number'].includes(typeof v)||typeof v==='number'&&!Number.isFinite(v))throw new TypeError('feature flag value must be a finite scalar');if(typeof v==='string'&&v.length>500)throw new TypeError('feature flag string is too long');return v;}
function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={DANGEROUS,PandoraFeatureFlagsService,flagKey,flagValue};
