-- pandora-primitive: pandora-commerce@1.0.0
-- target: customer-app-runtime-only
DO $$ BEGIN IF to_regclass('public.project_specs') IS NOT NULL OR to_regclass('public.projectos_execution_plans') IS NOT NULL OR to_regclass('public.pandora_projects') IS NOT NULL THEN RAISE EXCEPTION 'pandora-commerce customer primitive refused on Pandora Control Plane-like schema'; END IF; END $$;
CREATE TABLE IF NOT EXISTS public.primitive_commerce_products(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),scope_id uuid NOT NULL,name text NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(id,scope_id));
CREATE TABLE IF NOT EXISTS public.primitive_commerce_variants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),scope_id uuid NOT NULL,product_id uuid NOT NULL,sku text NOT NULL,price_minor bigint NOT NULL CHECK(price_minor>=0),currency text NOT NULL CHECK(currency~'^[A-Z]{3}$'),active boolean NOT NULL DEFAULT true,FOREIGN KEY(product_id,scope_id) REFERENCES public.primitive_commerce_products(id,scope_id) ON DELETE CASCADE,UNIQUE(scope_id,sku),UNIQUE(id,scope_id));
CREATE TABLE IF NOT EXISTS public.primitive_commerce_inventory(scope_id uuid NOT NULL,variant_id uuid NOT NULL,stock_on_hand bigint NOT NULL DEFAULT 0 CHECK(stock_on_hand>=0),reserved bigint NOT NULL DEFAULT 0 CHECK(reserved>=0 AND reserved<=stock_on_hand),PRIMARY KEY(scope_id,variant_id),FOREIGN KEY(variant_id,scope_id) REFERENCES public.primitive_commerce_variants(id,scope_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS public.primitive_commerce_orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),scope_id uuid NOT NULL,customer_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,status text NOT NULL CHECK(status IN('pending','confirmed','fulfilled','cancelled','refunded')),total_minor bigint NOT NULL CHECK(total_minor>=0),currency text NOT NULL CHECK(currency~'^[A-Z]{3}$'),idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(scope_id,idempotency_key),UNIQUE(id,scope_id));
CREATE TABLE IF NOT EXISTS public.primitive_commerce_order_items(order_id uuid NOT NULL,scope_id uuid NOT NULL,variant_id uuid NOT NULL,quantity integer NOT NULL CHECK(quantity>0),unit_price_minor bigint NOT NULL CHECK(unit_price_minor>=0),currency text NOT NULL CHECK(currency~'^[A-Z]{3}$'),PRIMARY KEY(order_id,variant_id),FOREIGN KEY(order_id,scope_id) REFERENCES public.primitive_commerce_orders(id,scope_id) ON DELETE CASCADE,FOREIGN KEY(variant_id,scope_id) REFERENCES public.primitive_commerce_variants(id,scope_id) ON DELETE RESTRICT);
ALTER TABLE public.primitive_commerce_products ENABLE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_products FORCE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_variants ENABLE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_variants FORCE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_inventory ENABLE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_inventory FORCE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_orders ENABLE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_orders FORCE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_order_items ENABLE ROW LEVEL SECURITY;ALTER TABLE public.primitive_commerce_order_items FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.primitive_commerce_products,public.primitive_commerce_variants,public.primitive_commerce_inventory,public.primitive_commerce_orders,public.primitive_commerce_order_items FROM anon,authenticated;GRANT SELECT ON public.primitive_commerce_orders,public.primitive_commerce_order_items TO authenticated;
CREATE POLICY primitive_commerce_orders_own ON public.primitive_commerce_orders FOR SELECT TO authenticated USING(customer_user_id=(SELECT auth.uid()));CREATE POLICY primitive_commerce_order_items_own ON public.primitive_commerce_order_items FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.primitive_commerce_orders o WHERE o.id=primitive_commerce_order_items.order_id AND o.scope_id=primitive_commerce_order_items.scope_id AND o.customer_user_id=(SELECT auth.uid())));
CREATE OR REPLACE FUNCTION public.primitive_commerce_reserve_inventory(p_scope_id uuid,p_variant_id uuid,p_quantity integer) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$BEGIN IF p_quantity<=0 THEN RAISE EXCEPTION 'quantity must be positive';END IF;UPDATE public.primitive_commerce_inventory SET reserved=reserved+p_quantity WHERE scope_id=p_scope_id AND variant_id=p_variant_id AND stock_on_hand-reserved>=p_quantity;RETURN FOUND;END$$;REVOKE ALL ON FUNCTION public.primitive_commerce_reserve_inventory(uuid,uuid,integer) FROM PUBLIC,anon,authenticated;
