'use strict';
const crypto=require('node:crypto'); const {assertIdempotentEventSink,createDomainEvent}=require('../../core/src/events');
class HmacWebhookVerifier {
 constructor({secret,toleranceSeconds=300,now=()=>Date.now()}){if(typeof secret!=='string'||secret.length<16)throw new TypeError('webhook secret must be server-side bounded secret material');this.secret=secret;this.toleranceSeconds=toleranceSeconds;this.now=now;}
 verify({rawBody,signature,timestamp}){if(!Buffer.isBuffer(rawBody))throw new TypeError('rawBody Buffer is required');if(typeof signature!=='string'||!/^sha256=[a-f0-9]{64}$/i.test(signature))return false;const ts=Number(timestamp);if(!Number.isFinite(ts)||Math.abs(this.now()/1000-ts)>this.toleranceSeconds)return false;const expected='sha256='+crypto.createHmac('sha256',this.secret).update(`${ts}.`).update(rawBody).digest('hex');const a=Buffer.from(expected);const b=Buffer.from(signature.toLowerCase());return a.length===b.length&&crypto.timingSafeEqual(a,b);}
}
class PandoraPayments {
 constructor({provider,eventStore,eventSink,webhookVerifier}){for(const m of ['createIntent','refund','normalizeWebhook'])if(!provider||typeof provider[m]!=='function')throw new TypeError(`payment provider.${m} is required`);if(!eventStore||typeof eventStore.claim!=='function'||typeof eventStore.complete!=='function'||typeof eventStore.fail!=='function')throw new TypeError('payment event idempotency store is required');assertIdempotentEventSink(eventSink,'payment event sink');if(!webhookVerifier||typeof webhookVerifier.verify!=='function')throw new TypeError('payment webhook verifier is required');this.provider=provider;this.eventStore=eventStore;this.eventSink=eventSink;this.webhookVerifier=webhookVerifier;}
 async createIntent(request){rejectCardData(request);const normalized=paymentRequest(request);const result=await this.provider.createIntent(normalized);if(!result||typeof result.paymentId!=='string'||typeof result.status!=='string')throw new Error('payment provider returned invalid intent');return Object.freeze({...result,amountMinor:normalized.amountMinor,currency:normalized.currency});}
 async refund({paymentId,amountMinor,currency,idempotencyKey}){const request=paymentRequest({paymentId,amountMinor,currency,idempotencyKey});const result=await this.provider.refund(request);if(!result||typeof result.refundId!=='string')throw new Error('payment provider returned invalid refund');return Object.freeze({...result});}
 async handleWebhook({project,rawBody,signature,timestamp}){if(!this.webhookVerifier.verify({rawBody,signature,timestamp}))throw Object.assign(new Error('invalid webhook signature'),{code:'INVALID_WEBHOOK_SIGNATURE'});let parsed;try{parsed=JSON.parse(rawBody.toString('utf8'));}catch{throw new Error('invalid webhook JSON');}const normalized=await this.provider.normalizeWebhook(parsed);if(!normalized||typeof normalized.eventId!=='string'||typeof normalized.type!=='string'||typeof normalized.paymentId!=='string')throw new Error('invalid normalized payment webhook');const claim=await this.eventStore.claim(normalized.eventId);if(!claim||claim.claimed!==true)return Object.freeze({duplicate:true,eventId:normalized.eventId});try{const allowed=new Set(['payment.completed','payment.refunded','payment.failed','payment.cancelled','payment.pending']);if(!allowed.has(normalized.type))throw new Error('unsupported normalized payment webhook type');const domainName=normalized.type==='payment.completed'?'payment.completed':normalized.type==='payment.refunded'?'payment.refunded':'payment.status_changed';const event=createDomainEvent({name:domainName,schemaVersion:'1.0',project,aggregate:{type:'payment',id:normalized.paymentId},payload:{status:String(normalized.status||'unknown'),amount_minor:String(normalized.amountMinor||''),currency:String(normalized.currency||'')},idempotencyKey:`provider:${normalized.eventId}`});await this.eventSink.publish(event);await this.eventStore.complete(normalized.eventId,{paymentId:normalized.paymentId,type:normalized.type});return Object.freeze({duplicate:false,event});}catch(error){await this.eventStore.fail(normalized.eventId,{code:typeof error.code==='string'?error.code:'WEBHOOK_PROCESSING_FAILED'});throw error;}}
}
function paymentRequest(input){if(!input||typeof input!=='object')throw new TypeError('payment request is required');const amount=String(input.amountMinor??'');if(!/^\d+$/.test(amount)||BigInt(amount)<=0n)throw new TypeError('amountMinor must be a positive integer');const currency=String(input.currency||'').toUpperCase();if(!/^[A-Z]{3}$/.test(currency))throw new TypeError('currency is required');const idempotencyKey=required(input.idempotencyKey,'idempotencyKey');return Object.freeze({paymentId:input.paymentId?required(input.paymentId,'paymentId'):null,amountMinor:amount,currency,idempotencyKey,customerRef:input.customerRef?required(input.customerRef,'customerRef'):null,metadata:safeMetadata(input.metadata)});}
function rejectCardData(value){if(!value||typeof value!=='object')return;for(const key of Object.keys(value))if(/(?:card|cvv|cvc|pan|expiry|track.?data)/i.test(key))throw new Error(`raw card field is forbidden: ${key}`);}
function safeMetadata(v){if(!v||typeof v!=='object'||Array.isArray(v))return{};const out={};for(const [k,x] of Object.entries(v))if(!/(?:secret|token|password|card)/i.test(k)&&(x==null||['string','number','boolean'].includes(typeof x)))out[k]=x;return Object.freeze(out);}function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={HmacWebhookVerifier,PandoraPayments,paymentRequest,rejectCardData};
