'use strict';
class PandoraSettingsService {
  constructor({repository,authorization}){if(!repository||typeof repository.getSettings!=='function'||typeof repository.saveSettings!=='function')throw new TypeError('settings repository contract is required');if(!authorization||typeof authorization.assertAllowed!=='function')throw new TypeError('settings authorization.assertAllowed is required');this.repository=repository;this.authorization=authorization;}
  async get({scopeId,identity}){const scope=required(scopeId,'scopeId');await this.authorization.assertAllowed({userId:required(identity&&identity.userId,'identity.userId'),tenantId:scope,permission:'settings.read'});const row=await this.repository.getSettings({scopeId:scope});return row?normalizeSettings(row):null;}
  async save({scopeId,identity,settings,idempotencyKey}){const scope=required(scopeId,'scopeId');await this.authorization.assertAllowed({userId:required(identity&&identity.userId,'identity.userId'),tenantId:scope,permission:'settings.manage'});const clean=normalizeSettings(settings);return this.repository.saveSettings({scopeId:scope,settings:clean,actorUserId:identity.userId,idempotencyKey:required(idempotencyKey,'idempotencyKey')});}
}
function normalizeSettings(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('settings must be an object');for(const key of Object.keys(value))if(!['businessName','timezone','currency','locale','branding','operationalDefaults'].includes(key))throw new TypeError(`unknown settings field: ${key}`);const out={};if(value.businessName!=null)out.businessName=text(value.businessName,200,'businessName');if(value.timezone!=null){out.timezone=text(value.timezone,64,'timezone');try{new Intl.DateTimeFormat('en-US',{timeZone:out.timezone}).format(new Date());}catch{throw new TypeError('timezone must be a valid IANA timezone');}}if(value.currency!=null){const c=text(value.currency,3,'currency').toUpperCase();if(!/^[A-Z]{3}$/.test(c))throw new TypeError('currency must be 3 letters');out.currency=c;}if(value.locale!=null){const l=text(value.locale,32,'locale');if(!/^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/.test(l))throw new TypeError('locale is invalid');out.locale=l;}if(value.branding!=null)out.branding=boundedObject(value.branding,'branding',16,300);if(value.operationalDefaults!=null)out.operationalDefaults=boundedObject(value.operationalDefaults,'operationalDefaults',32,500);return Object.freeze(out);}
function boundedObject(value,field,maxKeys,maxText){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError(`${field} must be an object`);const entries=Object.entries(value);if(entries.length>maxKeys)throw new TypeError(`${field} has too many keys`);const out={};for(const [k,v] of entries){if(!/^[a-z][a-z0-9_.-]{0,63}$/i.test(k))throw new TypeError(`${field}.${k} key is invalid`);if(!['string','number','boolean'].includes(typeof v))throw new TypeError(`${field}.${k} must be scalar`);if(typeof v==='string'&&v.length>maxText)throw new TypeError(`${field}.${k} is too long`);out[k]=v;}return Object.freeze(out);}
function text(v,max,f){if(typeof v!=='string'||!v.trim()||v.length>max)throw new TypeError(`${f} is invalid`);return v.trim();}function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={PandoraSettingsService,boundedObject,normalizeSettings};
