from pathlib import Path
p=Path(r'C:\Pandora\w1-r058-trusted-coordinator-20260916\supabase\functions\pandora-coordinator-gate\publisher.mjs')
s=p.read_text(encoding='utf-8')
old='''function assertChain(existing, envelope) {\n  if (!existing) {\n    if (\n      envelope.decisionGeneration !== 1 ||\n      envelope.priorGeneration !== null ||\n      envelope.priorCheckRunId !== null\n    ) throw new Error("DECISION_CHAIN_MISMATCH");\n    return null;\n  }\n  const row = asRecord(existing);\n  const meta = parseCheckExternalId(row.external_id);\n  if (!meta) throw new Error("TRUSTED_CHECK_METADATA_INVALID");\n  if (!Number.isSafeInteger(row.id) || row.id < 1) throw new Error("TRUSTED_CHECK_ID_INVALID");\n  if (meta.generation > envelope.decisionGeneration) throw new Error("STALE_DECISION_GENERATION");\n  if (meta.generation < envelope.decisionGeneration && (\n    envelope.priorGeneration !== meta.generation || envelope.priorCheckRunId !== row.id\n  )) throw new Error("DECISION_CHAIN_MISMATCH");\n  return meta;\n}\n'''
new='''async function assertChain(provider, existing, envelope) {\n  if (!existing) {\n    if (envelope.decisionGeneration === 1) {\n      if (envelope.priorGeneration !== null || envelope.priorCheckRunId !== null) {\n        throw new Error("DECISION_CHAIN_MISMATCH");\n      }\n      return null;\n    }\n    if (envelope.priorGeneration !== envelope.decisionGeneration - 1) {\n      throw new Error("DECISION_CHAIN_MISMATCH");\n    }\n    if (envelope.priorCheckRunId === null) {\n      return null;\n    }\n    const prior = asRecord(await provider.getCheck(envelope.priorCheckRunId));\n    const priorMeta = parseCheckExternalId(prior.external_id);\n    if (!priorMeta || prior.id !== envelope.priorCheckRunId ||\n        asRecord(prior.app).id !== INTEGRATION_APP_ID || prior.name !== RULE_CONTEXT ||\n        priorMeta.generation !== envelope.priorGeneration) {\n      throw new Error("DECISION_CHAIN_MISMATCH");\n    }\n    return null;\n  }\n  const row = asRecord(existing);\n  const meta = parseCheckExternalId(row.external_id);\n  if (!meta) throw new Error("TRUSTED_CHECK_METADATA_INVALID");\n  if (!Number.isSafeInteger(row.id) || row.id < 1) throw new Error("TRUSTED_CHECK_ID_INVALID");\n  if (meta.generation > envelope.decisionGeneration) throw new Error("STALE_DECISION_GENERATION");\n  if (meta.generation < envelope.decisionGeneration && (\n    envelope.priorGeneration !== meta.generation || envelope.priorCheckRunId !== row.id\n  )) throw new Error("DECISION_CHAIN_MISMATCH");\n  return meta;\n}\n'''
if old not in s: raise SystemExit('assertChain block not found')
s=s.replace(old,new)
s=s.replace('const priorMeta = assertChain(existing, envelope);','const priorMeta = await assertChain(provider, existing, envelope);')
p.write_text(s,encoding='utf-8')
print('patched publisher')
