from pathlib import Path
p=Path(r'C:\Pandora\w1-r058-trusted-coordinator-20260916\supabase\functions\pandora-coordinator-gate\index.ts')
s=p.read_text(encoding='utf-8')
old='''async function beginDecision(admin: ReturnType<typeof adminClient>, internalKey: string, envelope: JsonRecord, binding: JsonRecord) {\n  return rec(await rpc(admin, "pandora_coordinator_gate_begin_decision_v2", {\n    p_internal_key: internalKey,\n    p_repository: envelope.repository,\n    p_pull_request_number: envelope.pullRequestNumber,\n    p_decision_generation: envelope.decisionGeneration,\n    p_prior_generation: envelope.priorGeneration,\n    p_prior_check_run_id: envelope.priorCheckRunId,\n    p_head_sha: envelope.headSha,\n    p_base_sha: envelope.baseSha,\n    p_authoritative_snapshot_generation: envelope.authoritativeSnapshotGeneration,\n    p_authoritative_snapshot_revision: envelope.authoritativeSnapshotRevision,\n    p_authoritative_snapshot_sha256: envelope.authoritativeSnapshotSha256,\n    p_envelope_hash: binding.envelopeHash,\n    p_idempotency_key: binding.idempotencyKey,\n    p_decision_nonce: envelope.decisionNonce,\n    p_decision: envelope.decision,\n    p_expires_at: envelope.expiresAt,\n  }, "GATE_STATE_BEGIN_FAILED"));\n}\n'''
new='''async function beginDecision(admin: ReturnType<typeof adminClient>, internalKey: string, envelope: JsonRecord, binding: JsonRecord) {\n  const args = {\n    p_internal_key: internalKey, p_repository: envelope.repository,\n    p_pull_request_number: envelope.pullRequestNumber, p_decision_generation: envelope.decisionGeneration,\n    p_prior_generation: envelope.priorGeneration, p_prior_check_run_id: envelope.priorCheckRunId,\n    p_head_sha: envelope.headSha, p_base_sha: envelope.baseSha,\n    p_authoritative_snapshot_generation: envelope.authoritativeSnapshotGeneration,\n    p_authoritative_snapshot_revision: envelope.authoritativeSnapshotRevision,\n    p_authoritative_snapshot_sha256: envelope.authoritativeSnapshotSha256,\n    p_envelope_hash: binding.envelopeHash, p_idempotency_key: binding.idempotencyKey,\n    p_decision_nonce: envelope.decisionNonce, p_decision: envelope.decision, p_expires_at: envelope.expiresAt,\n  };\n  const result = await admin.rpc("pandora_coordinator_gate_begin_decision_v2", args);\n  if (!result.error) return rec(result.data);\n  const recovered = rec(await rpc(admin, "pandora_coordinator_gate_read_state_v1", {\n    p_internal_key: internalKey, p_repository: envelope.repository,\n    p_pull_request_number: envelope.pullRequestNumber,\n  }, "GATE_STATE_BEGIN_READBACK_FAILED"));\n  const snapshot = await readEffectiveSnapshot(admin, internalKey);\n'''
if old not in s: raise SystemExit('begin block not found')
s=s.replace(old,new)
tail='''  const same = recovered.repository === envelope.repository &&\n    recovered.pull_request_number === envelope.pullRequestNumber &&\n    recovered.current_generation === envelope.decisionGeneration &&\n    recovered.head_sha === envelope.headSha && recovered.base_sha === envelope.baseSha &&\n    recovered.authoritative_snapshot_generation === envelope.authoritativeSnapshotGeneration &&\n    recovered.authoritative_snapshot_revision === envelope.authoritativeSnapshotRevision &&\n    recovered.authoritative_snapshot_sha256 === envelope.authoritativeSnapshotSha256 &&\n    recovered.envelope_hash === binding.envelopeHash && recovered.idempotency_key === binding.idempotencyKey &&\n    recovered.decision_nonce === envelope.decisionNonce && recovered.decision === envelope.decision &&\n    recovered.current_check_run_id === null && recovered.provider_status === null && recovered.provider_conclusion === null &&\n    snapshot?.fenceState === "publishing";\n  if (!same) throw new Error("GATE_STATE_BEGIN_FAILED");\n  return { mode: "ambiguous_recovered", decisionId: recovered.current_decision_id, generation: recovered.current_generation };\n}\n'''
anchor='''  const snapshot = await readEffectiveSnapshot(admin, internalKey);\n'''
idx=s.index(anchor)+len(anchor)
s=s[:idx]+tail+s[idx:]
old_record='''  const appId = Number(rec(check.app).id);\n  return rec(await rpc(admin, "pandora_coordinator_gate_record_publish_v2", {\n    p_internal_key: internalKey,\n    p_repository: envelope.repository,\n    p_pull_request_number: envelope.pullRequestNumber,\n    p_decision_generation: envelope.decisionGeneration,\n    p_authoritative_snapshot_generation: envelope.authoritativeSnapshotGeneration,\n    p_envelope_hash: binding.envelopeHash,\n    p_idempotency_key: binding.idempotencyKey,\n    p_check_run_id: check.id,\n    p_provider_app_id: appId,\n    p_provider_status: check.status,\n    p_provider_conclusion: check.conclusion,\n  }, "GATE_STATE_RECORD_FAILED"));\n}\n'''
new_record='''  const appId = Number(rec(check.app).id);\n  const args = { p_internal_key: internalKey, p_repository: envelope.repository,\n    p_pull_request_number: envelope.pullRequestNumber, p_decision_generation: envelope.decisionGeneration,\n    p_authoritative_snapshot_generation: envelope.authoritativeSnapshotGeneration, p_envelope_hash: binding.envelopeHash,\n    p_idempotency_key: binding.idempotencyKey, p_check_run_id: check.id, p_provider_app_id: appId,\n    p_provider_status: check.status, p_provider_conclusion: check.conclusion };\n  const result = await admin.rpc("pandora_coordinator_gate_record_publish_v2", args);\n  if (!result.error) return rec(result.data);\n'''
if old_record not in s: raise SystemExit('record block not found')
s=s.replace(old_record,new_record)
record_tail='''  const recovered = rec(await rpc(admin, "pandora_coordinator_gate_read_state_v1", {\n    p_internal_key: internalKey, p_repository: envelope.repository, p_pull_request_number: envelope.pullRequestNumber,\n  }, "GATE_STATE_RECORD_READBACK_FAILED"));\n  const snapshot = await readEffectiveSnapshot(admin, internalKey);\n  const expectedConclusion = envelope.decision === "PASS" ? "success" : "action_required";\n  const same = recovered.current_generation === envelope.decisionGeneration &&\n    recovered.current_check_run_id === check.id && recovered.provider_status === "completed" &&\n    recovered.provider_conclusion === expectedConclusion && recovered.envelope_hash === binding.envelopeHash &&\n    recovered.idempotency_key === binding.idempotencyKey && snapshot?.fenceState === "idle";\n  if (!same) throw new Error("GATE_STATE_RECORD_FAILED");\n  return { ok: true, mode: "ambiguous_recovered", checkRunId: check.id, decision: envelope.decision };\n}\n'''
needle='''  if (!result.error) return rec(result.data);\n'''
pos=s.rindex(needle)+len(needle)
s=s[:pos]+record_tail+s[pos:]
old_commit='''  const committed = rec(await rpc(admin, "pandora_coordinator_snapshot_commit_v1", {\n    p_internal_key: internalKey,\n    p_repository: CANONICAL_REPOSITORY,\n    p_promotion_id: promotionId,\n  }, "SNAPSHOT_COMMIT_FAILED"));\n  return { ok: true, action: "promoteSnapshot", ...committed };\n}\n'''
new_commit='''  if (prepared.mode === "effective_replay") {\n    const effective = await readEffectiveSnapshot(admin, internalKey);\n    if (!effective || effective.fenceState !== "idle" || effective.snapshotGeneration !== prepared.snapshotGeneration) {\n      throw new Error("SNAPSHOT_EFFECTIVE_REPLAY_MISMATCH");\n    }\n    return { ok: true, action: "promoteSnapshot", mode: "effective_replay", ...effective };\n  }\n  const commitResult = await admin.rpc("pandora_coordinator_snapshot_commit_v1", {\n    p_internal_key: internalKey, p_repository: CANONICAL_REPOSITORY, p_promotion_id: promotionId,\n  });\n  if (!commitResult.error) return { ok: true, action: "promoteSnapshot", ...rec(commitResult.data) };\n  const effective = await readEffectiveSnapshot(admin, internalKey);\n  const recovered = effective?.fenceState === "idle" && effective.snapshotGeneration === prepared.snapshotGeneration &&\n    effective.snapshotRevision === candidateRevision && effective.snapshotSha256 === candidateSha256;\n  if (!recovered) throw new Error("SNAPSHOT_COMMIT_FAILED");\n  return { ok: true, action: "promoteSnapshot", mode: "ambiguous_recovered", ...effective };\n}\n'''
if old_commit not in s: raise SystemExit('snapshot commit block not found')
s=s.replace(old_commit,new_commit)
p.write_text(s,encoding='utf-8')
print('patched index.ts')
