'use strict';
const {assertIdempotentEventSink,createDomainEvent}=require('../../core/src/events');
class PandoraFormsService {
 constructor({repository,spamGuard,eventSink,notifications=null,maxPayloadBytes=64*1024}){if(!repository||typeof repository.getForm!=='function'||typeof repository.createSubmission!=='function')throw new TypeError('forms repository contract is required');if(!spamGuard||typeof spamGuard.assess!=='function')throw new TypeError('forms spam guard is required');assertIdempotentEventSink(eventSink,'forms event sink');this.repository=repository;this.spamGuard=spamGuard;this.eventSink=eventSink;this.notifications=notifications;this.maxPayloadBytes=maxPayloadBytes;}
 async submit({project,scopeId,formKey,identity=null,values,attachments=[],antiAbuse={},idempotencyKey}){const bytes=Buffer.byteLength(JSON.stringify(values||{}));if(bytes>this.maxPayloadBytes)throw Object.assign(new Error('form payload too large'),{code:'PAYLOAD_TOO_LARGE'});const form=await this.repository.getForm({scopeId:required(scopeId,'scopeId'),formKey:required(formKey,'formKey')});if(!form||form.active!==true)throw new Error('form unavailable');const clean=validateSchema(form.schema,values);const safeAttachments=validateAttachments(attachments,form.attachmentPolicy||{});const abuse=await this.spamGuard.assess({scopeId,formKey,identity,antiAbuse,payloadDigest:simpleDigest(clean)});if(!abuse||abuse.allowed!==true)throw Object.assign(new Error('form submission rejected by abuse controls'),{code:'ABUSE_REJECTED'});const submission=await this.repository.createSubmission({scopeId,formId:form.id,submitterUserId:identity&&identity.userId||null,values:clean,attachments:safeAttachments,idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:'form.submitted',project,actor:identity&&identity.userId?{userId:identity.userId}:null,aggregate:{type:'form_submission',id:String(submission.id)},payload:{formKey,status:String(submission.status||'submitted')},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);return Object.freeze({...submission,event});}
}
function validateSchema(schema,values){if(!schema||typeof schema!=='object'||!Array.isArray(schema.fields))throw new TypeError('form schema is invalid');if(!values||typeof values!=='object'||Array.isArray(values))throw new TypeError('form values must be an object');const definitions=new Map(schema.fields.map(field=>[field.name,field]));const out={};for(const [name,value] of Object.entries(values)){const field=definitions.get(name);if(!field)throw new Error(`unknown form field: ${name}`);out[name]=validateField(field,value);}for(const field of schema.fields)if(field.required===true&&!(field.name in out))throw new Error(`required form field missing: ${field.name}`);return Object.freeze(out);}
function validateField(field,value){if(!/^[a-z][a-z0-9_]{0,63}$/.test(field.name))throw new TypeError('invalid form field name');if(value==null){if(field.required)throw new Error(`required form field missing: ${field.name}`);return null;}if(field.type==='boolean'){if(typeof value!=='boolean')throw new TypeError(`${field.name} must be boolean`);return value;}if(field.type==='number'){if(typeof value!=='number'||!Number.isFinite(value))throw new TypeError(`${field.name} must be number`);if(Number.isFinite(field.min)&&value<field.min)throw new Error(`${field.name} below minimum`);if(Number.isFinite(field.max)&&value>field.max)throw new Error(`${field.name} above maximum`);return value;}if(!['text','email','textarea','select'].includes(field.type))throw new TypeError(`unsupported form field type: ${field.type}`);if(typeof value!=='string')throw new TypeError(`${field.name} must be text`);const max=Number.isInteger(field.maxLength)?Math.min(field.maxLength,10000):1000;if(value.length>max)throw new Error `${field.name} too long`);if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new Error(`${field.name} must be email`);if(field.type==='select'&&(!Array.isArray(field.options)||!field.options.includes(value)))throw new Error(`${field.name} has invalid option`);return value.trim();}
function validateAttachments(items,policy){if(!Array.isArray(items))throw new TypeError('attachments must be an array');const max=Number.isInteger(policy.maxFiles)?Math.min(policy.maxFiles,10):0;if(items.length>max)throw new Error('too many attachments');return Object.freeze(items.map(item=>{if(!item||typeof item.fileId!=='string'||typeof item.contentType!=='string'||!/^[-\w.+]+\/[-\w.+]+$/.test(item.contentType))throw new TypeError('invalid attachment reference');if(Array.isArray(policy.allowedContentTypes)&&!policy.allowedContentTypes.includes(item.contentType))throw new Error('attachment type not allowed');return Object.freeze({fileId:item.fileId,contentType:item.contentType});}));}
function simpleDigest(v){return require('node:crypto').createHash('sha256').update(JSON.stringify(v)).digest('hex');}function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={PandoraFormsService,validateAttachments,validateSchema};
