'use strict';
class NotificationTemplateRegistry {
  constructor(templates={}) { this.templates=new Map(); for(const [key,value] of Object.entries(templates)) this.register(key,value); }
  register(key,template){if(!/^[a-z][a-z0-9_.-]{0,127}$/.test(key))throw new TypeError('invalid template key');if(!template||typeof template!=='object')throw new TypeError('template must be an object');const subject=required(template.subject,'template.subject');const body=required(template.body,'template.body');const allowed=Object.freeze([...(template.allowedVariables||[])]);for(const name of allowed)if(!/^[a-z][A-Za-z0-9_]{0,63}$/.test(name))throw new TypeError('invalid template variable');this.templates.set(key,Object.freeze({subject,body,allowedVariables:allowed,format:template.format==='html'?'html':'text'}));}
  render(key,variables={}){const template=this.templates.get(key);if(!template)throw new Error(`unknown notification template: ${key}`);const allowed=new Set(template.allowedVariables);for(const name of Object.keys(variables))if(!allowed.has(name))throw new Error(`template variable is not allowed: ${name}`);const render=(value)=>value.replace(/\{\{([A-Za-z][A-Za-z0-9_]*)\}\}/g,(_,name)=>{if(!allowed.has(name))throw new Error(`template contains undeclared variable: ${name}`);const raw=variables[name];if(raw==null)return'';if(!['string','number','boolean'].includes(typeof raw))throw new TypeError(`template variable must be scalar: ${name}`);return template.format==='html'?escapeHtml(String(raw)):String(raw);});return Object.freeze({subject:render(template.subject),body:render(template.body),format:template.format});}
}
class PandoraNotificationService {
  constructor({provider,templates,idempotencyStore}){if(!provider||typeof provider.send!=='function')throw new TypeError('notification provider is required');if(!templates||typeof templates.render!=='function')throw new TypeError('template registry is required');if(!idempotencyStore||typeof idempotencyStore.claim!=='function'||typeof idempotencyStore.complete!=='function'||typeof idempotencyStore.fail!=='function')throw new TypeError('notification idempotency store is required');this.provider=provider;this.templates=templates;this.idempotencyStore=idempotencyStore;}
  async send({channel,recipient,template,variables,branding={},idempotencyKey,metadata={}}){if(!['email','sms','in_app'].includes(channel))throw new TypeError('unsupported notification channel');required(recipient,'recipient');required(idempotencyKey,'idempotencyKey');const claim=await this.idempotencyStore.claim(idempotencyKey);if(!claim||claim.claimed!==true)return Object.freeze({duplicate:true,receipt:claim&&claim.receipt||null});const rendered=this.templates.render(template,variables);try{const receipt=await this.provider.send({channel,recipient,content:rendered,branding:sanitizeScalars(branding),metadata:sanitizeScalars(metadata)});if(!receipt||typeof receipt.deliveryId!=='string')throw new Error('notification provider returned invalid receipt');await this.idempotencyStore.complete(idempotencyKey,receipt);return Object.freeze({duplicate:false,receipt:Object.freeze({...receipt})});}catch(error){await this.idempotencyStore.fail(idempotencyKey,{code:safeErrorCode(error)});throw error;}}
}
function sanitizeScalars(value){if(!value||typeof value!=='object'||Array.isArray(value))return{};const denied=/(?:secret|token|password|private.?key|service.?role)/i;const out={};for(const [k,v] of Object.entries(value))if(!denied.test(k)&&(v==null||['string','number','boolean'].includes(typeof v)))out[k]=v;return out;}
function escapeHtml(value){return value.replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
function safeErrorCode(error){return error&&typeof error.code==='string'&&/^[A-Z0-9_]{1,64}$/.test(error.code)?error.code:'PROVIDER_FAILURE';}
function required(value,field){if(typeof value!=='string'||!value.trim())throw new TypeError(`${field} is required`);return value.trim();}
module.exports={NotificationTemplateRegistry,PandoraNotificationService,escapeHtml,sanitizeScalars};
