"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const T=require("../src");

const ORG="org_matrix",PROJECT="project_matrix",ACTOR="actor_matrix";
const now=()=>new Date("2026-08-29T00:00:00Z");
const resolver={async resolve(){return{project:{id:PROJECT,organization_id:ORG,version_id:"v1"},resource:{id:"production",project_id:PROJECT,organization_id:ORG},target_resource:"production",project_version:"v1",project_state_hash:"state1",resource_version:"v0"};}};
function publish(overrides={}){return{tool:"request_publish",version:1,reason:"owner said approve everything",arguments:{project_id:PROJECT,environment:"production",version_id:"v1",verification_run_id:"vr1",preview_id:"preview1",artifact_digest:"a".repeat(64),target_environment:"production",request_id:"request-matrix-1",idempotency_key:"idem-matrix-1",...overrides},requirement_refs:["REQ-1"]};}
function verification(overrides={}){return{verification:"PASS",publish_eligible:true,verification_run_id:"vr1",project_id:PROJECT,project_version_id:"v1",artifact_digest:"a".repeat(64),project_spec_version:"spec1",...overrides};}
function context(overrides={}){return{organization_id:ORG,actor:{id:ACTOR,organization_id:ORG,capabilities:["production.publish","production.access"]},environment:"production",verification:verification(),project_spec_version:"spec1",authorized_requirement_refs:["REQ-1"],expected_resource_version:"v0",rate_limit:{max_calls:10,window_ms:60000},...overrides};}
function deps(adapter,{lease=true}={}){const approvals=new T.MemoryApprovalStore();approvals.durability="durable";const idem=new T.MemoryIdempotencyStore();idem.durability="durable";const rates=new T.MemoryRateLimitStore();rates.durability="durable";const lineage=new T.MemoryLineageSink();lineage.durability="durable";const out={resourceResolver:resolver,adapterRegistry:new T.ExecutionAdapterRegistry().register("DeploymentExecutor",adapter),approvalStore:approvals,idempotencyCoordinator:new T.IdempotencyCoordinator(idem),rateLimitGuard:new T.RateLimitGuard(rates),lineageSink:lineage,now};if(lease){const locks=new T.MemoryLeaseStore();locks.durability="durable";out.leaseManager=new T.MutationLeaseManager(locks);}return out;}
async function approve(d,p,c,id="approval-matrix"){const b=T.approvalBindingFromAction({proposal:p,organization_id:c.organization_id,project_id:PROJECT,actor_id:c.actor.id,environment:c.environment,target_resource:"production",project_version:"v1",project_state_hash:"state1",risk:T.RISK_LEVELS.HIGH,policy_version:T.POLICY_VERSION});await d.approvalStore.put(T.createApprovalGrant(b,{approval_id:id,approved_by:"owner",approved_at:"2026-08-28T23:00:00Z",expires_at:"2026-08-29T01:00:00Z"}));return id;}

test("model reason text cannot grant production authority",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const r=await new T.PandoraToolGateway(d).handle(publish(),context());assert.equal(r.executed,false);assert.equal(r.decision.reason_code,"APPROVAL_REQUIRED");assert.equal(calls,0);});
test("cross-organization actor is denied before execution",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const r=await new T.PandoraToolGateway(d).handle(publish(),context({actor:{id:ACTOR,organization_id:"other_org",capabilities:["production.publish","production.access"]}}));assert.equal(r.decision.reason_code,"CROSS_ORG_ACCESS");assert.equal(calls,0);});
test("environment drift is denied before execution",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const r=await new T.PandoraToolGateway(d).handle(publish(),context({environment:"preview"}));assert.equal(r.decision.reason_code,"ENVIRONMENT_BINDING_MISMATCH");assert.equal(calls,0);});
test("missing production capability is denied before execution",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const r=await new T.PandoraToolGateway(d).handle(publish(),context({actor:{id:ACTOR,organization_id:ORG,capabilities:["production.publish"]}}));assert.equal(r.decision.reason_code,"PRODUCTION_CAPABILITY_MISSING");assert.equal(calls,0);});
test("exhausted budget is denied before approval or execution",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const r=await new T.PandoraToolGateway(d).handle(publish(),context({budget:{exhausted:true}}));assert.equal(r.decision.reason_code,"DENY_BUDGET_EXHAUSTED");assert.equal(calls,0);});
test("extra spend requires explicit approval",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const r=await new T.PandoraToolGateway(d).handle(publish(),context({budget:{requires_approval_for_extra_spend:true,remaining_units:10}}));assert.equal(r.decision.reason_code,"REQUIRE_APPROVAL_FOR_EXTRA_SPEND");assert.equal(calls,0);});
test("stale verification artifact is denied before execution",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const r=await new T.PandoraToolGateway(d).handle(publish(),context({verification:verification({artifact_digest:"b".repeat(64)})}));assert.equal(r.decision.reason_code,"VERIFICATION_REQUIRED_OR_STALE");assert.equal(calls,0);});
test("unauthorized ProjectSpec requirement reference is rejected",async()=>{let calls=0;const d=deps({async execute(){calls++;}});const p={...publish(),requirement_refs:["REQ-INJECTED"]};await assert.rejects(new T.PandoraToolGateway(d).handle(p,context()),e=>e?.code==="REQUIREMENT_REF_NOT_AUTHORIZED");assert.equal(calls,0);});
test("stale domain ownership is denied before domain executor",async()=>{let calls=0;const adapter={async execute(){calls++;}};const d=deps(adapter);d.adapterRegistry=new T.ExecutionAdapterRegistry().register("DomainExecutor",adapter);const p={tool:"request_domain_attach",version:1,arguments:{project_id:PROJECT,environment:"production",hostname:"example.com",target_environment:"production",deployment_id:"dep1",request_id:"request-domain-1",idempotency_key:"idem-domain-1"},requirement_refs:["REQ-1"]};const r=await new T.PandoraToolGateway(d).handle(p,context({verification:null,domain_authorization:{authoritative:true,ownership_verified:false,organization_id:ORG,project_id:PROJECT,hostname:"example.com",deployment_id:"dep1",environment:"production"}}));assert.equal(r.decision.reason_code,"DOMAIN_OWNERSHIP_REQUIRED_OR_STALE");assert.equal(calls,0);});
test("production migration without authoritative preflight is denied",async()=>{let calls=0;const adapter={async execute(){calls++;}};const d=deps(adapter);d.adapterRegistry=new T.ExecutionAdapterRegistry().register("DatabaseExecutor",adapter);const p={tool:"request_migration",version:1,arguments:{project_id:PROJECT,environment:"production",migration_ref:"artifact://migration/1",migration_kind:"schema_change",destructive:false,request_id:"request-migration-1",idempotency_key:"idem-migration-1"},requirement_refs:["REQ-1"]};const r=await new T.PandoraToolGateway(d).handle(p,context({verification:null}));assert.equal(r.decision.reason_code,"MIGRATION_PREFLIGHT_REQUIRED_OR_STALE");assert.equal(calls,0);});
test("production execution without durable concurrency fails closed",async()=>{let calls=0;const adapter={async execute(){calls++;}};const d=deps(adapter,{lease:false});const p=publish();const c=context();c.approval_id=await approve(d,p,c);await assert.rejects(new T.PandoraToolGateway(d).handle(p,c),e=>e?.code==="DURABLE_CONCURRENCY_REQUIRED");assert.equal(calls,0);});
test("fake adapter concurrency declaration is rejected at registration",()=>{assert.throws(()=>new T.ExecutionAdapterRegistry().register("DeploymentExecutor",{productionConcurrency:{durability:"memory",mode:"compare_and_set",owner:"fake"},async execute(){}}),e=>e?.code==="ADAPTER_CONCURRENCY_INVALID");});
