"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const {WorkerFDeploymentExecutorAdapter,WorkerFDomainExecutorAdapter,WorkerADatabaseChangeExecutorAdapter}=require("../src/worker-adapters");
const ids={org:"11111111-1111-4111-8111-111111111111",project:"22222222-2222-4222-8222-222222222222",version:"33333333-3333-4333-8333-333333333333",prev:"44444444-4444-4444-8444-444444444444"};
function publishRequest(){return{tool:"request_publish",tool_call_id:"55555555-5555-4555-8555-555555555555",organization_id:ids.org,project_id:ids.project,action_hash:"a".repeat(64),arguments:{version_id:ids.version,preview_id:"preview-1",verification_run_id:"verify-1",artifact_digest:"b".repeat(64),idempotency_key:"idem-publish"}};}
test("Worker F publish bridge binds exact trusted preview and CAS contract",async()=>{let seen;const adapter=new WorkerFDeploymentExecutorAdapter({runtimeManager:{async publishVersion(input,preview){seen={input,preview};return{providerDeploymentId:"dpl_1"};}},contextResolver:{async resolvePublish(){return{preview_id:"preview-1",source_commit:"c".repeat(40),verification_ref:"verify-1",expected_production_version_id:ids.prev,preview_fact:{projectVersionId:ids.version,artifactDigest:"b".repeat(64),sourceCommit:"c".repeat(40)}};}}});const out=await adapter.execute(publishRequest());assert.equal(out.output.providerDeploymentId,"dpl_1");assert.equal(seen.input.authorizationRef,"a".repeat(64));assert.equal(seen.input.expectedProductionVersionId,ids.prev);assert.equal(adapter.productionConcurrency.mode,"compare_and_set");});
test("Worker F publish bridge rejects preview artifact drift before runtime",async()=>{let calls=0;const adapter=new WorkerFDeploymentExecutorAdapter({runtimeManager:{async publishVersion(){calls++;}},contextResolver:{async resolvePublish(){return{preview_id:"preview-1",source_commit:"c".repeat(40),preview_fact:{projectVersionId:ids.version,artifactDigest:"d".repeat(64),sourceCommit:"c".repeat(40)}};}}});await assert.rejects(adapter.execute(publishRequest()),e=>e?.code==="WORKER_F_PREVIEW_ARTIFACT_MISMATCH");assert.equal(calls,0);});
test("Worker F domain bridge carries exact authorized deployment lineage",async()=>{let seen;const adapter=new WorkerFDomainExecutorAdapter({runtimeManager:{async attachDomain(v){seen=v;return{state:"ready"};}},contextResolver:{async resolveDomain(){return{deployment_id:"dpl_1",hostname:"example.com",project_version_id:ids.version,artifact_digest:"b".repeat(64),source_commit:"c".repeat(40),verification_ref:"verify-1",expected_production_version_id:ids.prev};}}});const request={tool:"request_domain_attach",organization_id:ids.org,project_id:ids.project,action_hash:"a".repeat(64),arguments:{hostname:"example.com",deployment_id:"dpl_1",target_environment:"production"}};const out=await adapter.execute(request);assert.equal(out.output.state,"ready");assert.equal(seen.input.projectVersionId,ids.version);assert.equal(seen.domain,"example.com");assert.equal(adapter.productionConcurrency.mode,"claim");});
test("Worker A migration bridge claims approved exact plan and marks applied",async()=>{const events=[];const plan={id:"plan-1",organization_id:ids.org,project_id:ids.project,action_hash:"a".repeat(64),status:"approved"};const store={durability:"durable",async resolveExactPlan(){return plan;},async claimPlan(p,tool){events.push(["claim",tool]);return{...p,status:"executing",execution_tool_call_id:tool};},async markApplied(p,tool){events.push(["applied",tool]);return{...p,status:"applied"};},async markFailed(){events.push(["failed"]);}};const adapter=new WorkerADatabaseChangeExecutorAdapter({planStore:store,migrationExecutor:{async executeMigration(){events.push(["execute"]);return{schema_after:"ok"};}}});const req={tool:"request_migration",tool_call_id:"tool-1",organization_id:ids.org,project_id:ids.project,environment:"production",action_hash:"a".repeat(64),arguments:{migration_ref:"artifact://migration/1",idempotency_key:"idem-1"}};const out=await adapter.execute(req);assert.equal(out.output.status,"applied");assert.deepEqual(events.map(x=>x[0]),["claim","execute","applied"]);assert.equal(adapter.productionConcurrency.owner,"worker-a:pandora_database_change_plans");});
test("ambiguous migration does not falsely mark plan failed",async()=>{let failed=0;const plan={id:"plan-1",organization_id:ids.org,project_id:ids.project,action_hash:"a".repeat(64),status:"approved"};const store={durability:"durable",async resolveExactPlan(){return plan;},async claimPlan(){return{...plan,status:"executing"};},async markApplied(){},async markFailed(){failed++;}};const err=new Error("timeout");err.mutationMayHaveCommitted=true;const adapter=new WorkerADatabaseChangeExecutorAdapter({planStore:store,migrationExecutor:{async executeMigration(){throw err;}}});const req={tool:"request_migration",tool_call_id:"tool-1",organization_id:ids.org,project_id:ids.project,environment:"production",action_hash:"a".repeat(64),arguments:{migration_ref:"artifact://migration/1",idempotency_key:"idem-1"}};await assert.rejects(adapter.execute(req),e=>e===err);assert.equal(failed,0);});
