'use strict';
const {assertIdempotentEventSink,createDomainEvent}=require('../../core/src/events');
const CURRENCY_EXPONENTS=Object.freeze({JPY:0,KRW:0,PHP:2,USD:2,EUR:2,GBP:2,AUD:2,SGD:2,NOK:2});
class Money { constructor(minor,currency){this.minor=toBigInt(minor);this.currency=normalizeCurrency(currency);Object.freeze(this);} add(other){assertSame(this,other);return new Money(this.minor+other.minor,this.currency);} multiply(quantity){if(!Number.isInteger(quantity)||quantity<0)throw new TypeError('quantity must be a non-negative integer');return new Money(this.minor*BigInt(quantity),this.currency);} toJSON(){return{minor:this.minor.toString(),currency:this.currency};} }
class PandoraCommerceService {
 constructor({repository,eventSink}){for(const method of ['getSellableVariants','createOrderAtomic','setOrderStatus'])if(!repository||typeof repository[method]!=='function')throw new TypeError(`commerce repository.${method} is required`);if(repository.transactionSafe!==true)throw new Error('commerce repository must guarantee transaction-safe inventory');assertIdempotentEventSink(eventSink,'commerce event sink');this.repository=repository;this.eventSink=eventSink;}
 async quote({scopeId,items,currency}){const normalized=normalizeCartItems(items);const variants=await this.repository.getSellableVariants({scopeId:required(scopeId,'scopeId'),variantIds:normalized.map(i=>i.variantId)});const map=new Map(variants.map(v=>[String(v.id),v]));let total=new Money(0,currency);const lines=[];for(const item of normalized){const variant=map.get(item.variantId);if(!variant||variant.active===false)throw new Error(`variant unavailable: ${item.variantId}`);const price=new Money(variant.priceMinor,variant.currency);if(price.currency!==normalizeCurrency(currency))throw new Error('mixed-currency cart is forbidden');const line=price.multiply(item.quantity);total=total.add(line);lines.push(Object.freeze({variantId:item.variantId,quantity:item.quantity,unitPrice:price.toJSON(),lineTotal:line.toJSON()}));}return Object.freeze({currency:total.currency,totalMinor:total.minor.toString(),lines:Object.freeze(lines)});}
 async createOrder({project,scopeId,identity,items,currency,idempotencyKey}){const quote=await this.quote({scopeId,items,currency});const order=await this.repository.createOrderAtomic({scopeId,customerUserId:required(identity&&identity.userId,'identity.userId'),items:quote.lines.map(l=>({variantId:l.variantId,quantity:l.quantity,unitPriceMinor:l.unitPrice.minor})),currency:quote.currency,totalMinor:quote.totalMinor,idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:'order.created',schemaVersion:'1.0',project,actor:{userId:identity.userId},aggregate:{type:'order',id:String(order.id)},payload:{total_minor:quote.totalMinor,currency:quote.currency,status:String(order.status)},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);return Object.freeze({...order,quote,event});}
 async updateOrderStatus({project,scopeId,identity,orderId,status,idempotencyKey}){if(!['pending','confirmed','fulfilled','cancelled','refunded'].includes(status))throw new TypeError('invalid order status');const order=await this.repository.setOrderStatus({scopeId,orderId:required(orderId,'orderId'),status,actorUserId:required(identity&&identity.userId,'identity.userId'),idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:status==='fulfilled'?'order.completed':'order.status_changed',schemaVersion:'1.0',project,actor:{userId:identity.userId},aggregate:{type:'order',id:String(order.id)},payload:{status},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);return Object.freeze({...order,event});}
}
function normalizeCartItems(items){if(!Array.isArray(items)||items.length===0||items.length>100)throw new TypeError('items must contain 1-100 entries');const seen=new Set();return items.map((item)=>{if(!item||typeof item!=='object')throw new TypeError('cart item must be an object');const variantId=required(item.variantId,'variantId');if(seen.has(variantId))throw new Error(`duplicate variant: ${variantId}`);seen.add(variantId);if(!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>10000)throw new TypeError('quantity must be 1-10000');return Object.freeze({variantId,quantity:item.quantity});});}
function parseDecimalToMinor(value,currency,exponent=CURRENCY_EXPONENTS[normalizeCurrency(currency)]??2){if(typeof value!=='string'||!/^[-+]?\d+(?:\.\d+)?$/.test(value.trim()))throw new TypeError('money decimal must be a string');const negative=value.trim().startsWith('-');const raw=value.trim().replace(/^[-+]/,'');const [whole,fraction='']=raw.split('.');if(fraction.length>exponent)throw new Error('money value has more fractional precision than currency');const minor=BigInt(whole)*10n**BigInt(exponent)+BigInt((fraction+'0'.repeat(exponent)).slice(0,exponent)||'0');return new Money(negative?-minor:minor,currency);}
function toBigInt(v){if(typeof v==='bigint')return v;if(typeof v==='number'&&Number.isSafeInteger(v))return BigInt(v);if(typeof v==='string'&&/^-?\d+$/.test(v))return BigInt(v);throw new TypeError('money minor units must be an integer');}
function normalizeCurrency(v){if(typeof v!=='string'||!/^[A-Z]{3}$/.test(v.toUpperCase()))throw new TypeError('currency must be ISO-like 3-letter code');return v.toUpperCase();}function assertSame(a,b){if(a.currency!==b.currency)throw new Error('currency mismatch');}function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={CURRENCY_EXPONENTS,Money,PandoraCommerceService,normalizeCartItems,parseDecimalToMinor};
