'use strict';
const ALLOWED_FIELDS=Object.freeze(['displayName','email','phone','locale','timezone','marketingOptIn','preferences']);
const SENSITIVE=/(?:password|secret|token|medical|diagnosis|religion|race|ethnic|sexual|criminal|biometric|government.?id|passport|ssn|bank|card)/i;
class PandoraCustomerProfileService {
  constructor({repository,authorization}){for(const m of ['getProfile','upsertProfile'])if(!repository||typeof repository[m]!=='function')throw new TypeError(`profile repository.${m} is required`);if(!authorization||typeof authorization.assertAllowed!=='function')throw new TypeError('profile authorization.assertAllowed is required');this.repository=repository;this.authorization=authorization;}
  async getSelf({scopeId,identity}){const scope=required(scopeId,'scopeId'),userId=required(identity&&identity.userId,'identity.userId');const row=await this.repository.getProfile({scopeId:scope,userId});return row?publicProfile(row):null;}
  async updateSelf({scopeId,identity,patch,idempotencyKey}){const scope=required(scopeId,'scopeId'),userId=required(identity&&identity.userId,'identity.userId');const clean=normalizePatch(patch);return this.repository.upsertProfile({scopeId:scope,userId,patch:clean,actorUserId:userId,idempotencyKey:required(idempotencyKey,'idempotencyKey')});}
  async getForAdmin({scopeId,identity,userId}){const scope=required(scopeId,'scopeId');await this.authorization.assertAllowed({userId:required(identity&&identity.userId,'identity.userId'),tenantId:scope,permission:'users.read'});const row=await this.repository.getProfile({scopeId:scope,userId:required(userId,'userId')});return row?publicProfile(row):null;}
}
function normalizePatch(value){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('profile patch must be an object');const out={};for(const [key,v] of Object.entries(value)){if(SENSITIVE.test(key))throw new Error(`sensitive profile field is blocked: ${key}`);if(!ALLOWED_FIELDS.includes(key))throw new Error(`profile field is not allowed: ${key}`);if(key==='marketingOptIn'){if(typeof v!=='boolean')throw new TypeError('marketingOptIn must be boolean');out[key]=v;continue;}if(key==='preferences'){out[key]=boundedPreferences(v);continue;}if(v==null){out[key]=null;continue;}if(typeof v!=='string')throw new TypeError(`${key} must be text`);const max=key==='displayName'?160:key==='phone'?64:320;if(v.length>max)throw new TypeError(`${key} is too long`);if(key==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw new TypeError('email is invalid');if(key==='timezone')iana(v);out[key]=v.trim();}return Object.freeze(out);}
function boundedPreferences(value){if(value==null)return Object.freeze({});if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('preferences must be an object');const entries=Object.entries(value);if(entries.length>32)throw new TypeError('preferences are too broad');const out={};for(const [k,v] of entries){if(SENSITIVE.test(k)||!/^[a-z][a-z0-9_.-]{0,63}$/.test(k))throw new Error(`preference key is not allowed: ${k}`);if(!['string','number','boolean'].includes(typeof v))throw new TypeError(`preference ${k} must be scalar`);if(typeof v==='string'&&v.length>300)throw new TypeError(`preference ${k} is too long`);out[k]=v;}return Object.freeze(out);}
function publicProfile(row){const out={userId:String(row.userId)};for(const k of ALLOWED_FIELDS)if(k in row)out[k]=k==='preferences'?boundedPreferences(row[k]):row[k];return Object.freeze(out);}
function iana(v){try{new Intl.DateTimeFormat('en-US',{timeZone:v}).format(new Date());}catch{throw new TypeError('timezone must be a valid IANA timezone');}}
function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={ALLOWED_FIELDS,PandoraCustomerProfileService,boundedPreferences,normalizePatch,publicProfile};
