-- Operations Room durable scheduling foundation. Generated by the pinned Supabase CLI.
-- No worker registration, project activation, provider mutation, cron job or credential grant is seeded.
create table private.pandora_ops_workspaces (
 organization_id uuid not null references public.organizations(id),
 -- pandora_projects is the active security-invoker identity view, not a FK target.
 -- Keep historical identity here; initialization/claim/owner admission revalidate current scope.
 project_id uuid not null,
 paused boolean not null default true,
 no_production boolean not null default true,
 revision bigint not null default 0 check(revision>=0),
 max_concurrency integer not null default 1 check(max_concurrency between 1 and 256),
 total_budget_micros bigint not null default 0 check(total_budget_micros>=0),
 reserved_micros bigint not null default 0 check(reserved_micros>=0),
 spent_micros bigint not null default 0 check(spent_micros>=0),
 updated_at timestamptz not null default clock_timestamp(),
 primary key(organization_id,project_id),
 check(reserved_micros+spent_micros<=total_budget_micros)
);
create table private.pandora_ops_workers (
 organization_id uuid not null, project_id uuid not null,
 worker_key text not null check(worker_key ~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,119}$'),
 principal_key text not null check(length(principal_key) between 1 and 200),
 engine text not null check(engine='chatgpt'),
 lanes text[] not null check(cardinality(lanes)>0 and lanes <@ array['web','backend','mobile','growth','reliability','release','ares']),
 capabilities text[] not null default '{}',
 capacity integer not null check(capacity between 1 and 32),
 acknowledged boolean not null default false,
 connected boolean not null default false,
 health text not null default 'offline' check(health in ('ready','degraded','offline')),
 heartbeat_at timestamptz,
 registration_receipt text not null check(length(registration_receipt) between 1 and 1000),
 primary key(organization_id,project_id,worker_key),
 foreign key(organization_id,project_id) references private.pandora_ops_workspaces
);
create table private.pandora_ops_tasks (
 organization_id uuid not null, project_id uuid not null,
 task_key text not null check(task_key ~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,119}$'),
 spec jsonb not null check(jsonb_typeof(spec)='object' and spec->>'id'=task_key),
 spec_digest text not null check(spec_digest ~ '^[a-f0-9]{64}$'),
 status text not null default 'queued' check(status in ('queued','claimed','implementing','handed_off','verifying','blocked','failed','cancelled','complete')),
 revision bigint not null default 0 check(revision>=0),
 attempts integer not null default 0 check(attempts>=0),
 generation bigint not null default 0 check(generation>=0),
 cancel_requested boolean not null default false,
 queued_at timestamptz not null default clock_timestamp(),
 builder_worker_key text, builder_principal_key text,
 head_sha text check(head_sha is null or head_sha ~ '^[a-f0-9]{40}$'),
 handoff jsonb, verification jsonb,
 primary key(organization_id,project_id,task_key),
 foreign key(organization_id,project_id) references private.pandora_ops_workspaces
);
create table private.pandora_ops_dependencies (
 organization_id uuid not null, project_id uuid not null, task_key text not null, dependency_key text not null,
 primary key(organization_id,project_id,task_key,dependency_key),
 foreign key(organization_id,project_id,task_key) references private.pandora_ops_tasks,
 foreign key(organization_id,project_id,dependency_key) references private.pandora_ops_tasks,
 check(task_key<>dependency_key)
);
create table private.pandora_ops_leases (
 id uuid primary key default gen_random_uuid(),
 organization_id uuid not null, project_id uuid not null, task_key text not null, worker_key text not null,
 generation bigint not null check(generation>0),
 claim_request_key text not null,
 state text not null default 'held' check(state in ('held','dispatching','running','reconcile','released')),
 resources jsonb not null check(jsonb_typeof(resources)='array'),
 reserved_micros bigint not null check(reserved_micros>=0),
 charged_micros bigint check(charged_micros between 0 and reserved_micros),
 settlement_receipt text,
 created_at timestamptz not null default clock_timestamp(), expires_at timestamptz not null,
 unique(organization_id,project_id,task_key,generation),
 unique(organization_id,project_id,claim_request_key),
 foreign key(organization_id,project_id,task_key) references private.pandora_ops_tasks,
 foreign key(organization_id,project_id,worker_key) references private.pandora_ops_workers
);
create table private.pandora_ops_dispatch_outbox (
 id uuid primary key default gen_random_uuid(), lease_id uuid not null unique references private.pandora_ops_leases(id),
 state text not null default 'pending' check(state in ('pending','sending','acknowledged','reconcile')),
 acknowledgement jsonb, created_at timestamptz not null default clock_timestamp()
);
create table private.pandora_ops_events (
 id bigint generated always as identity primary key,
 organization_id uuid not null,project_id uuid not null,
 event_key text not null, task_key text, event_type text not null,
 receipt_ref text, occurred_at timestamptz not null default clock_timestamp(),
 unique(organization_id,project_id,event_key),
 foreign key(organization_id,project_id) references private.pandora_ops_workspaces
);
create index pandora_ops_runnable_idx on private.pandora_ops_tasks(organization_id,project_id,status,queued_at);
create index pandora_ops_active_leases_idx on private.pandora_ops_leases(organization_id,project_id,worker_key) where state<>'released';
create index pandora_ops_expiry_idx on private.pandora_ops_leases(expires_at) where state in ('held','dispatching','running');
create index pandora_ops_dependency_reverse_idx on private.pandora_ops_dependencies(organization_id,project_id,dependency_key);
create index pandora_ops_event_scope_idx on private.pandora_ops_events(organization_id,project_id,id);
-- State is service-owned. No model/browser receives direct table write access.
alter table private.pandora_ops_workspaces enable row level security;
alter table private.pandora_ops_workers enable row level security;
alter table private.pandora_ops_tasks enable row level security;
alter table private.pandora_ops_dependencies enable row level security;
alter table private.pandora_ops_leases enable row level security;
alter table private.pandora_ops_dispatch_outbox enable row level security;
alter table private.pandora_ops_events enable row level security;
revoke all on private.pandora_ops_workspaces,private.pandora_ops_workers,private.pandora_ops_tasks,private.pandora_ops_dependencies,private.pandora_ops_leases,private.pandora_ops_dispatch_outbox,private.pandora_ops_events from public,anon,authenticated,service_role;

create function private.pandora_ops_event_v1(p_org uuid,p_project uuid,p_key text,p_task text,p_type text,p_receipt text default null)
returns void language sql security definer set search_path='' as $$
 insert into private.pandora_ops_events(organization_id,project_id,event_key,task_key,event_type,receipt_ref)
 values(p_org,p_project,p_key,p_task,p_type,p_receipt) on conflict(organization_id,project_id,event_key) do nothing;
$$;
create function private.pandora_ops_immutable_event_v1() returns trigger language plpgsql set search_path='' as $$
begin raise exception 'OPS_EVENT_IMMUTABLE' using errcode='55000'; end; $$;
create trigger pandora_ops_event_immutable before update or delete on private.pandora_ops_events for each row execute function private.pandora_ops_immutable_event_v1();

create function private.pandora_ops_validate_spec_v1(s jsonb) returns void language plpgsql set search_path='' as $$
declare r jsonb; k text; v text; trim_chars text := E' \t\n\r\f\013'||chr(160)||chr(5760)||chr(8192)||chr(8193)||chr(8194)||chr(8195)||chr(8196)||chr(8197)||chr(8198)||chr(8199)||chr(8200)||chr(8201)||chr(8202)||chr(8232)||chr(8233)||chr(8239)||chr(8287)||chr(12288)||chr(65279);
begin
 if jsonb_typeof(s) is distinct from 'object' or not(s ?& array['id','title','lane','priority','dependsOn','resources','requiredCapabilities','maxCostMicros','maxDurationSeconds','maxAttempts','risk','acceptance','source','verificationProfile']) then raise exception 'OPS_SPEC_INVALID'; end if;
 for k in select jsonb_object_keys(s) loop if k<>all(array['id','title','lane','priority','dependsOn','resources','requiredCapabilities','maxCostMicros','maxDurationSeconds','maxAttempts','risk','acceptance','source','verificationProfile']) then raise exception 'OPS_SPEC_UNKNOWN_FIELD'; end if; end loop;
 if not coalesce(s->>'id' ~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,119}$',false) or not coalesce(length(s->>'title') between 1 and 240,false) then raise exception 'OPS_SPEC_ID_INVALID'; end if;
 if not coalesce(s->>'lane'=any(array['web','backend','mobile','growth','reliability','release','ares']),false) or not coalesce(s->>'risk'=any(array['read','source','preview','production','destructive']),false) then raise exception 'OPS_SPEC_CLASS_INVALID'; end if;
 if jsonb_typeof(s->'title') is distinct from 'string' or (s->>'title')<>btrim(s->>'title',trim_chars) or (s->>'title') ~ '[\x01-\x1f]' then raise exception 'OPS_SPEC_TITLE_INVALID'; end if;
 for k in select unnest(array['priority','maxAttempts','maxDurationSeconds','maxCostMicros']) loop if jsonb_typeof(s->k) is distinct from 'number' then raise exception 'OPS_SPEC_BUDGET_INVALID'; end if; end loop;
 if not coalesce((s->>'priority') ~ '^[0-3]$',false) or not coalesce((s->>'maxAttempts') ~ '^[1-3]$',false) or not coalesce((s->>'maxDurationSeconds') ~ '^[0-9]{1,4}$' and (s->>'maxDurationSeconds')::integer between 1 and 3600,false) or not coalesce((s->>'maxCostMicros') ~ '^[0-9]{1,13}$' and (s->>'maxCostMicros')::bigint<=1000000000000,false) then raise exception 'OPS_SPEC_BUDGET_INVALID'; end if;
 if jsonb_typeof(s->'resources') is distinct from 'array' or jsonb_typeof(s->'dependsOn') is distinct from 'array' or jsonb_typeof(s->'requiredCapabilities') is distinct from 'array' or jsonb_typeof(s->'acceptance') is distinct from 'array' then raise exception 'OPS_SPEC_ARRAY_INVALID'; end if;
 if jsonb_array_length(s->'resources')>64 or jsonb_array_length(s->'dependsOn')>500 or jsonb_array_length(s->'requiredCapabilities')>64 or jsonb_array_length(s->'acceptance') not between 1 and 32 then raise exception 'OPS_SPEC_ARRAY_LIMIT'; end if;
 for r in select value from jsonb_array_elements(s->'resources') loop
  if jsonb_typeof(r) is distinct from 'object' or not coalesce(length(r->>'key') between 1 and 400 and r->>'key' ~ '^[A-Za-z0-9][A-Za-z0-9_.:/-]*$',false) or position('..' in r->>'key')>0 or position('//' in r->>'key')>0 or right(r->>'key',1)='/' or not coalesce(r->>'mode' in ('read','write'),false) or (select count(*) from jsonb_object_keys(r))<>2 then raise exception 'OPS_RESOURCE_INVALID'; end if;
 end loop;
 if (select count(*) from jsonb_array_elements(s->'resources'))<>(select count(distinct entry.value->>'key') from jsonb_array_elements(s->'resources') entry(value)) then raise exception 'OPS_RESOURCE_DUPLICATE'; end if;
 if s->>'risk'<>'read' and not exists(select 1 from jsonb_array_elements(s->'resources') entry(value) where entry.value->>'mode'='write') then raise exception 'OPS_WRITE_RESOURCE_REQUIRED'; end if;
 for r in select value from jsonb_array_elements(s->'dependsOn') loop if jsonb_typeof(r)<>'string' or not coalesce(r#>>'{}' ~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,119}$',false) then raise exception 'OPS_DEPENDENCY_INVALID'; end if; end loop;
 for r in select value from jsonb_array_elements(s->'requiredCapabilities') loop if jsonb_typeof(r)<>'string' or not coalesce(r#>>'{}' ~ '^[a-z][a-z0-9._-]{1,100}$',false) then raise exception 'OPS_CAPABILITY_INVALID'; end if; end loop;
 if not coalesce(s->>'verificationProfile'=any(array['static_site','web_application','mobile_application','backend_service','business_system','automation','database_change','production_release']),false) or (s->>'risk' in ('production','destructive') and s->>'verificationProfile'<>'production_release') then raise exception 'OPS_VERIFICATION_PROFILE_INVALID'; end if;
 for k in select unnest(array['dependsOn','requiredCapabilities','acceptance']) loop if (select count(*) from jsonb_array_elements(s->k))<>(select count(distinct value) from jsonb_array_elements(s->k)) then raise exception 'OPS_SPEC_ARRAY_DUPLICATE'; end if; end loop;
 for r in select value from jsonb_array_elements(s->'acceptance') loop v:=r#>>'{}'; if jsonb_typeof(r)<>'string' or not coalesce(length(v) between 1 and 500,false) or v<>btrim(v,trim_chars) or v ~ '[\x01-\x1f]' then raise exception 'OPS_ACCEPTANCE_INVALID'; end if; end loop;
 if s->'source'<>'null'::jsonb then
  if jsonb_typeof(s->'source') is distinct from 'object' then raise exception 'OPS_SOURCE_INVALID'; end if;
  if not(s->'source' ?& array['repository','baseSha']) or (select count(*) from jsonb_object_keys(s->'source'))<>2 then raise exception 'OPS_SOURCE_INVALID'; end if;
  if not coalesce(s#>>'{source,repository}'=any(array['pandora-rvw-314296438-20260820/pandoras-box','pandora-rvw-314296438-20260820/pandoras-box-memory']),false) or not coalesce(s#>>'{source,baseSha}' ~ '^[a-f0-9]{40}$',false) then raise exception 'OPS_SOURCE_INVALID'; end if;
 elsif s->>'risk'='source' then raise exception 'OPS_EXACT_SOURCE_REQUIRED'; end if;
end; $$;

create function public.pandora_ops_initialize_v1(p_organization_id uuid,p_project_id uuid,p_budget_micros bigint,p_max_concurrency integer default 1)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
 if not exists(select 1 from public.pandora_projects where id=p_project_id and organization_id=p_organization_id and status<>'archived') then raise exception 'OPS_PROJECT_SCOPE_DENIED' using errcode='42501'; end if;
 if p_budget_micros is null or p_budget_micros<0 or p_max_concurrency is null then raise exception 'OPS_BUDGET_REQUIRED'; end if;
 insert into private.pandora_ops_workspaces(organization_id,project_id,total_budget_micros,max_concurrency) values(p_organization_id,p_project_id,p_budget_micros,p_max_concurrency) on conflict do nothing;
 return jsonb_build_object('initialized',true,'activation','explicit_control_required');
end; $$;

create function public.pandora_ops_ingest_v1(p_organization_id uuid,p_project_id uuid,p_tasks jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare s jsonb; old_digest text; h text;
begin
 perform 1 from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 if not found then raise exception 'OPS_WORKSPACE_MISSING'; end if;
 if jsonb_typeof(p_tasks) is distinct from 'array' or jsonb_array_length(p_tasks) not between 1 and 5000 then raise exception 'OPS_BATCH_INVALID'; end if;
 if (select count(*) from jsonb_array_elements(p_tasks))<>(select count(distinct x->>'id') from jsonb_array_elements(p_tasks) x) then raise exception 'OPS_DUPLICATE_TASK'; end if;
 for s in select value from jsonb_array_elements(p_tasks) loop
  perform private.pandora_ops_validate_spec_v1(s);
  h:=encode(extensions.digest(convert_to(s::text,'UTF8'),'sha256'),'hex');
  select spec_digest into old_digest from private.pandora_ops_tasks where organization_id=p_organization_id and project_id=p_project_id and task_key=s->>'id';
  if found and old_digest<>h then raise exception 'OPS_TASK_SPEC_CONFLICT'; end if;
  insert into private.pandora_ops_tasks(organization_id,project_id,task_key,spec,spec_digest) values(p_organization_id,p_project_id,s->>'id',s,h) on conflict do nothing;
 end loop;
 for s in select value from jsonb_array_elements(p_tasks) loop
  insert into private.pandora_ops_dependencies(organization_id,project_id,task_key,dependency_key) select p_organization_id,p_project_id,s->>'id',d from jsonb_array_elements_text(s->'dependsOn') d on conflict do nothing;
 end loop;
 if exists(with recursive reach(a,b) as (
  select task_key,dependency_key from private.pandora_ops_dependencies where organization_id=p_organization_id and project_id=p_project_id
  union select r.a,d.dependency_key from reach r join private.pandora_ops_dependencies d on d.task_key=r.b and d.organization_id=p_organization_id and d.project_id=p_project_id
 ) select 1 from reach where a=b) then raise exception 'OPS_DEPENDENCY_CYCLE'; end if;
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'ingest:'||encode(extensions.digest(convert_to(p_tasks::text,'UTF8'),'sha256'),'hex'),null,'tasks_ingested');
 return jsonb_build_object('accepted',jsonb_array_length(p_tasks));
end; $$;

create function public.pandora_ops_register_worker_v1(p_organization_id uuid,p_project_id uuid,p_worker_key text,p_principal_key text,p_lanes text[],p_capabilities text[],p_capacity integer,p_receipt_ref text)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
 -- Called only by a separately authenticated worker-registration adapter, never by a model or owner-browser route.
 insert into private.pandora_ops_workers(organization_id,project_id,worker_key,principal_key,engine,lanes,capabilities,capacity,acknowledged,connected,health,heartbeat_at,registration_receipt)
 values(p_organization_id,p_project_id,p_worker_key,p_principal_key,'chatgpt',p_lanes,p_capabilities,p_capacity,true,true,'ready',clock_timestamp(),p_receipt_ref);
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'worker:'||p_worker_key,null,'worker_acknowledged',p_receipt_ref);
 return jsonb_build_object('registered',true);
end; $$;

create function public.pandora_ops_heartbeat_v1(p_organization_id uuid,p_project_id uuid,p_worker_key text,p_principal_key text,p_connected boolean,p_health text)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
 update private.pandora_ops_workers set connected=p_connected,health=p_health,heartbeat_at=clock_timestamp() where organization_id=p_organization_id and project_id=p_project_id and worker_key=p_worker_key and principal_key=p_principal_key;
 if not found then raise exception 'OPS_WORKER_IDENTITY_MISMATCH' using errcode='42501'; end if;
 return jsonb_build_object('heartbeat',true);
end; $$;

create function public.pandora_ops_claim_v1(p_organization_id uuid,p_project_id uuid,p_task_key text,p_worker_key text,p_task_revision bigint,p_control_revision bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare w private.pandora_ops_workspaces%rowtype; t private.pandora_ops_tasks%rowtype; k private.pandora_ops_workers%rowtype; l private.pandora_ops_leases%rowtype; request_key text; cost bigint;
begin
 perform pg_advisory_xact_lock(hashtextextended('pandora-operations:'||p_organization_id::text,0));
 perform 1 from public.pandora_projects where id=p_project_id and organization_id=p_organization_id and status<>'archived' for share;
 if not found then raise exception 'OPS_PROJECT_SCOPE_DENIED' using errcode='42501'; end if;
 select * into w from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 if not found then raise exception 'OPS_WORKSPACE_MISSING'; end if;
 if w.paused or w.revision is distinct from p_control_revision then return jsonb_build_object('claimed',false,'reason','control_changed_or_paused'); end if;
 request_key:=p_task_key||':'||p_worker_key||':'||p_task_revision::text;
 select * into l from private.pandora_ops_leases where organization_id=p_organization_id and project_id=p_project_id and claim_request_key=request_key;
 if found then
  if l.state not in ('held','dispatching','running') or l.expires_at<=clock_timestamp() then return jsonb_build_object('claimed',false,'reason','claim_requires_reconciliation'); end if;
  return jsonb_build_object('claimed',true,'leaseId',l.id,'taskId',l.task_key,'workerId',l.worker_key,'generation',l.generation,'expiresAt',l.expires_at,'replayed',true);
 end if;
 select * into t from private.pandora_ops_tasks where organization_id=p_organization_id and project_id=p_project_id and task_key=p_task_key for update;
 if not found or t.status<>'queued' or t.revision is distinct from p_task_revision or t.cancel_requested then return jsonb_build_object('claimed',false,'reason','task_changed'); end if;
 if w.no_production and t.spec->>'risk' in ('production','destructive') then return jsonb_build_object('claimed',false,'reason','production_paused'); end if;
 select * into k from private.pandora_ops_workers where organization_id=p_organization_id and project_id=p_project_id and worker_key=p_worker_key;
 if not found or not k.acknowledged or not k.connected or k.health<>'ready' or k.heartbeat_at is null or k.heartbeat_at<clock_timestamp()-interval '60 seconds' or not(t.spec->>'lane'=any(k.lanes)) or not(array(select jsonb_array_elements_text(t.spec->'requiredCapabilities'))<@k.capabilities) then return jsonb_build_object('claimed',false,'reason','worker_unavailable'); end if;
 if exists(select 1 from private.pandora_ops_dependencies d join private.pandora_ops_tasks q on q.organization_id=d.organization_id and q.project_id=d.project_id and q.task_key=d.dependency_key where d.organization_id=p_organization_id and d.project_id=p_project_id and d.task_key=p_task_key and q.status<>'complete') then return jsonb_build_object('claimed',false,'reason','dependency_not_verified'); end if;
 if t.attempts>=(t.spec->>'maxAttempts')::integer then return jsonb_build_object('claimed',false,'reason','attempt_budget_exhausted'); end if;
 if (select count(*) from private.pandora_ops_leases where organization_id=p_organization_id and project_id=p_project_id and state<>'released')>=w.max_concurrency or (select count(*) from private.pandora_ops_leases where organization_id=p_organization_id and project_id=p_project_id and worker_key=p_worker_key and state<>'released')>=k.capacity then return jsonb_build_object('claimed',false,'reason','capacity_backpressure'); end if;
 -- Expired/ambiguous leases still conflict until authoritative reconciliation releases them.
 if exists(select 1 from private.pandora_ops_leases lease cross join lateral jsonb_array_elements(lease.resources) held cross join lateral jsonb_array_elements(t.spec->'resources') wanted where lease.organization_id=p_organization_id and lease.state<>'released' and (held->>'mode'='write' or wanted->>'mode'='write') and (held->>'key'=wanted->>'key' or left(held->>'key',length(wanted->>'key')+1)=(wanted->>'key')||'/' or left(wanted->>'key',length(held->>'key')+1)=(held->>'key')||'/')) then return jsonb_build_object('claimed',false,'reason','resource_conflict'); end if;
 cost:=(t.spec->>'maxCostMicros')::bigint;
 if cost>w.total_budget_micros-w.reserved_micros-w.spent_micros then return jsonb_build_object('claimed',false,'reason','cost_budget_exhausted'); end if;
 update private.pandora_ops_tasks set status='claimed',revision=revision+1,attempts=attempts+1,generation=generation+1,builder_worker_key=k.worker_key,builder_principal_key=k.principal_key where organization_id=p_organization_id and project_id=p_project_id and task_key=p_task_key returning * into t;
 insert into private.pandora_ops_leases(organization_id,project_id,task_key,worker_key,generation,claim_request_key,resources,reserved_micros,expires_at) values(p_organization_id,p_project_id,p_task_key,p_worker_key,t.generation,request_key,t.spec->'resources',cost,clock_timestamp()+make_interval(secs=>(t.spec->>'maxDurationSeconds')::integer)) returning * into l;
 update private.pandora_ops_workspaces set reserved_micros=reserved_micros+cost,updated_at=clock_timestamp() where organization_id=p_organization_id and project_id=p_project_id;
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'claim:'||l.id::text,p_task_key,'task_claimed');
 return jsonb_build_object('claimed',true,'leaseId',l.id,'taskId',t.task_key,'workerId',k.worker_key,'generation',t.generation,'expiresAt',l.expires_at,'replayed',false);
end; $$;

create function public.pandora_ops_dispatch_v1(p_organization_id uuid,p_project_id uuid,p_lease_id uuid,p_generation bigint,p_ack jsonb default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare l private.pandora_ops_leases%rowtype; o private.pandora_ops_dispatch_outbox%rowtype; w private.pandora_ops_workspaces%rowtype; t private.pandora_ops_tasks%rowtype; can_send boolean:=false;
begin
 -- A claim is not delivery authority after project archival or removal. Covers send intent and ACK.
 perform 1 from public.pandora_projects where id=p_project_id and organization_id=p_organization_id and status<>'archived' for share;
 if not found then raise exception 'OPS_PROJECT_SCOPE_DENIED' using errcode='42501'; end if;
 select * into w from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 select * into l from private.pandora_ops_leases where id=p_lease_id and organization_id=p_organization_id and project_id=p_project_id for update;
 if not found or l.generation is distinct from p_generation or l.state not in ('held','dispatching','running') or l.expires_at<=clock_timestamp() then raise exception 'OPS_LEASE_FENCED'; end if;
 select * into t from private.pandora_ops_tasks where organization_id=p_organization_id and project_id=p_project_id and task_key=l.task_key;
 if w.paused or t.cancel_requested or (w.no_production and t.spec->>'risk' in ('production','destructive')) then raise exception 'OPS_EXECUTION_PAUSED'; end if;
 insert into private.pandora_ops_dispatch_outbox(lease_id) values(l.id) on conflict do nothing;
 select * into o from private.pandora_ops_dispatch_outbox where lease_id=l.id for update;
 if p_ack is not null then
  if o.state not in ('sending','acknowledged') then raise exception 'OPS_ACK_WITHOUT_DISPATCH_INTENT'; end if;
  if p_ack->>'dispatchId' is distinct from o.id::text or p_ack->>'taskId' is distinct from l.task_key or p_ack->>'workerId' is distinct from l.worker_key or p_ack->>'generation' is distinct from p_generation::text or p_ack->'accepted' is distinct from 'true'::jsonb then raise exception 'OPS_WORKER_ACK_MISMATCH'; end if;
  if o.acknowledgement is not null and o.acknowledgement<>p_ack then raise exception 'OPS_ACK_CONFLICT'; end if;
  update private.pandora_ops_dispatch_outbox set state='acknowledged',acknowledgement=p_ack where id=o.id;
  update private.pandora_ops_leases set state='running' where id=l.id;
  update private.pandora_ops_tasks set status='implementing' where organization_id=p_organization_id and project_id=p_project_id and task_key=l.task_key;
  perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'dispatch-ack:'||o.id,l.task_key,'worker_started',o.id::text);
 else
  if o.state='pending' then
   update private.pandora_ops_dispatch_outbox set state='sending' where id=o.id;
   can_send:=true;
  end if;
  update private.pandora_ops_leases set state=case when state='held' then 'dispatching' else state end where id=l.id;
  perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'dispatch-intent:'||o.id,l.task_key,'dispatch_prepared',o.id::text);
 end if;
 return jsonb_build_object('dispatchId',o.id,'acknowledged',p_ack is not null or o.state='acknowledged','canSend',can_send);
end; $$;

create function public.pandora_ops_reconcile_required_v1(p_organization_id uuid,p_project_id uuid,p_lease_id uuid,p_generation bigint,p_reason text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare l private.pandora_ops_leases%rowtype;
begin
 perform 1 from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 select * into l from private.pandora_ops_leases where id=p_lease_id and organization_id=p_organization_id and project_id=p_project_id for update;
 if not found or l.generation is distinct from p_generation or l.state='released' then raise exception 'OPS_LEASE_FENCED'; end if;
 if p_reason is null or p_reason !~ '^[A-Z_]{3,80}$' then raise exception 'OPS_REASON_INVALID'; end if;
 update private.pandora_ops_leases set state='reconcile' where id=l.id;
 update private.pandora_ops_tasks set status='blocked' where organization_id=p_organization_id and project_id=p_project_id and task_key=l.task_key;
 update private.pandora_ops_dispatch_outbox set state='reconcile' where lease_id=l.id;
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'reconcile:'||l.id,l.task_key,'reconciliation_required',p_reason);
 return jsonb_build_object('reconciliationRequired',true,'leaseRetained',true);
end; $$;

create function public.pandora_ops_control_v1(p_organization_id uuid,p_project_id uuid,p_expected_revision bigint,p_action text,p_task_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare w private.pandora_ops_workspaces%rowtype;
begin
 select * into w from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 if not found or w.revision is distinct from p_expected_revision then raise exception 'OPS_CONTROL_REVISION_CONFLICT'; end if;
 if p_action='pause' then w.paused:=true;
 elsif p_action='resume' then w.paused:=false;
 elsif p_action='no_production' then w.no_production:=true;
 elsif p_action='cancel_task' then
  update private.pandora_ops_tasks set cancel_requested=true,status=case when status in ('queued','handed_off','verifying') then 'cancelled' else status end,revision=revision+1 where organization_id=p_organization_id and project_id=p_project_id and task_key=p_task_key and status not in ('complete','cancelled','failed');
  if not found then raise exception 'OPS_TASK_NOT_CANCELLABLE'; end if;
 else raise exception 'OPS_CONTROL_NOT_REGISTERED'; end if;
 update private.pandora_ops_workspaces set paused=w.paused,no_production=w.no_production,revision=revision+1,updated_at=clock_timestamp() where organization_id=p_organization_id and project_id=p_project_id returning * into w;
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'control:'||w.revision::text,p_task_key,'owner_'||p_action);
 return jsonb_build_object('revision',w.revision,'paused',w.paused,'noProduction',w.no_production);
end; $$;

create function public.pandora_ops_snapshot_v1(p_organization_id uuid,p_project_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare w private.pandora_ops_workspaces%rowtype; result jsonb;
begin
 select * into w from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id;
 if not found then raise exception 'OPS_WORKSPACE_MISSING'; end if;
 result:=jsonb_build_object(
 'controls',jsonb_build_object('revision',w.revision,'paused',w.paused,'noProduction',w.no_production,'maxConcurrency',w.max_concurrency),
 'budget',jsonb_build_object('availableMicros',w.total_budget_micros-w.reserved_micros-w.spent_micros),
 'foreignLeases',coalesce((select jsonb_agg(jsonb_build_object('resources',resources)) from private.pandora_ops_leases where organization_id=p_organization_id and project_id<>p_project_id and state<>'released'),'[]'::jsonb),
 'tasks',coalesce((select jsonb_agg(jsonb_build_object('spec',spec,'status',status,'attempt',attempts,'revision',revision,'generation',generation,'queuedAt',floor(extract(epoch from queued_at)*1000),'cancelRequested',cancel_requested,'headSha',head_sha,'specDigest',spec_digest,'pullRequest',handoff->'pullRequest')) from private.pandora_ops_tasks where organization_id=p_organization_id and project_id=p_project_id),'[]'::jsonb),
 'workers',coalesce((select jsonb_agg(jsonb_build_object('id',worker_key,'engine',engine,'lanes',lanes,'capabilities',capabilities,'capacity',capacity,'acknowledged',acknowledged,'connected',connected,'health',health,'heartbeatAt',floor(extract(epoch from heartbeat_at)*1000))) from private.pandora_ops_workers where organization_id=p_organization_id and project_id=p_project_id),'[]'::jsonb),
 'leases',coalesce((select jsonb_agg(jsonb_build_object('taskId',task_key,'workerId',worker_key,'generation',generation,'resources',resources,'state',state,'expiresAt',expires_at)) from private.pandora_ops_leases where organization_id=p_organization_id and project_id=p_project_id and state<>'released'),'[]'::jsonb));
 return result;
end; $$;

-- Function ACLs are explicit. Worker registration/claims are never granted to browser roles.
revoke all on function private.pandora_ops_event_v1(uuid,uuid,text,text,text,text),private.pandora_ops_immutable_event_v1(),private.pandora_ops_validate_spec_v1(jsonb) from public,anon,authenticated,service_role;
revoke all on function public.pandora_ops_initialize_v1(uuid,uuid,bigint,integer),public.pandora_ops_ingest_v1(uuid,uuid,jsonb),public.pandora_ops_register_worker_v1(uuid,uuid,text,text,text[],text[],integer,text),public.pandora_ops_heartbeat_v1(uuid,uuid,text,text,boolean,text),public.pandora_ops_claim_v1(uuid,uuid,text,text,bigint,bigint),public.pandora_ops_dispatch_v1(uuid,uuid,uuid,bigint,jsonb),public.pandora_ops_reconcile_required_v1(uuid,uuid,uuid,bigint,text),public.pandora_ops_control_v1(uuid,uuid,bigint,text,text),public.pandora_ops_snapshot_v1(uuid,uuid) from public,anon,authenticated;
grant execute on function public.pandora_ops_initialize_v1(uuid,uuid,bigint,integer),public.pandora_ops_ingest_v1(uuid,uuid,jsonb),public.pandora_ops_register_worker_v1(uuid,uuid,text,text,text[],text[],integer,text),public.pandora_ops_heartbeat_v1(uuid,uuid,text,text,boolean,text),public.pandora_ops_claim_v1(uuid,uuid,text,text,bigint,bigint),public.pandora_ops_dispatch_v1(uuid,uuid,uuid,bigint,jsonb),public.pandora_ops_reconcile_required_v1(uuid,uuid,uuid,bigint,text),public.pandora_ops_control_v1(uuid,uuid,bigint,text,text),public.pandora_ops_snapshot_v1(uuid,uuid) to service_role;
comment on table private.pandora_ops_events is 'Append-only coordination events. Not Build Theatre success evidence; projection requires existing canonical admission and independent receipts.';

-- Builder handoff and independent completion consume the existing verification authority.
-- They do not create a competing verifier or manufacture PASS rows.
create function private.pandora_ops_settle_v1(p_org uuid,p_project uuid,p_lease uuid,p_generation bigint,p_cost bigint,p_ref text)
returns void language plpgsql security definer set search_path='' as $$
declare l private.pandora_ops_leases%rowtype;
begin
 select * into l from private.pandora_ops_leases where id=p_lease and organization_id=p_org and project_id=p_project for update;
 if not found or l.generation is distinct from p_generation then raise exception 'OPS_LEASE_FENCED'; end if;
 if p_cost is null or p_cost<0 or p_cost>l.reserved_micros or p_ref is null or length(p_ref) not between 1 and 1000 then raise exception 'OPS_SETTLEMENT_EVIDENCE_REQUIRED'; end if;
 if l.state='released' then
  if l.charged_micros is distinct from p_cost or l.settlement_receipt is distinct from p_ref then raise exception 'OPS_SETTLEMENT_CONFLICT'; end if;
  return;
 end if;
 update private.pandora_ops_workspaces set reserved_micros=reserved_micros-l.reserved_micros,spent_micros=spent_micros+p_cost,updated_at=clock_timestamp() where organization_id=p_org and project_id=p_project;
 update private.pandora_ops_leases set state='released',charged_micros=p_cost,settlement_receipt=p_ref where id=l.id;
 perform private.pandora_ops_event_v1(p_org,p_project,'settle:'||l.id,l.task_key,'resource_released',p_ref);
end; $$;

create function public.pandora_ops_handoff_v1(p_organization_id uuid,p_project_id uuid,p_lease_id uuid,p_generation bigint,p_principal_key text,p_handoff jsonb,p_actual_cost_micros bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare l private.pandora_ops_leases%rowtype; t private.pandora_ops_tasks%rowtype; worker private.pandora_ops_workers%rowtype;
begin
 perform 1 from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 select * into l from private.pandora_ops_leases where id=p_lease_id and organization_id=p_organization_id and project_id=p_project_id for update;
 if not found or l.generation is distinct from p_generation then raise exception 'OPS_LEASE_FENCED'; end if;
 select * into worker from private.pandora_ops_workers where organization_id=p_organization_id and project_id=p_project_id and worker_key=l.worker_key;
 if worker.principal_key is distinct from p_principal_key then raise exception 'OPS_WORKER_IDENTITY_MISMATCH' using errcode='42501'; end if;
 select * into t from private.pandora_ops_tasks where organization_id=p_organization_id and project_id=p_project_id and task_key=l.task_key for update;
 if t.handoff=p_handoff and t.generation=p_generation and t.status in ('handed_off','verifying','complete') then
  perform private.pandora_ops_settle_v1(p_organization_id,p_project_id,l.id,p_generation,p_actual_cost_micros,p_handoff->>'receiptRef');
  return jsonb_build_object('handedOff',true,'replayed',true,'releaseVerified',t.status='complete');
 end if;
 if l.state<>'running' or l.expires_at<=clock_timestamp() or t.generation<>p_generation or t.cancel_requested then raise exception 'OPS_HANDOFF_FENCED'; end if;
 if jsonb_typeof(p_handoff) is distinct from 'object' or p_handoff->>'taskId' is distinct from t.task_key or p_handoff->>'workerId' is distinct from l.worker_key or p_handoff->>'generation' is distinct from p_generation::text or not coalesce(length(p_handoff->>'receiptRef') between 1 and 1000,false) or jsonb_typeof(p_handoff->'tests') is distinct from 'array' or jsonb_array_length(p_handoff->'tests')<1 or octet_length(p_handoff::text)>16384 then raise exception 'OPS_HANDOFF_EVIDENCE_REQUIRED'; end if;
 if t.spec->>'risk'<>'read' and not coalesce(p_handoff->>'headSha' ~ '^[a-f0-9]{40}$',false) then raise exception 'OPS_HANDOFF_EXACT_SOURCE_REQUIRED'; end if;
 if t.spec->>'risk'='source' and not coalesce(p_handoff->>'pullRequest' ~ '^[1-9][0-9]{0,9}$',false) then raise exception 'OPS_HANDOFF_PR_REQUIRED'; end if;
 update private.pandora_ops_tasks set status='handed_off',revision=revision+1,head_sha=p_handoff->>'headSha',handoff=p_handoff where organization_id=p_organization_id and project_id=p_project_id and task_key=t.task_key;
 perform private.pandora_ops_settle_v1(p_organization_id,p_project_id,l.id,p_generation,p_actual_cost_micros,p_handoff->>'receiptRef');
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'handoff:'||l.id,t.task_key,'implementation_handed_off',p_handoff->>'receiptRef');
 return jsonb_build_object('handedOff',true,'releaseVerified',false);
end; $$;

create function public.pandora_ops_verify_v1(p_organization_id uuid,p_project_id uuid,p_task_key text,p_generation bigint,p_verifier_key text,p_principal_key text,p_verification_run_id uuid,p_receipt jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare t private.pandora_ops_tasks%rowtype; worker private.pandora_ops_workers%rowtype; v public.pandora_verification_runs%rowtype;
begin
 perform 1 from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 select * into t from private.pandora_ops_tasks where organization_id=p_organization_id and project_id=p_project_id and task_key=p_task_key for update;
 if not found or t.generation is distinct from p_generation or t.status not in ('handed_off','verifying','complete') or t.cancel_requested then raise exception 'OPS_VERIFICATION_FENCED'; end if;
 select * into worker from private.pandora_ops_workers where organization_id=p_organization_id and project_id=p_project_id and worker_key=p_verifier_key;
 if not found or not worker.acknowledged or not worker.connected or worker.health<>'ready' or worker.heartbeat_at is null or worker.heartbeat_at<clock_timestamp()-interval '60 seconds' or worker.principal_key is distinct from p_principal_key or worker.principal_key=t.builder_principal_key or worker.worker_key=t.builder_worker_key or not('release'=any(worker.lanes)) then raise exception 'OPS_INDEPENDENT_VERIFIER_REQUIRED' using errcode='42501'; end if;
 select * into v from public.pandora_verification_runs where id=p_verification_run_id and organization_id=p_organization_id and project_id=p_project_id;
 if not found or v.status is distinct from 'PASS' or v.completed_at is null or v.source_commit is distinct from t.head_sha or v.required_check_profile is distinct from t.spec->>'verificationProfile' then raise exception 'OPS_CANONICAL_VERIFICATION_REQUIRED'; end if;
 if jsonb_typeof(p_receipt) is distinct from 'object' or p_receipt->>'taskId' is distinct from t.task_key or p_receipt->>'headSha' is distinct from t.head_sha or p_receipt->>'generation' is distinct from p_generation::text or p_receipt->>'taskSpecDigest' is distinct from t.spec_digest or p_receipt->>'verificationRunId' is distinct from v.id::text or not coalesce(length(p_receipt->>'ref') between 1 and 1000,false) or jsonb_typeof(p_receipt->'criteria') is distinct from 'array' or not((p_receipt->'criteria') @> (t.spec->'acceptance')) or octet_length(p_receipt::text)>16384 then raise exception 'OPS_VERIFICATION_RECEIPT_MISMATCH'; end if;
 if t.spec->>'risk' in ('production','destructive') and (not coalesce(length(p_receipt->>'approvalRef')>0,false) or not coalesce(length(p_receipt->>'rollbackRef')>0,false)) then raise exception 'OPS_PRODUCTION_PROOF_REQUIRED'; end if;
 if t.status='complete' then
  if t.verification is distinct from p_receipt then raise exception 'OPS_VERIFICATION_REPLAY_CONFLICT'; end if;
  return jsonb_build_object('complete',true,'replayed',true);
 end if;
 update private.pandora_ops_tasks set status='complete',revision=revision+1,verification=p_receipt where organization_id=p_organization_id and project_id=p_project_id and task_key=t.task_key;
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'verify:'||t.task_key||':'||p_generation,t.task_key,'verification_accepted',v.id::text);
 return jsonb_build_object('complete',true,'verificationRunId',v.id,'physicalDeviceVerified',false);
end; $$;

create function public.pandora_ops_recover_v1(p_organization_id uuid,p_project_id uuid,p_lease_id uuid,p_generation bigint,p_outcome text,p_cost_micros bigint,p_receipt jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare l private.pandora_ops_leases%rowtype; t private.pandora_ops_tasks%rowtype; next_state text;
begin
 perform 1 from private.pandora_ops_workspaces where organization_id=p_organization_id and project_id=p_project_id for update;
 select * into l from private.pandora_ops_leases where id=p_lease_id and organization_id=p_organization_id and project_id=p_project_id for update;
 if not found or l.generation is distinct from p_generation or l.state<>'reconcile' then raise exception 'OPS_RECOVERY_FENCED'; end if;
 select * into t from private.pandora_ops_tasks where organization_id=p_organization_id and project_id=p_project_id and task_key=l.task_key for update;
 -- Transport must prove the old worker is fenced before releasing a possibly in-flight action.
 if p_outcome is null or p_outcome not in ('not_executed','failed_verified','cancelled_verified') or p_receipt->'workerFenced' is distinct from 'true'::jsonb or p_receipt->'providerOutcomeKnown' is distinct from 'true'::jsonb or p_receipt->>'taskId' is distinct from t.task_key or p_receipt->>'generation' is distinct from p_generation::text or not coalesce(length(p_receipt->>'ref') between 1 and 1000,false) then raise exception 'OPS_RECOVERY_READBACK_REQUIRED'; end if;
 next_state:=case when t.cancel_requested or p_outcome='cancelled_verified' then 'cancelled' when p_outcome='not_executed' and t.attempts<(t.spec->>'maxAttempts')::integer then 'queued' else 'failed' end;
 perform private.pandora_ops_settle_v1(p_organization_id,p_project_id,l.id,p_generation,p_cost_micros,p_receipt->>'ref');
 update private.pandora_ops_tasks set status=next_state,revision=revision+1,queued_at=case when next_state='queued' then clock_timestamp() else queued_at end where organization_id=p_organization_id and project_id=p_project_id and task_key=t.task_key;
 perform private.pandora_ops_event_v1(p_organization_id,p_project_id,'recover:'||l.id,t.task_key,'recovery_'||next_state,p_receipt->>'ref');
 return jsonb_build_object('state',next_state,'leaseReleased',true);
end; $$;
revoke all on function private.pandora_ops_settle_v1(uuid,uuid,uuid,bigint,bigint,text) from public,anon,authenticated,service_role;
revoke all on function public.pandora_ops_handoff_v1(uuid,uuid,uuid,bigint,text,jsonb,bigint),public.pandora_ops_verify_v1(uuid,uuid,text,bigint,text,text,uuid,jsonb),public.pandora_ops_recover_v1(uuid,uuid,uuid,bigint,text,bigint,jsonb) from public,anon,authenticated;
grant execute on function public.pandora_ops_handoff_v1(uuid,uuid,uuid,bigint,text,jsonb,bigint),public.pandora_ops_verify_v1(uuid,uuid,text,bigint,text,text,uuid,jsonb),public.pandora_ops_recover_v1(uuid,uuid,uuid,bigint,text,bigint,jsonb) to service_role;

-- Recheck the authenticated owner inside the same transaction as the state change.
-- The edge adapter derives p_actor_id from getUser(), never from caller JSON.
create function public.pandora_ops_owner_request_v1(p_organization_id uuid,p_project_id uuid,p_actor_id uuid,p_operation text,p_payload jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
 perform 1 from public.memberships where organization_id=p_organization_id and user_id=p_actor_id and status='active' and role in ('owner','admin') for share;
 if not found then raise exception 'OPS_OWNER_SCOPE_DENIED' using errcode='42501'; end if;
 perform 1 from public.pandora_projects where id=p_project_id and organization_id=p_organization_id and status<>'archived' for share;
 if not found then raise exception 'OPS_OWNER_PROJECT_DENIED' using errcode='42501'; end if;
 if p_operation='overview' then return public.pandora_ops_snapshot_v1(p_organization_id,p_project_id);
 elsif p_operation='ingest' then return public.pandora_ops_ingest_v1(p_organization_id,p_project_id,p_payload->'tasks');
 elsif p_operation in ('pause','resume','no_production','cancel_task') then
  return public.pandora_ops_control_v1(p_organization_id,p_project_id,(p_payload->>'expectedRevision')::bigint,p_operation,case when p_operation='cancel_task' then p_payload->>'taskId' else null end);
 end if;
 raise exception 'OPS_OWNER_OPERATION_NOT_EXPOSED' using errcode='42501';
end; $$;
revoke all on function public.pandora_ops_owner_request_v1(uuid,uuid,uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.pandora_ops_owner_request_v1(uuid,uuid,uuid,text,jsonb) to service_role;
