begin;
alter table private.pandora_bedrock_reasoning_catalog alter column invocation_target drop not null,
 add column if not exists region text not null default 'us-east-1',add column if not exists output_modalities text[] not null default '{}'::text[],add column if not exists response_streaming_supported boolean not null default false,
 add column if not exists lifecycle_status text not null default 'UNKNOWN',add column if not exists lifecycle jsonb not null default '{}'::jsonb,add column if not exists agreement_status text not null default 'UNKNOWN',add column if not exists authorization_status text not null default 'UNKNOWN',add column if not exists entitlement_status text not null default 'UNKNOWN',add column if not exists region_availability text not null default 'UNKNOWN',
 add column if not exists conversational boolean not null default false,add column if not exists present_in_latest_sync boolean not null default true,add column if not exists last_verified_at timestamptz,add column if not exists runtime_verification_status text not null default 'untested',add column if not exists runtime_tested_at timestamptz,add column if not exists routable boolean not null default false,
 add column if not exists probe_http_status integer,add column if not exists probe_input_tokens bigint,add column if not exists probe_output_tokens bigint,add column if not exists probe_total_tokens bigint,add column if not exists probe_cost_micros bigint,add column if not exists probe_cost_status text not null default 'pending_pricing_readback',add column if not exists probe_pricing_source_ref text;
alter table private.pandora_bedrock_reasoning_catalog drop constraint if exists pandora_bedrock_reasoning_catalog_runtime_state_check,add constraint pandora_bedrock_reasoning_catalog_runtime_state_check check(runtime_state in('discovered','authorized','entitled','region_available','runtime_tested','routable','retired')) not valid;
create table if not exists private.pandora_bedrock_control_tickets(id uuid primary key default gen_random_uuid(),token_sha256 text not null unique check(token_sha256~'^[0-9a-f]{64}$'),operation text not null check(operation in('sync','sync_probe')),created_at timestamptz not null default clock_timestamp(),expires_at timestamptz not null,consumed_at timestamptz,check(expires_at>created_at));
alter table private.pandora_bedrock_control_tickets enable row level security;revoke all on private.pandora_bedrock_control_tickets from public,anon,authenticated,service_role;
create or replace function public.pandora_claim_bedrock_control_ticket_v1(p_token_sha256 text,p_operation text) returns jsonb language plpgsql security definer set search_path='pg_catalog','private','public','pg_temp' as $$declare v_id uuid;begin if session_user not in('postgres','service_role','supabase_admin') and coalesce(nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'role','')<>'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode='42501';end if;update private.pandora_bedrock_control_tickets set consumed_at=clock_timestamp() where token_sha256=p_token_sha256 and operation=p_operation and consumed_at is null and expires_at>clock_timestamp() returning id into v_id;if v_id is null then raise exception 'BEDROCK_CONTROL_TICKET_DENIED' using errcode='42501';end if;return jsonb_build_object('claimed',true,'ticketId',v_id);end;$$;
revoke all on function public.pandora_claim_bedrock_control_ticket_v1(text,text) from public,anon,authenticated;grant execute on function public.pandora_claim_bedrock_control_ticket_v1(text,text) to service_role;
create or replace function public.pandora_sync_bedrock_catalog_v1(p_snapshot jsonb) returns jsonb language plpgsql security definer set search_path='pg_catalog','private','public','pg_temp' as $$declare m jsonb;o timestamptz;r text;st text;rs text;n int:=0;c int:=0;begin if session_user not in('postgres','service_role','supabase_admin') and coalesce(nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'role','')<>'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode='42501';end if;if jsonb_typeof(p_snapshot->'models')<>'array' or jsonb_array_length(p_snapshot->'models') not between 1 and 500 then raise exception 'BEDROCK_SNAPSHOT_INVALID';end if;o:=(p_snapshot->>'observedAt')::timestamptz;r:=coalesce(nullif(p_snapshot->>'region',''),'us-east-1');
for m in select value from jsonb_array_elements(p_snapshot->'models') loop
 if coalesce(m->>'modelId','')!~'^[A-Za-z0-9][A-Za-z0-9._:-]{1,159}$' then continue;end if;
 st:=case when coalesce(m->>'lifecycleStatus','UNKNOWN')<>'ACTIVE' then 'retired' when coalesce(m->>'authorizationStatus','UNKNOWN')<>'AUTHORIZED' then 'discovered' when coalesce(m->>'agreementStatus','UNKNOWN')<>'AVAILABLE' or coalesce(m->>'entitlementStatus','UNKNOWN')<>'AVAILABLE' then 'authorized' when coalesce(m->>'regionAvailability','UNKNOWN')<>'AVAILABLE' then 'entitled' else 'region_available' end;
 rs:=case when st='retired' then 'lifecycle_'||lower(coalesce(m->>'lifecycleStatus','unknown')) when st='discovered' then 'authorization_'||lower(coalesce(m->>'authorizationStatus','unknown')) when coalesce(m->>'agreementStatus','UNKNOWN')<>'AVAILABLE' then 'agreement_'||lower(coalesce(m->>'agreementStatus','unknown')) when coalesce(m->>'entitlementStatus','UNKNOWN')<>'AVAILABLE' then 'entitlement_'||lower(coalesce(m->>'entitlementStatus','unknown')) when st='entitled' then 'region_'||lower(coalesce(m->>'regionAvailability','unknown')) when nullif(m->>'invocationTarget','') is null then 'invocation_target_unresolved' else 'runtime_probe_required' end;
 insert into private.pandora_bedrock_reasoning_catalog(model_id,model_name,provider_name,invocation_target,input_modalities,output_modalities,inference_types,risk_tier,capability_classes,observed_at,source_ref,runtime_state,runtime_reason,runtime_observed_at,region,response_streaming_supported,lifecycle_status,lifecycle,agreement_status,authorization_status,entitlement_status,region_availability,conversational,present_in_latest_sync,last_verified_at,runtime_verification_status,runtime_tested_at,routable,probe_http_status,probe_input_tokens,probe_output_tokens,probe_total_tokens,probe_cost_micros,probe_cost_status,probe_pricing_source_ref)
 values(m->>'modelId',coalesce(nullif(m->>'modelName',''),m->>'modelId'),coalesce(nullif(m->>'providerName',''),'Unknown'),nullif(m->>'invocationTarget',''),array(select jsonb_array_elements_text(coalesce(m->'inputModalities','[]'))),array(select jsonb_array_elements_text(coalesce(m->'outputModalities','[]'))),array(select jsonb_array_elements_text(coalesce(m->'inferenceTypes','[]'))),1,array(select jsonb_array_elements_text(coalesce(m->'capabilityClasses','[]'))),o,coalesce(nullif(m->>'sourceRef',''),'aws:bedrock:live-catalog-v2'),st,rs,o,r,coalesce((m->>'responseStreamingSupported')::boolean,false),coalesce(m->>'lifecycleStatus','UNKNOWN'),coalesce(m->'lifecycle','{}'),coalesce(m->>'agreementStatus','UNKNOWN'),coalesce(m->>'authorizationStatus','UNKNOWN'),coalesce(m->>'entitlementStatus','UNKNOWN'),coalesce(m->>'regionAvailability','UNKNOWN'),coalesce((m->>'conversational')::boolean,false),true,o,'untested',null,false,null,null,null,null,null,'pending_pricing_readback',null)
 on conflict(model_id) do update set model_name=excluded.model_name,provider_name=excluded.provider_name,invocation_target=excluded.invocation_target,input_modalities=excluded.input_modalities,output_modalities=excluded.output_modalities,inference_types=excluded.inference_types,capability_classes=excluded.capability_classes,observed_at=excluded.observed_at,source_ref=excluded.source_ref,runtime_state=excluded.runtime_state,runtime_reason=excluded.runtime_reason,runtime_observed_at=excluded.runtime_observed_at,region=excluded.region,response_streaming_supported=excluded.response_streaming_supported,lifecycle_status=excluded.lifecycle_status,lifecycle=excluded.lifecycle,agreement_status=excluded.agreement_status,authorization_status=excluded.authorization_status,entitlement_status=excluded.entitlement_status,region_availability=excluded.region_availability,conversational=excluded.conversational,present_in_latest_sync=true,last_verified_at=excluded.last_verified_at,runtime_verification_status='untested',runtime_tested_at=null,routable=false,probe_http_status=null,probe_input_tokens=null,probe_output_tokens=null,probe_total_tokens=null,probe_cost_micros=null,probe_cost_status='pending_pricing_readback',probe_pricing_source_ref=null;
 n:=n+1;if coalesce((m->>'conversational')::boolean,false) then c:=c+1;end if;end loop;
 update private.pandora_bedrock_reasoning_catalog set lifecycle_status='REMOVED',runtime_state='retired',runtime_reason='not_present_in_latest_aws_catalog',runtime_verification_status='untested',routable=false,runtime_observed_at=o,last_verified_at=o,present_in_latest_sync=false where observed_at is distinct from o;
 execute 'alter table private.pandora_bedrock_reasoning_catalog validate constraint pandora_bedrock_reasoning_catalog_runtime_state_check';
 return jsonb_build_object('modelCount',n,'conversationalCount',c,'observedAt',o,'region',r);end;$$;
revoke all on function public.pandora_sync_bedrock_catalog_v1(jsonb) from public,anon,authenticated;grant execute on function public.pandora_sync_bedrock_catalog_v1(jsonb) to service_role;
create or replace function public.pandora_record_bedrock_runtime_probes_v1(p_results jsonb,p_observed_at timestamptz) returns jsonb language plpgsql security definer set search_path='pg_catalog','private','public','pg_temp' as $$declare x jsonb;ok boolean;s int:=0;f int:=0;begin if session_user not in('postgres','service_role','supabase_admin') and coalesce(nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'role','')<>'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode='42501';end if;for x in select value from jsonb_array_elements(p_results) loop ok:=coalesce((x->>'success')::boolean,false);update private.pandora_bedrock_reasoning_catalog c set runtime_verification_status=case when ok then 'passed' else 'failed' end,runtime_tested_at=(x->>'attemptedAt')::timestamptz,runtime_observed_at=(x->>'attemptedAt')::timestamptz,probe_http_status=nullif(x->>'httpStatus','')::int,probe_input_tokens=coalesce((x->>'inputTokens')::bigint,0),probe_output_tokens=coalesce((x->>'outputTokens')::bigint,0),probe_total_tokens=coalesce((x->>'totalTokens')::bigint,0),routable=(ok and c.lifecycle_status='ACTIVE' and c.agreement_status='AVAILABLE' and c.authorization_status='AUTHORIZED' and c.entitlement_status='AVAILABLE' and c.region_availability='AVAILABLE' and c.conversational=true and c.present_in_latest_sync=true),runtime_state=case when ok and c.lifecycle_status='ACTIVE' and c.agreement_status='AVAILABLE' and c.authorization_status='AUTHORIZED' and c.entitlement_status='AVAILABLE' and c.region_availability='AVAILABLE' and c.conversational=true and c.present_in_latest_sync=true then 'routable' when c.lifecycle_status='ACTIVE' and c.agreement_status='AVAILABLE' and c.authorization_status='AUTHORIZED' and c.entitlement_status='AVAILABLE' and c.region_availability='AVAILABLE' and c.conversational=true and c.present_in_latest_sync=true then 'runtime_tested' when ok then 'runtime_tested' else c.runtime_state end,runtime_reason=case when ok and c.lifecycle_status='ACTIVE' and c.agreement_status='AVAILABLE' and c.authorization_status='AUTHORIZED' and c.entitlement_status='AVAILABLE' and c.region_availability='AVAILABLE' and c.conversational=true and c.present_in_latest_sync=true then 'bounded_runtime_probe_passed' when ok then 'runtime_passed_control_plane_not_fully_available' else left(coalesce(nullif(x->>'reason',''),'runtime_probe_failed'),240) end,last_verified_at=clock_timestamp(),probe_cost_status='pending_pricing_readback' where c.model_id=x->>'modelId' and c.observed_at=p_observed_at;if found and ok then s:=s+1;elsif found then f:=f+1;end if;end loop;return jsonb_build_object('recorded',s+f,'successes',s,'failures',f,'routable',(select count(*) from private.pandora_bedrock_reasoning_catalog where routable));end;$$;
revoke all on function public.pandora_record_bedrock_runtime_probes_v1(jsonb,timestamptz) from public,anon,authenticated;grant execute on function public.pandora_record_bedrock_runtime_probes_v1(jsonb,timestamptz) to service_role;
create or replace function public.pandora_record_bedrock_probe_costs_v1(p_costs jsonb) returns jsonb language plpgsql security definer set search_path='pg_catalog','private','public','pg_temp' as $$declare x jsonb;n int:=0;begin if session_user not in('postgres','service_role','supabase_admin') and coalesce(nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'role','')<>'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode='42501';end if;for x in select value from jsonb_array_elements(p_costs) loop update private.pandora_bedrock_reasoning_catalog set probe_cost_micros=nullif(x->>'costMicros','')::bigint,probe_cost_status=coalesce(nullif(x->>'costStatus',''),'priced'),probe_pricing_source_ref=nullif(x->>'sourceRef','') where model_id=x->>'modelId' and runtime_tested_at is not null;if found then n:=n+1;end if;end loop;return jsonb_build_object('updated',n,'totalCostMicros',(select coalesce(sum(probe_cost_micros),0) from private.pandora_bedrock_reasoning_catalog where runtime_tested_at is not null));end;$$;
revoke all on function public.pandora_record_bedrock_probe_costs_v1(jsonb) from public,anon,authenticated;grant execute on function public.pandora_record_bedrock_probe_costs_v1(jsonb) to service_role;
commit;
