-- Pandora remote migration history receipt.
-- Project ref: jcyqixttuebxqqfkjonq
-- Version: 20260917172703
-- Name: create_plp_staff_auth_preview_run_secret
-- Original SQL SHA-256: e7045cc904bf0dca2722fdf0f9d25cb767fbf8ce8df29f32979c1f1aeffa6d78
-- Original statement count: 1
-- Provider SQL bytes: 351
-- Canonical executable authority: not reconstructed in this history-only receipt.
-- Reconciliation: provider_only_identity_preserved_without_replay
-- Replay mode: history_receipt_noop; this file restores provider-version identity only and does not claim schema/effect parity.
select 1;
