-- Pandora remote migration history receipt.
-- Project ref: jcyqixttuebxqqfkjonq
-- Version: 20260917173339
-- Name: temporary_invoke_plp_staff_auth_acceptance
-- Original SQL SHA-256: 3cc79f4fa4030ae5a692d0ba005200ece78e8b8002acec28edba84c0706a9d7f
-- Original statement count: 1
-- Provider SQL bytes: 1406
-- Canonical executable authority: not reconstructed in this history-only receipt.
-- Reconciliation: provider_only_identity_preserved_without_replay
-- Replay mode: history_receipt_noop; this file restores provider-version identity only and does not claim schema/effect parity.
select 1;
