-- Pandora CI Rescue v2
-- Removes the retired ProjectOS event dependency, quarantines legacy work,
-- adds durable idempotency + generation fencing, and makes runtime mutations function-only.

create table if not exists private.pandora_ci_rescue_audit_events (
  id bigint generated by default as identity primary key,
  rescue_id uuid not null,
  actor text not null,
  event_type text not null,
  claim_generation bigint,
  previous_state jsonb,
  new_state jsonb,
  evidence_reference jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default clock_timestamp()
);

create index if not exists pandora_ci_rescue_audit_rescue_idx
  on private.pandora_ci_rescue_audit_events(rescue_id, id);

revoke all on table private.pandora_ci_rescue_audit_events from public, anon, authenticated;
revoke insert, update, delete, truncate on table private.pandora_ci_rescue_audit_events from service_role;
grant select on table private.pandora_ci_rescue_audit_events to service_role;

drop trigger if exists pandora_ci_rescue_external_event_v1 on public.projectos_external_events;
drop function if exists private.pandora_enqueue_ci_rescue_from_external_event_v1();

alter table private.pandora_ci_rescue_jobs
  drop constraint if exists pandora_ci_rescue_jobs_external_event_id_fkey;

alter table private.pandora_ci_rescue_jobs
  alter column external_event_id drop not null;

alter table private.pandora_ci_rescue_jobs
  add column if not exists delivery_id uuid,
  add column if not exists pr_number integer,
  add column if not exists idempotency_key text,
  add column if not exists claimed_by text,
  add column if not exists claim_generation bigint not null default 0,
  add column if not exists superseded_by_sha text,
  add column if not exists transient_retry_consumed boolean not null default false;

update private.pandora_ci_rescue_jobs
set delivery_id = (evidence->>'deliveryId')::uuid
where delivery_id is null
  and coalesce(evidence->>'deliveryId','') ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$';

update private.pandora_ci_rescue_jobs
set transient_retry_consumed = (transient_retry_count > 0)
where transient_retry_consumed is distinct from (transient_retry_count > 0);

update private.pandora_ci_rescue_jobs
set idempotency_key = 'legacy:' || id::text
where idempotency_key is null;

alter table private.pandora_ci_rescue_jobs
  alter column idempotency_key set not null;

create unique index if not exists pandora_ci_rescue_jobs_idempotency_key_uq
  on private.pandora_ci_rescue_jobs(idempotency_key);

create unique index if not exists pandora_ci_rescue_jobs_delivery_id_uq
  on private.pandora_ci_rescue_jobs(delivery_id)
  where delivery_id is not null;

do $constraints$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid='private.pandora_ci_rescue_jobs'::regclass
      and conname='pandora_ci_rescue_claim_generation_v2'
  ) then
    alter table private.pandora_ci_rescue_jobs
      add constraint pandora_ci_rescue_claim_generation_v2
      check (claim_generation >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid='private.pandora_ci_rescue_jobs'::regclass
      and conname='pandora_ci_rescue_pr_number_v2'
  ) then
    alter table private.pandora_ci_rescue_jobs
      add constraint pandora_ci_rescue_pr_number_v2
      check (pr_number is null or pr_number > 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid='private.pandora_ci_rescue_jobs'::regclass
      and conname='pandora_ci_rescue_superseded_sha_v2'
  ) then
    alter table private.pandora_ci_rescue_jobs
      add constraint pandora_ci_rescue_superseded_sha_v2
      check (superseded_by_sha is null or superseded_by_sha ~ '^[0-9a-f]{40}$');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid='private.pandora_ci_rescue_jobs'::regclass
      and conname='pandora_ci_rescue_transient_consumed_v2'
  ) then
    alter table private.pandora_ci_rescue_jobs
      add constraint pandora_ci_rescue_transient_consumed_v2
      check (
        (transient_retry_consumed and transient_retry_count = 1)
        or
        (not transient_retry_consumed and transient_retry_count = 0)
      );
  end if;
end;
$constraints$;

create table if not exists private.pandora_ci_rescue_workflow_allowlist (
  workflow_name text primary key,
  enabled boolean not null default true,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

insert into private.pandora_ci_rescue_workflow_allowlist(workflow_name, enabled)
values
  ('Canonical release evidence', true),
  ('Engineering toolchain', true),
  ('Windows Worker Contract', true),
  ('Pandora mobile exact-source gate', true),
  ('Dependency Review', true),
  ('Pandora Integration', true)
on conflict (workflow_name) do update
  set enabled=excluded.enabled, updated_at=clock_timestamp();

delete from private.pandora_ci_rescue_workflow_allowlist
where workflow_name in ('Kimi Evaluation and Verification', 'ProjectOS security regression');

revoke all on table private.pandora_ci_rescue_workflow_allowlist from public, anon, authenticated;
revoke insert, update, delete, truncate on table private.pandora_ci_rescue_workflow_allowlist from service_role;
grant select on table private.pandora_ci_rescue_workflow_allowlist to service_role;

insert into private.pandora_ci_rescue_audit_events(
  rescue_id, actor, event_type, claim_generation, previous_state, new_state, evidence_reference
)
select
  id,
  'migration:ci_rescue_v2',
  'legacy_queue_quarantine',
  claim_generation,
  jsonb_build_object(
    'status', status,
    'sourceAttemptCount', source_attempt_count,
    'transientRetryCount', transient_retry_count,
    'externalEventId', external_event_id
  ),
  jsonb_build_object(
    'status', 'superseded',
    'lastErrorCode', 'LEGACY_PROJECTOS_QUEUE_QUARANTINED'
  ),
  jsonb_build_object('reason', 'retired_event_source_dependency')
from private.pandora_ci_rescue_jobs
where external_event_id is not null
  and status not in ('completed','superseded','blocked','failed');

update private.pandora_ci_rescue_jobs
set status='superseded',
    last_error_code='LEGACY_PROJECTOS_QUEUE_QUARANTINED',
    lease_token=null,
    lease_until=null,
    claimed_by=null,
    updated_at=clock_timestamp(),
    completed_at=clock_timestamp(),
    evidence=evidence || jsonb_build_object(
      'legacyQueueQuarantinedAt', clock_timestamp(),
      'legacyQueueQuarantineReason', 'retired_event_source_dependency'
    )
where external_event_id is not null
  and status not in ('completed','superseded','blocked','failed');

create or replace function private.pandora_ci_rescue_guard_v2()
returns trigger
language plpgsql
security definer
set search_path to 'pg_catalog', 'private', 'public'
as $function$
declare
  v_allowed boolean := false;
begin
  if new.repository is distinct from old.repository
     or new.branch is distinct from old.branch
     or new.origin_failing_sha is distinct from old.origin_failing_sha
     or new.delivery_id is distinct from old.delivery_id
     or new.idempotency_key is distinct from old.idempotency_key
     or new.pr_number is distinct from old.pr_number
     or new.external_event_id is distinct from old.external_event_id then
    raise exception 'ci rescue immutable provenance changed' using errcode='55000';
  end if;

  if old.status in ('completed','superseded','blocked','failed') then
    raise exception 'ci rescue terminal state is immutable' using errcode='55000';
  end if;

  if new.source_attempt_count < old.source_attempt_count
     or new.source_attempt_count > old.source_attempt_count + 1
     or new.source_attempt_count > 2 then
    raise exception 'ci rescue source attempt violation' using errcode='55000';
  end if;

  if new.transient_retry_count < old.transient_retry_count
     or new.transient_retry_count > old.transient_retry_count + 1
     or new.transient_retry_count > 1
     or (old.transient_retry_consumed and not new.transient_retry_consumed)
     or new.transient_retry_consumed is distinct from (new.transient_retry_count = 1) then
    raise exception 'ci rescue transient retry violation' using errcode='55000';
  end if;

  if new.claim_generation < old.claim_generation
     or new.claim_generation > old.claim_generation + 1 then
    raise exception 'ci rescue claim generation violation' using errcode='55000';
  end if;

  if new.claim_generation = old.claim_generation + 1 then
    if nullif(new.claimed_by,'') is null
       or new.lease_token is null
       or new.lease_until is null
       or new.lease_until <= clock_timestamp() then
      raise exception 'ci rescue invalid fenced claim' using errcode='55000';
    end if;
  elsif new.claimed_by is distinct from old.claimed_by and new.claimed_by is not null then
    raise exception 'ci rescue claimant changed without generation bump' using errcode='55000';
  end if;

  if new.lease_token is distinct from old.lease_token
     and new.lease_token is not null
     and new.claim_generation <> old.claim_generation + 1 then
    raise exception 'ci rescue lease token changed without generation bump' using errcode='55000';
  end if;

  if new.status = old.status then
    v_allowed := true;
  elsif old.status='queued' and new.status in ('retrying','analyzing','blocked','superseded','failed') then
    v_allowed := true;
  elsif old.status='retrying' and new.status in ('analyzing','verifying','blocked','superseded','failed') then
    v_allowed := true;
  elsif old.status='analyzing' and new.status in ('repairing','blocked','superseded','failed') then
    v_allowed := true;
  elsif old.status='repairing' and new.status in ('verifying','blocked','superseded','failed') then
    v_allowed := true;
  elsif old.status='verifying' and new.status in ('completed','analyzing','blocked','superseded','failed') then
    v_allowed := true;
  end if;

  if not v_allowed then
    raise exception 'ci rescue illegal state transition % -> %', old.status, new.status using errcode='55000';
  end if;

  if new.source_attempt_count = old.source_attempt_count + 1 and new.status <> 'repairing' then
    raise exception 'source attempt may increment only when entering repairing' using errcode='55000';
  end if;

  if new.transient_retry_count = old.transient_retry_count + 1 and new.status <> 'retrying' then
    raise exception 'transient retry may increment only when entering retrying' using errcode='55000';
  end if;

  if new.status='superseded'
     and new.superseded_by_sha is null
     and coalesce(new.last_error_code,'') <> 'LEGACY_PROJECTOS_QUEUE_QUARANTINED' then
    raise exception 'superseded rescue requires successor sha' using errcode='55000';
  end if;

  if new.status in ('completed','superseded','blocked','failed') then
    if new.completed_at is null then
      raise exception 'terminal rescue requires completed_at' using errcode='55000';
    end if;
  elsif new.completed_at is not null then
    raise exception 'nonterminal rescue cannot have completed_at' using errcode='55000';
  end if;

  return new;
end;
$function$;

drop trigger if exists pandora_ci_rescue_guard_v2 on private.pandora_ci_rescue_jobs;
create trigger pandora_ci_rescue_guard_v2
before update on private.pandora_ci_rescue_jobs
for each row execute function private.pandora_ci_rescue_guard_v2();

create or replace function private.pandora_ci_rescue_audit_trigger_v2()
returns trigger
language plpgsql
security definer
set search_path to 'pg_catalog', 'private', 'public'
as $function$
declare
  v_actor text;
  v_event text;
begin
  v_actor := nullif(current_setting('app.actor', true),'');
  if v_actor is null then
    v_actor := session_user;
  end if;

  if tg_op='INSERT' then
    v_event := 'enqueued';
    insert into private.pandora_ci_rescue_audit_events(
      rescue_id, actor, event_type, claim_generation, previous_state, new_state, evidence_reference
    ) values (
      new.id, v_actor, v_event, new.claim_generation, null, to_jsonb(new),
      coalesce(new.evidence->'evidenceReference','{}'::jsonb)
    );
    return new;
  end if;

  if new.claim_generation = old.claim_generation + 1 then
    v_event := 'claimed';
  elsif new.status is distinct from old.status then
    v_event := 'transition';
  else
    v_event := 'updated';
  end if;

  insert into private.pandora_ci_rescue_audit_events(
    rescue_id, actor, event_type, claim_generation, previous_state, new_state, evidence_reference
  ) values (
    new.id, v_actor, v_event, new.claim_generation, to_jsonb(old), to_jsonb(new),
    coalesce(new.evidence->'evidenceReference','{}'::jsonb)
  );
  return new;
end;
$function$;

drop trigger if exists pandora_ci_rescue_audit_v2 on private.pandora_ci_rescue_jobs;
create trigger pandora_ci_rescue_audit_v2
after insert or update on private.pandora_ci_rescue_jobs
for each row execute function private.pandora_ci_rescue_audit_trigger_v2();

create or replace function public.pandora_ci_rescue_enqueue_v2(
  p_delivery_id uuid,
  p_repository text,
  p_branch text,
  p_head_sha text,
  p_workflow_run_id bigint,
  p_workflow_name text,
  p_pr_number integer default null,
  p_evidence jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'private', 'public'
as $function$
declare
  v_org uuid;
  v_name text := left(trim(coalesce(p_workflow_name,'')),200);
  v_sha text := lower(trim(coalesce(p_head_sha,'')));
  v_branch text := trim(coalesce(p_branch,''));
  v_key text;
  v_row private.pandora_ci_rescue_jobs%rowtype;
begin
  perform private.assert_control_service_role();
  perform set_config('app.actor','webhook:pandora-github-webhook',true);

  if p_repository <> 'pandora-rvw-314296438-20260820/pandoras-box'
     or v_branch='' or v_branch='main'
     or v_branch !~ '^[A-Za-z0-9._/-]{1,220}$'
     or v_sha !~ '^[0-9a-f]{40}$'
     or p_workflow_run_id is null or p_workflow_run_id < 1
     or p_delivery_id is null
     or (p_pr_number is not null and p_pr_number < 1) then
    raise exception 'invalid ci rescue enqueue payload' using errcode='22023';
  end if;

  if not exists (
    select 1 from private.pandora_ci_rescue_workflow_allowlist
    where workflow_name=v_name and enabled
  ) then
    return jsonb_build_object('accepted',false,'reason','workflow_not_eligible','workflow',v_name);
  end if;

  select organization_id into v_org
  from private.project_canonical_registry
  where canonical_provider='github'
    and canonical_repository=p_repository
    and canonical_ref='refs/heads/main'
  order by updated_at desc
  limit 1;

  if v_org is null then
    raise exception 'canonical project registry missing' using errcode='55000';
  end if;

  v_key := p_repository || ':' || coalesce(p_pr_number,0)::text || ':' || v_sha || ':' || p_workflow_run_id::text;

  insert into private.pandora_ci_rescue_jobs(
    external_event_id, delivery_id, organization_id, repository, branch,
    origin_failing_sha, current_failing_sha, workflow_run_id, workflow_name,
    pr_number, idempotency_key, evidence
  ) values (
    null, p_delivery_id, v_org, p_repository, v_branch,
    v_sha, v_sha, p_workflow_run_id, v_name,
    p_pr_number, v_key,
    coalesce(p_evidence,'{}'::jsonb) || jsonb_build_object(
      'deliveryId',p_delivery_id,
      'enqueuedAt',clock_timestamp()
    )
  )
  on conflict (idempotency_key) do nothing;

  select * into v_row
  from private.pandora_ci_rescue_jobs
  where idempotency_key=v_key;

  return jsonb_build_object(
    'accepted',true,
    'id',v_row.id,
    'status',v_row.status,
    'idempotencyKey',v_row.idempotency_key,
    'claimGeneration',v_row.claim_generation
  );
end;
$function$;

create or replace function public.pandora_ci_rescue_claim_v2(
  p_claimed_by text,
  p_limit integer default 2
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'private', 'public'
as $function$
declare
  v_result jsonb;
  v_actor text := trim(coalesce(p_claimed_by,''));
begin
  perform private.assert_control_service_role();
  if v_actor !~ '^[A-Za-z0-9._:/-]{3,120}$' then
    raise exception 'invalid ci rescue claimant' using errcode='22023';
  end if;
  if p_limit < 1 or p_limit > 4 then
    raise exception 'invalid ci rescue claim limit' using errcode='22023';
  end if;
  perform set_config('app.actor',v_actor,true);

  with picked as (
    select j.id
    from private.pandora_ci_rescue_jobs j
    where j.status in ('queued','retrying','verifying')
      and j.delivery_id is not null
      and (j.lease_until is null or j.lease_until < clock_timestamp())
    order by j.created_at
    for update skip locked
    limit p_limit
  ), leased as (
    update private.pandora_ci_rescue_jobs j
       set claimed_by=v_actor,
           claim_generation=j.claim_generation+1,
           lease_token=gen_random_uuid(),
           lease_until=clock_timestamp()+interval '3 minutes',
           updated_at=clock_timestamp()
      from picked p
     where j.id=p.id
     returning j.*
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',id,
    'deliveryId',delivery_id,
    'organizationId',organization_id,
    'repository',repository,
    'branch',branch,
    'originFailingSha',origin_failing_sha,
    'currentFailingSha',current_failing_sha,
    'workflowRunId',workflow_run_id,
    'workflowName',workflow_name,
    'prNumber',pr_number,
    'status',status,
    'sourceAttemptCount',source_attempt_count,
    'transientRetryCount',transient_retry_count,
    'transientRetryConsumed',transient_retry_consumed,
    'claimGeneration',claim_generation,
    'claimedBy',claimed_by,
    'leaseToken',lease_token,
    'evidence',evidence
  ) order by created_at),'[]'::jsonb)
  into v_result from leased;

  return v_result;
end;
$function$;

create or replace function public.pandora_ci_rescue_transition_v2(
  p_id uuid,
  p_claimed_by text,
  p_claim_generation bigint,
  p_lease_token uuid,
  p_status text,
  p_patch jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'private', 'public'
as $function$
declare
  v_row private.pandora_ci_rescue_jobs%rowtype;
  v_patch jsonb := coalesce(p_patch,'{}'::jsonb);
  v_source_attempts integer;
  v_transient_attempts integer;
  v_current_sha text;
  v_run_id bigint;
  v_repair_sha text;
  v_superseded_sha text;
  v_provider text;
  v_error text;
  v_evidence jsonb;
begin
  perform private.assert_control_service_role();
  if p_status not in ('queued','retrying','analyzing','repairing','verifying','completed','superseded','blocked','failed') then
    raise exception 'invalid ci rescue status' using errcode='22023';
  end if;
  if (v_patch - array[
    'sourceAttemptCount','transientRetryCount','currentFailingSha','workflowRunId',
    'repairCommitSha','supersededBySha','modelProvider','lastErrorCode','evidence','evidenceReference'
  ]) <> '{}'::jsonb then
    raise exception 'invalid ci rescue patch keys' using errcode='22023';
  end if;

  select * into v_row
  from private.pandora_ci_rescue_jobs
  where id=p_id
    and claimed_by=p_claimed_by
    and claim_generation=p_claim_generation
    and lease_token=p_lease_token
    and lease_until is not null
    and lease_until >= clock_timestamp()
  for update;

  if v_row.id is null then
    raise exception 'ci rescue stale claim' using errcode='55000';
  end if;

  perform set_config('app.actor',p_claimed_by,true);

  v_source_attempts := coalesce((v_patch->>'sourceAttemptCount')::integer,v_row.source_attempt_count);
  v_transient_attempts := coalesce((v_patch->>'transientRetryCount')::integer,v_row.transient_retry_count);
  v_current_sha := lower(coalesce(nullif(v_patch->>'currentFailingSha',''),v_row.current_failing_sha));
  v_run_id := coalesce((v_patch->>'workflowRunId')::bigint,v_row.workflow_run_id);
  v_repair_sha := case when v_patch ? 'repairCommitSha' then nullif(lower(v_patch->>'repairCommitSha'),'') else v_row.repair_commit_sha end;
  v_superseded_sha := case when v_patch ? 'supersededBySha' then nullif(lower(v_patch->>'supersededBySha'),'') else v_row.superseded_by_sha end;
  v_provider := case when v_patch ? 'modelProvider' then nullif(left(v_patch->>'modelProvider',40),'') else v_row.model_provider end;
  v_error := case when v_patch ? 'lastErrorCode' then nullif(left(v_patch->>'lastErrorCode',160),'') else v_row.last_error_code end;
  v_evidence := v_row.evidence
    || coalesce(v_patch->'evidence','{}'::jsonb)
    || case when v_patch ? 'evidenceReference'
            then jsonb_build_object('evidenceReference',v_patch->'evidenceReference')
            else '{}'::jsonb end;

  if v_source_attempts not between 0 and 2
     or v_transient_attempts not between 0 and 1
     or v_current_sha !~ '^[0-9a-f]{40}$'
     or (v_repair_sha is not null and v_repair_sha !~ '^[0-9a-f]{40}$')
     or (v_superseded_sha is not null and v_superseded_sha !~ '^[0-9a-f]{40}$')
     or v_run_id < 1 then
    raise exception 'invalid ci rescue patch values' using errcode='22023';
  end if;

  update private.pandora_ci_rescue_jobs
     set status=p_status,
         source_attempt_count=v_source_attempts,
         transient_retry_count=v_transient_attempts,
         transient_retry_consumed=(v_transient_attempts=1),
         current_failing_sha=v_current_sha,
         workflow_run_id=v_run_id,
         repair_commit_sha=v_repair_sha,
         superseded_by_sha=v_superseded_sha,
         model_provider=v_provider,
         last_error_code=v_error,
         evidence=v_evidence,
         claimed_by=null,
         lease_token=null,
         lease_until=null,
         updated_at=clock_timestamp(),
         completed_at=case when p_status in ('completed','superseded','blocked','failed') then clock_timestamp() else null end
   where id=p_id
     and claimed_by=p_claimed_by
     and claim_generation=p_claim_generation
     and lease_token=p_lease_token
   returning * into v_row;

  if v_row.id is null then
    raise exception 'ci rescue stale claim' using errcode='55000';
  end if;

  return jsonb_build_object(
    'id',v_row.id,
    'status',v_row.status,
    'sourceAttemptCount',v_row.source_attempt_count,
    'transientRetryCount',v_row.transient_retry_count,
    'currentFailingSha',v_row.current_failing_sha,
    'workflowRunId',v_row.workflow_run_id,
    'repairCommitSha',v_row.repair_commit_sha,
    'supersededBySha',v_row.superseded_by_sha,
    'claimGeneration',v_row.claim_generation,
    'updatedAt',v_row.updated_at,
    'completedAt',v_row.completed_at
  );
end;
$function$;

revoke execute on function public.pandora_ci_rescue_enqueue_v2(uuid,text,text,text,bigint,text,integer,jsonb)
  from public, anon, authenticated;
grant execute on function public.pandora_ci_rescue_enqueue_v2(uuid,text,text,text,bigint,text,integer,jsonb)
  to service_role;

revoke execute on function public.pandora_ci_rescue_claim_v2(text,integer)
  from public, anon, authenticated;
grant execute on function public.pandora_ci_rescue_claim_v2(text,integer)
  to service_role;

revoke execute on function public.pandora_ci_rescue_transition_v2(uuid,text,bigint,uuid,text,jsonb)
  from public, anon, authenticated;
grant execute on function public.pandora_ci_rescue_transition_v2(uuid,text,bigint,uuid,text,jsonb)
  to service_role;

revoke execute on function public.pandora_ci_rescue_claim_v1(integer)
  from public, anon, authenticated, service_role;
revoke execute on function public.pandora_ci_rescue_update_v1(uuid,uuid,text,jsonb)
  from public, anon, authenticated, service_role;

revoke all on table private.pandora_ci_rescue_jobs from public, anon, authenticated;
revoke insert, update, delete, truncate on table private.pandora_ci_rescue_jobs from service_role;
grant select on table private.pandora_ci_rescue_jobs to service_role;

create or replace function private.pandora_ci_rescue_agent_config_v2()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_url text;
  v_secret text;
begin
  select decrypted_secret into v_url
  from vault.decrypted_secrets
  where name='pandora_ci_rescue_agent_url'
  order by created_at desc
  limit 1;

  select decrypted_secret into v_secret
  from vault.decrypted_secrets
  where name='pandora_ci_rescue_agent_secret'
  order by created_at desc
  limit 1;

  if v_url !~ '^https://'
     or nullif(v_secret,'') is null
     or length(v_secret) < 32 then
    return jsonb_build_object('configured',false);
  end if;

  return jsonb_build_object('configured',true,'url',v_url,'secret',v_secret);
end;
$function$;

revoke all on function private.pandora_ci_rescue_agent_config_v2() from public, anon, authenticated;
grant execute on function private.pandora_ci_rescue_agent_config_v2() to service_role;

create or replace function private.pandora_ci_rescue_dispatch_tick_v1()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_key text;
  v_request_id bigint;
  v_pending integer;
begin
  select count(*) into v_pending
  from private.pandora_ci_rescue_jobs
  where status in ('queued','retrying','verifying')
    and delivery_id is not null
    and (lease_until is null or lease_until < clock_timestamp());

  if v_pending=0 then
    return jsonb_build_object('pending',0,'dispatched',false);
  end if;

  select decrypted_secret into v_key
  from vault.decrypted_secrets
  where name='pandora_ci_rescue_internal_v1'
  order by created_at desc
  limit 1;

  if nullif(v_key,'') is null then
    return jsonb_build_object('pending',v_pending,'dispatched',false,'error','INTERNAL_KEY_UNAVAILABLE');
  end if;

  execute 'select net.http_post($1,$2,$3,$4,$5)'
    into v_request_id
    using
      'https://jcyqixttuebxqqfkjonq.supabase.co/functions/v1/pandora-ci-rescue-runner',
      jsonb_build_object('limit',least(v_pending,2)),
      '{}'::jsonb,
      jsonb_build_object('content-type','application/json','x-pandora-internal-key',v_key),
      120000;

  v_key := null;
  return jsonb_build_object('pending',v_pending,'dispatched',true,'requestId',v_request_id);
exception when others then
  v_key := null;
  return jsonb_build_object('pending',coalesce(v_pending,0),'dispatched',false,'error','DISPATCH_FAILED');
end;
$function$;
