-- Pandora domain acquisition: governed Vercel Registrar quotes and purchases.
-- Provider credentials remain Vault-backed. Registrant contact data is transmitted
-- only to the registrar for the explicit purchase and is never persisted by Pandora.

create table if not exists public.pandora_domain_quotes (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  requested_by uuid not null, domain text not null, provider text not null default 'vercel', available boolean not null,
  years integer, purchase_price numeric(12,2), renewal_price numeric(12,2), currency text not null default 'USD',
  contact_schema jsonb not null default '{}'::jsonb, status text not null default 'quoted', expires_at timestamptz not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint pandora_domain_quotes_domain_check check (length(domain) between 1 and 253),
  constraint pandora_domain_quotes_provider_check check (provider = 'vercel'),
  constraint pandora_domain_quotes_years_check check (years is null or years between 1 and 10),
  constraint pandora_domain_quotes_price_check check (purchase_price is null or purchase_price > 0),
  constraint pandora_domain_quotes_status_check check (status in ('quoted','unavailable','consumed','expired'))
);
create index if not exists pandora_domain_quotes_lookup_idx on public.pandora_domain_quotes(organization_id, requested_by, domain, created_at desc);
alter table public.pandora_domain_quotes enable row level security;
revoke all on public.pandora_domain_quotes from anon, authenticated;
grant select, insert, update on public.pandora_domain_quotes to service_role;

create table if not exists public.pandora_domain_purchases (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid not null references public.projectos_projects(id) on delete cascade, requested_by uuid not null,
  quote_id uuid not null references public.pandora_domain_quotes(id) on delete restrict, domain text not null, provider text not null default 'vercel',
  idempotency_key text not null, status text not null default 'claimed', purchase_price numeric(12,2) not null, currency text not null default 'USD',
  years integer not null, auto_renew boolean not null, provider_project_id text, provider_order_id text, connection_status text not null default 'pending',
  safe_result jsonb not null default '{}'::jsonb, normalized_error jsonb not null default '{}'::jsonb,
  claimed_at timestamptz not null default now(), started_at timestamptz, finished_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint pandora_domain_purchases_domain_check check (length(domain) between 1 and 253),
  constraint pandora_domain_purchases_provider_check check (provider = 'vercel'),
  constraint pandora_domain_purchases_key_check check (idempotency_key ~ '^[0-9a-f]{64}$'),
  constraint pandora_domain_purchases_status_check check (status in ('claimed','running','uncertain','succeeded','failed')),
  constraint pandora_domain_purchases_connection_check check (connection_status in ('pending','connected','needs_reconciliation')),
  constraint pandora_domain_purchases_years_check check (years between 1 and 10), unique(provider, idempotency_key)
);
create index if not exists pandora_domain_purchases_project_idx on public.pandora_domain_purchases(organization_id, project_id, created_at desc);
alter table public.pandora_domain_purchases enable row level security;
revoke all on public.pandora_domain_purchases from anon, authenticated;
grant select, insert, update on public.pandora_domain_purchases to service_role;

alter table public.pandora_project_domains add column if not exists acquisition_source text, add column if not exists registrar_order_id text,
  add column if not exists registered_at timestamptz, add column if not exists auto_renew boolean;

create or replace function private.pandora_normalize_domain_20260830(p_domain text) returns text
language plpgsql immutable strict set search_path='pg_catalog' as $$
declare v_domain text; begin
  v_domain:=lower(btrim(p_domain)); v_domain:=regexp_replace(v_domain,'^https?://','','i'); v_domain:=split_part(v_domain,'/',1); v_domain:=regexp_replace(v_domain,'\.$','','');
  if length(v_domain)>253 or v_domain !~ '^(?=.{1,253}$)([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$' then raise exception 'INVALID_DOMAIN' using errcode='22023'; end if;
  return v_domain; end; $$;

create or replace function private.pandora_domain_price_value_20260830(p_body jsonb,p_key text) returns numeric
language plpgsql immutable set search_path='pg_catalog' as $$
declare v_value jsonb; v_text text; begin
  v_value:=p_body->p_key; if v_value is null or v_value='null'::jsonb then return null; end if;
  if jsonb_typeof(v_value) in ('number','string') then v_text:=trim(both '"' from v_value::text);
  elsif jsonb_typeof(v_value)='object' then v_text:=coalesce(v_value->>'value',v_value->>'amount',v_value->>'price'); end if;
  if v_text is null or v_text !~ '^[0-9]+(\.[0-9]+)?$' then return null; end if; return v_text::numeric; end; $$;

create or replace function private.pandora_domain_vercel_api_20260830(p_method text,p_path text,p_body jsonb default null) returns jsonb
language plpgsql security definer set search_path='pg_catalog','private','vault','extensions','public' as $$
declare v_token text; v_team_id text; v_method extensions.http_method; v_response extensions.http_response; v_url text; v_body jsonb; v_base_path text; begin
  if upper(coalesce(p_method,'')) not in ('GET','POST') then raise exception 'DOMAIN_PROVIDER_METHOD_NOT_ALLOWED' using errcode='22023'; end if;
  if p_path is null or p_path like '%..%' or p_path ~ E'[\r\n]' then raise exception 'DOMAIN_PROVIDER_PATH_INVALID' using errcode='22023'; end if;
  v_base_path:=split_part(p_path,'?',1);
  if not ((upper(p_method)='GET' and v_base_path ~ '^/v1/registrar/domains/[A-Za-z0-9.-]+/(availability|price|contact-info/schema|contact-verification)$')
    or (upper(p_method)='POST' and v_base_path ~ '^/v1/registrar/domains/[A-Za-z0-9.-]+/buy$') or (upper(p_method)='POST' and v_base_path='/v11/projects')
    or (upper(p_method)='GET' and v_base_path ~ '^/v9/projects/(prj_[A-Za-z0-9]+|[a-z0-9][a-z0-9-]{0,99})$')
    or (upper(p_method)='POST' and v_base_path ~ '^/v10/projects/prj_[A-Za-z0-9]+/domains$')
    or (upper(p_method)='GET' and v_base_path ~ '^/v9/projects/prj_[A-Za-z0-9]+/domains/[A-Za-z0-9.-]+$')
    or (upper(p_method)='GET' and v_base_path ~ '^/v6/domains/[A-Za-z0-9.-]+/config$')) then raise exception 'DOMAIN_PROVIDER_PATH_NOT_ALLOWED' using errcode='22023'; end if;
  if p_path like '%?%' and not (v_base_path ~ '/price$' and p_path ~ '\?years=[1-9][0-9]?$') then raise exception 'DOMAIN_PROVIDER_QUERY_NOT_ALLOWED' using errcode='22023'; end if;
  select config_value into strict v_team_id from public.pandora_runtime_provider_configs where provider='vercel' and config_key='team_id' and active=true;
  select decrypted_secret into strict v_token from vault.decrypted_secrets where name='vercel' limit 1;
  if nullif(btrim(v_token),'') is null then raise exception 'DOMAIN_PROVIDER_CREDENTIAL_UNAVAILABLE' using errcode='55000'; end if;
  v_method:=upper(p_method)::extensions.http_method; v_url:='https://api.vercel.com'||p_path||case when p_path like '%?%' then '&' else '?' end||'teamId='||v_team_id;
  select * into v_response from extensions.http((v_method,v_url::varchar,array[extensions.http_header('authorization','Bearer '||v_token),extensions.http_header('content-type','application/json'),extensions.http_header('accept','application/json'),extensions.http_header('user-agent','Pandora-Domain-Registrar/1.0')]::extensions.http_header[],case when p_body is null then null else 'application/json' end::varchar,case when p_body is null then null else p_body::text end::varchar)::extensions.http_request);
  begin v_body:=nullif(v_response.content,'')::jsonb; exception when others then v_body:=jsonb_build_object('error',jsonb_build_object('code','unreadable_provider_response')); end;
  return jsonb_build_object('status',v_response.status,'body',coalesce(v_body,'{}'::jsonb)); end; $$;
revoke all on function private.pandora_domain_vercel_api_20260830(text,text,jsonb) from public,anon,authenticated;

create or replace function public.pandora_quote_domain(p_organization_id uuid,p_domain text) returns jsonb
language plpgsql security definer set search_path='pg_catalog','public','private','auth' as $$
declare v_user uuid:=auth.uid(); v_domain text; v_availability jsonb; v_price jsonb; v_schema jsonb; v_available boolean; v_years integer; v_purchase numeric; v_renewal numeric; v_quote public.pandora_domain_quotes%rowtype; begin
  if v_user is null then raise exception 'SIGN_IN_REQUIRED' using errcode='28000'; end if;
  if not exists(select 1 from public.memberships m where m.organization_id=p_organization_id and m.user_id=v_user and m.status::text='active' and m.role::text in ('owner','admin')) then raise exception 'OWNER_ROLE_REQUIRED' using errcode='42501'; end if;
  v_domain:=private.pandora_normalize_domain_20260830(p_domain); v_availability:=private.pandora_domain_vercel_api_20260830('GET','/v1/registrar/domains/'||v_domain||'/availability',null);
  if coalesce((v_availability->>'status')::integer,0)<>200 then raise exception 'DOMAIN_QUOTE_UNAVAILABLE' using errcode='55000'; end if; v_available:=coalesce((v_availability#>>'{body,available}')::boolean,false);
  if not v_available then insert into public.pandora_domain_quotes(organization_id,requested_by,domain,available,status,expires_at) values(p_organization_id,v_user,v_domain,false,'unavailable',now()+interval '5 minutes') returning * into v_quote; return jsonb_build_object('quoteId',v_quote.id,'domain',v_domain,'available',false,'currency','USD','expiresAt',v_quote.expires_at,'contactSchema','{}'::jsonb); end if;
  v_price:=private.pandora_domain_vercel_api_20260830('GET','/v1/registrar/domains/'||v_domain||'/price?years=1',null); if coalesce((v_price->>'status')::integer,0)<>200 then raise exception 'DOMAIN_PRICE_UNAVAILABLE' using errcode='55000'; end if;
  v_years:=coalesce((v_price#>>'{body,years}')::integer,1); v_purchase:=private.pandora_domain_price_value_20260830(v_price->'body','purchasePrice'); v_renewal:=private.pandora_domain_price_value_20260830(v_price->'body','renewalPrice'); if v_years<1 or v_years>10 or v_purchase is null or v_purchase<=0 then raise exception 'DOMAIN_PRICE_INVALID' using errcode='55000'; end if;
  v_schema:=private.pandora_domain_vercel_api_20260830('GET','/v1/registrar/domains/'||v_domain||'/contact-info/schema',null); if coalesce((v_schema->>'status')::integer,0)<>200 then raise exception 'DOMAIN_CONTACT_SCHEMA_UNAVAILABLE' using errcode='55000'; end if;
  insert into public.pandora_domain_quotes(organization_id,requested_by,domain,available,years,purchase_price,renewal_price,currency,contact_schema,status,expires_at) values(p_organization_id,v_user,v_domain,true,v_years,v_purchase,v_renewal,'USD',coalesce(v_schema->'body','{}'::jsonb),'quoted',now()+interval '5 minutes') returning * into v_quote;
  return jsonb_build_object('quoteId',v_quote.id,'domain',v_quote.domain,'available',true,'years',v_quote.years,'purchasePrice',v_quote.purchase_price,'renewalPrice',v_quote.renewal_price,'currency',v_quote.currency,'expiresAt',v_quote.expires_at,'contactSchema',v_quote.contact_schema); end; $$;
revoke all on function public.pandora_quote_domain(uuid,text) from public,anon; grant execute on function public.pandora_quote_domain(uuid,text) to authenticated;

-- Purchase is exact-quote, explicit-confirmation, idempotent, and never persists registrant PII.
create or replace function public.pandora_purchase_domain(p_organization_id uuid,p_project_identifier text,p_quote_id uuid,p_expected_price numeric,p_auto_renew boolean,p_contact_information jsonb,p_idempotency_key text,p_confirm boolean) returns jsonb
language plpgsql security definer set search_path='pg_catalog','public','private','auth','extensions' as $$
declare v_user uuid:=auth.uid(); v_quote public.pandora_domain_quotes%rowtype; v_project public.projectos_projects%rowtype; v_purchase public.pandora_domain_purchases%rowtype; v_existing public.pandora_domain_purchases%rowtype; v_operation_key text; v_availability jsonb; v_price jsonb; v_buy jsonb; v_current_price numeric; v_order_id text; v_provider_project_id text; v_provider_project_name text; v_project_create jsonb; v_project_get jsonb; v_attach jsonb; v_domain_read jsonb; v_domain_config jsonb; v_ownership_verified boolean:=false; v_dns_configured boolean:=false; v_connection_status text:='pending'; v_domain_status text:='pending'; v_existing_domain_id uuid; v_has_primary boolean; v_config jsonb; v_journey jsonb; v_required text; v_country text; v_phone text; v_now timestamptz:=now(); begin
  if v_user is null then raise exception 'SIGN_IN_REQUIRED' using errcode='28000'; end if; if not exists(select 1 from public.memberships m where m.organization_id=p_organization_id and m.user_id=v_user and m.status::text='active' and m.role::text in ('owner','admin')) then raise exception 'OWNER_ROLE_REQUIRED' using errcode='42501'; end if; if p_confirm is not true then raise exception 'DOMAIN_PURCHASE_CONFIRMATION_REQUIRED' using errcode='22023'; end if; if p_idempotency_key is null or length(p_idempotency_key) not between 8 and 200 or p_idempotency_key !~ '^[A-Za-z0-9._:-]+$' then raise exception 'INVALID_IDEMPOTENCY_KEY' using errcode='22023'; end if;
  select * into v_quote from public.pandora_domain_quotes where id=p_quote_id and organization_id=p_organization_id and requested_by=v_user for update; if not found then raise exception 'DOMAIN_QUOTE_NOT_FOUND' using errcode='P0002'; end if; if v_quote.status<>'quoted' or not v_quote.available or v_quote.expires_at<=v_now then raise exception 'DOMAIN_QUOTE_EXPIRED' using errcode='22023'; end if; if p_expected_price is null or round(p_expected_price,2)<>round(v_quote.purchase_price,2) then raise exception 'DOMAIN_PRICE_CONFIRMATION_MISMATCH' using errcode='22023'; end if;
  if p_project_identifier ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then select * into v_project from public.projectos_projects where organization_id=p_organization_id and id=p_project_identifier::uuid and status<>'archived'; else select * into v_project from public.projectos_projects where organization_id=p_organization_id and project_key=p_project_identifier and status<>'archived'; end if; if not found then raise exception 'PROJECT_NOT_FOUND' using errcode='P0002'; end if;
  if jsonb_typeof(p_contact_information)<>'object' then raise exception 'DOMAIN_CONTACT_INVALID' using errcode='22023'; end if; foreach v_required in array array['firstName','lastName','email','phone','address1','city','state','zip','country'] loop if nullif(btrim(p_contact_information->>v_required),'') is null then raise exception 'DOMAIN_CONTACT_REQUIRED_%',v_required using errcode='22023'; end if; end loop; if (p_contact_information->>'email') !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then raise exception 'DOMAIN_CONTACT_EMAIL_INVALID' using errcode='22023'; end if; v_phone:=p_contact_information->>'phone'; if v_phone !~ '^\+[1-9][0-9]{7,14}$' then raise exception 'DOMAIN_CONTACT_PHONE_INVALID' using errcode='22023'; end if; v_country:=upper(p_contact_information->>'country'); if v_country !~ '^[A-Z]{2}$' then raise exception 'DOMAIN_CONTACT_COUNTRY_INVALID' using errcode='22023'; end if; p_contact_information:=jsonb_set(p_contact_information,'{country}',to_jsonb(v_country),true);
  v_operation_key:=encode(extensions.digest(convert_to('purchase_domain|'||p_organization_id::text||'|'||v_user::text||'|'||p_quote_id::text||'|'||p_idempotency_key,'UTF8'),'sha256'),'hex'); begin insert into public.pandora_domain_purchases(organization_id,project_id,requested_by,quote_id,domain,idempotency_key,status,purchase_price,currency,years,auto_renew) values(p_organization_id,v_project.id,v_user,v_quote.id,v_quote.domain,v_operation_key,'claimed',v_quote.purchase_price,v_quote.currency,v_quote.years,p_auto_renew) returning * into v_purchase; exception when unique_violation then select * into v_existing from public.pandora_domain_purchases where provider='vercel' and idempotency_key=v_operation_key; if v_existing.status='succeeded' then return jsonb_build_object('ok',true,'replayed',true,'purchaseId',v_existing.id,'orderId',v_existing.provider_order_id,'domain',v_existing.domain,'projectId',v_existing.project_id,'status','pending','purchasePrice',v_existing.purchase_price,'currency',v_existing.currency,'years',v_existing.years,'autoRenew',v_existing.auto_renew,'connectionStatus',v_existing.connection_status); elsif v_existing.status='uncertain' then return jsonb_build_object('ok',false,'code','DOMAIN_PURCHASE_RECONCILIATION_REQUIRED','domain',v_existing.domain); else return jsonb_build_object('ok',false,'code','DOMAIN_PURCHASE_IN_PROGRESS','domain',v_existing.domain); end if; end; update public.pandora_domain_purchases set status='running',started_at=v_now,updated_at=v_now where id=v_purchase.id;
  v_availability:=private.pandora_domain_vercel_api_20260830('GET','/v1/registrar/domains/'||v_quote.domain||'/availability',null); if coalesce((v_availability->>'status')::integer,0)<>200 then update public.pandora_domain_purchases set status='failed',normalized_error='{"code":"availability_unavailable"}'::jsonb,finished_at=now(),updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',false,'code','DOMAIN_AVAILABILITY_UNAVAILABLE','domain',v_quote.domain); end if; if coalesce((v_availability#>>'{body,available}')::boolean,false) is not true then update public.pandora_domain_quotes set status='unavailable',updated_at=now() where id=v_quote.id; update public.pandora_domain_purchases set status='failed',normalized_error='{"code":"domain_not_available"}'::jsonb,finished_at=now(),updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',false,'code','DOMAIN_NOT_AVAILABLE','domain',v_quote.domain); end if;
  v_price:=private.pandora_domain_vercel_api_20260830('GET','/v1/registrar/domains/'||v_quote.domain||'/price?years='||v_quote.years,null); if coalesce((v_price->>'status')::integer,0)<>200 then update public.pandora_domain_purchases set status='failed',normalized_error='{"code":"price_unavailable"}'::jsonb,finished_at=now(),updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',false,'code','DOMAIN_PRICE_UNAVAILABLE','domain',v_quote.domain); end if; v_current_price:=private.pandora_domain_price_value_20260830(v_price->'body','purchasePrice'); if v_current_price is null or round(v_current_price,2)<>round(v_quote.purchase_price,2) then update public.pandora_domain_quotes set purchase_price=v_current_price,expires_at=now()+interval '5 minutes',updated_at=now() where id=v_quote.id; update public.pandora_domain_purchases set status='failed',normalized_error=jsonb_build_object('code','price_changed','currentPrice',v_current_price),finished_at=now(),updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',false,'code','DOMAIN_PRICE_CHANGED','domain',v_quote.domain,'quoteId',v_quote.id,'purchasePrice',v_current_price,'currency',v_quote.currency,'years',v_quote.years,'expiresAt',now()+interval '5 minutes'); end if;
  v_buy:=private.pandora_domain_vercel_api_20260830('POST','/v1/registrar/domains/'||v_quote.domain||'/buy',jsonb_build_object('autoRenew',p_auto_renew,'years',v_quote.years,'expectedPrice',v_quote.purchase_price,'contactInformation',p_contact_information)); if coalesce((v_buy->>'status')::integer,0) not between 200 and 299 then if coalesce((v_buy->>'status')::integer,0)>=500 or coalesce((v_buy->>'status')::integer,0)=0 then update public.pandora_domain_purchases set status='uncertain',normalized_error=jsonb_build_object('code','provider_ambiguous','httpStatus',v_buy->>'status'),updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',false,'code','DOMAIN_PURCHASE_RECONCILIATION_REQUIRED','domain',v_quote.domain); end if; update public.pandora_domain_purchases set status='failed',normalized_error=jsonb_build_object('code','provider_rejected','httpStatus',v_buy->>'status'),finished_at=now(),updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',false,'code','DOMAIN_PURCHASE_REJECTED','domain',v_quote.domain); end if; v_order_id:=nullif(v_buy#>>'{body,orderId}',''); if v_order_id is null then update public.pandora_domain_purchases set status='uncertain',normalized_error='{"code":"order_id_missing"}'::jsonb,updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',false,'code','DOMAIN_PURCHASE_RECONCILIATION_REQUIRED','domain',v_quote.domain); end if;
  v_config:=coalesce(v_project.config,'{}'::jsonb); v_journey:=coalesce(v_config->'customerJourney','{}'::jsonb); v_provider_project_id:=nullif(v_journey->>'vercelProjectId',''); v_provider_project_name:=nullif(v_journey->>'vercelProjectName',''); if v_provider_project_id is null then v_provider_project_name:='pandora-'||left(trim(both '-' from regexp_replace(lower(v_project.name),'[^a-z0-9]+','-','g')),42)||'-'||left(v_project.id::text,8); v_project_create:=private.pandora_domain_vercel_api_20260830('POST','/v11/projects',jsonb_build_object('name',v_provider_project_name,'framework',null,'skipGitConnectDuringLink',true,'enablePreviewFeedback',true,'enableProductionFeedback',true)); if coalesce((v_project_create->>'status')::integer,0) in (200,201) then v_provider_project_id:=nullif(v_project_create#>>'{body,id}',''); v_provider_project_name:=coalesce(nullif(v_project_create#>>'{body,name}',''),v_provider_project_name); else v_project_get:=private.pandora_domain_vercel_api_20260830('GET','/v9/projects/'||v_provider_project_name,null); if coalesce((v_project_get->>'status')::integer,0)=200 then v_provider_project_id:=nullif(v_project_get#>>'{body,id}',''); v_provider_project_name:=coalesce(nullif(v_project_get#>>'{body,name}',''),v_provider_project_name); end if; end if; if v_provider_project_id is not null then v_journey:=v_journey||jsonb_build_object('vercelProjectId',v_provider_project_id,'vercelProjectName',v_provider_project_name,'runtimeStatus','ready','runtimeUpdatedAt',now()); v_config:=v_config||jsonb_build_object('customerJourney',v_journey); update public.projectos_projects set config=v_config,updated_at=now() where organization_id=p_organization_id and id=v_project.id; end if; end if;
  if v_provider_project_id is not null and v_provider_project_id ~ '^prj_[A-Za-z0-9]+$' then v_attach:=private.pandora_domain_vercel_api_20260830('POST','/v10/projects/'||v_provider_project_id||'/domains',jsonb_build_object('name',v_quote.domain)); if coalesce((v_attach->>'status')::integer,0) not in (200,201) then v_attach:=private.pandora_domain_vercel_api_20260830('GET','/v9/projects/'||v_provider_project_id||'/domains/'||v_quote.domain,null); end if; if coalesce((v_attach->>'status')::integer,0) in (200,201) then v_connection_status:='connected'; v_domain_read:=private.pandora_domain_vercel_api_20260830('GET','/v9/projects/'||v_provider_project_id||'/domains/'||v_quote.domain,null); v_domain_config:=private.pandora_domain_vercel_api_20260830('GET','/v6/domains/'||v_quote.domain||'/config',null); if coalesce((v_domain_read->>'status')::integer,0)=200 then v_ownership_verified:=coalesce((v_domain_read#>>'{body,verified}')::boolean,false); end if; if coalesce((v_domain_config->>'status')::integer,0)=200 then v_dns_configured:=coalesce(not (v_domain_config#>>'{body,misconfigured}')::boolean,false); end if; v_domain_status:=case when not v_ownership_verified then 'verification_required' when not v_dns_configured then 'dns_pending' else 'routing_pending' end; else v_connection_status:='needs_reconciliation'; v_domain_status:='pending'; end if; else v_connection_status:='needs_reconciliation'; end if;
  select id into v_existing_domain_id from public.pandora_project_domains where organization_id=p_organization_id and project_id=v_project.id and lower(domain)=lower(v_quote.domain) limit 1; select exists(select 1 from public.pandora_project_domains where project_id=v_project.id and primary_domain=true) into v_has_primary; if v_existing_domain_id is null then insert into public.pandora_project_domains(organization_id,project_id,provider,environment,provider_project_id,domain,status,verified,primary_domain,verification,ownership_verified,dns_configured,tls_ready,routing_ready,runtime_healthy,provider_payload,acquisition_source,registrar_order_id,registered_at,auto_renew,last_checked_at,updated_at) values(p_organization_id,v_project.id,'vercel','production',v_provider_project_id,v_quote.domain,v_domain_status,false,not v_has_primary,'[]'::jsonb,v_ownership_verified,v_dns_configured,false,false,false,jsonb_build_object('orderId',v_order_id,'purchasePrice',v_quote.purchase_price,'years',v_quote.years,'autoRenew',p_auto_renew),'vercel_registrar',v_order_id,now(),p_auto_renew,now(),now()); else update public.pandora_project_domains set provider='vercel',environment='production',provider_project_id=v_provider_project_id,status=v_domain_status,verified=false,ownership_verified=v_ownership_verified,dns_configured=v_dns_configured,tls_ready=false,routing_ready=false,runtime_healthy=false,provider_payload=jsonb_build_object('orderId',v_order_id,'purchasePrice',v_quote.purchase_price,'years',v_quote.years,'autoRenew',p_auto_renew),acquisition_source='vercel_registrar',registrar_order_id=v_order_id,registered_at=coalesce(registered_at,now()),auto_renew=p_auto_renew,last_checked_at=now(),updated_at=now() where id=v_existing_domain_id; end if;
  v_journey:=coalesce(v_config->'customerJourney','{}'::jsonb)||jsonb_build_object('requestedDomain',v_quote.domain,'domainStatus',v_domain_status,'runtimeUpdatedAt',now()); v_config:=v_config||jsonb_build_object('customerJourney',v_journey); update public.projectos_projects set config=v_config,updated_at=now() where organization_id=p_organization_id and id=v_project.id; update public.pandora_domain_quotes set status='consumed',updated_at=now() where id=v_quote.id; update public.pandora_domain_purchases set status='succeeded',provider_project_id=v_provider_project_id,provider_order_id=v_order_id,connection_status=v_connection_status,safe_result=jsonb_build_object('orderId',v_order_id,'domain',v_quote.domain,'projectId',v_project.id,'providerProjectId',v_provider_project_id,'connectionStatus',v_connection_status,'ownershipVerified',v_ownership_verified,'dnsConfigured',v_dns_configured),finished_at=now(),updated_at=now() where id=v_purchase.id; return jsonb_build_object('ok',true,'purchaseId',v_purchase.id,'orderId',v_order_id,'domain',v_quote.domain,'projectId',v_project.id,'projectKey',v_project.project_key,'projectName',v_project.name,'status',v_domain_status,'purchasePrice',v_quote.purchase_price,'currency',v_quote.currency,'years',v_quote.years,'autoRenew',p_auto_renew,'connectionStatus',v_connection_status); end; $$;
revoke all on function public.pandora_purchase_domain(uuid,text,uuid,numeric,boolean,jsonb,text,boolean) from public,anon; grant execute on function public.pandora_purchase_domain(uuid,text,uuid,numeric,boolean,jsonb,text,boolean) to authenticated;

comment on function public.pandora_quote_domain(uuid,text) is 'Returns a short-lived exact Vercel Registrar quote without exposing provider credentials.';
comment on function public.pandora_purchase_domain(uuid,text,uuid,numeric,boolean,jsonb,text,boolean) is 'Purchases only an exact unexpired quoted domain after explicit confirmation; registrant PII is never persisted.';
