create index if not exists idx_cpar_reviewer_runtime_proof_fk on private.canonical_physical_android_receipts (reviewer_runtime_proof_id);
create index if not exists idx_cpar_verification_evidence_fk on private.canonical_physical_android_receipts (verification_evidence_id);
create index if not exists idx_cpar_owner_dispatch_fk on private.canonical_physical_android_receipts (owner_dispatch_id);
create index if not exists idx_cpar_owner_plan_fk on private.canonical_physical_android_receipts (owner_plan_id);
create index if not exists idx_croa_owner_user_fk on private.canonical_release_owner_authorizations (owner_user_id);
create index if not exists idx_croa_review_receipt_fk on private.canonical_release_owner_authorizations (review_receipt_id);
create index if not exists idx_crrr_mobile_receipt_fk on private.canonical_release_review_receipts (physical_mobile_data_receipt_id);
create index if not exists idx_crrr_org_reviewer_fk on private.canonical_release_review_receipts (organization_id, reviewer_id);
create index if not exists idx_crrr_reviewer_runtime_proof_fk on private.canonical_release_review_receipts (reviewer_runtime_proof_id);
create index if not exists idx_crrr_wifi_receipt_fk on private.canonical_release_review_receipts (physical_wifi_receipt_id);
create index if not exists idx_cri_runtime_proof_fk on private.compute_reviewer_identities (runtime_proof_id);
create index if not exists idx_cwi_registered_plan_fk on private.compute_worker_identities (registered_by_plan_id);
create index if not exists idx_edo_runtime_proof_fk on private.execution_dispatch_outbox (runtime_proof_id);
create index if not exists idx_edo_verification_evidence_fk on private.execution_dispatch_outbox (verification_evidence_id);
create index if not exists idx_edo_verifier_runtime_proof_fk on private.execution_dispatch_outbox (verifier_runtime_proof_id);
create index if not exists idx_gwra_reviewer_runtime_proof_fk on private.governed_worker_review_attestations (reviewer_runtime_proof_id);
create index if not exists idx_gwra_dispatch_fk on private.governed_worker_review_attestations (dispatch_id);
create index if not exists idx_gwra_plan_fk on private.governed_worker_review_attestations (plan_id);
create index if not exists idx_paaj_org_observer_fk on private.physical_android_authority_jtis (organization_id, observer_id);
create index if not exists idx_waj_org_worker_fk on private.worker_authority_jtis (organization_id, worker_id);
