-- Pandora remote migration history receipt.
-- Project ref: jcyqixttuebxqqfkjonq
-- Version: 20260917102225
-- Name: temporary_plp_runtime_rest_verifier
-- Original SQL SHA-256: bad99eceed36b7df09d84a79c8f5cd0a640fa120fa6cc168691ef421fecf2e8a
-- Original statement count: 1
-- Provider SQL bytes: 2401
-- Canonical executable authority: not reconstructed in this history-only receipt.
-- Reconciliation: provider_only_identity_preserved_without_replay
-- Replay mode: history_receipt_noop; this file restores provider-version identity only and does not claim schema/effect parity.
select 1;
