
begin;

create table if not exists private.pandora_github_governed_write_receipts (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  repository text not null,
  base_sha text not null check (base_sha ~ '^[0-9a-f]{40}$'),
  branch_name text not null unique,
  commit_sha text not null check (commit_sha ~ '^[0-9a-f]{40}$'),
  pull_request integer not null check (pull_request > 0),
  files jsonb not null check (jsonb_typeof(files)='array'),
  provider_readback jsonb not null check (jsonb_typeof(provider_readback)='object'),
  created_at timestamptz not null default clock_timestamp()
);

alter table private.pandora_github_governed_write_receipts enable row level security;
revoke all on table private.pandora_github_governed_write_receipts from public, anon, authenticated;

create or replace function private.pandora_github_governed_write_v1(
  p_expected_base_sha text,
  p_branch_suffix text,
  p_files jsonb,
  p_commit_message text,
  p_idempotency_key text,
  p_pr_title text default null,
  p_pr_body text default null
) returns jsonb
language plpgsql
security definer
set search_path='pg_catalog','private','public','extensions','vault','pg_temp'
as $function$
declare
  v_repo constant text := 'pandora-rvw-314296438-20260820/pandoras-box';
  v_prefix constant text := '/repos/pandora-rvw-314296438-20260820/pandoras-box';
  v_receipt private.pandora_github_governed_write_receipts%rowtype;
  v_env jsonb;
  v_main_sha text;
  v_commit jsonb;
  v_tree_sha text;
  v_tree jsonb;
  v_file jsonb;
  v_path text;
  v_content text;
  v_expected_sha text;
  v_existing_sha text;
  v_delete boolean;
  v_blob_sha text;
  v_tree_entries jsonb := '[]'::jsonb;
  v_written jsonb := '[]'::jsonb;
  v_total_bytes bigint := 0;
  v_new_tree_sha text;
  v_new_commit_sha text;
  v_branch text;
  v_pr jsonb;
  v_pr_no integer;
  v_pr_url text;
  v_ref_readback jsonb;
  v_pr_readback jsonb;
  v_provider_readback jsonb;
  v_title text;
  v_body text;
  v_role text;
begin
  v_role := coalesce(
    nullif(current_setting('request.jwt.claims', true),'')::jsonb->>'role',
    ''
  );
  if session_user not in ('postgres','service_role','supabase_admin')
     and v_role <> 'service_role' then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_SERVICE_ROLE_REQUIRED' using errcode='42501';
  end if;

  if coalesce(p_expected_base_sha,'') !~ '^[0-9a-f]{40}$'
     or coalesce(p_branch_suffix,'') !~ '^[a-z0-9][a-z0-9._-]{5,100}$'
     or char_length(coalesce(btrim(p_commit_message),'')) not between 5 and 200
     or char_length(coalesce(btrim(p_idempotency_key),'')) not between 12 and 180
     or jsonb_typeof(p_files) <> 'array'
     or jsonb_array_length(p_files) not between 1 and 24
     or char_length(coalesce(p_pr_title,'')) > 200
     or char_length(coalesce(p_pr_body,'')) > 12000 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_INPUT_INVALID' using errcode='22023';
  end if;

  select *
  into v_receipt
  from private.pandora_github_governed_write_receipts
  where idempotency_key=btrim(p_idempotency_key)
  limit 1;

  if found then
    v_env := private.pandora_integration_github_api_20260825(
      'GET', v_prefix||'/git/ref/heads/'||v_receipt.branch_name, null
    );
    if coalesce((v_env->>'status')::integer,0) <> 200
       or v_env#>>'{body,object,sha}' is distinct from v_receipt.commit_sha then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_REPLAY_REF_MISMATCH';
    end if;

    v_env := private.pandora_integration_github_api_20260825(
      'GET', v_prefix||'/pulls/'||v_receipt.pull_request::text, null
    );
    if coalesce((v_env->>'status')::integer,0) <> 200
       or v_env#>>'{body,head,sha}' is distinct from v_receipt.commit_sha
       or v_env#>>'{body,base,ref}' is distinct from 'main' then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_REPLAY_PR_MISMATCH';
    end if;

    return jsonb_build_object(
      'ok',true,
      'replayed',true,
      'repository',v_receipt.repository,
      'baseSha',v_receipt.base_sha,
      'branch',v_receipt.branch_name,
      'commitSha',v_receipt.commit_sha,
      'pullRequest',v_receipt.pull_request,
      'files',v_receipt.files,
      'credentialSource','supabase-vault',
      'providerReadbackVerified',true,
      'mainMutated',false,
      'forceUpdateUsed',false
    );
  end if;

  if (
    select count(*) <> count(distinct value->>'path')
    from jsonb_array_elements(p_files)
  ) then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_DUPLICATE_PATH' using errcode='22023';
  end if;

  v_env := private.pandora_integration_github_api_20260825(
    'GET', v_prefix||'/git/ref/heads/main', null
  );
  if coalesce((v_env->>'status')::integer,0) <> 200 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_MAIN_READ_FAILED';
  end if;
  v_main_sha := v_env#>>'{body,object,sha}';
  if v_main_sha is distinct from p_expected_base_sha then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_STALE_BASE';
  end if;

  v_env := private.pandora_integration_github_api_20260825(
    'GET', v_prefix||'/git/commits/'||v_main_sha, null
  );
  if coalesce((v_env->>'status')::integer,0) <> 200 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_COMMIT_READ_FAILED';
  end if;
  v_commit := v_env->'body';
  v_tree_sha := v_commit#>>'{tree,sha}';
  if coalesce(v_tree_sha,'') !~ '^[0-9a-f]{40}$' then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_TREE_SHA_INVALID';
  end if;

  v_env := private.pandora_integration_github_api_20260825(
    'GET', v_prefix||'/git/trees/'||v_tree_sha||'?recursive=1', null
  );
  if coalesce((v_env->>'status')::integer,0) <> 200 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_TREE_READ_FAILED';
  end if;
  v_tree := v_env->'body';

  for v_file in
    select value from jsonb_array_elements(p_files)
  loop
    if jsonb_typeof(v_file) <> 'object' then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_FILE_INVALID' using errcode='22023';
    end if;

    v_path := coalesce(v_file->>'path','');
    v_expected_sha := nullif(v_file->>'expectedSha','');
    v_delete := coalesce(v_file->'delete','false'::jsonb) = 'true'::jsonb;

    if char_length(v_path) not between 1 and 300
       or v_path ~ '(^/|\\|//|(^|/)\.\.?(/|$))'
       or lower(v_path) ~ '(^|/)\.git(/|$)'
       or lower(v_path) ~ '(^|/)(\.env($|\.)|id_rsa$|id_ed25519$|[^/]+\.(pem|key|p12|pfx|jks)$)' then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_PATH_REJECTED: %', v_path using errcode='22023';
    end if;

    select e->>'sha'
    into v_existing_sha
    from jsonb_array_elements(coalesce(v_tree->'tree','[]'::jsonb)) e
    where e->>'type'='blob' and e->>'path'=v_path
    limit 1;

    if v_expected_sha is not null
       and (v_expected_sha !~ '^[0-9a-f]{40}$' or v_existing_sha is distinct from v_expected_sha) then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_EXPECTED_SHA_MISMATCH: %', v_path;
    end if;

    if v_delete then
      if v_existing_sha is null then
        raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_DELETE_TARGET_MISSING: %', v_path;
      end if;
      v_tree_entries := v_tree_entries || jsonb_build_array(jsonb_build_object(
        'path',v_path,'mode','100644','type','blob','sha',null
      ));
      v_written := v_written || jsonb_build_array(jsonb_build_object('path',v_path,'op','delete'));
      continue;
    end if;

    v_content := v_file->>'content';
    if v_content is null or octet_length(v_content) < 1 or octet_length(v_content) > 500000 then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_CONTENT_INVALID: %', v_path using errcode='22023';
    end if;

    v_total_bytes := v_total_bytes + octet_length(v_content);
    if v_total_bytes > 2000000 then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_TOTAL_TOO_LARGE' using errcode='22023';
    end if;

    if v_content ~ '(github_pat_[A-Za-z0-9_]{20,}|gh[pousr]_[A-Za-z0-9_]{20,}|AIza[0-9A-Za-z_-]{20,}|sb_secret_[A-Za-z0-9_-]{20,}|-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----)'
       or v_content ~* 'postgres(ql)?://[^[:space:]:@]+:[^[:space:]@]+@'
       or v_content ~* 'SUPABASE_SERVICE_ROLE_KEY[[:space:]]*=' then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_CREDENTIAL_REJECTED: %', v_path using errcode='22023';
    end if;

    v_env := private.pandora_integration_github_api_20260825(
      'POST',
      v_prefix||'/git/blobs',
      jsonb_build_object('content',v_content,'encoding','utf-8')
    );
    if coalesce((v_env->>'status')::integer,0) not between 200 and 299 then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_BLOB_FAILED: %', v_path;
    end if;

    v_blob_sha := v_env#>>'{body,sha}';
    if coalesce(v_blob_sha,'') !~ '^[0-9a-f]{40}$' then
      raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_BLOB_SHA_INVALID: %', v_path;
    end if;

    v_tree_entries := v_tree_entries || jsonb_build_array(jsonb_build_object(
      'path',v_path,'mode','100644','type','blob','sha',v_blob_sha
    ));
    v_written := v_written || jsonb_build_array(jsonb_build_object(
      'path',v_path,
      'op',case when v_existing_sha is null then 'create' else 'update' end,
      'priorSha',v_existing_sha,
      'blobSha',v_blob_sha
    ));
  end loop;

  v_env := private.pandora_integration_github_api_20260825(
    'POST',
    v_prefix||'/git/trees',
    jsonb_build_object('base_tree',v_tree_sha,'tree',v_tree_entries)
  );
  if coalesce((v_env->>'status')::integer,0) not between 200 and 299 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_TREE_CREATE_FAILED';
  end if;
  v_new_tree_sha := v_env#>>'{body,sha}';
  if coalesce(v_new_tree_sha,'') !~ '^[0-9a-f]{40}$' then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_NEW_TREE_INVALID';
  end if;

  v_env := private.pandora_integration_github_api_20260825(
    'POST',
    v_prefix||'/git/commits',
    jsonb_build_object(
      'message',btrim(p_commit_message),
      'tree',v_new_tree_sha,
      'parents',jsonb_build_array(v_main_sha)
    )
  );
  if coalesce((v_env->>'status')::integer,0) not between 200 and 299 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_COMMIT_CREATE_FAILED';
  end if;
  v_new_commit_sha := v_env#>>'{body,sha}';
  if coalesce(v_new_commit_sha,'') !~ '^[0-9a-f]{40}$' then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_COMMIT_INVALID';
  end if;

  v_env := private.pandora_integration_github_api_20260825(
    'GET', v_prefix||'/git/ref/heads/main', null
  );
  if coalesce((v_env->>'status')::integer,0) <> 200
     or v_env#>>'{body,object,sha}' is distinct from v_main_sha then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_MAIN_MOVED';
  end if;

  v_branch := 'chatgpt/'||p_branch_suffix;
  v_env := private.pandora_integration_github_api_20260825(
    'POST',
    v_prefix||'/git/refs',
    jsonb_build_object('ref','refs/heads/'||v_branch,'sha',v_new_commit_sha)
  );
  if coalesce((v_env->>'status')::integer,0) not between 200 and 299 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_BRANCH_CREATE_FAILED';
  end if;

  v_title := coalesce(nullif(btrim(p_pr_title),''), btrim(p_commit_message));
  v_body := coalesce(
    nullif(p_pr_body,''),
    'Governed source write through the Supabase Vault-backed GitHub transport.'||E'\n\n'||
    'Exact base SHA: '||v_main_sha||E'\n'||
    'Branch: '||v_branch||E'\n\n'||
    'This operation created a task branch and pull request only. It did not mutate main, force-update a ref, merge, deploy, or claim CI success.'
  );

  v_env := private.pandora_integration_github_api_20260825(
    'POST',
    v_prefix||'/pulls',
    jsonb_build_object(
      'title',v_title,
      'head',v_branch,
      'base','main',
      'body',v_body
    )
  );
  if coalesce((v_env->>'status')::integer,0) not between 200 and 299 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_PR_CREATE_FAILED';
  end if;
  v_pr := v_env->'body';
  v_pr_no := nullif(v_pr->>'number','')::integer;
  v_pr_url := v_pr->>'html_url';
  if v_pr_no is null or v_pr_no < 1 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_PR_INVALID';
  end if;

  v_env := private.pandora_integration_github_api_20260825(
    'GET',v_prefix||'/git/ref/heads/'||v_branch,null
  );
  if coalesce((v_env->>'status')::integer,0) <> 200 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_BRANCH_READBACK_FAILED';
  end if;
  v_ref_readback := v_env->'body';

  v_env := private.pandora_integration_github_api_20260825(
    'GET',v_prefix||'/pulls/'||v_pr_no::text,null
  );
  if coalesce((v_env->>'status')::integer,0) <> 200 then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_PR_READBACK_FAILED';
  end if;
  v_pr_readback := v_env->'body';

  if v_ref_readback#>>'{object,sha}' is distinct from v_new_commit_sha
     or v_pr_readback#>>'{head,sha}' is distinct from v_new_commit_sha
     or v_pr_readback#>>'{base,ref}' is distinct from 'main'
     or v_pr_readback->>'state' is distinct from 'open' then
    raise exception 'PANDORA_GITHUB_GOVERNED_WRITE_PROVIDER_READBACK_MISMATCH';
  end if;

  v_provider_readback := jsonb_build_object(
    'verified',true,
    'repository',v_repo,
    'baseBranch','main',
    'baseSha',v_main_sha,
    'branch',v_branch,
    'commitSha',v_new_commit_sha,
    'pullRequest',v_pr_no,
    'pullRequestUrl',v_pr_url,
    'pullRequestState','open',
    'files',v_written,
    'credentialSource','supabase-vault',
    'mainMutated',false,
    'forceUpdateUsed',false,
    'verifiedAt',clock_timestamp()
  );

  insert into private.pandora_github_governed_write_receipts(
    idempotency_key,repository,base_sha,branch_name,commit_sha,pull_request,files,provider_readback
  ) values (
    btrim(p_idempotency_key),v_repo,v_main_sha,v_branch,v_new_commit_sha,v_pr_no,v_written,v_provider_readback
  )
  returning * into v_receipt;

  return jsonb_build_object(
    'ok',true,
    'replayed',false,
    'repository',v_repo,
    'baseSha',v_main_sha,
    'branch',v_branch,
    'commitSha',v_new_commit_sha,
    'pullRequest',v_pr_no,
    'pullRequestUrl',v_pr_url,
    'files',v_written,
    'credentialSource','supabase-vault',
    'providerReadbackVerified',true,
    'receiptId',v_receipt.id,
    'mainMutated',false,
    'forceUpdateUsed',false
  );
end;
$function$;

revoke all on function private.pandora_github_governed_write_v1(text,text,jsonb,text,text,text,text)
from public,anon,authenticated;
grant execute on function private.pandora_github_governed_write_v1(text,text,jsonb,text,text,text,text)
to service_role;

comment on function private.pandora_github_governed_write_v1(text,text,jsonb,text,text,text,text)
is 'Service-role-only canonical Pandora source writer. Uses Supabase Vault Github_supabase transport to create exact-base chatgpt/* branches, commits and PRs with provider readback. Never writes main directly and never force-updates refs.';

commit;
