-- Pandora remote migration history receipt.
-- Project ref: jcyqixttuebxqqfkjonq
-- Version: 20260918054602
-- Name: eurofish_private_rpc_grant_hardening_v1
-- Original SQL SHA-256: 72bc39c8da3abb7649acffb61ab4fee9caec0f922eb24c030f95b48d74535702
-- Original statement count: 1
-- Provider SQL bytes: 362
-- Canonical executable authority: not reconstructed in this history-only receipt.
-- Reconciliation: provider_only_identity_preserved_without_replay
-- Replay mode: history_receipt_noop; this file restores provider-version identity only and does not claim schema/effect parity.
select 1;
