-- Pandora Project Experience Drift Telemetry v1
-- Observation-only telemetry comparing legacy compatibility surfaces with the
-- canonical Project Experience Projection. These records may never feed back
-- into customer-visible experience state or mutation authorization.

create table if not exists private.pandora_project_experience_drift_observations (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  project_id uuid not null references public.projectos_projects(id) on delete cascade,
  source text not null check (source in ('customer_journey','build_theatre')),
  drift_code text not null,
  severity text not null default 'warning' check (severity in ('info','warning')),
  legacy_state text,
  canonical_state text not null,
  canonical_transition_sequence bigint not null check (canonical_transition_sequence >= 1),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  occurrence_count bigint not null default 1 check (occurrence_count >= 1),
  resolved_at timestamptz,
  constraint pandora_project_experience_drift_project_org_check
    check (private.pandora_control_plane_project_org_matches(organization_id, project_id)),
  constraint pandora_project_experience_drift_identity_key
    unique (project_id, source, drift_code)
);

comment on table private.pandora_project_experience_drift_observations is
  'Observation-only lifecycle drift telemetry. Never authoritative for Project Experience state or customer action gates.';

revoke all on table private.pandora_project_experience_drift_observations from public;
revoke all on table private.pandora_project_experience_drift_observations from anon;
revoke all on table private.pandora_project_experience_drift_observations from authenticated;
grant select on table private.pandora_project_experience_drift_observations to service_role;

create index if not exists pandora_project_experience_drift_active_idx
  on private.pandora_project_experience_drift_observations
  (organization_id, project_id, last_seen_at desc)
  where resolved_at is null;

create index if not exists pandora_project_experience_drift_resolved_idx
  on private.pandora_project_experience_drift_observations (resolved_at)
  where resolved_at is not null;

create or replace function private.pandora_capture_project_experience_drift_v1(
  p_project_id uuid
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_now timestamptz := now();
begin
  if p_project_id is null then
    return;
  end if;

  -- Resolve prior active observations first. Current disagreements are upserted
  -- below in the same transaction, making repeated capture idempotent without
  -- creating duplicate rows.
  update private.pandora_project_experience_drift_observations
  set resolved_at = v_now
  where project_id = p_project_id
    and resolved_at is null;

  insert into private.pandora_project_experience_drift_observations (
    organization_id,
    project_id,
    source,
    drift_code,
    severity,
    legacy_state,
    canonical_state,
    canonical_transition_sequence,
    details,
    first_seen_at,
    last_seen_at,
    occurrence_count,
    resolved_at
  )
  with canonical as (
    select e.*
    from public.pandora_project_experience_projection e
    where e.project_id = p_project_id
  ),
  legacy as (
    select
      p.organization_id,
      p.id as project_id,
      p.config -> 'customerJourney' as customer_journey,
      t.build_job_id as theatre_build_job_id,
      t.project_version_id as theatre_project_version_id,
      t.owner_state as theatre_owner_state,
      t.owner_stage as theatre_owner_stage,
      t.needs_you as theatre_needs_you,
      t.retry_available as theatre_retry_available,
      t.updated_at as theatre_updated_at
    from public.projectos_projects p
    left join public.pandora_build_theatre_projection t
      on t.project_id = p.id
    where p.id = p_project_id
  ),
  drift_rows as (
    -- Legacy customerJourney says Live while canonical truth does not.
    select
      l.organization_id,
      l.project_id,
      'customer_journey'::text as source,
      'legacy_live_without_canonical_live'::text as drift_code,
      'warning'::text as severity,
      l.customer_journey ->> 'stage' as legacy_state,
      e.experience_state as canonical_state,
      e.transition_sequence as canonical_transition_sequence,
      jsonb_build_object(
        'legacyStage', l.customer_journey ->> 'stage',
        'publishedVersionId', l.customer_journey ->> 'publishedVersionId',
        'canonicalProductionVersionId', e.production_version_id,
        'observationOnly', true
      ) as details
    from legacy l
    join canonical e on true
    where l.customer_journey is not null
      and l.customer_journey ->> 'stage' = 'live'
      and e.experience_state <> 'LIVE'

    union all

    -- Canonical production is live but legacy customerJourney is stuck on a
    -- non-live stage. This is a compatibility drift signal only; canonical Live
    -- remains authoritative.
    select
      l.organization_id,
      l.project_id,
      'customer_journey',
      'canonical_live_legacy_stage_stale',
      'warning',
      l.customer_journey ->> 'stage',
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'legacyStage', l.customer_journey ->> 'stage',
        'canonicalProductionVersionId', e.production_version_id,
        'legacyPublishedVersionId', l.customer_journey ->> 'publishedVersionId',
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where l.customer_journey is not null
      and e.experience_state = 'LIVE'
      and e.production_version_id is not null
      and coalesce(l.customer_journey ->> 'stage', '') <> 'live'

    union all

    select
      l.organization_id,
      l.project_id,
      'customer_journey',
      'published_version_mismatch',
      'warning',
      l.customer_journey ->> 'publishedVersionId',
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'legacyPublishedVersionId', l.customer_journey ->> 'publishedVersionId',
        'canonicalProductionVersionId', e.production_version_id,
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where nullif(l.customer_journey ->> 'publishedVersionId', '') is not null
      and (l.customer_journey ->> 'publishedVersionId') is distinct from e.production_version_id::text

    union all

    select
      l.organization_id,
      l.project_id,
      'customer_journey',
      'preview_version_outside_canonical_graph',
      'warning',
      l.customer_journey ->> 'previewVersionId',
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'legacyPreviewVersionId', l.customer_journey ->> 'previewVersionId',
        'canonicalCurrentVersionId', e.current_version_id,
        'canonicalCandidateVersionId', e.candidate_version_id,
        'canonicalProductionVersionId', e.production_version_id,
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where nullif(l.customer_journey ->> 'previewVersionId', '') is not null
      and (l.customer_journey ->> 'previewVersionId') is distinct from e.current_version_id::text
      and (l.customer_journey ->> 'previewVersionId') is distinct from e.candidate_version_id::text
      and (l.customer_journey ->> 'previewVersionId') is distinct from e.production_version_id::text

    union all

    select
      l.organization_id,
      l.project_id,
      'build_theatre',
      'active_build_job_mismatch',
      'warning',
      l.theatre_owner_state,
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'theatreBuildJobId', l.theatre_build_job_id,
        'canonicalActiveBuildJobId', e.active_build_job_id,
        'theatreOwnerStage', l.theatre_owner_stage,
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where l.theatre_build_job_id is not null
      and e.active_build_job_id is not null
      and l.theatre_build_job_id <> e.active_build_job_id

    union all

    select
      l.organization_id,
      l.project_id,
      'build_theatre',
      'theatre_version_outside_canonical_graph',
      'warning',
      l.theatre_project_version_id::text,
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'theatreProjectVersionId', l.theatre_project_version_id,
        'canonicalCurrentVersionId', e.current_version_id,
        'canonicalCandidateVersionId', e.candidate_version_id,
        'canonicalProductionVersionId', e.production_version_id,
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where l.theatre_project_version_id is not null
      and l.theatre_project_version_id is distinct from e.current_version_id
      and l.theatre_project_version_id is distinct from e.candidate_version_id
      and l.theatre_project_version_id is distinct from e.production_version_id

    union all

    -- Only compare activity flags when Build Theatre points at the same active
    -- build job. A LIVE canonical state with a background theatre build is valid
    -- precedence and is deliberately not treated as state drift.
    select
      l.organization_id,
      l.project_id,
      'build_theatre',
      'needs_you_mismatch',
      'warning',
      l.theatre_owner_state,
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'theatreBuildJobId', l.theatre_build_job_id,
        'theatreNeedsYou', l.theatre_needs_you,
        'canonicalNeedsYou', e.needs_you,
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where l.theatre_build_job_id = e.active_build_job_id
      and l.theatre_needs_you is distinct from e.needs_you

    union all

    select
      l.organization_id,
      l.project_id,
      'build_theatre',
      'retry_available_mismatch',
      'warning',
      l.theatre_owner_state,
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'theatreBuildJobId', l.theatre_build_job_id,
        'theatreRetryAvailable', l.theatre_retry_available,
        'canonicalRetryAvailable', e.retry_available,
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where l.theatre_build_job_id = e.active_build_job_id
      and l.theatre_retry_available is distinct from e.retry_available

    union all

    select
      l.organization_id,
      l.project_id,
      'build_theatre',
      'theatre_live_without_canonical_live',
      'warning',
      l.theatre_owner_state,
      e.experience_state,
      e.transition_sequence,
      jsonb_build_object(
        'theatreOwnerState', l.theatre_owner_state,
        'theatreOwnerStage', l.theatre_owner_stage,
        'theatreUpdatedAt', l.theatre_updated_at,
        'observationOnly', true
      )
    from legacy l
    join canonical e on true
    where l.theatre_owner_state = 'live'
      and e.experience_state <> 'LIVE'
  )
  select
    d.organization_id,
    d.project_id,
    d.source,
    d.drift_code,
    d.severity,
    d.legacy_state,
    d.canonical_state,
    d.canonical_transition_sequence,
    d.details,
    v_now,
    v_now,
    1,
    null
  from drift_rows d
  on conflict (project_id, source, drift_code)
  do update set
    organization_id = excluded.organization_id,
    severity = excluded.severity,
    legacy_state = excluded.legacy_state,
    canonical_state = excluded.canonical_state,
    canonical_transition_sequence = excluded.canonical_transition_sequence,
    details = excluded.details,
    last_seen_at = excluded.last_seen_at,
    occurrence_count = private.pandora_project_experience_drift_observations.occurrence_count + 1,
    resolved_at = null;
end;
$$;

revoke all on function private.pandora_capture_project_experience_drift_v1(uuid) from public;
revoke all on function private.pandora_capture_project_experience_drift_v1(uuid) from anon;
revoke all on function private.pandora_capture_project_experience_drift_v1(uuid) from authenticated;
grant execute on function private.pandora_capture_project_experience_drift_v1(uuid) to service_role;

create or replace function private.pandora_prune_project_experience_drift_v1(
  p_retention interval default interval '30 days'
)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog, private
as $$
declare
  v_deleted bigint;
begin
  if p_retention < interval '1 day' then
    raise exception 'drift retention must be at least 1 day' using errcode = '22023';
  end if;

  delete from private.pandora_project_experience_drift_observations
  where resolved_at is not null
    and resolved_at < now() - p_retention;
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

revoke all on function private.pandora_prune_project_experience_drift_v1(interval) from public;
revoke all on function private.pandora_prune_project_experience_drift_v1(interval) from anon;
revoke all on function private.pandora_prune_project_experience_drift_v1(interval) from authenticated;
grant execute on function private.pandora_prune_project_experience_drift_v1(interval) to service_role;

-- Keep the existing canonical touch/refresh flow and append telemetry capture
-- after canonical refresh. Telemetry never writes to the projection itself.
create or replace function private.pandora_project_experience_touch_v1()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_project_id uuid;
begin
  if tg_table_name = 'projectos_projects' then
    if tg_op = 'DELETE' then
      v_project_id := old.id;
    else
      v_project_id := new.id;
    end if;
  else
    if tg_op = 'DELETE' then
      v_project_id := old.project_id;
    else
      v_project_id := new.project_id;
    end if;
  end if;

  perform private.pandora_refresh_project_experience_projection_v1(v_project_id);
  perform private.pandora_capture_project_experience_drift_v1(v_project_id);

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function private.pandora_project_experience_touch_v1() from public;

-- Establish the observation baseline without mutating any customer-facing truth.
do $$
declare
  r record;
begin
  for r in
    select p.id
    from public.projectos_projects p
    order by p.created_at, p.id
  loop
    perform private.pandora_capture_project_experience_drift_v1(r.id);
  end loop;
end;
$$;
