'use strict';
const ALLOWED_TOOL_PROPOSALS=Object.freeze(['read_file','write_file','list_files','query_schema','request_migration','run_build','run_tests','inspect_build_error','create_preview','inspect_preview','publish_project']);
const BLOCKED_PATH_SEGMENTS=Object.freeze(['.git','.env','node_modules','secrets','.ssh']);
const DEFAULT_MAX_ARGUMENT_BYTES=128*1024;
/** @param {unknown} value */ function isRecord(value){return !!value&&typeof value==='object'&&!Array.isArray(value);}
/** @param {string} path */ function isSafeRelativePath(path){if(!path||path.length>512||path.startsWith('/')||path.includes('\\')||path.includes('\0'))return false;const segments=path.split('/');return !segments.some(segment=>segment==='..'||BLOCKED_PATH_SEGMENTS.includes(segment.toLowerCase()));}
/** @param {unknown} proposal @param {{maxArgumentBytes?: number}} options */
function validateToolProposal(proposal,options={}){/** @type {string[]} */const errors=[];if(!isRecord(proposal))return{ok:false,errors:['tool proposal must be an object'],value:null};const record=/** @type {Record<string, unknown>} */(proposal);if(typeof record.tool!=='string'||!ALLOWED_TOOL_PROPOSALS.includes(record.tool))errors.push('unsupported tool proposal');if(!isRecord(record.arguments))errors.push('arguments must be an object');if(typeof record.reason!=='string'||record.reason.trim()==='')errors.push('reason is required');if(isRecord(record.arguments)){const args=/** @type {Record<string, unknown>} */(record.arguments);for(const key of ['path','source_path','target_path'])if(args[key]!==undefined&&(typeof args[key]!=='string'||!isSafeRelativePath(String(args[key]))))errors.push(`${key} is unsafe`);const bytes=utf8ByteLength(JSON.stringify(args));if(bytes>(options.maxArgumentBytes??DEFAULT_MAX_ARGUMENT_BYTES))errors.push('tool arguments exceed size limit');}return errors.length?{ok:false,errors,value:null}:{ok:true,errors:[],value:record};}
/** @param {unknown} value @param {(value: unknown) => {ok: boolean, errors: string[], value: unknown}} validator */ function validateStructuredResult(value,validator){try{const result=validator(value);return result.ok?result:{ok:false,errors:result.errors,value:null};}catch(error){return{ok:false,errors:[error instanceof Error?error.message:'structured output validation failed'],value:null};}}
/** @param {string} value */ function utf8ByteLength(value){let bytes=0;for(const char of value){const code=char.codePointAt(0)??0;bytes+=code<=0x7f?1:code<=0x7ff?2:code<=0xffff?3:4;}return bytes;}
module.exports={ALLOWED_TOOL_PROPOSALS,DEFAULT_MAX_ARGUMENT_BYTES,isSafeRelativePath,validateStructuredResult,validateToolProposal};
