'use strict';
const {assertIdempotentEventSink,createDomainEvent}=require('../../core/src/events');
const DEFAULT_CONTACT_FIELDS=Object.freeze(['name','email','phone','company','source','status','ownerUserId','tags']);
const SENSITIVE_FIELD=/(?:password|secret|token|medical|diagnosis|religion|race|ethnic|sexual|criminal|biometric|government.?id|passport|ssn)/i;
class PandoraCrmService {
 constructor({repository,eventSink,allowedContactFields=DEFAULT_CONTACT_FIELDS}){for(const m of ['upsertContact','createLead','addInteraction','listContacts'])if(!repository||typeof repository[m]!=='function')throw new TypeError(`crm repository.${m} is required`);assertIdempotentEventSink(eventSink,'crm event sink');this.repository=repository;this.eventSink=eventSink;this.allowed=new Set(allowedContactFields);for(const field of this.allowed)if(SENSITIVE_FIELD.test(field))throw new Error(`sensitive CRM field requires explicit separate governance: ${field}`);}
 async upsertContact({project,scopeId,identity,contact,idempotencyKey}){const clean=minimizeContact(contact,this.allowed);const result=await this.repository.upsertContact({scopeId:required(scopeId,'scopeId'),actorUserId:required(identity&&identity.userId,'identity.userId'),contact:clean,idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:'customer.created',project,actor:{userId:identity.userId},aggregate:{type:'contact',id:String(result.id)},payload:{source:clean.source||'',status:clean.status||''},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);return Object.freeze({...result,event});}
 async createLead({project,scopeId,identity,contactId,status='new',source='',idempotencyKey}){const result=await this.repository.createLead({scopeId:required(scopeId,'scopeId'),contactId:required(contactId,'contactId'),status:required(status,'status'),source:bounded(source,200),actorUserId:required(identity&&identity.userId,'identity.userId'),idempotencyKey:required(idempotencyKey,'idempotencyKey')});const event=createDomainEvent({name:'lead.created',project,actor:{userId:identity.userId},aggregate:{type:'lead',id:String(result.id)},payload:{status,source},idempotencyKey:`event:${idempotencyKey}`});await this.eventSink.publish(event);return Object.freeze({...result,event});}
 async addInteraction({scopeId,identity,contactId,type,note}){if(!['note','call','email','meeting','status_change'].includes(type))throw new TypeError('unsupported CRM interaction type');return this.repository.addInteraction({scopeId:required(scopeId,'scopeId'),contactId:required(contactId,'contactId'),type,note:bounded(note,4000),actorUserId:required(identity&&identity.userId,'identity.userId')});}
 async listContacts({scopeId,limit=50,cursor=null}){if(!Number.isInteger(limit)||limit<1||limit>200)throw new TypeError('limit must be 1-200');return this.repository.listContacts({scopeId:required(scopeId,'scopeId'),limit,cursor});}
}
function minimizeContact(value,allowed){if(!value||typeof value!=='object'||Array.isArray(value))throw new TypeError('contact must be an object');const out={};for(const [key,raw] of Object.entries(value)){if(SENSITIVE_FIELD.test(key))throw new Error(`sensitive CRM field is blocked by default: ${key}`);if(!allowed.has(key))throw new Error(`CRM field is not allowed: ${key}`);if(key==='tags'){if(!Array.isArray(raw)||raw.length>50||raw.some(x=>typeof x!=='string'||x.length>100))throw new TypeError('contact.tags must be bounded strings');out.tags=[...new Set(raw.map(x=>x.trim()).filter(Boolean))];continue;}if(raw!=null&&typeof raw!=='string')throw new TypeError(`contact.${key} must be text`);out[key]=raw==null?null:bounded(raw,key==='phone'?64:320);}return Object.freeze(out);}
function bounded(v,max){if(typeof v!=='string'||v.length>max)throw new TypeError(`text must be <= ${max} characters`);return v.trim();}function required(v,f){if(typeof v!=='string'||!v.trim())throw new TypeError(`${f} is required`);return v.trim();}
module.exports={DEFAULT_CONTACT_FIELDS,PandoraCrmService,minimizeContact};
